// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.
// Run `npm run gen:cards -w engine` after adding or removing a card file.

import type { CardShard } from "../card-shards.js";

import _poolAbyssalGatekeeper from "../pool/abyssal-gatekeeper.js";
import _poolAlabornMusketeer from "../pool/alaborn-musketeer.js";
import _poolAnafenzaTheForemost from "../pool/anafenza-the-foremost.js";
import _poolAnodetLurker from "../pool/anodet-lurker.js";
import _poolAppetiteForTheUnnatural from "../pool/appetite-for-the-unnatural.js";
import _poolArchonOfCruelty from "../pool/archon-of-cruelty.js";
import _poolArmyOfTheDamned from "../pool/army-of-the-damned.js";
import _poolAtarkaWorldRender from "../pool/atarka-world-render.js";
import _poolAvacynAngelOfHope from "../pool/avacyn-angel-of-hope.js";
import _poolBakeIntoAPie from "../pool/bake-into-a-pie.js";
import _poolBeastWithin from "../pool/beast-within.js";
import _poolBehemothSledge from "../pool/behemoth-sledge.js";
import _poolBellowingAegisaur from "../pool/bellowing-aegisaur.js";
import _poolBlightedCataract from "../pool/blighted-cataract.js";
import _poolBrotherhoodPatriarch from "../pool/brotherhood-patriarch.js";
import _poolCanopyGargantuan from "../pool/canopy-gargantuan.js";
import _poolCaptainOfUmbar from "../pool/captain-of-umbar.js";
import _poolCaptivatingVampire from "../pool/captivating-vampire.js";
import _poolCarvenCaryatid from "../pool/carven-caryatid.js";
import _poolCavesOfKoilos from "../pool/caves-of-koilos.js";
import _poolChitterspitter from "../pool/chitterspitter.js";
import _poolChivalricAlliance from "../pool/chivalric-alliance.js";
import _poolCinderBarrens from "../pool/cinder-barrens.js";
import _poolCommandTower from "../pool/command-tower.js";
import _poolCondemn from "../pool/condemn.js";
import _poolCrashingDrawbridge from "../pool/crashing-drawbridge.js";
import _poolCrucibleOfFire from "../pool/crucible-of-fire.js";
import _poolDeadlyDerision from "../pool/deadly-derision.js";
import _poolDeadlyVisit from "../pool/deadly-visit.js";
import _poolDecimate from "../pool/decimate.js";
import _poolDeeptreadMerrow from "../pool/deeptread-merrow.js";
import _poolDefenseOfTheHeart from "../pool/defense-of-the-heart.js";
import _poolDementiaBat from "../pool/dementia-bat.js";
import _poolDiscipleOfTheOldWays from "../pool/disciple-of-the-old-ways.js";
import _poolDoctorDoomKingOfLatveria from "../pool/doctor-doom-king-of-latveria.js";
import _poolDogmeatEverLoyal from "../pool/dogmeat-ever-loyal.js";
import _poolDreamTwist from "../pool/dream-twist.js";
import _poolEloiseNephaliaSleuth from "../pool/eloise-nephalia-sleuth.js";
import _poolEmeriaAngel from "../pool/emeria-angel.js";
import _poolErraticVisionary from "../pool/erratic-visionary.js";
import _poolFaerieDuelist from "../pool/faerie-duelist.js";
import _poolFanBearer from "../pool/fan-bearer.js";
import _poolFeebleness from "../pool/feebleness.js";
import _poolFireSprites from "../pool/fire-sprites.js";
import _poolFlamewaveInvoker from "../pool/flamewave-invoker.js";
import _poolFlight from "../pool/flight.js";
import _poolForsakenMonument from "../pool/forsaken-monument.js";
import _poolFyndhornBow from "../pool/fyndhorn-bow.js";
import _poolGalvanicIteration from "../pool/galvanic-iteration.js";
import _poolGalvanicKey from "../pool/galvanic-key.js";
import _poolGameTrail from "../pool/game-trail.js";
import _poolGiadaFontOfHope from "../pool/giada-font-of-hope.js";
import _poolGisaAndGeralf from "../pool/gisa-and-geralf.js";
import _poolGlissasCourier from "../pool/glissas-courier.js";
import _poolGnawingVermin from "../pool/gnawing-vermin.js";
import _poolGoblinCannon from "../pool/goblin-cannon.js";
import _poolGoldlustTriad from "../pool/goldlust-triad.js";
import _poolGoldmeadowHarrier from "../pool/goldmeadow-harrier.js";
import _poolGontiCannyAcquisitor from "../pool/gonti-canny-acquisitor.js";
import _poolGorgonsHead from "../pool/gorgons-head.js";
import _poolGuardianKirin from "../pool/guardian-kirin.js";
import _poolHalimarDepths from "../pool/halimar-depths.js";
import _poolHaplessResearcher from "../pool/hapless-researcher.js";
import _poolHarrierNaga from "../pool/harrier-naga.js";
import _poolHarvestSeason from "../pool/harvest-season.js";
import _poolHealersHawk from "../pool/healers-hawk.js";
import _poolHengeOfRamos from "../pool/henge-of-ramos.js";
import _poolHourOfDefeat from "../pool/hour-of-defeat.js";
import _poolHowlingFury from "../pool/howling-fury.js";
import _poolIchorWellspring from "../pool/ichor-wellspring.js";
import _poolImperiousPerfect from "../pool/imperious-perfect.js";
import _poolInfiniteGuidelineStation from "../pool/infinite-guideline-station.js";
import _poolInsomniaCrownCity from "../pool/insomnia-crown-city.js";
import _poolIntoTheFloodMaw from "../pool/into-the-flood-maw.js";
import _poolIrrigationDitch from "../pool/irrigation-ditch.js";
import _poolIsshinTwoHeavensAsOne from "../pool/isshin-two-heavens-as-one.js";
import _poolIvyGleefulSpellthief from "../pool/ivy-gleeful-spellthief.js";
import _poolIxhelScionOfAtraxa from "../pool/ixhel-scion-of-atraxa.js";
import _poolJandorsSaddlebags from "../pool/jandors-saddlebags.js";
import _poolKamiOfTwistedReflection from "../pool/kami-of-twisted-reflection.js";
import _poolKoalaSheep from "../pool/koala-sheep.js";
import _poolKolaghansCommand from "../pool/kolaghans-command.js";
import _poolKorCartographer from "../pool/kor-cartographer.js";
import _poolKrarkClanStoker from "../pool/krark-clan-stoker.js";
import _poolKravensCats from "../pool/kravens-cats.js";
import _poolLaboratoryDrudge from "../pool/laboratory-drudge.js";
import _poolLlanowarTribe from "../pool/llanowar-tribe.js";
import _poolLoxodonMystic from "../pool/loxodon-mystic.js";
import _poolLurchingRotbeast from "../pool/lurching-rotbeast.js";
import _poolMachinesmithAutomaton from "../pool/machinesmith-automaton.js";
import _poolMahadiEmporiumMaster from "../pool/mahadi-emporium-master.js";
import _poolMakindiMesas from "../pool/makindi-mesas.js";
import _poolMalevolentAwakening from "../pool/malevolent-awakening.js";
import _poolMerfolkCoralsmith from "../pool/merfolk-coralsmith.js";
import _poolMetallicSliver from "../pool/metallic-sliver.js";
import _poolMinotaurAggressor from "../pool/minotaur-aggressor.js";
import _poolMorbidHunger from "../pool/morbid-hunger.js";
import _poolMortify from "../pool/mortify.js";
import _poolMossKami from "../pool/moss-kami.js";
import _poolMossViper from "../pool/moss-viper.js";
import _poolNadirKraken from "../pool/nadir-kraken.js";
import _poolNettleSwine from "../pool/nettle-swine.js";
import _poolNimbusWings from "../pool/nimbus-wings.js";
import _poolNoblePanther from "../pool/noble-panther.js";
import _poolNyxbloomAncient from "../pool/nyxbloom-ancient.js";
import _poolNyxbornBrute from "../pool/nyxborn-brute.js";
import _poolOgreResister from "../pool/ogre-resister.js";
import _poolOracleOfMulDaya from "../pool/oracle-of-mul-daya.js";
import _poolOrazcaFrillback from "../pool/orazca-frillback.js";
import _poolPersist from "../pool/persist.js";
import _poolPiggyBank from "../pool/piggy-bank.js";
import _poolPrismariTheInspiration from "../pool/prismari-the-inspiration.js";
import _poolProsshSkyraiderOfKher from "../pool/prossh-skyraider-of-kher.js";
import _poolProwlingSerpopard from "../pool/prowling-serpopard.js";
import _poolPsionicPulse from "../pool/psionic-pulse.js";
import _poolPyroclasticElemental from "../pool/pyroclastic-elemental.js";
import _poolPyrohemia from "../pool/pyrohemia.js";
import _poolRampagingHippo from "../pool/rampaging-hippo.js";
import _poolRaugrinCrystal from "../pool/raugrin-crystal.js";
import _poolRayOfDissolution from "../pool/ray-of-dissolution.js";
import _poolRejuvenatingSprings from "../pool/rejuvenating-springs.js";
import _poolRelentlessAssault from "../pool/relentless-assault.js";
import _poolResculpt from "../pool/resculpt.js";
import _poolRighteousBlow from "../pool/righteous-blow.js";
import _poolRithsAttendant from "../pool/riths-attendant.js";
import _poolRocHunter from "../pool/roc-hunter.js";
import _poolRubblebeltRecluse from "../pool/rubblebelt-recluse.js";
import _poolRumbleArena from "../pool/rumble-arena.js";
import _poolRuneCervinRider from "../pool/rune-cervin-rider.js";
import _poolRushwoodElemental from "../pool/rushwood-elemental.js";
import _poolSacredPrey from "../pool/sacred-prey.js";
import _poolSadisticHypnotist from "../pool/sadistic-hypnotist.js";
import _poolSagesReverie from "../pool/sages-reverie.js";
import _poolSalvagedManaworker from "../pool/salvaged-manaworker.js";
import _poolScrapTrawler from "../pool/scrap-trawler.js";
import _poolSeaGate from "../pool/sea-gate.js";
import _poolSeacoastDrake from "../pool/seacoast-drake.js";
import _poolSeasideCitadel from "../pool/seaside-citadel.js";
import _poolSeatOfTheSynod from "../pool/seat-of-the-synod.js";
import _poolSeleniaDarkAngel from "../pool/selenia-dark-angel.js";
import _poolSerrasEmbrace from "../pool/serras-embrace.js";
import _poolShamblingGhoul from "../pool/shambling-ghoul.js";
import _poolSheHulkAttorneyAtLaw from "../pool/she-hulk-attorney-at-law.js";
import _poolShelteredThicket from "../pool/sheltered-thicket.js";
import _poolSheoldredWhisperingOne from "../pool/sheoldred-whispering-one.js";
import _poolShopkeepersBane from "../pool/shopkeepers-bane.js";
import _poolSilverbackShaman from "../pool/silverback-shaman.js";
import _poolSkullOfOrm from "../pool/skull-of-orm.js";
import _poolSkullbriarTheWalkingGrave from "../pool/skullbriar-the-walking-grave.js";
import _poolSkylinePredator from "../pool/skyline-predator.js";
import _poolSleightOfHand from "../pool/sleight-of-hand.js";
import _poolSolemnOffering from "../pool/solemn-offering.js";
import _poolSoulOfTheRapids from "../pool/soul-of-the-rapids.js";
import _poolSpareSupplies from "../pool/spare-supplies.js";
import _poolSparkDouble from "../pool/spark-double.js";
import _poolSpectralSailor from "../pool/spectral-sailor.js";
import _poolSplendidReclamation from "../pool/splendid-reclamation.js";
import _poolStarlitAngel from "../pool/starlit-angel.js";
import _poolSteamVents from "../pool/steam-vents.js";
import _poolSterlingHound from "../pool/sterling-hound.js";
import _poolStoneKavu from "../pool/stone-kavu.js";
import _poolStoneSeederHierophant from "../pool/stone-seeder-hierophant.js";
import _poolStrangle from "../pool/strangle.js";
import _poolStromkirkCaptain from "../pool/stromkirk-captain.js";
import _poolSulfurVent from "../pool/sulfur-vent.js";
import _poolSunspireGriffin from "../pool/sunspire-griffin.js";
import _poolSupplyLineCranes from "../pool/supply-line-cranes.js";
import _poolSurveillanceRoom from "../pool/surveillance-room.js";
import _poolSymbioticWurm from "../pool/symbiotic-wurm.js";
import _poolTakeAGlance from "../pool/take-a-glance.js";
import _poolTangledIslet from "../pool/tangled-islet.js";
import _poolTarpan from "../pool/tarpan.js";
import _poolTcriBuilding from "../pool/tcri-building.js";
import _poolTempleOfTheFalseGod from "../pool/temple-of-the-false-god.js";
import _poolTemurAscendancy from "../pool/temur-ascendancy.js";
import _poolTesharAncestorsApostle from "../pool/teshar-ancestors-apostle.js";
import _poolTheGaffer from "../pool/the-gaffer.js";
import _poolTheIncredibleHulk from "../pool/the-incredible-hulk.js";
import _poolTheUnspeakable from "../pool/the-unspeakable.js";
import _poolThrillOfTheHunt from "../pool/thrill-of-the-hunt.js";
import _poolThrivingBluff from "../pool/thriving-bluff.js";
import _poolThrivingMoor from "../pool/thriving-moor.js";
import _poolTidings from "../pool/tidings.js";
import _poolTurnToFrog from "../pool/turn-to-frog.js";
import _poolTwinferno from "../pool/twinferno.js";
import _poolUndercityDireRat from "../pool/undercity-dire-rat.js";
import _poolUrbanDaggertooth from "../pool/urban-daggertooth.js";
import _poolUtopiaTree from "../pool/utopia-tree.js";
import _poolValakutStoneforge from "../pool/valakut-stoneforge.js";
import _poolVeneratedRotpriest from "../pool/venerated-rotpriest.js";
import _poolVonaButcherOfMagan from "../pool/vona-butcher-of-magan.js";
import _poolVraskasContempt from "../pool/vraskas-contempt.js";
import _poolWallOfRoots from "../pool/wall-of-roots.js";
import _poolWanderingArchaic from "../pool/wandering-archaic.js";
import _poolWhiteKnight from "../pool/white-knight.js";
import _poolWittyRoastmaster from "../pool/witty-roastmaster.js";
import _poolWoeStrider from "../pool/woe-strider.js";
import _poolWoodlandChasm from "../pool/woodland-chasm.js";
import _poolWornPowerstone from "../pool/worn-powerstone.js";
import _poolWraithViciousVigilante from "../pool/wraith-vicious-vigilante.js";
import _poolWreckageWickerfolk from "../pool/wreckage-wickerfolk.js";
import _poolYoungRedDragon from "../pool/young-red-dragon.js";
import _poolYoungWeiRecruits from "../pool/young-wei-recruits.js";
import _tokensBirdToken from "../tokens/bird-token.js";
import _tokensCatBirdToken from "../tokens/cat-bird-token.js";
import _tokensConstructTokenArtifactCount from "../tokens/construct-token-artifact-count.js";
import _tokensElfDruidToken from "../tokens/elf-druid-token.js";
import _tokensPlantToken from "../tokens/plant-token.js";

const shard: CardShard = {
  pool: [
    _poolAbyssalGatekeeper,
    _poolAlabornMusketeer,
    _poolAnafenzaTheForemost,
    _poolAnodetLurker,
    _poolAppetiteForTheUnnatural,
    _poolArchonOfCruelty,
    _poolArmyOfTheDamned,
    _poolAtarkaWorldRender,
    _poolAvacynAngelOfHope,
    _poolBakeIntoAPie,
    _poolBeastWithin,
    _poolBehemothSledge,
    _poolBellowingAegisaur,
    _poolBlightedCataract,
    _poolBrotherhoodPatriarch,
    _poolCanopyGargantuan,
    _poolCaptainOfUmbar,
    _poolCaptivatingVampire,
    _poolCarvenCaryatid,
    _poolCavesOfKoilos,
    _poolChitterspitter,
    _poolChivalricAlliance,
    _poolCinderBarrens,
    _poolCommandTower,
    _poolCondemn,
    _poolCrashingDrawbridge,
    _poolCrucibleOfFire,
    _poolDeadlyDerision,
    _poolDeadlyVisit,
    _poolDecimate,
    _poolDeeptreadMerrow,
    _poolDefenseOfTheHeart,
    _poolDementiaBat,
    _poolDiscipleOfTheOldWays,
    _poolDoctorDoomKingOfLatveria,
    _poolDogmeatEverLoyal,
    _poolDreamTwist,
    _poolEloiseNephaliaSleuth,
    _poolEmeriaAngel,
    _poolErraticVisionary,
    _poolFaerieDuelist,
    _poolFanBearer,
    _poolFeebleness,
    _poolFireSprites,
    _poolFlamewaveInvoker,
    _poolFlight,
    _poolForsakenMonument,
    _poolFyndhornBow,
    _poolGalvanicIteration,
    _poolGalvanicKey,
    _poolGameTrail,
    _poolGiadaFontOfHope,
    _poolGisaAndGeralf,
    _poolGlissasCourier,
    _poolGnawingVermin,
    _poolGoblinCannon,
    _poolGoldlustTriad,
    _poolGoldmeadowHarrier,
    _poolGontiCannyAcquisitor,
    _poolGorgonsHead,
    _poolGuardianKirin,
    _poolHalimarDepths,
    _poolHaplessResearcher,
    _poolHarrierNaga,
    _poolHarvestSeason,
    _poolHealersHawk,
    _poolHengeOfRamos,
    _poolHourOfDefeat,
    _poolHowlingFury,
    _poolIchorWellspring,
    _poolImperiousPerfect,
    _poolInfiniteGuidelineStation,
    _poolInsomniaCrownCity,
    _poolIntoTheFloodMaw,
    _poolIrrigationDitch,
    _poolIsshinTwoHeavensAsOne,
    _poolIvyGleefulSpellthief,
    _poolIxhelScionOfAtraxa,
    _poolJandorsSaddlebags,
    _poolKamiOfTwistedReflection,
    _poolKoalaSheep,
    _poolKolaghansCommand,
    _poolKorCartographer,
    _poolKrarkClanStoker,
    _poolKravensCats,
    _poolLaboratoryDrudge,
    _poolLlanowarTribe,
    _poolLoxodonMystic,
    _poolLurchingRotbeast,
    _poolMachinesmithAutomaton,
    _poolMahadiEmporiumMaster,
    _poolMakindiMesas,
    _poolMalevolentAwakening,
    _poolMerfolkCoralsmith,
    _poolMetallicSliver,
    _poolMinotaurAggressor,
    _poolMorbidHunger,
    _poolMortify,
    _poolMossKami,
    _poolMossViper,
    _poolNadirKraken,
    _poolNettleSwine,
    _poolNimbusWings,
    _poolNoblePanther,
    _poolNyxbloomAncient,
    _poolNyxbornBrute,
    _poolOgreResister,
    _poolOracleOfMulDaya,
    _poolOrazcaFrillback,
    _poolPersist,
    _poolPiggyBank,
    _poolPrismariTheInspiration,
    _poolProsshSkyraiderOfKher,
    _poolProwlingSerpopard,
    _poolPsionicPulse,
    _poolPyroclasticElemental,
    _poolPyrohemia,
    _poolRampagingHippo,
    _poolRaugrinCrystal,
    _poolRayOfDissolution,
    _poolRejuvenatingSprings,
    _poolRelentlessAssault,
    _poolResculpt,
    _poolRighteousBlow,
    _poolRithsAttendant,
    _poolRocHunter,
    _poolRubblebeltRecluse,
    _poolRumbleArena,
    _poolRuneCervinRider,
    _poolRushwoodElemental,
    _poolSacredPrey,
    _poolSadisticHypnotist,
    _poolSagesReverie,
    _poolSalvagedManaworker,
    _poolScrapTrawler,
    _poolSeaGate,
    _poolSeacoastDrake,
    _poolSeasideCitadel,
    _poolSeatOfTheSynod,
    _poolSeleniaDarkAngel,
    _poolSerrasEmbrace,
    _poolShamblingGhoul,
    _poolSheHulkAttorneyAtLaw,
    _poolShelteredThicket,
    _poolSheoldredWhisperingOne,
    _poolShopkeepersBane,
    _poolSilverbackShaman,
    _poolSkullOfOrm,
    _poolSkullbriarTheWalkingGrave,
    _poolSkylinePredator,
    _poolSleightOfHand,
    _poolSolemnOffering,
    _poolSoulOfTheRapids,
    _poolSpareSupplies,
    _poolSparkDouble,
    _poolSpectralSailor,
    _poolSplendidReclamation,
    _poolStarlitAngel,
    _poolSteamVents,
    _poolSterlingHound,
    _poolStoneKavu,
    _poolStoneSeederHierophant,
    _poolStrangle,
    _poolStromkirkCaptain,
    _poolSulfurVent,
    _poolSunspireGriffin,
    _poolSupplyLineCranes,
    _poolSurveillanceRoom,
    _poolSymbioticWurm,
    _poolTakeAGlance,
    _poolTangledIslet,
    _poolTarpan,
    _poolTcriBuilding,
    _poolTempleOfTheFalseGod,
    _poolTemurAscendancy,
    _poolTesharAncestorsApostle,
    _poolTheGaffer,
    _poolTheIncredibleHulk,
    _poolTheUnspeakable,
    _poolThrillOfTheHunt,
    _poolThrivingBluff,
    _poolThrivingMoor,
    _poolTidings,
    _poolTurnToFrog,
    _poolTwinferno,
    _poolUndercityDireRat,
    _poolUrbanDaggertooth,
    _poolUtopiaTree,
    _poolValakutStoneforge,
    _poolVeneratedRotpriest,
    _poolVonaButcherOfMagan,
    _poolVraskasContempt,
    _poolWallOfRoots,
    _poolWanderingArchaic,
    _poolWhiteKnight,
    _poolWittyRoastmaster,
    _poolWoeStrider,
    _poolWoodlandChasm,
    _poolWornPowerstone,
    _poolWraithViciousVigilante,
    _poolWreckageWickerfolk,
    _poolYoungRedDragon,
    _poolYoungWeiRecruits,
  ],
  tokens: [
    _tokensBirdToken,
    _tokensCatBirdToken,
    _tokensConstructTokenArtifactCount,
    _tokensElfDruidToken,
    _tokensPlantToken,
  ],
};

export default shard;
