// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.
// Run `npm run gen:cards -w engine` after adding or removing a card file.

import type { CardShard } from "../card-shards.js";

import _poolAIMLabs from "../pool/a-i-m-labs.js";
import _poolAangDestinedSavior from "../pool/aang-destined-savior.js";
import _poolAbyssalHorror from "../pool/abyssal-horror.js";
import _poolAdarkarWastes from "../pool/adarkar-wastes.js";
import _poolAdventurersInn from "../pool/adventurers-inn.js";
import _poolAegisTurtle from "../pool/aegis-turtle.js";
import _poolAmprynTactician from "../pool/ampryn-tactician.js";
import _poolAnabaShaman from "../pool/anaba-shaman.js";
import _poolAnkleShanker from "../pool/ankle-shanker.js";
import _poolAragornKingOfGondor from "../pool/aragorn-king-of-gondor.js";
import _poolArgothianEnchantress from "../pool/argothian-enchantress.js";
import _poolAspectOfGorgon from "../pool/aspect-of-gorgon.js";
import _poolAtzocanSeer from "../pool/atzocan-seer.js";
import _poolAuriokTransfixer from "../pool/auriok-transfixer.js";
import _poolAvenFisher from "../pool/aven-fisher.js";
import _poolAzoriusGuildgate from "../pool/azorius-guildgate.js";
import _poolAzulaAlwaysLies from "../pool/azula-always-lies.js";
import _poolBilboBirthdayCelebrant from "../pool/bilbo-birthday-celebrant.js";
import _poolBlackPantherVanguard from "../pool/black-panther-vanguard.js";
import _poolBlackbladeReforged from "../pool/blackblade-reforged.js";
import _poolBloodArtist from "../pool/blood-artist.js";
import _poolBloodPet from "../pool/blood-pet.js";
import _poolBloodbraidElf from "../pool/bloodbraid-elf.js";
import _poolBorderGuard from "../pool/border-guard.js";
import _poolBotanicalPlaza from "../pool/botanical-plaza.js";
import _poolBraveKinDuo from "../pool/brave-kin-duo.js";
import _poolBringBack from "../pool/bring-back.js";
import _poolBurdenedAerialist from "../pool/burdened-aerialist.js";
import _poolBurrogBanemaker from "../pool/burrog-banemaker.js";
import _poolCameraLauncher from "../pool/camera-launcher.js";
import _poolCaveSense from "../pool/cave-sense.js";
import _poolCelestialForce from "../pool/celestial-force.js";
import _poolChainToMemory from "../pool/chain-to-memory.js";
import _poolClockOfOmens from "../pool/clock-of-omens.js";
import _poolCloudOfFaeries from "../pool/cloud-of-faeries.js";
import _poolCloudshift from "../pool/cloudshift.js";
import _poolCoastalHornclaw from "../pool/coastal-hornclaw.js";
import _poolCollectiveBlessing from "../pool/collective-blessing.js";
import _poolConclaveNaturalists from "../pool/conclave-naturalists.js";
import _poolConduitPylons from "../pool/conduit-pylons.js";
import _poolCosmiumBlast from "../pool/cosmium-blast.js";
import _poolCrossbowInfantry from "../pool/crossbow-infantry.js";
import _poolCruelFinality from "../pool/cruel-finality.js";
import _poolCryptGhast from "../pool/crypt-ghast.js";
import _poolDeftDuelist from "../pool/deft-duelist.js";
import _poolDerangedOutcast from "../pool/deranged-outcast.js";
import _poolDesolationProwler from "../pool/desolation-prowler.js";
import _poolDimirAqueduct from "../pool/dimir-aqueduct.js";
import _poolDirtwaterWraith from "../pool/dirtwater-wraith.js";
import _poolDisperse from "../pool/disperse.js";
import _poolDreamBeavers from "../pool/dream-beavers.js";
import _poolDreamrootCascade from "../pool/dreamroot-cascade.js";
import _poolDromokaWarrior from "../pool/dromoka-warrior.js";
import _poolElasIlKorSadisticPilgrim from "../pool/elas-il-kor-sadistic-pilgrim.js";
import _poolEmeraldMedallion from "../pool/emerald-medallion.js";
import _poolEnergizer from "../pool/energizer.js";
import _poolEnhancedAwareness from "../pool/enhanced-awareness.js";
import _poolEreborFlamesmith from "../pool/erebor-flamesmith.js";
import _poolExecutionersHood from "../pool/executioners-hood.js";
import _poolFangOfShigeki from "../pool/fang-of-shigeki.js";
import _poolFencingAce from "../pool/fencing-ace.js";
import _poolFeralKrushok from "../pool/feral-krushok.js";
import _poolFirefly from "../pool/firefly.js";
import _poolFloodfarmVerge from "../pool/floodfarm-verge.js";
import _poolFortuitousFind from "../pool/fortuitous-find.js";
import _poolFrenziedRaptor from "../pool/frenzied-raptor.js";
import _poolFrogSquirrels from "../pool/frog-squirrels.js";
import _poolFuelTheFlames from "../pool/fuel-the-flames.js";
import _poolFurtiveAnalyst from "../pool/furtive-analyst.js";
import _poolGaladhrimGuide from "../pool/galadhrim-guide.js";
import _poolGoreSwine from "../pool/gore-swine.js";
import _poolGoringCeratops from "../pool/goring-ceratops.js";
import _poolGrafMole from "../pool/graf-mole.js";
import _poolGravePact from "../pool/grave-pact.js";
import _poolGreaterForgeling from "../pool/greater-forgeling.js";
import _poolGrixisCharm from "../pool/grixis-charm.js";
import _poolHagraSharpshooter from "../pool/hagra-sharpshooter.js";
import _poolHardenedScaleArmor from "../pool/hardened-scale-armor.js";
import _poolHarvesterOfSouls from "../pool/harvester-of-souls.js";
import _poolHeliodsPilgrim from "../pool/heliods-pilgrim.js";
import _poolHexplateGolem from "../pool/hexplate-golem.js";
import _poolHorizonScholar from "../pool/horizon-scholar.js";
import _poolHorridVigor from "../pool/horrid-vigor.js";
import _poolHuatlisRaptor from "../pool/huatlis-raptor.js";
import _poolHurlerCyclops from "../pool/hurler-cyclops.js";
import _poolIfritWardenOfInferno from "../pool/ifrit-warden-of-inferno.js";
import _poolIlMhegPixie from "../pool/il-mheg-pixie.js";
import _poolInkriseInfiltrator from "../pool/inkrise-infiltrator.js";
import _poolInspiringCall from "../pool/inspiring-call.js";
import _poolIntimidation from "../pool/intimidation.js";
import _poolIrohGrandLotus from "../pool/iroh-grand-lotus.js";
import _poolJeongJeongsDeserters from "../pool/jeong-jeongs-deserters.js";
import _poolKavuClimber from "../pool/kavu-climber.js";
import _poolKeenEyedArchers from "../pool/keen-eyed-archers.js";
import _poolKingpinsEnforcers from "../pool/kingpins-enforcers.js";
import _poolLavaglidePathway from "../pool/lavaglide-pathway.js";
import _poolLightOfHope from "../pool/light-of-hope.js";
import _poolLoporritScout from "../pool/loporrit-scout.js";
import _poolLumengridGargoyle from "../pool/lumengrid-gargoyle.js";
import _poolManyPartings from "../pool/many-partings.js";
import _poolMarkovPatrician from "../pool/markov-patrician.js";
import _poolMarshBoa from "../pool/marsh-boa.js";
import _poolMaryJaneWatson from "../pool/mary-jane-watson.js";
import _poolMeditationPools from "../pool/meditation-pools.js";
import _poolMessengerFalcons from "../pool/messenger-falcons.js";
import _poolMetastaticEvangel from "../pool/metastatic-evangel.js";
import _poolMetropolisSprite from "../pool/metropolis-sprite.js";
import _poolMoaningWall from "../pool/moaning-wall.js";
import _poolMoggRaider from "../pool/mogg-raider.js";
import _poolMoorishCavalry from "../pool/moorish-cavalry.js";
import _poolMoriokScavenger from "../pool/moriok-scavenger.js";
import _poolMurasaBrute from "../pool/murasa-brute.js";
import _poolMyrMoonvessel from "../pool/myr-moonvessel.js";
import _poolNayaBattlemage from "../pool/naya-battlemage.js";
import _poolNimbleInnovator from "../pool/nimble-innovator.js";
import _poolNimbleThopterist from "../pool/nimble-thopterist.js";
import _poolOfferImmortality from "../pool/offer-immortality.js";
import _poolOmenOfTheDead from "../pool/omen-of-the-dead.js";
import _poolOrcishBowmasters from "../pool/orcish-bowmasters.js";
import _poolPanharmonicon from "../pool/panharmonicon.js";
import _poolPantherWarriors from "../pool/panther-warriors.js";
import _poolPiousWayfarer from "../pool/pious-wayfarer.js";
import _poolPollutedDead from "../pool/polluted-dead.js";
import _poolPrakhataPillarBug from "../pool/prakhata-pillar-bug.js";
import _poolPurpleCrystalCrab from "../pool/purple-crystal-crab.js";
import _poolRazorfieldThresher from "../pool/razorfield-thresher.js";
import _poolReadyToRumble from "../pool/ready-to-rumble.js";
import _poolRejuvenate from "../pool/rejuvenate.js";
import _poolReturnOfTheWildspeaker from "../pool/return-of-the-wildspeaker.js";
import _poolReturnToBattle from "../pool/return-to-battle.js";
import _poolRiteOfReplication from "../pool/rite-of-replication.js";
import _poolRootwaterHunter from "../pool/rootwater-hunter.js";
import _poolSageOfLatNam from "../pool/sage-of-lat-nam.js";
import _poolSavageLands from "../pool/savage-lands.js";
import _poolSephirothsIntervention from "../pool/sephiroths-intervention.js";
import _poolSerumVisions from "../pool/serum-visions.js";
import _poolSetessanSkirmisher from "../pool/setessan-skirmisher.js";
import _poolShadowGlider from "../pool/shadow-glider.js";
import _poolShatteringBlow from "../pool/shattering-blow.js";
import _poolShivanHellkite from "../pool/shivan-hellkite.js";
import _poolShuSoldierFarmers from "../pool/shu-soldier-farmers.js";
import _poolSkyshroudElf from "../pool/skyshroud-elf.js";
import _poolSneeringShadewriter from "../pool/sneering-shadewriter.js";
import _poolSpinedThopter from "../pool/spined-thopter.js";
import _poolSpireMonitor from "../pool/spire-monitor.js";
import _poolSquire from "../pool/squire.js";
import _poolStarfieldVocalist from "../pool/starfield-vocalist.js";
import _poolSwelteringSuns from "../pool/sweltering-suns.js";
import _poolTangleMantis from "../pool/tangle-mantis.js";
import _poolTempleOfMalice from "../pool/temple-of-malice.js";
import _poolTheaterOfHorrors from "../pool/theater-of-horrors.js";
import _poolTitansGrave from "../pool/titans-grave.js";
import _poolTopazDragon from "../pool/topaz-dragon.js";
import _poolTophTheFirstMetalbender from "../pool/toph-the-first-metalbender.js";
import _poolTowerGargoyle from "../pool/tower-gargoyle.js";
import _poolTowerOfEons from "../pool/tower-of-eons.js";
import _poolTravelingMinister from "../pool/traveling-minister.js";
import _poolTreatsToShare from "../pool/treats-to-share.js";
import _poolTributeToTheWorldTree from "../pool/tribute-to-the-world-tree.js";
import _poolTripNoose from "../pool/trip-noose.js";
import _poolUmbrisFearManifest from "../pool/umbris-fear-manifest.js";
import _poolUnearth from "../pool/unearth.js";
import _poolUnexplainedDisappearance from "../pool/unexplained-disappearance.js";
import _poolUnfulfilledDesires from "../pool/unfulfilled-desires.js";
import _poolUniversityCampus from "../pool/university-campus.js";
import _poolVermiculos from "../pool/vermiculos.js";
import _poolVialOfPoison from "../pool/vial-of-poison.js";
import _poolVibrantCityscape from "../pool/vibrant-cityscape.js";
import _poolVineglimmerSnarl from "../pool/vineglimmer-snarl.js";
import _poolVituGhaziTheCityTree from "../pool/vitu-ghazi-the-city-tree.js";
import _poolVoidSnare from "../pool/void-snare.js";
import _poolVoltCharge from "../pool/volt-charge.js";
import _poolVulpineGoliath from "../pool/vulpine-goliath.js";
import _poolWallOfLostThoughts from "../pool/wall-of-lost-thoughts.js";
import _poolWanderersIntervention from "../pool/wanderers-intervention.js";
import _poolWarleadersCall from "../pool/warleaders-call.js";
import _poolWatcherInTheMist from "../pool/watcher-in-the-mist.js";
import _poolWateryGrave from "../pool/watery-grave.js";
import _poolWildwoodPatrol from "../pool/wildwood-patrol.js";
import _poolWindStrider from "../pool/wind-strider.js";
import _poolWindseekerCentaur from "../pool/windseeker-centaur.js";
import _poolWindsweptHeath from "../pool/windswept-heath.js";
import _poolZodiacTiger from "../pool/zodiac-tiger.js";
import _tokensDragonSpiritToken from "../tokens/dragon-spirit-token.js";
import _tokensGreenCatToken11 from "../tokens/green-cat-token-1-1.js";
import _tokensMyrToken from "../tokens/myr-token.js";

const shard: CardShard = {
  pool: [
    _poolAIMLabs,
    _poolAangDestinedSavior,
    _poolAbyssalHorror,
    _poolAdarkarWastes,
    _poolAdventurersInn,
    _poolAegisTurtle,
    _poolAmprynTactician,
    _poolAnabaShaman,
    _poolAnkleShanker,
    _poolAragornKingOfGondor,
    _poolArgothianEnchantress,
    _poolAspectOfGorgon,
    _poolAtzocanSeer,
    _poolAuriokTransfixer,
    _poolAvenFisher,
    _poolAzoriusGuildgate,
    _poolAzulaAlwaysLies,
    _poolBilboBirthdayCelebrant,
    _poolBlackPantherVanguard,
    _poolBlackbladeReforged,
    _poolBloodArtist,
    _poolBloodPet,
    _poolBloodbraidElf,
    _poolBorderGuard,
    _poolBotanicalPlaza,
    _poolBraveKinDuo,
    _poolBringBack,
    _poolBurdenedAerialist,
    _poolBurrogBanemaker,
    _poolCameraLauncher,
    _poolCaveSense,
    _poolCelestialForce,
    _poolChainToMemory,
    _poolClockOfOmens,
    _poolCloudOfFaeries,
    _poolCloudshift,
    _poolCoastalHornclaw,
    _poolCollectiveBlessing,
    _poolConclaveNaturalists,
    _poolConduitPylons,
    _poolCosmiumBlast,
    _poolCrossbowInfantry,
    _poolCruelFinality,
    _poolCryptGhast,
    _poolDeftDuelist,
    _poolDerangedOutcast,
    _poolDesolationProwler,
    _poolDimirAqueduct,
    _poolDirtwaterWraith,
    _poolDisperse,
    _poolDreamBeavers,
    _poolDreamrootCascade,
    _poolDromokaWarrior,
    _poolElasIlKorSadisticPilgrim,
    _poolEmeraldMedallion,
    _poolEnergizer,
    _poolEnhancedAwareness,
    _poolEreborFlamesmith,
    _poolExecutionersHood,
    _poolFangOfShigeki,
    _poolFencingAce,
    _poolFeralKrushok,
    _poolFirefly,
    _poolFloodfarmVerge,
    _poolFortuitousFind,
    _poolFrenziedRaptor,
    _poolFrogSquirrels,
    _poolFuelTheFlames,
    _poolFurtiveAnalyst,
    _poolGaladhrimGuide,
    _poolGoreSwine,
    _poolGoringCeratops,
    _poolGrafMole,
    _poolGravePact,
    _poolGreaterForgeling,
    _poolGrixisCharm,
    _poolHagraSharpshooter,
    _poolHardenedScaleArmor,
    _poolHarvesterOfSouls,
    _poolHeliodsPilgrim,
    _poolHexplateGolem,
    _poolHorizonScholar,
    _poolHorridVigor,
    _poolHuatlisRaptor,
    _poolHurlerCyclops,
    _poolIfritWardenOfInferno,
    _poolIlMhegPixie,
    _poolInkriseInfiltrator,
    _poolInspiringCall,
    _poolIntimidation,
    _poolIrohGrandLotus,
    _poolJeongJeongsDeserters,
    _poolKavuClimber,
    _poolKeenEyedArchers,
    _poolKingpinsEnforcers,
    _poolLavaglidePathway,
    _poolLightOfHope,
    _poolLoporritScout,
    _poolLumengridGargoyle,
    _poolManyPartings,
    _poolMarkovPatrician,
    _poolMarshBoa,
    _poolMaryJaneWatson,
    _poolMeditationPools,
    _poolMessengerFalcons,
    _poolMetastaticEvangel,
    _poolMetropolisSprite,
    _poolMoaningWall,
    _poolMoggRaider,
    _poolMoorishCavalry,
    _poolMoriokScavenger,
    _poolMurasaBrute,
    _poolMyrMoonvessel,
    _poolNayaBattlemage,
    _poolNimbleInnovator,
    _poolNimbleThopterist,
    _poolOfferImmortality,
    _poolOmenOfTheDead,
    _poolOrcishBowmasters,
    _poolPanharmonicon,
    _poolPantherWarriors,
    _poolPiousWayfarer,
    _poolPollutedDead,
    _poolPrakhataPillarBug,
    _poolPurpleCrystalCrab,
    _poolRazorfieldThresher,
    _poolReadyToRumble,
    _poolRejuvenate,
    _poolReturnOfTheWildspeaker,
    _poolReturnToBattle,
    _poolRiteOfReplication,
    _poolRootwaterHunter,
    _poolSageOfLatNam,
    _poolSavageLands,
    _poolSephirothsIntervention,
    _poolSerumVisions,
    _poolSetessanSkirmisher,
    _poolShadowGlider,
    _poolShatteringBlow,
    _poolShivanHellkite,
    _poolShuSoldierFarmers,
    _poolSkyshroudElf,
    _poolSneeringShadewriter,
    _poolSpinedThopter,
    _poolSpireMonitor,
    _poolSquire,
    _poolStarfieldVocalist,
    _poolSwelteringSuns,
    _poolTangleMantis,
    _poolTempleOfMalice,
    _poolTheaterOfHorrors,
    _poolTitansGrave,
    _poolTopazDragon,
    _poolTophTheFirstMetalbender,
    _poolTowerGargoyle,
    _poolTowerOfEons,
    _poolTravelingMinister,
    _poolTreatsToShare,
    _poolTributeToTheWorldTree,
    _poolTripNoose,
    _poolUmbrisFearManifest,
    _poolUnearth,
    _poolUnexplainedDisappearance,
    _poolUnfulfilledDesires,
    _poolUniversityCampus,
    _poolVermiculos,
    _poolVialOfPoison,
    _poolVibrantCityscape,
    _poolVineglimmerSnarl,
    _poolVituGhaziTheCityTree,
    _poolVoidSnare,
    _poolVoltCharge,
    _poolVulpineGoliath,
    _poolWallOfLostThoughts,
    _poolWanderersIntervention,
    _poolWarleadersCall,
    _poolWatcherInTheMist,
    _poolWateryGrave,
    _poolWildwoodPatrol,
    _poolWindStrider,
    _poolWindseekerCentaur,
    _poolWindsweptHeath,
    _poolZodiacTiger,
  ],
  tokens: [
    _tokensDragonSpiritToken,
    _tokensGreenCatToken11,
    _tokensMyrToken,
  ],
};

export default shard;
