// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.
// Run `npm run gen:cards -w engine` after adding or removing a card file.

import type { CardShard } from "../card-shards.js";

import _poolAIMSynthoids from "../pool/a-i-m-synthoids.js";
import _poolAdaptiveGemguard from "../pool/adaptive-gemguard.js";
import _poolAffaProtector from "../pool/affa-protector.js";
import _poolArdbert from "../pool/ardbert.js";
import _poolAttendedKnight from "../pool/attended-knight.js";
import _poolAuspiciousArrival from "../pool/auspicious-arrival.js";
import _poolBargain from "../pool/bargain.js";
import _poolBetorKinToAll from "../pool/betor-kin-to-all.js";
import _poolBlackChocobo from "../pool/black-chocobo.js";
import _poolBlightedBat from "../pool/blighted-bat.js";
import _poolBlisterBeetle from "../pool/blister-beetle.js";
import _poolBloodcrusherOfKhorne from "../pool/bloodcrusher-of-khorne.js";
import _poolBruseTarlBoorishHerder from "../pool/bruse-tarl-boorish-herder.js";
import _poolBuriedAlive from "../pool/buried-alive.js";
import _poolBurningFields from "../pool/burning-fields.js";
import _poolCadaverImp from "../pool/cadaver-imp.js";
import _poolCavernThoctar from "../pool/cavern-thoctar.js";
import _poolCelestialAncient from "../pool/celestial-ancient.js";
import _poolChargingBadger from "../pool/charging-badger.js";
import _poolCinderElemental from "../pool/cinder-elemental.js";
import _poolCodieVociferousCodex from "../pool/codie-vociferous-codex.js";
import _poolColorfulFeiyiSparrow from "../pool/colorful-feiyi-sparrow.js";
import _poolCoralBarrier from "../pool/coral-barrier.js";
import _poolCravenKnight from "../pool/craven-knight.js";
import _poolCrumblingVestige from "../pool/crumbling-vestige.js";
import _poolDamn from "../pool/damn.js";
import _poolDarkDeed from "../pool/dark-deed.js";
import _poolDarkOffering from "../pool/dark-offering.js";
import _poolDedicatedMartyr from "../pool/dedicated-martyr.js";
import _poolDemandAnswers from "../pool/demand-answers.js";
import _poolDesertDrake from "../pool/desert-drake.js";
import _poolDesolationTwin from "../pool/desolation-twin.js";
import _poolDouserOfLights from "../pool/douser-of-lights.js";
import _poolDragonsRageChanneler from "../pool/dragons-rage-channeler.js";
import _poolDramaticRescue from "../pool/dramatic-rescue.js";
import _poolDriftingShade from "../pool/drifting-shade.js";
import _poolDrownyardExplorers from "../pool/drownyard-explorers.js";
import _poolDwarvenBloodboiler from "../pool/dwarven-bloodboiler.js";
import _poolEleshNornMotherOfMachines from "../pool/elesh-norn-mother-of-machines.js";
import _poolErietteOfTheCharmedApple from "../pool/eriette-of-the-charmed-apple.js";
import _poolEtheriumAstrolabe from "../pool/etherium-astrolabe.js";
import _poolEyeOfRamos from "../pool/eye-of-ramos.js";
import _poolFadeIntoAntiquity from "../pool/fade-into-antiquity.js";
import _poolFairgroundsPatrol from "../pool/fairgrounds-patrol.js";
import _poolFinalDeath from "../pool/final-death.js";
import _poolFlightOfFancy from "../pool/flight-of-fancy.js";
import _poolFrogTongue from "../pool/frog-tongue.js";
import _poolGelectrode from "../pool/gelectrode.js";
import _poolGenerousVisitor from "../pool/generous-visitor.js";
import _poolGhostlySentinel from "../pool/ghostly-sentinel.js";
import _poolGleamingGeardrake from "../pool/gleaming-geardrake.js";
import _poolGlimmeringAngel from "../pool/glimmering-angel.js";
import _poolGoblinOffensive from "../pool/goblin-offensive.js";
import _poolGrayOgre from "../pool/gray-ogre.js";
import _poolGrazingGladehart from "../pool/grazing-gladehart.js";
import _poolGyreEngineer from "../pool/gyre-engineer.js";
import _poolHavocDevils from "../pool/havoc-devils.js";
import _poolHedronRover from "../pool/hedron-rover.js";
import _poolHithlainKnots from "../pool/hithlain-knots.js";
import _poolHulkingBugbear from "../pool/hulking-bugbear.js";
import _poolHuntersInsight from "../pool/hunters-insight.js";
import _poolHurloonMinotaur from "../pool/hurloon-minotaur.js";
import _poolIcecaveCrasher from "../pool/icecave-crasher.js";
import _poolImotekhTheStormlord from "../pool/imotekh-the-stormlord.js";
import _poolImperialCeratops from "../pool/imperial-ceratops.js";
import _poolJuggernaut from "../pool/juggernaut.js";
import _poolKazanduNectarpot from "../pool/kazandu-nectarpot.js";
import _poolKessigWolf from "../pool/kessig-wolf.js";
import _poolKnightlyValor from "../pool/knightly-valor.js";
import _poolKraulRaider from "../pool/kraul-raider.js";
import _poolKrovikanScoundrel from "../pool/krovikan-scoundrel.js";
import _poolKujarSeedsculptor from "../pool/kujar-seedsculptor.js";
import _poolLonelySandbar from "../pool/lonely-sandbar.js";
import _poolMagesGuile from "../pool/mages-guile.js";
import _poolMagmaticForce from "../pool/magmatic-force.js";
import _poolMantisEngine from "../pool/mantis-engine.js";
import _poolMemorialToGenius from "../pool/memorial-to-genius.js";
import _poolMessengersSpeed from "../pool/messengers-speed.js";
import _poolMistLeopard from "../pool/mist-leopard.js";
import _poolMistvaultBridge from "../pool/mistvault-bridge.js";
import _poolMorgueTheft from "../pool/morgue-theft.js";
import _poolNaturesSpiral from "../pool/natures-spiral.js";
import _poolNecroblossomSnarl from "../pool/necroblossom-snarl.js";
import _poolNephaliaDrownyard from "../pool/nephalia-drownyard.js";
import _poolNeurokReplica from "../pool/neurok-replica.js";
import _poolNezumiInformant from "../pool/nezumi-informant.js";
import _poolNipGwyllion from "../pool/nip-gwyllion.js";
import _poolNullBrooch from "../pool/null-brooch.js";
import _poolOjerAxonilDeepestMight from "../pool/ojer-axonil-deepest-might.js";
import _poolOldGhastbark from "../pool/old-ghastbark.js";
import _poolOnyxMage from "../pool/onyx-mage.js";
import _poolPetAvengers from "../pool/pet-avengers.js";
import _poolPhalanxVanguard from "../pool/phalanx-vanguard.js";
import _poolPlatedSlagwurm from "../pool/plated-slagwurm.js";
import _poolPrairieStream from "../pool/prairie-stream.js";
import _poolPrescientChimera from "../pool/prescient-chimera.js";
import _poolQilinsBlessing from "../pool/qilins-blessing.js";
import _poolQuaketuskBoar from "../pool/quaketusk-boar.js";
import _poolRaffinesTower from "../pool/raffines-tower.js";
import _poolRagingPoltergeist from "../pool/raging-poltergeist.js";
import _poolRenegadeDemon from "../pool/renegade-demon.js";
import _poolReprieve from "../pool/reprieve.js";
import _poolRevivingMelody from "../pool/reviving-melody.js";
import _poolRiverSneak from "../pool/river-sneak.js";
import _poolRuinsOfTrokair from "../pool/ruins-of-trokair.js";
import _poolRunedServitor from "../pool/runed-servitor.js";
import _poolSacredArmory from "../pool/sacred-armory.js";
import _poolSaheeliRadiantCreator from "../pool/saheeli-radiant-creator.js";
import _poolSanctuaryCat from "../pool/sanctuary-cat.js";
import _poolSavaiTriome from "../pool/savai-triome.js";
import _poolScarlandThrinax from "../pool/scarland-thrinax.js";
import _poolScatterArc from "../pool/scatter-arc.js";
import _poolSeaSpirit from "../pool/sea-spirit.js";
import _poolSerpentSpecialist from "../pool/serpent-specialist.js";
import _poolShadowcloakVampire from "../pool/shadowcloak-vampire.js";
import _poolShockingSharpshooter from "../pool/shocking-sharpshooter.js";
import _poolSimicGrowthChamber from "../pool/simic-growth-chamber.js";
import _poolSimicSkySwallower from "../pool/simic-sky-swallower.js";
import _poolSkaabWrangler from "../pool/skaab-wrangler.js";
import _poolSlagwoodsBridge from "../pool/slagwoods-bridge.js";
import _poolSneakAttack from "../pool/sneak-attack.js";
import _poolSoulknifeSpy from "../pool/soulknife-spy.js";
import _poolSpiritualGuardian from "../pool/spiritual-guardian.js";
import _poolSpottedGriffin from "../pool/spotted-griffin.js";
import _poolSteadfastness from "../pool/steadfastness.js";
import _poolStingingBarrier from "../pool/stinging-barrier.js";
import _poolStolenGrain from "../pool/stolen-grain.js";
import _poolStormFleetSprinter from "../pool/storm-fleet-sprinter.js";
import _poolStormfrontPegasus from "../pool/stormfront-pegasus.js";
import _poolSunscorchedDivide from "../pool/sunscorched-divide.js";
import _poolSurveyTheWreckage from "../pool/survey-the-wreckage.js";
import _poolSylvanCaryatid from "../pool/sylvan-caryatid.js";
import _poolTaiga from "../pool/taiga.js";
import _poolTempleAcolyte from "../pool/temple-acolyte.js";
import _poolTheMasterOfKeys from "../pool/the-master-of-keys.js";
import _poolTheUrDragon from "../pool/the-ur-dragon.js";
import _poolThoughtCourier from "../pool/thought-courier.js";
import _poolThrottle from "../pool/throttle.js";
import _poolTorWauki from "../pool/tor-wauki.js";
import _poolTuknirDeathlock from "../pool/tuknir-deathlock.js";
import _poolTymnaTheWeaver from "../pool/tymna-the-weaver.js";
import _poolUnderseaInvader from "../pool/undersea-invader.js";
import _poolViciousConquistador from "../pool/vicious-conquistador.js";
import _poolVictimize from "../pool/victimize.js";
import _poolVoicelessSpirit from "../pool/voiceless-spirit.js";
import _poolWallOfIce from "../pool/wall-of-ice.js";
import _poolWaterServant from "../pool/water-servant.js";
import _poolWeaponizeTheMonsters from "../pool/weaponize-the-monsters.js";
import _poolWeightOfTheUnderworld from "../pool/weight-of-the-underworld.js";
import _poolWithstandDeath from "../pool/withstand-death.js";
import _poolWortBoggartAuntie from "../pool/wort-boggart-auntie.js";
import _poolYellowScarvesTroops from "../pool/yellow-scarves-troops.js";
import _poolZookeeperMechan from "../pool/zookeeper-mechan.js";
import _tokensHornetToken from "../tokens/hornet-token.js";
import _tokensImpTokenJudith from "../tokens/imp-token-judith.js";
import _tokensRatToken from "../tokens/rat-token.js";
import _tokensSaprolingToken from "../tokens/saproling-token.js";
import _tokensSpawnToken from "../tokens/spawn-token.js";

const shard: CardShard = {
  pool: [
    _poolAIMSynthoids,
    _poolAdaptiveGemguard,
    _poolAffaProtector,
    _poolArdbert,
    _poolAttendedKnight,
    _poolAuspiciousArrival,
    _poolBargain,
    _poolBetorKinToAll,
    _poolBlackChocobo,
    _poolBlightedBat,
    _poolBlisterBeetle,
    _poolBloodcrusherOfKhorne,
    _poolBruseTarlBoorishHerder,
    _poolBuriedAlive,
    _poolBurningFields,
    _poolCadaverImp,
    _poolCavernThoctar,
    _poolCelestialAncient,
    _poolChargingBadger,
    _poolCinderElemental,
    _poolCodieVociferousCodex,
    _poolColorfulFeiyiSparrow,
    _poolCoralBarrier,
    _poolCravenKnight,
    _poolCrumblingVestige,
    _poolDamn,
    _poolDarkDeed,
    _poolDarkOffering,
    _poolDedicatedMartyr,
    _poolDemandAnswers,
    _poolDesertDrake,
    _poolDesolationTwin,
    _poolDouserOfLights,
    _poolDragonsRageChanneler,
    _poolDramaticRescue,
    _poolDriftingShade,
    _poolDrownyardExplorers,
    _poolDwarvenBloodboiler,
    _poolEleshNornMotherOfMachines,
    _poolErietteOfTheCharmedApple,
    _poolEtheriumAstrolabe,
    _poolEyeOfRamos,
    _poolFadeIntoAntiquity,
    _poolFairgroundsPatrol,
    _poolFinalDeath,
    _poolFlightOfFancy,
    _poolFrogTongue,
    _poolGelectrode,
    _poolGenerousVisitor,
    _poolGhostlySentinel,
    _poolGleamingGeardrake,
    _poolGlimmeringAngel,
    _poolGoblinOffensive,
    _poolGrayOgre,
    _poolGrazingGladehart,
    _poolGyreEngineer,
    _poolHavocDevils,
    _poolHedronRover,
    _poolHithlainKnots,
    _poolHulkingBugbear,
    _poolHuntersInsight,
    _poolHurloonMinotaur,
    _poolIcecaveCrasher,
    _poolImotekhTheStormlord,
    _poolImperialCeratops,
    _poolJuggernaut,
    _poolKazanduNectarpot,
    _poolKessigWolf,
    _poolKnightlyValor,
    _poolKraulRaider,
    _poolKrovikanScoundrel,
    _poolKujarSeedsculptor,
    _poolLonelySandbar,
    _poolMagesGuile,
    _poolMagmaticForce,
    _poolMantisEngine,
    _poolMemorialToGenius,
    _poolMessengersSpeed,
    _poolMistLeopard,
    _poolMistvaultBridge,
    _poolMorgueTheft,
    _poolNaturesSpiral,
    _poolNecroblossomSnarl,
    _poolNephaliaDrownyard,
    _poolNeurokReplica,
    _poolNezumiInformant,
    _poolNipGwyllion,
    _poolNullBrooch,
    _poolOjerAxonilDeepestMight,
    _poolOldGhastbark,
    _poolOnyxMage,
    _poolPetAvengers,
    _poolPhalanxVanguard,
    _poolPlatedSlagwurm,
    _poolPrairieStream,
    _poolPrescientChimera,
    _poolQilinsBlessing,
    _poolQuaketuskBoar,
    _poolRaffinesTower,
    _poolRagingPoltergeist,
    _poolRenegadeDemon,
    _poolReprieve,
    _poolRevivingMelody,
    _poolRiverSneak,
    _poolRuinsOfTrokair,
    _poolRunedServitor,
    _poolSacredArmory,
    _poolSaheeliRadiantCreator,
    _poolSanctuaryCat,
    _poolSavaiTriome,
    _poolScarlandThrinax,
    _poolScatterArc,
    _poolSeaSpirit,
    _poolSerpentSpecialist,
    _poolShadowcloakVampire,
    _poolShockingSharpshooter,
    _poolSimicGrowthChamber,
    _poolSimicSkySwallower,
    _poolSkaabWrangler,
    _poolSlagwoodsBridge,
    _poolSneakAttack,
    _poolSoulknifeSpy,
    _poolSpiritualGuardian,
    _poolSpottedGriffin,
    _poolSteadfastness,
    _poolStingingBarrier,
    _poolStolenGrain,
    _poolStormFleetSprinter,
    _poolStormfrontPegasus,
    _poolSunscorchedDivide,
    _poolSurveyTheWreckage,
    _poolSylvanCaryatid,
    _poolTaiga,
    _poolTempleAcolyte,
    _poolTheMasterOfKeys,
    _poolTheUrDragon,
    _poolThoughtCourier,
    _poolThrottle,
    _poolTorWauki,
    _poolTuknirDeathlock,
    _poolTymnaTheWeaver,
    _poolUnderseaInvader,
    _poolViciousConquistador,
    _poolVictimize,
    _poolVoicelessSpirit,
    _poolWallOfIce,
    _poolWaterServant,
    _poolWeaponizeTheMonsters,
    _poolWeightOfTheUnderworld,
    _poolWithstandDeath,
    _poolWortBoggartAuntie,
    _poolYellowScarvesTroops,
    _poolZookeeperMechan,
  ],
  tokens: [
    _tokensHornetToken,
    _tokensImpTokenJudith,
    _tokensRatToken,
    _tokensSaprolingToken,
    _tokensSpawnToken,
  ],
};

export default shard;
