// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.
// Run `npm run gen:cards -w engine` after adding or removing a card file.

import type { CardShard } from "../card-shards.js";

import _poolAgonyWarp from "../pool/agony-warp.js";
import _poolAmbitionsCost from "../pool/ambitions-cost.js";
import _poolAngelOfLight from "../pool/angel-of-light.js";
import _poolAngrathsRampage from "../pool/angraths-rampage.js";
import _poolArcRunner from "../pool/arc-runner.js";
import _poolArchaeologicalDig from "../pool/archaeological-dig.js";
import _poolAridMesa from "../pool/arid-mesa.js";
import _poolArmoredSkaab from "../pool/armored-skaab.js";
import _poolAttercop from "../pool/attercop.js";
import _poolAuraShards from "../pool/aura-shards.js";
import _poolAzoriusChancery from "../pool/azorius-chancery.js";
import _poolAzoriusKnightArbiter from "../pool/azorius-knight-arbiter.js";
import _poolBattlefieldRaptor from "../pool/battlefield-raptor.js";
import _poolBayouDragonfly from "../pool/bayou-dragonfly.js";
import _poolBenalishMarshal from "../pool/benalish-marshal.js";
import _poolBigScore from "../pool/big-score.js";
import _poolBilboBagginsBurglar from "../pool/bilbo-baggins-burglar.js";
import _poolBilliardRoom from "../pool/billiard-room.js";
import _poolBlackDragon from "../pool/black-dragon.js";
import _poolBlechLoafingPest from "../pool/blech-loafing-pest.js";
import _poolBlessedSpirits from "../pool/blessed-spirits.js";
import _poolBloodflowConnoisseur from "../pool/bloodflow-connoisseur.js";
import _poolBloodrockCyclops from "../pool/bloodrock-cyclops.js";
import _poolBloodstoneCameo from "../pool/bloodstone-cameo.js";
import _poolBorderlandMinotaur from "../pool/borderland-minotaur.js";
import _poolCapashenStandard from "../pool/capashen-standard.js";
import _poolCatacombCrocodile from "../pool/catacomb-crocodile.js";
import _poolCatapultSquad from "../pool/catapult-squad.js";
import _poolCephalidScout from "../pool/cephalid-scout.js";
import _poolChatterOfTheSquirrel from "../pool/chatter-of-the-squirrel.js";
import _poolCoordinatedCharge from "../pool/coordinated-charge.js";
import _poolCrossbowAmbush from "../pool/crossbow-ambush.js";
import _poolCryptOfTheEternals from "../pool/crypt-of-the-eternals.js";
import _poolDaringThunderThief from "../pool/daring-thunder-thief.js";
import _poolDarksteelIngot from "../pool/darksteel-ingot.js";
import _poolDarksteelRelic from "../pool/darksteel-relic.js";
import _poolDawnhartRejuvenator from "../pool/dawnhart-rejuvenator.js";
import _poolDazzlingLights from "../pool/dazzling-lights.js";
import _poolDeadlyPlot from "../pool/deadly-plot.js";
import _poolDemolitionField from "../pool/demolition-field.js";
import _poolEarthOriginYak from "../pool/earth-origin-yak.js";
import _poolEiganjoSeatOfTheEmpire from "../pool/eiganjo-seat-of-the-empire.js";
import _poolEncampmentKeeper from "../pool/encampment-keeper.js";
import _poolEnfeeblement from "../pool/enfeeblement.js";
import _poolErtaiTheCorrupted from "../pool/ertai-the-corrupted.js";
import _poolEtherealGuidance from "../pool/ethereal-guidance.js";
import _poolExclusionMage from "../pool/exclusion-mage.js";
import _poolFiligreeFamiliar from "../pool/filigree-familiar.js";
import _poolFirescreamer from "../pool/firescreamer.js";
import _poolFiskTower from "../pool/fisk-tower.js";
import _poolFrogButler from "../pool/frog-butler.js";
import _poolFrontierSiege from "../pool/frontier-siege.js";
import _poolFuneralCharm from "../pool/funeral-charm.js";
import _poolGhirapurGearcrafter from "../pool/ghirapur-gearcrafter.js";
import _poolGhostLitRedeemer from "../pool/ghost-lit-redeemer.js";
import _poolGiantCockroach from "../pool/giant-cockroach.js";
import _poolGlowingAnemone from "../pool/glowing-anemone.js";
import _poolGrayMerchantOfAsphodel from "../pool/gray-merchant-of-asphodel.js";
import _poolGreenwoodSentinel from "../pool/greenwood-sentinel.js";
import _poolGustSkimmer from "../pool/gust-skimmer.js";
import _poolHaloScarab from "../pool/halo-scarab.js";
import _poolHavocJester from "../pool/havoc-jester.js";
import _poolHawkeyeClintBarton from "../pool/hawkeye-clint-barton.js";
import _poolHecteyes from "../pool/hecteyes.js";
import _poolHeraldOfTheFair from "../pool/herald-of-the-fair.js";
import _poolHighbornGhoul from "../pool/highborn-ghoul.js";
import _poolHiredBlade from "../pool/hired-blade.js";
import _poolHobgoblinDragoon from "../pool/hobgoblin-dragoon.js";
import _poolHorizonSeeker from "../pool/horizon-seeker.js";
import _poolHornetQueen from "../pool/hornet-queen.js";
import _poolIcatianPriest from "../pool/icatian-priest.js";
import _poolIdyllicTutor from "../pool/idyllic-tutor.js";
import _poolIgneousCur from "../pool/igneous-cur.js";
import _poolIncurableOgre from "../pool/incurable-ogre.js";
import _poolIronpawAspirant from "../pool/ironpaw-aspirant.js";
import _poolJunktown from "../pool/junktown.js";
import _poolKarnsBastion from "../pool/karns-bastion.js";
import _poolKeeningApparition from "../pool/keening-apparition.js";
import _poolKembasSkyguard from "../pool/kembas-skyguard.js";
import _poolKodamasReach from "../pool/kodamas-reach.js";
import _poolKongmingSleepingDragon from "../pool/kongming-sleeping-dragon.js";
import _poolLavaAxe from "../pool/lava-axe.js";
import _poolLeopardSpottedJiao from "../pool/leopard-spotted-jiao.js";
import _poolLightningBlast from "../pool/lightning-blast.js";
import _poolLostLegion from "../pool/lost-legion.js";
import _poolLotusGuardian from "../pool/lotus-guardian.js";
import _poolMakindiOx from "../pool/makindi-ox.js";
import _poolMammothSpider from "../pool/mammoth-spider.js";
import _poolManaPrism from "../pool/mana-prism.js";
import _poolMandibleJusticiar from "../pool/mandible-justiciar.js";
import _poolMarkOfFury from "../pool/mark-of-fury.js";
import _poolMastersCall from "../pool/masters-call.js";
import _poolMesaUnicorn from "../pool/mesa-unicorn.js";
import _poolMetathranSoldier from "../pool/metathran-soldier.js";
import _poolMiirymSentinelWyrm from "../pool/miirym-sentinel-wyrm.js";
import _poolMinamoSchoolAtWatersEdge from "../pool/minamo-school-at-waters-edge.js";
import _poolMireShade from "../pool/mire-shade.js";
import _poolMnemonicWall from "../pool/mnemonic-wall.js";
import _poolMoxOpal from "../pool/mox-opal.js";
import _poolMysticPeak from "../pool/mystic-peak.js";
import _poolNantukoElder from "../pool/nantuko-elder.js";
import _poolNarnamCobra from "../pool/narnam-cobra.js";
import _poolOhranFrostfang from "../pool/ohran-frostfang.js";
import _poolOvergrownFarmland from "../pool/overgrown-farmland.js";
import _poolPlasmancer from "../pool/plasmancer.js";
import _poolPollutedMire from "../pool/polluted-mire.js";
import _poolPongify from "../pool/pongify.js";
import _poolPrimevalHerald from "../pool/primeval-herald.js";
import _poolProdigiousGrowth from "../pool/prodigious-growth.js";
import _poolProtectorOfGondor from "../pool/protector-of-gondor.js";
import _poolPython from "../pool/python.js";
import _poolRainOfFilth from "../pool/rain-of-filth.js";
import _poolRakingClaws from "../pool/raking-claws.js";
import _poolRazakethTheFoulblooded from "../pool/razaketh-the-foulblooded.js";
import _poolReachThroughMists from "../pool/reach-through-mists.js";
import _poolRelicBarrier from "../pool/relic-barrier.js";
import _poolRenegadeTroops from "../pool/renegade-troops.js";
import _poolRimefurReindeer from "../pool/rimefur-reindeer.js";
import _poolRottedHulk from "../pool/rotted-hulk.js";
import _poolRuneScarredDemon from "../pool/rune-scarred-demon.js";
import _poolSelesnyaSignet from "../pool/selesnya-signet.js";
import _poolServoExhibition from "../pool/servo-exhibition.js";
import _poolSetessanTraining from "../pool/setessan-training.js";
import _poolShimmeringGrotto from "../pool/shimmering-grotto.js";
import _poolSkycloudExpanse from "../pool/skycloud-expanse.js";
import _poolSlobadGoblinTinkerer from "../pool/slobad-goblin-tinkerer.js";
import _poolSmash from "../pool/smash.js";
import _poolSolemnSimulacrum from "../pool/solemn-simulacrum.js";
import _poolSolveTheEquation from "../pool/solve-the-equation.js";
import _poolSorinOfHouseMarkov from "../pool/sorin-of-house-markov.js";
import _poolSouldrinker from "../pool/souldrinker.js";
import _poolSpiderwigBoggart from "../pool/spiderwig-boggart.js";
import _poolSporecapSpider from "../pool/sporecap-spider.js";
import _poolStormHerd from "../pool/storm-herd.js";
import _poolStrawSoldiers from "../pool/straw-soldiers.js";
import _poolStripedRiverwinder from "../pool/striped-riverwinder.js";
import _poolStrongarmMonk from "../pool/strongarm-monk.js";
import _poolSunTitan from "../pool/sun-titan.js";
import _poolSundialDawnTyrant from "../pool/sundial-dawn-tyrant.js";
import _poolSyrAlinTheLionsClaw from "../pool/syr-alin-the-lions-claw.js";
import _poolTanglespanLookout from "../pool/tanglespan-lookout.js";
import _poolTasseledDromedary from "../pool/tasseled-dromedary.js";
import _poolTeamTransmitter from "../pool/team-transmitter.js";
import _poolTerraStomper from "../pool/terra-stomper.js";
import _poolTerrainGenerator from "../pool/terrain-generator.js";
import _poolTheLordMasterOfHell from "../pool/the-lord-master-of-hell.js";
import _poolThermoAlchemist from "../pool/thermo-alchemist.js";
import _poolThorin from "../pool/thorin.js";
import _poolTidalKraken from "../pool/tidal-kraken.js";
import _poolTigraFelineFury from "../pool/tigra-feline-fury.js";
import _poolTrainedCaracal from "../pool/trained-caracal.js";
import _poolTraumaticCritique from "../pool/traumatic-critique.js";
import _poolTrokinHighGuard from "../pool/trokin-high-guard.js";
import _poolTwoHeadedZombie from "../pool/two-headed-zombie.js";
import _poolUndergrowthLeopard from "../pool/undergrowth-leopard.js";
import _poolUnnaturalRestoration from "../pool/unnatural-restoration.js";
import _poolValakutInvoker from "../pool/valakut-invoker.js";
import _poolVandalblast from "../pool/vandalblast.js";
import _poolVandalize from "../pool/vandalize.js";
import _poolVibraniumEnergyDaggers from "../pool/vibranium-energy-daggers.js";
import _poolVirtuousVariant from "../pool/virtuous-variant.js";
import _poolVolcanicVillain from "../pool/volcanic-villain.js";
import _poolWallOfRunes from "../pool/wall-of-runes.js";
import _poolWardenOfGeometries from "../pool/warden-of-geometries.js";
import _poolWardscaleCrocodile from "../pool/wardscale-crocodile.js";
import _poolWarpathGhoul from "../pool/warpath-ghoul.js";
import _poolWarpedLandscape from "../pool/warped-landscape.js";
import _poolWebWarriors from "../pool/web-warriors.js";
import _poolWindriderEel from "../pool/windrider-eel.js";
import _poolWindurstFederationCenter from "../pool/windurst-federation-center.js";
import _poolWinterflame from "../pool/winterflame.js";
import _poolWirewoodHivemaster from "../pool/wirewood-hivemaster.js";
import _poolZimoneInfiniteAnalyst from "../pool/zimone-infinite-analyst.js";
import _poolZofConsumption from "../pool/zof-consumption.js";
import _tokensVampireToken11 from "../tokens/vampire-token-1-1.js";

const shard: CardShard = {
  pool: [
    _poolAgonyWarp,
    _poolAmbitionsCost,
    _poolAngelOfLight,
    _poolAngrathsRampage,
    _poolArcRunner,
    _poolArchaeologicalDig,
    _poolAridMesa,
    _poolArmoredSkaab,
    _poolAttercop,
    _poolAuraShards,
    _poolAzoriusChancery,
    _poolAzoriusKnightArbiter,
    _poolBattlefieldRaptor,
    _poolBayouDragonfly,
    _poolBenalishMarshal,
    _poolBigScore,
    _poolBilboBagginsBurglar,
    _poolBilliardRoom,
    _poolBlackDragon,
    _poolBlechLoafingPest,
    _poolBlessedSpirits,
    _poolBloodflowConnoisseur,
    _poolBloodrockCyclops,
    _poolBloodstoneCameo,
    _poolBorderlandMinotaur,
    _poolCapashenStandard,
    _poolCatacombCrocodile,
    _poolCatapultSquad,
    _poolCephalidScout,
    _poolChatterOfTheSquirrel,
    _poolCoordinatedCharge,
    _poolCrossbowAmbush,
    _poolCryptOfTheEternals,
    _poolDaringThunderThief,
    _poolDarksteelIngot,
    _poolDarksteelRelic,
    _poolDawnhartRejuvenator,
    _poolDazzlingLights,
    _poolDeadlyPlot,
    _poolDemolitionField,
    _poolEarthOriginYak,
    _poolEiganjoSeatOfTheEmpire,
    _poolEncampmentKeeper,
    _poolEnfeeblement,
    _poolErtaiTheCorrupted,
    _poolEtherealGuidance,
    _poolExclusionMage,
    _poolFiligreeFamiliar,
    _poolFirescreamer,
    _poolFiskTower,
    _poolFrogButler,
    _poolFrontierSiege,
    _poolFuneralCharm,
    _poolGhirapurGearcrafter,
    _poolGhostLitRedeemer,
    _poolGiantCockroach,
    _poolGlowingAnemone,
    _poolGrayMerchantOfAsphodel,
    _poolGreenwoodSentinel,
    _poolGustSkimmer,
    _poolHaloScarab,
    _poolHavocJester,
    _poolHawkeyeClintBarton,
    _poolHecteyes,
    _poolHeraldOfTheFair,
    _poolHighbornGhoul,
    _poolHiredBlade,
    _poolHobgoblinDragoon,
    _poolHorizonSeeker,
    _poolHornetQueen,
    _poolIcatianPriest,
    _poolIdyllicTutor,
    _poolIgneousCur,
    _poolIncurableOgre,
    _poolIronpawAspirant,
    _poolJunktown,
    _poolKarnsBastion,
    _poolKeeningApparition,
    _poolKembasSkyguard,
    _poolKodamasReach,
    _poolKongmingSleepingDragon,
    _poolLavaAxe,
    _poolLeopardSpottedJiao,
    _poolLightningBlast,
    _poolLostLegion,
    _poolLotusGuardian,
    _poolMakindiOx,
    _poolMammothSpider,
    _poolManaPrism,
    _poolMandibleJusticiar,
    _poolMarkOfFury,
    _poolMastersCall,
    _poolMesaUnicorn,
    _poolMetathranSoldier,
    _poolMiirymSentinelWyrm,
    _poolMinamoSchoolAtWatersEdge,
    _poolMireShade,
    _poolMnemonicWall,
    _poolMoxOpal,
    _poolMysticPeak,
    _poolNantukoElder,
    _poolNarnamCobra,
    _poolOhranFrostfang,
    _poolOvergrownFarmland,
    _poolPlasmancer,
    _poolPollutedMire,
    _poolPongify,
    _poolPrimevalHerald,
    _poolProdigiousGrowth,
    _poolProtectorOfGondor,
    _poolPython,
    _poolRainOfFilth,
    _poolRakingClaws,
    _poolRazakethTheFoulblooded,
    _poolReachThroughMists,
    _poolRelicBarrier,
    _poolRenegadeTroops,
    _poolRimefurReindeer,
    _poolRottedHulk,
    _poolRuneScarredDemon,
    _poolSelesnyaSignet,
    _poolServoExhibition,
    _poolSetessanTraining,
    _poolShimmeringGrotto,
    _poolSkycloudExpanse,
    _poolSlobadGoblinTinkerer,
    _poolSmash,
    _poolSolemnSimulacrum,
    _poolSolveTheEquation,
    _poolSorinOfHouseMarkov,
    _poolSouldrinker,
    _poolSpiderwigBoggart,
    _poolSporecapSpider,
    _poolStormHerd,
    _poolStrawSoldiers,
    _poolStripedRiverwinder,
    _poolStrongarmMonk,
    _poolSunTitan,
    _poolSundialDawnTyrant,
    _poolSyrAlinTheLionsClaw,
    _poolTanglespanLookout,
    _poolTasseledDromedary,
    _poolTeamTransmitter,
    _poolTerraStomper,
    _poolTerrainGenerator,
    _poolTheLordMasterOfHell,
    _poolThermoAlchemist,
    _poolThorin,
    _poolTidalKraken,
    _poolTigraFelineFury,
    _poolTrainedCaracal,
    _poolTraumaticCritique,
    _poolTrokinHighGuard,
    _poolTwoHeadedZombie,
    _poolUndergrowthLeopard,
    _poolUnnaturalRestoration,
    _poolValakutInvoker,
    _poolVandalblast,
    _poolVandalize,
    _poolVibraniumEnergyDaggers,
    _poolVirtuousVariant,
    _poolVolcanicVillain,
    _poolWallOfRunes,
    _poolWardenOfGeometries,
    _poolWardscaleCrocodile,
    _poolWarpathGhoul,
    _poolWarpedLandscape,
    _poolWebWarriors,
    _poolWindriderEel,
    _poolWindurstFederationCenter,
    _poolWinterflame,
    _poolWirewoodHivemaster,
    _poolZimoneInfiniteAnalyst,
    _poolZofConsumption,
  ],
  tokens: [
    _tokensVampireToken11,
  ],
};

export default shard;
