// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.
// Run `npm run gen:cards -w engine` after adding or removing a card file.

import type { CardShard } from "../card-shards.js";

import _poolAbbeyGriffin from "../pool/abbey-griffin.js";
import _poolAccordersShield from "../pool/accorders-shield.js";
import _poolAerialDoombot from "../pool/aerial-doombot.js";
import _poolAerialResponder from "../pool/aerial-responder.js";
import _poolAfterlifeFromTheLoam from "../pool/afterlife-from-the-loam.js";
import _poolAgentOfKotis from "../pool/agent-of-kotis.js";
import _poolAkroanMastiff from "../pool/akroan-mastiff.js";
import _poolAlandraSkyDreamer from "../pool/alandra-sky-dreamer.js";
import _poolAltarsLight from "../pool/altars-light.js";
import _poolAminatouTheFateshifter from "../pool/aminatou-the-fateshifter.js";
import _poolAncientGreenwarden from "../pool/ancient-greenwarden.js";
import _poolAngelOfInvention from "../pool/angel-of-invention.js";
import _poolAngelicSkirmisher from "../pool/angelic-skirmisher.js";
import _poolArcaneSignet from "../pool/arcane-signet.js";
import _poolArrowsOfJustice from "../pool/arrows-of-justice.js";
import _poolAuthorityOfTheConsuls from "../pool/authority-of-the-consuls.js";
import _poolAxegrinderGiant from "../pool/axegrinder-giant.js";
import _poolBadgermole from "../pool/badgermole.js";
import _poolBagOfHolding from "../pool/bag-of-holding.js";
import _poolBardHeirOfGirion from "../pool/bard-heir-of-girion.js";
import _poolBarrowWitches from "../pool/barrow-witches.js";
import _poolBiteDown from "../pool/bite-down.js";
import _poolBlazemireVerge from "../pool/blazemire-verge.js";
import _poolBloodPact from "../pool/blood-pact.js";
import _poolBogImp from "../pool/bog-imp.js";
import _poolBoggartBrute from "../pool/boggart-brute.js";
import _poolBoilingRockPrison from "../pool/boiling-rock-prison.js";
import _poolBoneDevourer from "../pool/bone-devourer.js";
import _poolBrawn from "../pool/brawn.js";
import _poolBreathstealer from "../pool/breathstealer.js";
import _poolBredForTheHunt from "../pool/bred-for-the-hunt.js";
import _poolCactusfolkSureshot from "../pool/cactusfolk-sureshot.js";
import _poolCanopyGorger from "../pool/canopy-gorger.js";
import _poolCanopyTactician from "../pool/canopy-tactician.js";
import _poolCarrionAnts from "../pool/carrion-ants.js";
import _poolCastleEmbereth from "../pool/castle-embereth.js";
import _poolCatharsShield from "../pool/cathars-shield.js";
import _poolCavalierOfDawn from "../pool/cavalier-of-dawn.js";
import _poolCavernOfSouls from "../pool/cavern-of-souls.js";
import _poolCelestialUnicorn from "../pool/celestial-unicorn.js";
import _poolCloudreaderSphinx from "../pool/cloudreader-sphinx.js";
import _poolCoastalTower from "../pool/coastal-tower.js";
import _poolCommandersInsignia from "../pool/commanders-insignia.js";
import _poolCopyEnchantment from "../pool/copy-enchantment.js";
import _poolCoruscationMage from "../pool/coruscation-mage.js";
import _poolCragcrownPathway from "../pool/cragcrown-pathway.js";
import _poolCrawWurm from "../pool/craw-wurm.js";
import _poolCrazedGoblin from "../pool/crazed-goblin.js";
import _poolCreamOfTheCrop from "../pool/cream-of-the-crop.js";
import _poolCruelRevival from "../pool/cruel-revival.js";
import _poolCrypticCaves from "../pool/cryptic-caves.js";
import _poolCunningBreezedancer from "../pool/cunning-breezedancer.js";
import _poolDarkstarAugur from "../pool/darkstar-augur.js";
import _poolDawnhartDisciple from "../pool/dawnhart-disciple.js";
import _poolDeathcapMarionette from "../pool/deathcap-marionette.js";
import _poolDebtToTheDeathless from "../pool/debt-to-the-deathless.js";
import _poolDefyGravity from "../pool/defy-gravity.js";
import _poolDesertOfTheMindful from "../pool/desert-of-the-mindful.js";
import _poolDestroyEvil from "../pool/destroy-evil.js";
import _poolDiabolicEdict from "../pool/diabolic-edict.js";
import _poolDragonlordAtarka from "../pool/dragonlord-atarka.js";
import _poolDriftingMeadow from "../pool/drifting-meadow.js";
import _poolDualSunAdepts from "../pool/dual-sun-adepts.js";
import _poolDuskanaTheRageMother from "../pool/duskana-the-rage-mother.js";
import _poolEddieBrock from "../pool/eddie-brock.js";
import _poolEldraziTemple from "../pool/eldrazi-temple.js";
import _poolElsha from "../pool/elsha.js";
import _poolElvesOfDeepShadow from "../pool/elves-of-deep-shadow.js";
import _poolElvishChampion from "../pool/elvish-champion.js";
import _poolEmryLurkerOfTheLoch from "../pool/emry-lurker-of-the-loch.js";
import _poolEnslavedScout from "../pool/enslaved-scout.js";
import _poolEtchedFamiliar from "../pool/etched-familiar.js";
import _poolExperimentalAviator from "../pool/experimental-aviator.js";
import _poolFallOfTheGavel from "../pool/fall-of-the-gavel.js";
import _poolFatalFumes from "../pool/fatal-fumes.js";
import _poolFelhideMinotaur from "../pool/felhide-minotaur.js";
import _poolFelidarGuardian from "../pool/felidar-guardian.js";
import _poolFieldCreeper from "../pool/field-creeper.js";
import _poolFieryHellhound from "../pool/fiery-hellhound.js";
import _poolFireNationSentinels from "../pool/fire-nation-sentinels.js";
import _poolFlamekinBrawler from "../pool/flamekin-brawler.js";
import _poolFlowstoneHellion from "../pool/flowstone-hellion.js";
import _poolFlyingCarpet from "../pool/flying-carpet.js";
import _poolFountainOfYouth from "../pool/fountain-of-youth.js";
import _poolFrostboilSnarl from "../pool/frostboil-snarl.js";
import _poolFrostbridgeGuard from "../pool/frostbridge-guard.js";
import _poolFrostburnWeird from "../pool/frostburn-weird.js";
import _poolFungalSprouting from "../pool/fungal-sprouting.js";
import _poolFurnaceWhelp from "../pool/furnace-whelp.js";
import _poolFyndhornBrownie from "../pool/fyndhorn-brownie.js";
import _poolGalewindMoose from "../pool/galewind-moose.js";
import _poolGarnaBloodfistOfKeld from "../pool/garna-bloodfist-of-keld.js";
import _poolGiantsBoulder from "../pool/giants-boulder.js";
import _poolGoblinBalloonBrigade from "../pool/goblin-balloon-brigade.js";
import _poolGoblinPiker from "../pool/goblin-piker.js";
import _poolGreatHornKrushok from "../pool/great-horn-krushok.js";
import _poolGroveRumbler from "../pool/grove-rumbler.js";
import _poolHajarLoyalBodyguard from "../pool/hajar-loyal-bodyguard.js";
import _poolHeraldOfEternalDawn from "../pool/herald-of-eternal-dawn.js";
import _poolHinataDawnCrowned from "../pool/hinata-dawn-crowned.js";
import _poolHuatlisSnubhorn from "../pool/huatlis-snubhorn.js";
import _poolHullcarver from "../pool/hullcarver.js";
import _poolHundroog from "../pool/hundroog.js";
import _poolHungryGhoul from "../pool/hungry-ghoul.js";
import _poolIchorclawMyr from "../pool/ichorclaw-myr.js";
import _poolIlluminatedWings from "../pool/illuminated-wings.js";
import _poolImpactTremors from "../pool/impact-tremors.js";
import _poolImperialSeal from "../pool/imperial-seal.js";
import _poolInstantRamen from "../pool/instant-ramen.js";
import _poolIsolatedChapel from "../pool/isolated-chapel.js";
import _poolIzzetLocket from "../pool/izzet-locket.js";
import _poolJadecraftArtisan from "../pool/jadecraft-artisan.js";
import _poolJewelEyedCobra from "../pool/jewel-eyed-cobra.js";
import _poolJoinTheDance from "../pool/join-the-dance.js";
import _poolJourneyersKite from "../pool/journeyers-kite.js";
import _poolJudgesFamiliar from "../pool/judges-familiar.js";
import _poolJump from "../pool/jump.js";
import _poolKeenGlidemaster from "../pool/keen-glidemaster.js";
import _poolKeeperOfSecrets from "../pool/keeper-of-secrets.js";
import _poolKiboUktabiPrince from "../pool/kibo-uktabi-prince.js";
import _poolKiorasFollower from "../pool/kioras-follower.js";
import _poolKishlaVillage from "../pool/kishla-village.js";
import _poolKitesailScout from "../pool/kitesail-scout.js";
import _poolKnightOfMeadowgrain from "../pool/knight-of-meadowgrain.js";
import _poolKotisSibsigChampion from "../pool/kotis-sibsig-champion.js";
import _poolKrakenHatchling from "../pool/kraken-hatchling.js";
import _poolKranioceros from "../pool/kranioceros.js";
import _poolKutzilMalametExemplar from "../pool/kutzil-malamet-exemplar.js";
import _poolLegionLoyalty from "../pool/legion-loyalty.js";
import _poolLightningHelix from "../pool/lightning-helix.js";
import _poolLordSkittersButcher from "../pool/lord-skitters-butcher.js";
import _poolLuminousBroodmoth from "../pool/luminous-broodmoth.js";
import _poolMagmakinArtillerist from "../pool/magmakin-artillerist.js";
import _poolMagusOfTheBazaar from "../pool/magus-of-the-bazaar.js";
import _poolMassacreWurm from "../pool/massacre-wurm.js";
import _poolMerfolkOfTheDepths from "../pool/merfolk-of-the-depths.js";
import _poolMerfolkSovereign from "../pool/merfolk-sovereign.js";
import _poolMidnightBanshee from "../pool/midnight-banshee.js";
import _poolMigratingKetradon from "../pool/migrating-ketradon.js";
import _poolMindslicer from "../pool/mindslicer.js";
import _poolMishrasFactory from "../pool/mishras-factory.js";
import _poolMithrilCoat from "../pool/mithril-coat.js";
import _poolMonstrousCarabid from "../pool/monstrous-carabid.js";
import _poolMorphling from "../pool/morphling.js";
import _poolNarsetEnlightenedMaster from "../pool/narset-enlightened-master.js";
import _poolNezumiBoneReader from "../pool/nezumi-bone-reader.js";
import _poolNomadicElf from "../pool/nomadic-elf.js";
import _poolNoviceDissector from "../pool/novice-dissector.js";
import _poolOakenBoon from "../pool/oaken-boon.js";
import _poolOmenOfTheHunt from "../pool/omen-of-the-hunt.js";
import _poolOnduSkyruins from "../pool/ondu-skyruins.js";
import _poolOrcishLumberjack from "../pool/orcish-lumberjack.js";
import _poolOrzhovCluestone from "../pool/orzhov-cluestone.js";
import _poolOverflowingInsight from "../pool/overflowing-insight.js";
import _poolPersonalTutor from "../pool/personal-tutor.js";
import _poolPhyrexianDelver from "../pool/phyrexian-delver.js";
import _poolPhyrexianVivisector from "../pool/phyrexian-vivisector.js";
import _poolPickYourPoison from "../pool/pick-your-poison.js";
import _poolPiousInterdiction from "../pool/pious-interdiction.js";
import _poolPiranhaFly from "../pool/piranha-fly.js";
import _poolPridemalkin from "../pool/pridemalkin.js";
import _poolRakdosGuildgate from "../pool/rakdos-guildgate.js";
import _poolRampantGrowth from "../pool/rampant-growth.js";
import _poolRangersPath from "../pool/rangers-path.js";
import _poolRavagedHighlands from "../pool/ravaged-highlands.js";
import _poolRavenousSquirrel from "../pool/ravenous-squirrel.js";
import _poolRazorgrassAmbush from "../pool/razorgrass-ambush.js";
import _poolRearingEmbermare from "../pool/rearing-embermare.js";
import _poolReconstruction from "../pool/reconstruction.js";
import _poolResurgentBelief from "../pool/resurgent-belief.js";
import _poolRhoxWarMonk from "../pool/rhox-war-monk.js";
import _poolRhysTheRedeemed from "../pool/rhys-the-redeemed.js";
import _poolRideTheRails from "../pool/ride-the-rails.js";
import _poolRimewoodFalls from "../pool/rimewood-falls.js";
import _poolRipscalePredator from "../pool/ripscale-predator.js";
import _poolRitesOfFlourishing from "../pool/rites-of-flourishing.js";
import _poolRivenTurnbull from "../pool/riven-turnbull.js";
import _poolRottingMastodon from "../pool/rotting-mastodon.js";
import _poolRoyalFalcon from "../pool/royal-falcon.js";
import _poolRussetWolves from "../pool/russet-wolves.js";
import _poolSakuraTribeElder from "../pool/sakura-tribe-elder.js";
import _poolSanguineSyphoner from "../pool/sanguine-syphoner.js";
import _poolSarumansTrickery from "../pool/sarumans-trickery.js";
import _poolScarwoodGoblins from "../pool/scarwood-goblins.js";
import _poolScorchingShot from "../pool/scorching-shot.js";
import _poolScreechingPhoenix from "../pool/screeching-phoenix.js";
import _poolSeaOfClouds from "../pool/sea-of-clouds.js";
import _poolSealOfRemoval from "../pool/seal-of-removal.js";
import _poolSecludedCourtyard from "../pool/secluded-courtyard.js";
import _poolSelflessCathar from "../pool/selfless-cathar.js";
import _poolSharedRoots from "../pool/shared-roots.js";
import _poolShortBow from "../pool/short-bow.js";
import _poolSiegeGangLieutenant from "../pool/siege-gang-lieutenant.js";
import _poolSkullOfRamos from "../pool/skull-of-ramos.js";
import _poolSoliton from "../pool/soliton.js";
import _poolSoporificSprings from "../pool/soporific-springs.js";
import _poolSoulstoneSanctuary from "../pool/soulstone-sanctuary.js";
import _poolSpawningPit from "../pool/spawning-pit.js";
import _poolSphinxSummoner from "../pool/sphinx-summoner.js";
import _poolSpinalCentipede from "../pool/spinal-centipede.js";
import _poolStampedingRhino from "../pool/stampeding-rhino.js";
import _poolSteadfastSentry from "../pool/steadfast-sentry.js";
import _poolStirge from "../pool/stirge.js";
import _poolStompingGround from "../pool/stomping-ground.js";
import _poolStrandsOfNight from "../pool/strands-of-night.js";
import _poolStubbornDenial from "../pool/stubborn-denial.js";
import _poolSunBlessedPeak from "../pool/sun-blessed-peak.js";
import _poolSunlitMarsh from "../pool/sunlit-marsh.js";
import _poolSvyelunOfSeaAndSky from "../pool/svyelun-of-sea-and-sky.js";
import _poolSwiftEnd from "../pool/swift-end.js";
import _poolSwiftSpinner from "../pool/swift-spinner.js";
import _poolSylvanBrushstrider from "../pool/sylvan-brushstrider.js";
import _poolSylvanRanger from "../pool/sylvan-ranger.js";
import _poolSylvanReclamation from "../pool/sylvan-reclamation.js";
import _poolSyrGwynHeroOfAshvale from "../pool/syr-gwyn-hero-of-ashvale.js";
import _poolTamiyosJournal from "../pool/tamiyos-journal.js";
import _poolTarPitcher from "../pool/tar-pitcher.js";
import _poolTectonicGiant from "../pool/tectonic-giant.js";
import _poolTempleGarden from "../pool/temple-garden.js";
import _poolTevalsJudgment from "../pool/tevals-judgment.js";
import _poolTheDrossPits from "../pool/the-dross-pits.js";
import _poolTheJollyBalloonMan from "../pool/the-jolly-balloon-man.js";
import _poolThornwindFaeries from "../pool/thornwind-faeries.js";
import _poolTitanothRex from "../pool/titanoth-rex.js";
import _poolTomeOfLegends from "../pool/tome-of-legends.js";
import _poolTouchstone from "../pool/touchstone.js";
import _poolTriumphOfTheHordes from "../pool/triumph-of-the-hordes.js";
import _poolTrollHornCameo from "../pool/troll-horn-cameo.js";
import _poolTrygonPredator from "../pool/trygon-predator.js";
import _poolTurtleLair from "../pool/turtle-lair.js";
import _poolUkudCobra from "../pool/ukud-cobra.js";
import _poolUlvenwaldHydra from "../pool/ulvenwald-hydra.js";
import _poolUnhinge from "../pool/unhinge.js";
import _poolValiantGuard from "../pool/valiant-guard.js";
import _poolViashinoSandsprinter from "../pool/viashino-sandsprinter.js";
import _poolVillainousWrath from "../pool/villainous-wrath.js";
import _poolVivVisionTeenSynthezoid from "../pool/viv-vision-teen-synthezoid.js";
import _poolVoiceOfMany from "../pool/voice-of-many.js";
import _poolVoidwielder from "../pool/voidwielder.js";
import _poolVulshokMorningstar from "../pool/vulshok-morningstar.js";
import _poolWardenOfEvosIsle from "../pool/warden-of-evos-isle.js";
import _poolWarriorsCharge from "../pool/warriors-charge.js";
import _poolWarshipScout from "../pool/warship-scout.js";
import _poolWaspLancer from "../pool/wasp-lancer.js";
import _poolWeftstalkerArdent from "../pool/weftstalker-ardent.js";
import _poolWildAesthir from "../pool/wild-aesthir.js";
import _poolWildWanderer from "../pool/wild-wanderer.js";
import _poolWingedTempleOfOrazca from "../pool/winged-temple-of-orazca.js";
import _poolWingmantleChaplain from "../pool/wingmantle-chaplain.js";
import _poolWinotaJoinerOfForces from "../pool/winota-joiner-of-forces.js";
import _poolWoodlandPatrol from "../pool/woodland-patrol.js";
import _poolZephid from "../pool/zephid.js";
import _poolZephyrCharge from "../pool/zephyr-charge.js";
import _poolZndrspltEyeOfWisdom from "../pool/zndrsplt-eye-of-wisdom.js";
import _tokensBatToken from "../tokens/bat-token.js";
import _tokensClueToken from "../tokens/clue-token.js";
import _tokensGolemTrampleToken from "../tokens/golem-trample-token.js";
import _tokensHumanWarriorToken from "../tokens/human-warrior-token.js";
import _tokensPegasusToken22 from "../tokens/pegasus-token-2-2.js";
import _tokensSpiritToken from "../tokens/spirit-token.js";

const shard: CardShard = {
  pool: [
    _poolAbbeyGriffin,
    _poolAccordersShield,
    _poolAerialDoombot,
    _poolAerialResponder,
    _poolAfterlifeFromTheLoam,
    _poolAgentOfKotis,
    _poolAkroanMastiff,
    _poolAlandraSkyDreamer,
    _poolAltarsLight,
    _poolAminatouTheFateshifter,
    _poolAncientGreenwarden,
    _poolAngelOfInvention,
    _poolAngelicSkirmisher,
    _poolArcaneSignet,
    _poolArrowsOfJustice,
    _poolAuthorityOfTheConsuls,
    _poolAxegrinderGiant,
    _poolBadgermole,
    _poolBagOfHolding,
    _poolBardHeirOfGirion,
    _poolBarrowWitches,
    _poolBiteDown,
    _poolBlazemireVerge,
    _poolBloodPact,
    _poolBogImp,
    _poolBoggartBrute,
    _poolBoilingRockPrison,
    _poolBoneDevourer,
    _poolBrawn,
    _poolBreathstealer,
    _poolBredForTheHunt,
    _poolCactusfolkSureshot,
    _poolCanopyGorger,
    _poolCanopyTactician,
    _poolCarrionAnts,
    _poolCastleEmbereth,
    _poolCatharsShield,
    _poolCavalierOfDawn,
    _poolCavernOfSouls,
    _poolCelestialUnicorn,
    _poolCloudreaderSphinx,
    _poolCoastalTower,
    _poolCommandersInsignia,
    _poolCopyEnchantment,
    _poolCoruscationMage,
    _poolCragcrownPathway,
    _poolCrawWurm,
    _poolCrazedGoblin,
    _poolCreamOfTheCrop,
    _poolCruelRevival,
    _poolCrypticCaves,
    _poolCunningBreezedancer,
    _poolDarkstarAugur,
    _poolDawnhartDisciple,
    _poolDeathcapMarionette,
    _poolDebtToTheDeathless,
    _poolDefyGravity,
    _poolDesertOfTheMindful,
    _poolDestroyEvil,
    _poolDiabolicEdict,
    _poolDragonlordAtarka,
    _poolDriftingMeadow,
    _poolDualSunAdepts,
    _poolDuskanaTheRageMother,
    _poolEddieBrock,
    _poolEldraziTemple,
    _poolElsha,
    _poolElvesOfDeepShadow,
    _poolElvishChampion,
    _poolEmryLurkerOfTheLoch,
    _poolEnslavedScout,
    _poolEtchedFamiliar,
    _poolExperimentalAviator,
    _poolFallOfTheGavel,
    _poolFatalFumes,
    _poolFelhideMinotaur,
    _poolFelidarGuardian,
    _poolFieldCreeper,
    _poolFieryHellhound,
    _poolFireNationSentinels,
    _poolFlamekinBrawler,
    _poolFlowstoneHellion,
    _poolFlyingCarpet,
    _poolFountainOfYouth,
    _poolFrostboilSnarl,
    _poolFrostbridgeGuard,
    _poolFrostburnWeird,
    _poolFungalSprouting,
    _poolFurnaceWhelp,
    _poolFyndhornBrownie,
    _poolGalewindMoose,
    _poolGarnaBloodfistOfKeld,
    _poolGiantsBoulder,
    _poolGoblinBalloonBrigade,
    _poolGoblinPiker,
    _poolGreatHornKrushok,
    _poolGroveRumbler,
    _poolHajarLoyalBodyguard,
    _poolHeraldOfEternalDawn,
    _poolHinataDawnCrowned,
    _poolHuatlisSnubhorn,
    _poolHullcarver,
    _poolHundroog,
    _poolHungryGhoul,
    _poolIchorclawMyr,
    _poolIlluminatedWings,
    _poolImpactTremors,
    _poolImperialSeal,
    _poolInstantRamen,
    _poolIsolatedChapel,
    _poolIzzetLocket,
    _poolJadecraftArtisan,
    _poolJewelEyedCobra,
    _poolJoinTheDance,
    _poolJourneyersKite,
    _poolJudgesFamiliar,
    _poolJump,
    _poolKeenGlidemaster,
    _poolKeeperOfSecrets,
    _poolKiboUktabiPrince,
    _poolKiorasFollower,
    _poolKishlaVillage,
    _poolKitesailScout,
    _poolKnightOfMeadowgrain,
    _poolKotisSibsigChampion,
    _poolKrakenHatchling,
    _poolKranioceros,
    _poolKutzilMalametExemplar,
    _poolLegionLoyalty,
    _poolLightningHelix,
    _poolLordSkittersButcher,
    _poolLuminousBroodmoth,
    _poolMagmakinArtillerist,
    _poolMagusOfTheBazaar,
    _poolMassacreWurm,
    _poolMerfolkOfTheDepths,
    _poolMerfolkSovereign,
    _poolMidnightBanshee,
    _poolMigratingKetradon,
    _poolMindslicer,
    _poolMishrasFactory,
    _poolMithrilCoat,
    _poolMonstrousCarabid,
    _poolMorphling,
    _poolNarsetEnlightenedMaster,
    _poolNezumiBoneReader,
    _poolNomadicElf,
    _poolNoviceDissector,
    _poolOakenBoon,
    _poolOmenOfTheHunt,
    _poolOnduSkyruins,
    _poolOrcishLumberjack,
    _poolOrzhovCluestone,
    _poolOverflowingInsight,
    _poolPersonalTutor,
    _poolPhyrexianDelver,
    _poolPhyrexianVivisector,
    _poolPickYourPoison,
    _poolPiousInterdiction,
    _poolPiranhaFly,
    _poolPridemalkin,
    _poolRakdosGuildgate,
    _poolRampantGrowth,
    _poolRangersPath,
    _poolRavagedHighlands,
    _poolRavenousSquirrel,
    _poolRazorgrassAmbush,
    _poolRearingEmbermare,
    _poolReconstruction,
    _poolResurgentBelief,
    _poolRhoxWarMonk,
    _poolRhysTheRedeemed,
    _poolRideTheRails,
    _poolRimewoodFalls,
    _poolRipscalePredator,
    _poolRitesOfFlourishing,
    _poolRivenTurnbull,
    _poolRottingMastodon,
    _poolRoyalFalcon,
    _poolRussetWolves,
    _poolSakuraTribeElder,
    _poolSanguineSyphoner,
    _poolSarumansTrickery,
    _poolScarwoodGoblins,
    _poolScorchingShot,
    _poolScreechingPhoenix,
    _poolSeaOfClouds,
    _poolSealOfRemoval,
    _poolSecludedCourtyard,
    _poolSelflessCathar,
    _poolSharedRoots,
    _poolShortBow,
    _poolSiegeGangLieutenant,
    _poolSkullOfRamos,
    _poolSoliton,
    _poolSoporificSprings,
    _poolSoulstoneSanctuary,
    _poolSpawningPit,
    _poolSphinxSummoner,
    _poolSpinalCentipede,
    _poolStampedingRhino,
    _poolSteadfastSentry,
    _poolStirge,
    _poolStompingGround,
    _poolStrandsOfNight,
    _poolStubbornDenial,
    _poolSunBlessedPeak,
    _poolSunlitMarsh,
    _poolSvyelunOfSeaAndSky,
    _poolSwiftEnd,
    _poolSwiftSpinner,
    _poolSylvanBrushstrider,
    _poolSylvanRanger,
    _poolSylvanReclamation,
    _poolSyrGwynHeroOfAshvale,
    _poolTamiyosJournal,
    _poolTarPitcher,
    _poolTectonicGiant,
    _poolTempleGarden,
    _poolTevalsJudgment,
    _poolTheDrossPits,
    _poolTheJollyBalloonMan,
    _poolThornwindFaeries,
    _poolTitanothRex,
    _poolTomeOfLegends,
    _poolTouchstone,
    _poolTriumphOfTheHordes,
    _poolTrollHornCameo,
    _poolTrygonPredator,
    _poolTurtleLair,
    _poolUkudCobra,
    _poolUlvenwaldHydra,
    _poolUnhinge,
    _poolValiantGuard,
    _poolViashinoSandsprinter,
    _poolVillainousWrath,
    _poolVivVisionTeenSynthezoid,
    _poolVoiceOfMany,
    _poolVoidwielder,
    _poolVulshokMorningstar,
    _poolWardenOfEvosIsle,
    _poolWarriorsCharge,
    _poolWarshipScout,
    _poolWaspLancer,
    _poolWeftstalkerArdent,
    _poolWildAesthir,
    _poolWildWanderer,
    _poolWingedTempleOfOrazca,
    _poolWingmantleChaplain,
    _poolWinotaJoinerOfForces,
    _poolWoodlandPatrol,
    _poolZephid,
    _poolZephyrCharge,
    _poolZndrspltEyeOfWisdom,
  ],
  tokens: [
    _tokensBatToken,
    _tokensClueToken,
    _tokensGolemTrampleToken,
    _tokensHumanWarriorToken,
    _tokensPegasusToken22,
    _tokensSpiritToken,
  ],
};

export default shard;
