// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.
// Run `npm run gen:cards -w engine` after adding or removing a card file.

import type { CardShard } from "../card-shards.js";

import _poolAbandonAttachments from "../pool/abandon-attachments.js";
import _poolAbdelAdrianGorionsWard from "../pool/abdel-adrian-gorions-ward.js";
import _poolActOfTreason from "../pool/act-of-treason.js";
import _poolAetherChanneler from "../pool/aether-channeler.js";
import _poolAeveProgenitorOoze from "../pool/aeve-progenitor-ooze.js";
import _poolAffaGuardHound from "../pool/affa-guard-hound.js";
import _poolAkroanHorse from "../pool/akroan-horse.js";
import _poolAlelaArtfulProvocateur from "../pool/alela-artful-provocateur.js";
import _poolAleshasLegacy from "../pool/aleshas-legacy.js";
import _poolAnaconda from "../pool/anaconda.js";
import _poolAncestorsProphet from "../pool/ancestors-prophet.js";
import _poolAncientSpring from "../pool/ancient-spring.js";
import _poolAntQueen from "../pool/ant-queen.js";
import _poolArborbackStomper from "../pool/arborback-stomper.js";
import _poolArmorOfShadows from "../pool/armor-of-shadows.js";
import _poolArmoredWarhorse from "../pool/armored-warhorse.js";
import _poolAscendedLawmage from "../pool/ascended-lawmage.js";
import _poolAshlingRimebound from "../pool/ashling-rimebound.js";
import _poolAssassinsTrophy from "../pool/assassins-trophy.js";
import _poolAuraFracture from "../pool/aura-fracture.js";
import _poolAutomaticLibrarian from "../pool/automatic-librarian.js";
import _poolAvenBattlePriest from "../pool/aven-battle-priest.js";
import _poolAxebaneBeast from "../pool/axebane-beast.js";
import _poolBalshanCollaborator from "../pool/balshan-collaborator.js";
import _poolBarkchannelPathway from "../pool/barkchannel-pathway.js";
import _poolBatterskull from "../pool/batterskull.js";
import _poolBellowingTanglewurm from "../pool/bellowing-tanglewurm.js";
import _poolBlanchwoodTreefolk from "../pool/blanchwood-treefolk.js";
import _poolBloodsoakedInsight from "../pool/bloodsoaked-insight.js";
import _poolBlurredMongoose from "../pool/blurred-mongoose.js";
import _poolBoggartTrawler from "../pool/boggart-trawler.js";
import _poolBoltOfKeranos from "../pool/bolt-of-keranos.js";
import _poolBoonReflection from "../pool/boon-reflection.js";
import _poolBorosLocket from "../pool/boros-locket.js";
import _poolBothersomeQuasit from "../pool/bothersome-quasit.js";
import _poolBragoKingEternal from "../pool/brago-king-eternal.js";
import _poolBrambleSovereign from "../pool/bramble-sovereign.js";
import _poolBrassSecretary from "../pool/brass-secretary.js";
import _poolBreakDown from "../pool/break-down.js";
import _poolBriaRiptideRogue from "../pool/bria-riptide-rogue.js";
import _poolBridgeworksBattle from "../pool/bridgeworks-battle.js";
import _poolBrightbladeStoat from "../pool/brightblade-stoat.js";
import _poolBrightclimbPathway from "../pool/brightclimb-pathway.js";
import _poolBrotherhoodsEnd from "../pool/brotherhoods-end.js";
import _poolBullHippo from "../pool/bull-hippo.js";
import _poolBurnBright from "../pool/burn-bright.js";
import _poolCabalTrainee from "../pool/cabal-trainee.js";
import _poolCallTheCavalry from "../pool/call-the-cavalry.js";
import _poolCanopyVista from "../pool/canopy-vista.js";
import _poolCarnifexDemon from "../pool/carnifex-demon.js";
import _poolChainDevil from "../pool/chain-devil.js";
import _poolChakramSlinger from "../pool/chakram-slinger.js";
import _poolCobblebrute from "../pool/cobblebrute.js";
import _poolCoerciveRecruiter from "../pool/coercive-recruiter.js";
import _poolCoilAndCatch from "../pool/coil-and-catch.js";
import _poolCoiledTinviper from "../pool/coiled-tinviper.js";
import _poolColosYearling from "../pool/colos-yearling.js";
import _poolContagionClasp from "../pool/contagion-clasp.js";
import _poolCopperMyr from "../pool/copper-myr.js";
import _poolCoralMerfolk from "../pool/coral-merfolk.js";
import _poolCorsairCaptain from "../pool/corsair-captain.js";
import _poolCoverOfDarkness from "../pool/cover-of-darkness.js";
import _poolCrashOfRhinos from "../pool/crash-of-rhinos.js";
import _poolCrestedSunmare from "../pool/crested-sunmare.js";
import _poolCrosswayTroublemakers from "../pool/crossway-troublemakers.js";
import _poolDanithaNewBenaliasLight from "../pool/danitha-new-benalias-light.js";
import _poolDauntlessScrapbot from "../pool/dauntless-scrapbot.js";
import _poolDauthiVoidwalker from "../pool/dauthi-voidwalker.js";
import _poolDeadlyInsect from "../pool/deadly-insect.js";
import _poolDeadlyRollick from "../pool/deadly-rollick.js";
import _poolDeathreapRitual from "../pool/deathreap-ritual.js";
import _poolDeathsPresence from "../pool/deaths-presence.js";
import _poolDelayedBlastFireball from "../pool/delayed-blast-fireball.js";
import _poolDimirLocket from "../pool/dimir-locket.js";
import _poolDispel from "../pool/dispel.js";
import _poolDonatelloWayWithMachines from "../pool/donatello-way-with-machines.js";
import _poolDoubleCleave from "../pool/double-cleave.js";
import _poolDoublingSeason from "../pool/doubling-season.js";
import _poolDreamThiefsBandana from "../pool/dream-thiefs-bandana.js";
import _poolDuelistsHeritage from "../pool/duelists-heritage.js";
import _poolEarthbenderAscension from "../pool/earthbender-ascension.js";
import _poolEbonyTreefolk from "../pool/ebony-treefolk.js";
import _poolEidolonOfInspiration from "../pool/eidolon-of-inspiration.js";
import _poolElderfangVenom from "../pool/elderfang-venom.js";
import _poolEmberethShieldbreaker from "../pool/embereth-shieldbreaker.js";
import _poolEmeriasCall from "../pool/emerias-call.js";
import _poolEnduringTenacity from "../pool/enduring-tenacity.js";
import _poolEsperCormorants from "../pool/esper-cormorants.js";
import _poolEssenceHarvest from "../pool/essence-harvest.js";
import _poolEtherealArmor from "../pool/ethereal-armor.js";
import _poolFierceWitchstalker from "../pool/fierce-witchstalker.js";
import _poolFireNationAmbushers from "../pool/fire-nation-ambushers.js";
import _poolFiresOfUndeath from "../pool/fires-of-undeath.js";
import _poolFurnaceSpirit from "../pool/furnace-spirit.js";
import _poolGarrisonCat from "../pool/garrison-cat.js";
import _poolGeodeGrotto from "../pool/geode-grotto.js";
import _poolGildedSentinel from "../pool/gilded-sentinel.js";
import _poolGimliOfTheGlitteringCaves from "../pool/gimli-of-the-glittering-caves.js";
import _poolGlacialFloodplain from "../pool/glacial-floodplain.js";
import _poolGloriousAnthem from "../pool/glorious-anthem.js";
import _poolGoblinFireslinger from "../pool/goblin-fireslinger.js";
import _poolGoblinGardener from "../pool/goblin-gardener.js";
import _poolGolgariSignet from "../pool/golgari-signet.js";
import _poolGoliathSpider from "../pool/goliath-spider.js";
import _poolGoodFortuneUnicorn from "../pool/good-fortune-unicorn.js";
import _poolGranGran from "../pool/gran-gran.js";
import _poolGravedigger from "../pool/gravedigger.js";
import _poolGrazilaxxIllithidScholar from "../pool/grazilaxx-illithid-scholar.js";
import _poolGrimDiscovery from "../pool/grim-discovery.js";
import _poolGrizzledOutrider from "../pool/grizzled-outrider.js";
import _poolGuideOfSouls from "../pool/guide-of-souls.js";
import _poolHairStrungKoto from "../pool/hair-strung-koto.js";
import _poolHaldanAvidArcanist from "../pool/haldan-avid-arcanist.js";
import _poolHarrow from "../pool/harrow.js";
import _poolHateMirage from "../pool/hate-mirage.js";
import _poolHeliodTheRadiantDawn from "../pool/heliod-the-radiant-dawn.js";
import _poolHelmOfTheGods from "../pool/helm-of-the-gods.js";
import _poolHowlingMine from "../pool/howling-mine.js";
import _poolHulkingOgre from "../pool/hulking-ogre.js";
import _poolHypnoticSprite from "../pool/hypnotic-sprite.js";
import _poolIllusionistsBracers from "../pool/illusionists-bracers.js";
import _poolImpulse from "../pool/impulse.js";
import _poolInvigoratingHotSpring from "../pool/invigorating-hot-spring.js";
import _poolInvoluntaryEmployment from "../pool/involuntary-employment.js";
import _poolItllQuenchYa from "../pool/itll-quench-ya.js";
import _poolIzzetBoilerworks from "../pool/izzet-boilerworks.js";
import _poolJackhammer from "../pool/jackhammer.js";
import _poolJaxisTheTroublemaker from "../pool/jaxis-the-troublemaker.js";
import _poolJhessianInfiltrator from "../pool/jhessian-infiltrator.js";
import _poolKalastriaNightwatch from "../pool/kalastria-nightwatch.js";
import _poolKarametrasAcolyte from "../pool/karametras-acolyte.js";
import _poolKazanduMammoth from "../pool/kazandu-mammoth.js";
import _poolKindlyCustomer from "../pool/kindly-customer.js";
import _poolKrangUtromWarlord from "../pool/krang-utrom-warlord.js";
import _poolKraulStinger from "../pool/kraul-stinger.js";
import _poolLeonardoTheBalance from "../pool/leonardo-the-balance.js";
import _poolLeoninArmorguard from "../pool/leonin-armorguard.js";
import _poolLifesLegacy from "../pool/lifes-legacy.js";
import _poolLochKorrigan from "../pool/loch-korrigan.js";
import _poolLushOasis from "../pool/lush-oasis.js";
import _poolManaDrain from "../pool/mana-drain.js";
import _poolManagorgerHydra from "../pool/managorger-hydra.js";
import _poolMarshFlats from "../pool/marsh-flats.js";
import _poolMassProduction from "../pool/mass-production.js";
import _poolMerfolkTraders from "../pool/merfolk-traders.js";
import _poolMillikin from "../pool/millikin.js";
import _poolMindspliceApparatus from "../pool/mindsplice-apparatus.js";
import _poolMirageMesa from "../pool/mirage-mesa.js";
import _poolMirriCatWarrior from "../pool/mirri-cat-warrior.js";
import _poolMoltenTributary from "../pool/molten-tributary.js";
import _poolMoltensteelDragon from "../pool/moltensteel-dragon.js";
import _poolMomentOfCraving from "../pool/moment-of-craving.js";
import _poolMonasteryMentor from "../pool/monastery-mentor.js";
import _poolMooglesValor from "../pool/moogles-valor.js";
import _poolMoxJasper from "../pool/mox-jasper.js";
import _poolMysticSnake from "../pool/mystic-snake.js";
import _poolNaturesRhythm from "../pool/natures-rhythm.js";
import _poolNecroskitter from "../pool/necroskitter.js";
import _poolNemesisOfReason from "../pool/nemesis-of-reason.js";
import _poolNoDachi from "../pool/no-dachi.js";
import _poolNulldrifter from "../pool/nulldrifter.js";
import _poolOboroPalaceInTheClouds from "../pool/oboro-palace-in-the-clouds.js";
import _poolOmnathLocusOfRage from "../pool/omnath-locus-of-rage.js";
import _poolOmniCheesePizza from "../pool/omni-cheese-pizza.js";
import _poolOneirophage from "../pool/oneirophage.js";
import _poolOrcishMechanics from "../pool/orcish-mechanics.js";
import _poolOrochiLeafcaller from "../pool/orochi-leafcaller.js";
import _poolOssification from "../pool/ossification.js";
import _poolOvergrownArmasaur from "../pool/overgrown-armasaur.js";
import _poolOverwhelmingInstinct from "../pool/overwhelming-instinct.js";
import _poolPeacewalkerColossus from "../pool/peacewalker-colossus.js";
import _poolPhyrexianTower from "../pool/phyrexian-tower.js";
import _poolPiaNalaarConsulOfRevival from "../pool/pia-nalaar-consul-of-revival.js";
import _poolPincherBeetles from "../pool/pincher-beetles.js";
import _poolPontiffOfBlight from "../pool/pontiff-of-blight.js";
import _poolPristineTalisman from "../pool/pristine-talisman.js";
import _poolPutridGoblin from "../pool/putrid-goblin.js";
import _poolQasaliPridemage from "../pool/qasali-pridemage.js";
import _poolQuagmireDruid from "../pool/quagmire-druid.js";
import _poolQueensCommission from "../pool/queens-commission.js";
import _poolQuintoriusHistoryChaser from "../pool/quintorius-history-chaser.js";
import _poolRadhaHeirToKeld from "../pool/radha-heir-to-keld.js";
import _poolRagingCougar from "../pool/raging-cougar.js";
import _poolRaiseThePast from "../pool/raise-the-past.js";
import _poolRatcatcher from "../pool/ratcatcher.js";
import _poolRavagingHorde from "../pool/ravaging-horde.js";
import _poolRecklessAssault from "../pool/reckless-assault.js";
import _poolRetreatToEmeria from "../pool/retreat-to-emeria.js";
import _poolRevTitheExtractor from "../pool/rev-tithe-extractor.js";
import _poolReyhanLastOfTheAbzan from "../pool/reyhan-last-of-the-abzan.js";
import _poolRidgescaleTusker from "../pool/ridgescale-tusker.js";
import _poolRishkarPeemaRenegade from "../pool/rishkar-peema-renegade.js";
import _poolRottedHystrix from "../pool/rotted-hystrix.js";
import _poolRubyMedallion from "../pool/ruby-medallion.js";
import _poolSazhsChocobo from "../pool/sazhs-chocobo.js";
import _poolScarecrowGuide from "../pool/scarecrow-guide.js";
import _poolSearingFlesh from "../pool/searing-flesh.js";
import _poolSevinnesReclamation from "../pool/sevinnes-reclamation.js";
import _poolShalaiAndHallar from "../pool/shalai-and-hallar.js";
import _poolShamanOfThePack from "../pool/shaman-of-the-pack.js";
import _poolShamanicRevelation from "../pool/shamanic-revelation.js";
import _poolSheoldredsEdict from "../pool/sheoldreds-edict.js";
import _poolShimmerMyr from "../pool/shimmer-myr.js";
import _poolSinisterSabotage from "../pool/sinister-sabotage.js";
import _poolSirShandlarOfEberyn from "../pool/sir-shandlar-of-eberyn.js";
import _poolSkyshipStalker from "../pool/skyship-stalker.js";
import _poolSkysnareSpider from "../pool/skysnare-spider.js";
import _poolSlipThroughSpace from "../pool/slip-through-space.js";
import _poolSnappingVoidcraw from "../pool/snapping-voidcraw.js";
import _poolSnowCoveredMountain from "../pool/snow-covered-mountain.js";
import _poolSocialClimber from "../pool/social-climber.js";
import _poolSorcererOfTheFang from "../pool/sorcerer-of-the-fang.js";
import _poolSpitefulBanditry from "../pool/spiteful-banditry.js";
import _poolSquirrelanoids from "../pool/squirrelanoids.js";
import _poolStargaze from "../pool/stargaze.js";
import _poolStarnheimAspirant from "../pool/starnheim-aspirant.js";
import _poolStoicBuilder from "../pool/stoic-builder.js";
import _poolStolenByTheFae from "../pool/stolen-by-the-fae.js";
import _poolStoneRain from "../pool/stone-rain.js";
import _poolStonehornChanter from "../pool/stonehorn-chanter.js";
import _poolStormShaman from "../pool/storm-shaman.js";
import _poolStormcloudSpirit from "../pool/stormcloud-spirit.js";
import _poolStormscaleScion from "../pool/stormscale-scion.js";
import _poolSubterraneanCavern from "../pool/subterranean-cavern.js";
import _poolSuddenStrike from "../pool/sudden-strike.js";
import _poolSultaiAscendancy from "../pool/sultai-ascendancy.js";
import _poolSunCollaredRaptor from "../pool/sun-collared-raptor.js";
import _poolSunkenHollow from "../pool/sunken-hollow.js";
import _poolSurvivorOfKorlis from "../pool/survivor-of-korlis.js";
import _poolSvyeluniteTemple from "../pool/svyelunite-temple.js";
import _poolSweettoothWitch from "../pool/sweettooth-witch.js";
import _poolSylvanTutor from "../pool/sylvan-tutor.js";
import _poolTalasAirShip from "../pool/talas-air-ship.js";
import _poolTalismanOfHierarchy from "../pool/talisman-of-hierarchy.js";
import _poolTatyova from "../pool/tatyova.js";
import _poolTavernScoundrel from "../pool/tavern-scoundrel.js";
import _poolTerritorialScythecat from "../pool/territorial-scythecat.js";
import _poolTezzeretsGambit from "../pool/tezzerets-gambit.js";
import _poolThaliaGuardianOfThraben from "../pool/thalia-guardian-of-thraben.js";
import _poolTheEmperorOfPalamecia from "../pool/the-emperor-of-palamecia.js";
import _poolTheTenRings from "../pool/the-ten-rings.js";
import _poolTheWhizzerClassicSpeedster from "../pool/the-whizzer-classic-speedster.js";
import _poolThoughtVessel from "../pool/thought-vessel.js";
import _poolThrashingBrontodon from "../pool/thrashing-brontodon.js";
import _poolThrivingHeath from "../pool/thriving-heath.js";
import _poolTimberwatchElf from "../pool/timberwatch-elf.js";
import _poolTishanaVoiceOfThunder from "../pool/tishana-voice-of-thunder.js";
import _poolTitansStrength from "../pool/titans-strength.js";
import _poolTomeBlast from "../pool/tome-blast.js";
import _poolTormodsCrypt from "../pool/tormods-crypt.js";
import _poolTrailOfCrumbs from "../pool/trail-of-crumbs.js";
import _poolTrainingCenter from "../pool/training-center.js";
import _poolTreetopVillage from "../pool/treetop-village.js";
import _poolTrostaniDiscordant from "../pool/trostani-discordant.js";
import _poolUndeadAugur from "../pool/undead-augur.js";
import _poolVerdantSunsAvatar from "../pool/verdant-suns-avatar.js";
import _poolVileMutilator from "../pool/vile-mutilator.js";
import _poolViridianAcolyte from "../pool/viridian-acolyte.js";
import _poolViridianZealot from "../pool/viridian-zealot.js";
import _poolVodalianHexcatcher from "../pool/vodalian-hexcatcher.js";
import _poolVoraciousHydra from "../pool/voracious-hydra.js";
import _poolVorpalSword from "../pool/vorpal-sword.js";
import _poolVoyagingSatyr from "../pool/voyaging-satyr.js";
import _poolVulshokBerserker from "../pool/vulshok-berserker.js";
import _poolWaytaTrainerProdigy from "../pool/wayta-trainer-prodigy.js";
import _poolWellRested from "../pool/well-rested.js";
import _poolWildCantor from "../pool/wild-cantor.js";
import _poolWillowrushVerge from "../pool/willowrush-verge.js";
import _poolZagothCrystal from "../pool/zagoth-crystal.js";
import _poolZellDincht from "../pool/zell-dincht.js";
import _poolZephyrNet from "../pool/zephyr-net.js";
import _tokensFaerieToken from "../tokens/faerie-token.js";
import _tokensIllusionTokenMinn from "../tokens/illusion-token-minn.js";
import _tokensInsectTokenBlackGreen from "../tokens/insect-token-black-green.js";
import _tokensRabbitToken from "../tokens/rabbit-token.js";
import _tokensTarmogoyfToken from "../tokens/tarmogoyf-token.js";

const shard: CardShard = {
  pool: [
    _poolAbandonAttachments,
    _poolAbdelAdrianGorionsWard,
    _poolActOfTreason,
    _poolAetherChanneler,
    _poolAeveProgenitorOoze,
    _poolAffaGuardHound,
    _poolAkroanHorse,
    _poolAlelaArtfulProvocateur,
    _poolAleshasLegacy,
    _poolAnaconda,
    _poolAncestorsProphet,
    _poolAncientSpring,
    _poolAntQueen,
    _poolArborbackStomper,
    _poolArmorOfShadows,
    _poolArmoredWarhorse,
    _poolAscendedLawmage,
    _poolAshlingRimebound,
    _poolAssassinsTrophy,
    _poolAuraFracture,
    _poolAutomaticLibrarian,
    _poolAvenBattlePriest,
    _poolAxebaneBeast,
    _poolBalshanCollaborator,
    _poolBarkchannelPathway,
    _poolBatterskull,
    _poolBellowingTanglewurm,
    _poolBlanchwoodTreefolk,
    _poolBloodsoakedInsight,
    _poolBlurredMongoose,
    _poolBoggartTrawler,
    _poolBoltOfKeranos,
    _poolBoonReflection,
    _poolBorosLocket,
    _poolBothersomeQuasit,
    _poolBragoKingEternal,
    _poolBrambleSovereign,
    _poolBrassSecretary,
    _poolBreakDown,
    _poolBriaRiptideRogue,
    _poolBridgeworksBattle,
    _poolBrightbladeStoat,
    _poolBrightclimbPathway,
    _poolBrotherhoodsEnd,
    _poolBullHippo,
    _poolBurnBright,
    _poolCabalTrainee,
    _poolCallTheCavalry,
    _poolCanopyVista,
    _poolCarnifexDemon,
    _poolChainDevil,
    _poolChakramSlinger,
    _poolCobblebrute,
    _poolCoerciveRecruiter,
    _poolCoilAndCatch,
    _poolCoiledTinviper,
    _poolColosYearling,
    _poolContagionClasp,
    _poolCopperMyr,
    _poolCoralMerfolk,
    _poolCorsairCaptain,
    _poolCoverOfDarkness,
    _poolCrashOfRhinos,
    _poolCrestedSunmare,
    _poolCrosswayTroublemakers,
    _poolDanithaNewBenaliasLight,
    _poolDauntlessScrapbot,
    _poolDauthiVoidwalker,
    _poolDeadlyInsect,
    _poolDeadlyRollick,
    _poolDeathreapRitual,
    _poolDeathsPresence,
    _poolDelayedBlastFireball,
    _poolDimirLocket,
    _poolDispel,
    _poolDonatelloWayWithMachines,
    _poolDoubleCleave,
    _poolDoublingSeason,
    _poolDreamThiefsBandana,
    _poolDuelistsHeritage,
    _poolEarthbenderAscension,
    _poolEbonyTreefolk,
    _poolEidolonOfInspiration,
    _poolElderfangVenom,
    _poolEmberethShieldbreaker,
    _poolEmeriasCall,
    _poolEnduringTenacity,
    _poolEsperCormorants,
    _poolEssenceHarvest,
    _poolEtherealArmor,
    _poolFierceWitchstalker,
    _poolFireNationAmbushers,
    _poolFiresOfUndeath,
    _poolFurnaceSpirit,
    _poolGarrisonCat,
    _poolGeodeGrotto,
    _poolGildedSentinel,
    _poolGimliOfTheGlitteringCaves,
    _poolGlacialFloodplain,
    _poolGloriousAnthem,
    _poolGoblinFireslinger,
    _poolGoblinGardener,
    _poolGolgariSignet,
    _poolGoliathSpider,
    _poolGoodFortuneUnicorn,
    _poolGranGran,
    _poolGravedigger,
    _poolGrazilaxxIllithidScholar,
    _poolGrimDiscovery,
    _poolGrizzledOutrider,
    _poolGuideOfSouls,
    _poolHairStrungKoto,
    _poolHaldanAvidArcanist,
    _poolHarrow,
    _poolHateMirage,
    _poolHeliodTheRadiantDawn,
    _poolHelmOfTheGods,
    _poolHowlingMine,
    _poolHulkingOgre,
    _poolHypnoticSprite,
    _poolIllusionistsBracers,
    _poolImpulse,
    _poolInvigoratingHotSpring,
    _poolInvoluntaryEmployment,
    _poolItllQuenchYa,
    _poolIzzetBoilerworks,
    _poolJackhammer,
    _poolJaxisTheTroublemaker,
    _poolJhessianInfiltrator,
    _poolKalastriaNightwatch,
    _poolKarametrasAcolyte,
    _poolKazanduMammoth,
    _poolKindlyCustomer,
    _poolKrangUtromWarlord,
    _poolKraulStinger,
    _poolLeonardoTheBalance,
    _poolLeoninArmorguard,
    _poolLifesLegacy,
    _poolLochKorrigan,
    _poolLushOasis,
    _poolManaDrain,
    _poolManagorgerHydra,
    _poolMarshFlats,
    _poolMassProduction,
    _poolMerfolkTraders,
    _poolMillikin,
    _poolMindspliceApparatus,
    _poolMirageMesa,
    _poolMirriCatWarrior,
    _poolMoltenTributary,
    _poolMoltensteelDragon,
    _poolMomentOfCraving,
    _poolMonasteryMentor,
    _poolMooglesValor,
    _poolMoxJasper,
    _poolMysticSnake,
    _poolNaturesRhythm,
    _poolNecroskitter,
    _poolNemesisOfReason,
    _poolNoDachi,
    _poolNulldrifter,
    _poolOboroPalaceInTheClouds,
    _poolOmnathLocusOfRage,
    _poolOmniCheesePizza,
    _poolOneirophage,
    _poolOrcishMechanics,
    _poolOrochiLeafcaller,
    _poolOssification,
    _poolOvergrownArmasaur,
    _poolOverwhelmingInstinct,
    _poolPeacewalkerColossus,
    _poolPhyrexianTower,
    _poolPiaNalaarConsulOfRevival,
    _poolPincherBeetles,
    _poolPontiffOfBlight,
    _poolPristineTalisman,
    _poolPutridGoblin,
    _poolQasaliPridemage,
    _poolQuagmireDruid,
    _poolQueensCommission,
    _poolQuintoriusHistoryChaser,
    _poolRadhaHeirToKeld,
    _poolRagingCougar,
    _poolRaiseThePast,
    _poolRatcatcher,
    _poolRavagingHorde,
    _poolRecklessAssault,
    _poolRetreatToEmeria,
    _poolRevTitheExtractor,
    _poolReyhanLastOfTheAbzan,
    _poolRidgescaleTusker,
    _poolRishkarPeemaRenegade,
    _poolRottedHystrix,
    _poolRubyMedallion,
    _poolSazhsChocobo,
    _poolScarecrowGuide,
    _poolSearingFlesh,
    _poolSevinnesReclamation,
    _poolShalaiAndHallar,
    _poolShamanOfThePack,
    _poolShamanicRevelation,
    _poolSheoldredsEdict,
    _poolShimmerMyr,
    _poolSinisterSabotage,
    _poolSirShandlarOfEberyn,
    _poolSkyshipStalker,
    _poolSkysnareSpider,
    _poolSlipThroughSpace,
    _poolSnappingVoidcraw,
    _poolSnowCoveredMountain,
    _poolSocialClimber,
    _poolSorcererOfTheFang,
    _poolSpitefulBanditry,
    _poolSquirrelanoids,
    _poolStargaze,
    _poolStarnheimAspirant,
    _poolStoicBuilder,
    _poolStolenByTheFae,
    _poolStoneRain,
    _poolStonehornChanter,
    _poolStormShaman,
    _poolStormcloudSpirit,
    _poolStormscaleScion,
    _poolSubterraneanCavern,
    _poolSuddenStrike,
    _poolSultaiAscendancy,
    _poolSunCollaredRaptor,
    _poolSunkenHollow,
    _poolSurvivorOfKorlis,
    _poolSvyeluniteTemple,
    _poolSweettoothWitch,
    _poolSylvanTutor,
    _poolTalasAirShip,
    _poolTalismanOfHierarchy,
    _poolTatyova,
    _poolTavernScoundrel,
    _poolTerritorialScythecat,
    _poolTezzeretsGambit,
    _poolThaliaGuardianOfThraben,
    _poolTheEmperorOfPalamecia,
    _poolTheTenRings,
    _poolTheWhizzerClassicSpeedster,
    _poolThoughtVessel,
    _poolThrashingBrontodon,
    _poolThrivingHeath,
    _poolTimberwatchElf,
    _poolTishanaVoiceOfThunder,
    _poolTitansStrength,
    _poolTomeBlast,
    _poolTormodsCrypt,
    _poolTrailOfCrumbs,
    _poolTrainingCenter,
    _poolTreetopVillage,
    _poolTrostaniDiscordant,
    _poolUndeadAugur,
    _poolVerdantSunsAvatar,
    _poolVileMutilator,
    _poolViridianAcolyte,
    _poolViridianZealot,
    _poolVodalianHexcatcher,
    _poolVoraciousHydra,
    _poolVorpalSword,
    _poolVoyagingSatyr,
    _poolVulshokBerserker,
    _poolWaytaTrainerProdigy,
    _poolWellRested,
    _poolWildCantor,
    _poolWillowrushVerge,
    _poolZagothCrystal,
    _poolZellDincht,
    _poolZephyrNet,
  ],
  tokens: [
    _tokensFaerieToken,
    _tokensIllusionTokenMinn,
    _tokensInsectTokenBlackGreen,
    _tokensRabbitToken,
    _tokensTarmogoyfToken,
  ],
};

export default shard;
