// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.
// Run `npm run gen:cards -w engine` after adding or removing a card file.

import type { CardShard } from "../card-shards.js";

import _poolAftermathAnalyst from "../pool/aftermath-analyst.js";
import _poolAllThatGlitters from "../pool/all-that-glitters.js";
import _poolAlpineGrizzly from "../pool/alpine-grizzly.js";
import _poolAmbassadorOak from "../pool/ambassador-oak.js";
import _poolAmbushParty from "../pool/ambush-party.js";
import _poolAnHavvaTownship from "../pool/an-havva-township.js";
import _poolAnabaBodyguard from "../pool/anaba-bodyguard.js";
import _poolAphettoGrifter from "../pool/aphetto-grifter.js";
import _poolArchangelOfThune from "../pool/archangel-of-thune.js";
import _poolArchmageEmeritus from "../pool/archmage-emeritus.js";
import _poolAssaultStrobe from "../pool/assault-strobe.js";
import _poolAvacynsPilgrim from "../pool/avacyns-pilgrim.js";
import _poolAvenReedstalker from "../pool/aven-reedstalker.js";
import _poolBarktoothWarbeard from "../pool/barktooth-warbeard.js";
import _poolBasalThrull from "../pool/basal-thrull.js";
import _poolBattleDisplay from "../pool/battle-display.js";
import _poolBellowingCrier from "../pool/bellowing-crier.js";
import _poolBishopOfWings from "../pool/bishop-of-wings.js";
import _poolBladedSentinel from "../pool/bladed-sentinel.js";
import _poolBlastedLandscape from "../pool/blasted-landscape.js";
import _poolBleachboneVerge from "../pool/bleachbone-verge.js";
import _poolBlessedLight from "../pool/blessed-light.js";
import _poolBlightning from "../pool/blightning.js";
import _poolBodyDropper from "../pool/body-dropper.js";
import _poolBrineShaman from "../pool/brine-shaman.js";
import _poolCanyonWildcat from "../pool/canyon-wildcat.js";
import _poolCaravanHurda from "../pool/caravan-hurda.js";
import _poolCastleArdenvale from "../pool/castle-ardenvale.js";
import _poolChampionOfTheParish from "../pool/champion-of-the-parish.js";
import _poolCharismaticVanguard from "../pool/charismatic-vanguard.js";
import _poolChorusOfWoe from "../pool/chorus-of-woe.js";
import _poolChronomaton from "../pool/chronomaton.js";
import _poolCitywatchSphinx from "../pool/citywatch-sphinx.js";
import _poolCleaverRiot from "../pool/cleaver-riot.js";
import _poolCliffhavenSellSword from "../pool/cliffhaven-sell-sword.js";
import _poolCloudManta from "../pool/cloud-manta.js";
import _poolConsulateSkygate from "../pool/consulate-skygate.js";
import _poolContentiousPlan from "../pool/contentious-plan.js";
import _poolCustodianOfTheTrove from "../pool/custodian-of-the-trove.js";
import _poolDawnToDusk from "../pool/dawn-to-dusk.js";
import _poolDealGoneBad from "../pool/deal-gone-bad.js";
import _poolDefiantElf from "../pool/defiant-elf.js";
import _poolDemonsDisciple from "../pool/demons-disciple.js";
import _poolDemonsGrasp from "../pool/demons-grasp.js";
import _poolDismember from "../pool/dismember.js";
import _poolDragonkinBerserker from "../pool/dragonkin-berserker.js";
import _poolDragonsPresence from "../pool/dragons-presence.js";
import _poolDryadsFavor from "../pool/dryads-favor.js";
import _poolDuskdaleWurm from "../pool/duskdale-wurm.js";
import _poolElfhamePalace from "../pool/elfhame-palace.js";
import _poolEmeraldOryx from "../pool/emerald-oryx.js";
import _poolEnormousBaloth from "../pool/enormous-baloth.js";
import _poolEternalWitness from "../pool/eternal-witness.js";
import _poolEyeblightAssassin from "../pool/eyeblight-assassin.js";
import _poolFiligreeSages from "../pool/filigree-sages.js";
import _poolFinneasAceArcher from "../pool/finneas-ace-archer.js";
import _poolFlawlessManeuver from "../pool/flawless-maneuver.js";
import _poolFrenziedDevils from "../pool/frenzied-devils.js";
import _poolGaleSwooper from "../pool/gale-swooper.js";
import _poolGingerbreadHunter from "../pool/gingerbread-hunter.js";
import _poolGixianInfiltrator from "../pool/gixian-infiltrator.js";
import _poolGlimmerbell from "../pool/glimmerbell.js";
import _poolGlorySeeker from "../pool/glory-seeker.js";
import _poolGluttonousZombie from "../pool/gluttonous-zombie.js";
import _poolGoblinRoughrider from "../pool/goblin-roughrider.js";
import _poolGoblinSettler from "../pool/goblin-settler.js";
import _poolGoldenHind from "../pool/golden-hind.js";
import _poolGravespawnSovereign from "../pool/gravespawn-sovereign.js";
import _poolGrimBackwoods from "../pool/grim-backwoods.js";
import _poolGrimclimbPathway from "../pool/grimclimb-pathway.js";
import _poolGuardianLions from "../pool/guardian-lions.js";
import _poolHauntedMire from "../pool/haunted-mire.js";
import _poolHedronCrawler from "../pool/hedron-crawler.js";
import _poolHelpfulHunter from "../pool/helpful-hunter.js";
import _poolHorseshoeCrab from "../pool/horseshoe-crab.js";
import _poolHowlingGolem from "../pool/howling-golem.js";
import _poolHumblingElder from "../pool/humbling-elder.js";
import _poolInfernalTribute from "../pool/infernal-tribute.js";
import _poolInquisitivePuppet from "../pool/inquisitive-puppet.js";
import _poolInspiredCharge from "../pool/inspired-charge.js";
import _poolInvokeTheDivine from "../pool/invoke-the-divine.js";
import _poolJasmineBoreal from "../pool/jasmine-boreal.js";
import _poolLeapingMaster from "../pool/leaping-master.js";
import _poolLeyDruid from "../pool/ley-druid.js";
import _poolLightningStrike from "../pool/lightning-strike.js";
import _poolLithatog from "../pool/lithatog.js";
import _poolLlanowarCavalry from "../pool/llanowar-cavalry.js";
import _poolLlanowarVisionary from "../pool/llanowar-visionary.js";
import _poolLoyalGuardian from "../pool/loyal-guardian.js";
import _poolLumraBellowOfTheWoods from "../pool/lumra-bellow-of-the-woods.js";
import _poolMalachiteGolem from "../pool/malachite-golem.js";
import _poolManalith from "../pool/manalith.js";
import _poolMarbleChalice from "../pool/marble-chalice.js";
import _poolMartyrForTheCause from "../pool/martyr-for-the-cause.js";
import _poolMendingHands from "../pool/mending-hands.js";
import _poolMerfolkOfThePearlTrident from "../pool/merfolk-of-the-pearl-trident.js";
import _poolMightOfOaks from "../pool/might-of-oaks.js";
import _poolMishraEminentOne from "../pool/mishra-eminent-one.js";
import _poolMoonwingMoth from "../pool/moonwing-moth.js";
import _poolMossMonster from "../pool/moss-monster.js";
import _poolNetworkDisruptor from "../pool/network-disruptor.js";
import _poolNobleHierarch from "../pool/noble-hierarch.js";
import _poolNorinTheWary from "../pool/norin-the-wary.js";
import _poolObsidianGiant from "../pool/obsidian-giant.js";
import _poolOverwhelmingStampede from "../pool/overwhelming-stampede.js";
import _poolPlaguemawBeast from "../pool/plaguemaw-beast.js";
import _poolProtomatterPowder from "../pool/protomatter-powder.js";
import _poolPuresteelPaladin from "../pool/puresteel-paladin.js";
import _poolQuicksilverPietroMaximoff from "../pool/quicksilver-pietro-maximoff.js";
import _poolRaccoonRallier from "../pool/raccoon-rallier.js";
import _poolRakdosShredFreak from "../pool/rakdos-shred-freak.js";
import _poolRavenousIntruder from "../pool/ravenous-intruder.js";
import _poolRememberTheFallen from "../pool/remember-the-fallen.js";
import _poolRiftBolt from "../pool/rift-bolt.js";
import _poolRingOfTheLucii from "../pool/ring-of-the-lucii.js";
import _poolRisingOfTheDay from "../pool/rising-of-the-day.js";
import _poolRodeoPyromancers from "../pool/rodeo-pyromancers.js";
import _poolRoothaMasteringTheMoment from "../pool/rootha-mastering-the-moment.js";
import _poolRuggedHighlands from "../pool/rugged-highlands.js";
import _poolRuinationWurm from "../pool/ruination-wurm.js";
import _poolRuinsRecluse from "../pool/ruins-recluse.js";
import _poolScoriaElemental from "../pool/scoria-elemental.js";
import _poolSeekerOfSkybreak from "../pool/seeker-of-skybreak.js";
import _poolSelesnyaEvangel from "../pool/selesnya-evangel.js";
import _poolSerpentAssassin from "../pool/serpent-assassin.js";
import _poolSerraAdvocate from "../pool/serra-advocate.js";
import _poolSerraAngel from "../pool/serra-angel.js";
import _poolShamanOfSpring from "../pool/shaman-of-spring.js";
import _poolShamblingGoblin from "../pool/shambling-goblin.js";
import _poolSharlayanNationOfScholars from "../pool/sharlayan-nation-of-scholars.js";
import _poolShatterskullRecruit from "../pool/shatterskull-recruit.js";
import _poolShriekdiver from "../pool/shriekdiver.js";
import _poolSkyTheaterStrix from "../pool/sky-theater-strix.js";
import _poolSlagdrillScrapper from "../pool/slagdrill-scrapper.js";
import _poolSnapcasterMage from "../pool/snapcaster-mage.js";
import _poolSolRing from "../pool/sol-ring.js";
import _poolSparkReaper from "../pool/spark-reaper.js";
import _poolSpectatorSeating from "../pool/spectator-seating.js";
import _poolSpiritSummoning from "../pool/spirit-summoning.js";
import _poolSpitefulBully from "../pool/spiteful-bully.js";
import _poolStealerOfSecrets from "../pool/stealer-of-secrets.js";
import _poolStorytellerPixie from "../pool/storyteller-pixie.js";
import _poolSuburbanSanctuary from "../pool/suburban-sanctuary.js";
import _poolSugarRush from "../pool/sugar-rush.js";
import _poolSupplyRunners from "../pool/supply-runners.js";
import _poolSupremeVerdict from "../pool/supreme-verdict.js";
import _poolSwanSong from "../pool/swan-song.js";
import _poolSwiftfootBoots from "../pool/swiftfoot-boots.js";
import _poolTarmogoyf from "../pool/tarmogoyf.js";
import _poolTempleBell from "../pool/temple-bell.js";
import _poolTempleOfDeceit from "../pool/temple-of-deceit.js";
import _poolTempleOfMalady from "../pool/temple-of-malady.js";
import _poolTheLadyOfTheMountain from "../pool/the-lady-of-the-mountain.js";
import _poolThinkTank from "../pool/think-tank.js";
import _poolTinderFarm from "../pool/tinder-farm.js";
import _poolTomeRaider from "../pool/tome-raider.js";
import _poolTwoHeadedHellkite from "../pool/two-headed-hellkite.js";
import _poolUndergrowthRecon from "../pool/undergrowth-recon.js";
import _poolUndergrowthStadium from "../pool/undergrowth-stadium.js";
import _poolVampireNoble from "../pool/vampire-noble.js";
import _poolVentureDeeper from "../pool/venture-deeper.js";
import _poolViridianShaman from "../pool/viridian-shaman.js";
import _poolVolcanicIsland from "../pool/volcanic-island.js";
import _poolVoraciousVarmint from "../pool/voracious-varmint.js";
import _poolWastelandScorpion from "../pool/wasteland-scorpion.js";
import _poolWatercourser from "../pool/watercourser.js";
import _poolWestfoldRider from "../pool/westfold-rider.js";
import _poolWilt from "../pool/wilt.js";
import _poolWindriderPatrol from "../pool/windrider-patrol.js";
import _poolWinterMisanthropicGuide from "../pool/winter-misanthropic-guide.js";
import _poolWorldMap from "../pool/world-map.js";
import _poolYoshimaru from "../pool/yoshimaru.js";
import _poolYouthfulScholar from "../pool/youthful-scholar.js";
import _poolZodiacRooster from "../pool/zodiac-rooster.js";
import _poolZodiacSnake from "../pool/zodiac-snake.js";
import _tokensBananaToken from "../tokens/banana-token.js";
import _tokensDeathtouchSnakeToken from "../tokens/deathtouch-snake-token.js";
import _tokensHumanSoldierToken from "../tokens/human-soldier-token.js";
import _tokensInsectTokenFlyingHaste from "../tokens/insect-token-flying-haste.js";
import _tokensRatTokenVren from "../tokens/rat-token-vren.js";
import _tokensRobotVillainToken from "../tokens/robot-villain-token.js";

const shard: CardShard = {
  pool: [
    _poolAftermathAnalyst,
    _poolAllThatGlitters,
    _poolAlpineGrizzly,
    _poolAmbassadorOak,
    _poolAmbushParty,
    _poolAnHavvaTownship,
    _poolAnabaBodyguard,
    _poolAphettoGrifter,
    _poolArchangelOfThune,
    _poolArchmageEmeritus,
    _poolAssaultStrobe,
    _poolAvacynsPilgrim,
    _poolAvenReedstalker,
    _poolBarktoothWarbeard,
    _poolBasalThrull,
    _poolBattleDisplay,
    _poolBellowingCrier,
    _poolBishopOfWings,
    _poolBladedSentinel,
    _poolBlastedLandscape,
    _poolBleachboneVerge,
    _poolBlessedLight,
    _poolBlightning,
    _poolBodyDropper,
    _poolBrineShaman,
    _poolCanyonWildcat,
    _poolCaravanHurda,
    _poolCastleArdenvale,
    _poolChampionOfTheParish,
    _poolCharismaticVanguard,
    _poolChorusOfWoe,
    _poolChronomaton,
    _poolCitywatchSphinx,
    _poolCleaverRiot,
    _poolCliffhavenSellSword,
    _poolCloudManta,
    _poolConsulateSkygate,
    _poolContentiousPlan,
    _poolCustodianOfTheTrove,
    _poolDawnToDusk,
    _poolDealGoneBad,
    _poolDefiantElf,
    _poolDemonsDisciple,
    _poolDemonsGrasp,
    _poolDismember,
    _poolDragonkinBerserker,
    _poolDragonsPresence,
    _poolDryadsFavor,
    _poolDuskdaleWurm,
    _poolElfhamePalace,
    _poolEmeraldOryx,
    _poolEnormousBaloth,
    _poolEternalWitness,
    _poolEyeblightAssassin,
    _poolFiligreeSages,
    _poolFinneasAceArcher,
    _poolFlawlessManeuver,
    _poolFrenziedDevils,
    _poolGaleSwooper,
    _poolGingerbreadHunter,
    _poolGixianInfiltrator,
    _poolGlimmerbell,
    _poolGlorySeeker,
    _poolGluttonousZombie,
    _poolGoblinRoughrider,
    _poolGoblinSettler,
    _poolGoldenHind,
    _poolGravespawnSovereign,
    _poolGrimBackwoods,
    _poolGrimclimbPathway,
    _poolGuardianLions,
    _poolHauntedMire,
    _poolHedronCrawler,
    _poolHelpfulHunter,
    _poolHorseshoeCrab,
    _poolHowlingGolem,
    _poolHumblingElder,
    _poolInfernalTribute,
    _poolInquisitivePuppet,
    _poolInspiredCharge,
    _poolInvokeTheDivine,
    _poolJasmineBoreal,
    _poolLeapingMaster,
    _poolLeyDruid,
    _poolLightningStrike,
    _poolLithatog,
    _poolLlanowarCavalry,
    _poolLlanowarVisionary,
    _poolLoyalGuardian,
    _poolLumraBellowOfTheWoods,
    _poolMalachiteGolem,
    _poolManalith,
    _poolMarbleChalice,
    _poolMartyrForTheCause,
    _poolMendingHands,
    _poolMerfolkOfThePearlTrident,
    _poolMightOfOaks,
    _poolMishraEminentOne,
    _poolMoonwingMoth,
    _poolMossMonster,
    _poolNetworkDisruptor,
    _poolNobleHierarch,
    _poolNorinTheWary,
    _poolObsidianGiant,
    _poolOverwhelmingStampede,
    _poolPlaguemawBeast,
    _poolProtomatterPowder,
    _poolPuresteelPaladin,
    _poolQuicksilverPietroMaximoff,
    _poolRaccoonRallier,
    _poolRakdosShredFreak,
    _poolRavenousIntruder,
    _poolRememberTheFallen,
    _poolRiftBolt,
    _poolRingOfTheLucii,
    _poolRisingOfTheDay,
    _poolRodeoPyromancers,
    _poolRoothaMasteringTheMoment,
    _poolRuggedHighlands,
    _poolRuinationWurm,
    _poolRuinsRecluse,
    _poolScoriaElemental,
    _poolSeekerOfSkybreak,
    _poolSelesnyaEvangel,
    _poolSerpentAssassin,
    _poolSerraAdvocate,
    _poolSerraAngel,
    _poolShamanOfSpring,
    _poolShamblingGoblin,
    _poolSharlayanNationOfScholars,
    _poolShatterskullRecruit,
    _poolShriekdiver,
    _poolSkyTheaterStrix,
    _poolSlagdrillScrapper,
    _poolSnapcasterMage,
    _poolSolRing,
    _poolSparkReaper,
    _poolSpectatorSeating,
    _poolSpiritSummoning,
    _poolSpitefulBully,
    _poolStealerOfSecrets,
    _poolStorytellerPixie,
    _poolSuburbanSanctuary,
    _poolSugarRush,
    _poolSupplyRunners,
    _poolSupremeVerdict,
    _poolSwanSong,
    _poolSwiftfootBoots,
    _poolTarmogoyf,
    _poolTempleBell,
    _poolTempleOfDeceit,
    _poolTempleOfMalady,
    _poolTheLadyOfTheMountain,
    _poolThinkTank,
    _poolTinderFarm,
    _poolTomeRaider,
    _poolTwoHeadedHellkite,
    _poolUndergrowthRecon,
    _poolUndergrowthStadium,
    _poolVampireNoble,
    _poolVentureDeeper,
    _poolViridianShaman,
    _poolVolcanicIsland,
    _poolVoraciousVarmint,
    _poolWastelandScorpion,
    _poolWatercourser,
    _poolWestfoldRider,
    _poolWilt,
    _poolWindriderPatrol,
    _poolWinterMisanthropicGuide,
    _poolWorldMap,
    _poolYoshimaru,
    _poolYouthfulScholar,
    _poolZodiacRooster,
    _poolZodiacSnake,
  ],
  tokens: [
    _tokensBananaToken,
    _tokensDeathtouchSnakeToken,
    _tokensHumanSoldierToken,
    _tokensInsectTokenFlyingHaste,
    _tokensRatTokenVren,
    _tokensRobotVillainToken,
  ],
};

export default shard;
