// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.
// Run `npm run gen:cards -w engine` after adding or removing a card file.

import type { CardShard } from "../card-shards.js";

import _poolActOfTreason from "../pool/act-of-treason.js";
import _poolAffaGuardHound from "../pool/affa-guard-hound.js";
import _poolAlelaArtfulProvocateur from "../pool/alela-artful-provocateur.js";
import _poolAleshasLegacy from "../pool/aleshas-legacy.js";
import _poolAnaconda from "../pool/anaconda.js";
import _poolAncestorsProphet from "../pool/ancestors-prophet.js";
import _poolAncientSpring from "../pool/ancient-spring.js";
import _poolAntQueen from "../pool/ant-queen.js";
import _poolArborbackStomper from "../pool/arborback-stomper.js";
import _poolArmoredWarhorse from "../pool/armored-warhorse.js";
import _poolAscendedLawmage from "../pool/ascended-lawmage.js";
import _poolAssassinsTrophy from "../pool/assassins-trophy.js";
import _poolAuraFracture from "../pool/aura-fracture.js";
import _poolAutomaticLibrarian from "../pool/automatic-librarian.js";
import _poolAvenBattlePriest from "../pool/aven-battle-priest.js";
import _poolAxebaneBeast from "../pool/axebane-beast.js";
import _poolBalshanCollaborator from "../pool/balshan-collaborator.js";
import _poolBarkchannelPathway from "../pool/barkchannel-pathway.js";
import _poolBlanchwoodTreefolk from "../pool/blanchwood-treefolk.js";
import _poolBlurredMongoose from "../pool/blurred-mongoose.js";
import _poolBoggartTrawler from "../pool/boggart-trawler.js";
import _poolBoltOfKeranos from "../pool/bolt-of-keranos.js";
import _poolBorosLocket from "../pool/boros-locket.js";
import _poolBrassSecretary from "../pool/brass-secretary.js";
import _poolBreakDown from "../pool/break-down.js";
import _poolBriaRiptideRogue from "../pool/bria-riptide-rogue.js";
import _poolBridgeworksBattle from "../pool/bridgeworks-battle.js";
import _poolBrightbladeStoat from "../pool/brightblade-stoat.js";
import _poolBrightclimbPathway from "../pool/brightclimb-pathway.js";
import _poolBullHippo from "../pool/bull-hippo.js";
import _poolBurnBright from "../pool/burn-bright.js";
import _poolCabalTrainee from "../pool/cabal-trainee.js";
import _poolCallTheCavalry from "../pool/call-the-cavalry.js";
import _poolCanopyVista from "../pool/canopy-vista.js";
import _poolChainDevil from "../pool/chain-devil.js";
import _poolChakramSlinger from "../pool/chakram-slinger.js";
import _poolCobblebrute from "../pool/cobblebrute.js";
import _poolCoiledTinviper from "../pool/coiled-tinviper.js";
import _poolColosYearling from "../pool/colos-yearling.js";
import _poolCopperMyr from "../pool/copper-myr.js";
import _poolCoralMerfolk from "../pool/coral-merfolk.js";
import _poolCrashOfRhinos from "../pool/crash-of-rhinos.js";
import _poolDeadlyInsect from "../pool/deadly-insect.js";
import _poolDeadlyRollick from "../pool/deadly-rollick.js";
import _poolDimirLocket from "../pool/dimir-locket.js";
import _poolDonatelloWayWithMachines from "../pool/donatello-way-with-machines.js";
import _poolDoubleCleave from "../pool/double-cleave.js";
import _poolDoublingSeason from "../pool/doubling-season.js";
import _poolEbonyTreefolk from "../pool/ebony-treefolk.js";
import _poolEidolonOfInspiration from "../pool/eidolon-of-inspiration.js";
import _poolEmberethShieldbreaker from "../pool/embereth-shieldbreaker.js";
import _poolEsperCormorants from "../pool/esper-cormorants.js";
import _poolFierceWitchstalker from "../pool/fierce-witchstalker.js";
import _poolFireNationAmbushers from "../pool/fire-nation-ambushers.js";
import _poolFiresOfUndeath from "../pool/fires-of-undeath.js";
import _poolFurnaceSpirit from "../pool/furnace-spirit.js";
import _poolGarrisonCat from "../pool/garrison-cat.js";
import _poolGildedSentinel from "../pool/gilded-sentinel.js";
import _poolGlacialFloodplain from "../pool/glacial-floodplain.js";
import _poolGloriousAnthem from "../pool/glorious-anthem.js";
import _poolGoblinFireslinger from "../pool/goblin-fireslinger.js";
import _poolGoblinGardener from "../pool/goblin-gardener.js";
import _poolGolgariSignet from "../pool/golgari-signet.js";
import _poolGoliathSpider from "../pool/goliath-spider.js";
import _poolGravedigger from "../pool/gravedigger.js";
import _poolGrimDiscovery from "../pool/grim-discovery.js";
import _poolGrizzledOutrider from "../pool/grizzled-outrider.js";
import _poolHairStrungKoto from "../pool/hair-strung-koto.js";
import _poolHarrow from "../pool/harrow.js";
import _poolHateMirage from "../pool/hate-mirage.js";
import _poolHowlingMine from "../pool/howling-mine.js";
import _poolHulkingOgre from "../pool/hulking-ogre.js";
import _poolIzzetBoilerworks from "../pool/izzet-boilerworks.js";
import _poolJackhammer from "../pool/jackhammer.js";
import _poolJhessianInfiltrator from "../pool/jhessian-infiltrator.js";
import _poolKalastriaNightwatch from "../pool/kalastria-nightwatch.js";
import _poolKazanduMammoth from "../pool/kazandu-mammoth.js";
import _poolKindlyCustomer from "../pool/kindly-customer.js";
import _poolKraulStinger from "../pool/kraul-stinger.js";
import _poolLeonardoTheBalance from "../pool/leonardo-the-balance.js";
import _poolLeoninArmorguard from "../pool/leonin-armorguard.js";
import _poolLochKorrigan from "../pool/loch-korrigan.js";
import _poolManaDrain from "../pool/mana-drain.js";
import _poolManagorgerHydra from "../pool/managorger-hydra.js";
import _poolMarshFlats from "../pool/marsh-flats.js";
import _poolMassProduction from "../pool/mass-production.js";
import _poolMerfolkTraders from "../pool/merfolk-traders.js";
import _poolMirriCatWarrior from "../pool/mirri-cat-warrior.js";
import _poolMoltenTributary from "../pool/molten-tributary.js";
import _poolMoltensteelDragon from "../pool/moltensteel-dragon.js";
import _poolMomentOfCraving from "../pool/moment-of-craving.js";
import _poolMysticSnake from "../pool/mystic-snake.js";
import _poolNoDachi from "../pool/no-dachi.js";
import _poolOboroPalaceInTheClouds from "../pool/oboro-palace-in-the-clouds.js";
import _poolOmnathLocusOfRage from "../pool/omnath-locus-of-rage.js";
import _poolOmniCheesePizza from "../pool/omni-cheese-pizza.js";
import _poolOneirophage from "../pool/oneirophage.js";
import _poolOrcishMechanics from "../pool/orcish-mechanics.js";
import _poolOrochiLeafcaller from "../pool/orochi-leafcaller.js";
import _poolOvergrownArmasaur from "../pool/overgrown-armasaur.js";
import _poolOverwhelmingInstinct from "../pool/overwhelming-instinct.js";
import _poolPhyrexianTower from "../pool/phyrexian-tower.js";
import _poolPincherBeetles from "../pool/pincher-beetles.js";
import _poolPristineTalisman from "../pool/pristine-talisman.js";
import _poolQuagmireDruid from "../pool/quagmire-druid.js";
import _poolQueensCommission from "../pool/queens-commission.js";
import _poolQuintoriusHistoryChaser from "../pool/quintorius-history-chaser.js";
import _poolRadhaHeirToKeld from "../pool/radha-heir-to-keld.js";
import _poolRagingCougar from "../pool/raging-cougar.js";
import _poolRatcatcher from "../pool/ratcatcher.js";
import _poolRavagingHorde from "../pool/ravaging-horde.js";
import _poolRecklessAssault from "../pool/reckless-assault.js";
import _poolReyhanLastOfTheAbzan from "../pool/reyhan-last-of-the-abzan.js";
import _poolRidgescaleTusker from "../pool/ridgescale-tusker.js";
import _poolRishkarPeemaRenegade from "../pool/rishkar-peema-renegade.js";
import _poolRottedHystrix from "../pool/rotted-hystrix.js";
import _poolRubyMedallion from "../pool/ruby-medallion.js";
import _poolSazhsChocobo from "../pool/sazhs-chocobo.js";
import _poolScarecrowGuide from "../pool/scarecrow-guide.js";
import _poolSearingFlesh from "../pool/searing-flesh.js";
import _poolShalaiAndHallar from "../pool/shalai-and-hallar.js";
import _poolShamanicRevelation from "../pool/shamanic-revelation.js";
import _poolSheoldredsEdict from "../pool/sheoldreds-edict.js";
import _poolSinisterSabotage from "../pool/sinister-sabotage.js";
import _poolSirShandlarOfEberyn from "../pool/sir-shandlar-of-eberyn.js";
import _poolSkyshipStalker from "../pool/skyship-stalker.js";
import _poolSkysnareSpider from "../pool/skysnare-spider.js";
import _poolSnowCoveredMountain from "../pool/snow-covered-mountain.js";
import _poolSocialClimber from "../pool/social-climber.js";
import _poolSorcererOfTheFang from "../pool/sorcerer-of-the-fang.js";
import _poolSquirrelanoids from "../pool/squirrelanoids.js";
import _poolStoicBuilder from "../pool/stoic-builder.js";
import _poolStoneRain from "../pool/stone-rain.js";
import _poolStonehornChanter from "../pool/stonehorn-chanter.js";
import _poolStormShaman from "../pool/storm-shaman.js";
import _poolStormcloudSpirit from "../pool/stormcloud-spirit.js";
import _poolSubterraneanCavern from "../pool/subterranean-cavern.js";
import _poolSuddenStrike from "../pool/sudden-strike.js";
import _poolSultaiAscendancy from "../pool/sultai-ascendancy.js";
import _poolSunCollaredRaptor from "../pool/sun-collared-raptor.js";
import _poolSunkenHollow from "../pool/sunken-hollow.js";
import _poolSurvivorOfKorlis from "../pool/survivor-of-korlis.js";
import _poolSvyeluniteTemple from "../pool/svyelunite-temple.js";
import _poolSweettoothWitch from "../pool/sweettooth-witch.js";
import _poolTalasAirShip from "../pool/talas-air-ship.js";
import _poolTalismanOfHierarchy from "../pool/talisman-of-hierarchy.js";
import _poolTatyova from "../pool/tatyova.js";
import _poolTerritorialScythecat from "../pool/territorial-scythecat.js";
import _poolThaliaGuardianOfThraben from "../pool/thalia-guardian-of-thraben.js";
import _poolTheEmperorOfPalamecia from "../pool/the-emperor-of-palamecia.js";
import _poolTheWhizzerClassicSpeedster from "../pool/the-whizzer-classic-speedster.js";
import _poolThoughtVessel from "../pool/thought-vessel.js";
import _poolThrashingBrontodon from "../pool/thrashing-brontodon.js";
import _poolTitansStrength from "../pool/titans-strength.js";
import _poolTomeBlast from "../pool/tome-blast.js";
import _poolTrainingCenter from "../pool/training-center.js";
import _poolUndeadAugur from "../pool/undead-augur.js";
import _poolViridianAcolyte from "../pool/viridian-acolyte.js";
import _poolViridianZealot from "../pool/viridian-zealot.js";
import _poolVoyagingSatyr from "../pool/voyaging-satyr.js";
import _poolVulshokBerserker from "../pool/vulshok-berserker.js";
import _poolWaytaTrainerProdigy from "../pool/wayta-trainer-prodigy.js";
import _poolWildCantor from "../pool/wild-cantor.js";
import _poolZagothCrystal from "../pool/zagoth-crystal.js";
import _poolZephyrNet from "../pool/zephyr-net.js";
import _tokensFaerieToken from "../tokens/faerie-token.js";
import _tokensIllusionTokenMinn from "../tokens/illusion-token-minn.js";
import _tokensInsectTokenBlackGreen from "../tokens/insect-token-black-green.js";
import _tokensTarmogoyfToken from "../tokens/tarmogoyf-token.js";

const shard: CardShard = {
  pool: [
    _poolActOfTreason,
    _poolAffaGuardHound,
    _poolAlelaArtfulProvocateur,
    _poolAleshasLegacy,
    _poolAnaconda,
    _poolAncestorsProphet,
    _poolAncientSpring,
    _poolAntQueen,
    _poolArborbackStomper,
    _poolArmoredWarhorse,
    _poolAscendedLawmage,
    _poolAssassinsTrophy,
    _poolAuraFracture,
    _poolAutomaticLibrarian,
    _poolAvenBattlePriest,
    _poolAxebaneBeast,
    _poolBalshanCollaborator,
    _poolBarkchannelPathway,
    _poolBlanchwoodTreefolk,
    _poolBlurredMongoose,
    _poolBoggartTrawler,
    _poolBoltOfKeranos,
    _poolBorosLocket,
    _poolBrassSecretary,
    _poolBreakDown,
    _poolBriaRiptideRogue,
    _poolBridgeworksBattle,
    _poolBrightbladeStoat,
    _poolBrightclimbPathway,
    _poolBullHippo,
    _poolBurnBright,
    _poolCabalTrainee,
    _poolCallTheCavalry,
    _poolCanopyVista,
    _poolChainDevil,
    _poolChakramSlinger,
    _poolCobblebrute,
    _poolCoiledTinviper,
    _poolColosYearling,
    _poolCopperMyr,
    _poolCoralMerfolk,
    _poolCrashOfRhinos,
    _poolDeadlyInsect,
    _poolDeadlyRollick,
    _poolDimirLocket,
    _poolDonatelloWayWithMachines,
    _poolDoubleCleave,
    _poolDoublingSeason,
    _poolEbonyTreefolk,
    _poolEidolonOfInspiration,
    _poolEmberethShieldbreaker,
    _poolEsperCormorants,
    _poolFierceWitchstalker,
    _poolFireNationAmbushers,
    _poolFiresOfUndeath,
    _poolFurnaceSpirit,
    _poolGarrisonCat,
    _poolGildedSentinel,
    _poolGlacialFloodplain,
    _poolGloriousAnthem,
    _poolGoblinFireslinger,
    _poolGoblinGardener,
    _poolGolgariSignet,
    _poolGoliathSpider,
    _poolGravedigger,
    _poolGrimDiscovery,
    _poolGrizzledOutrider,
    _poolHairStrungKoto,
    _poolHarrow,
    _poolHateMirage,
    _poolHowlingMine,
    _poolHulkingOgre,
    _poolIzzetBoilerworks,
    _poolJackhammer,
    _poolJhessianInfiltrator,
    _poolKalastriaNightwatch,
    _poolKazanduMammoth,
    _poolKindlyCustomer,
    _poolKraulStinger,
    _poolLeonardoTheBalance,
    _poolLeoninArmorguard,
    _poolLochKorrigan,
    _poolManaDrain,
    _poolManagorgerHydra,
    _poolMarshFlats,
    _poolMassProduction,
    _poolMerfolkTraders,
    _poolMirriCatWarrior,
    _poolMoltenTributary,
    _poolMoltensteelDragon,
    _poolMomentOfCraving,
    _poolMysticSnake,
    _poolNoDachi,
    _poolOboroPalaceInTheClouds,
    _poolOmnathLocusOfRage,
    _poolOmniCheesePizza,
    _poolOneirophage,
    _poolOrcishMechanics,
    _poolOrochiLeafcaller,
    _poolOvergrownArmasaur,
    _poolOverwhelmingInstinct,
    _poolPhyrexianTower,
    _poolPincherBeetles,
    _poolPristineTalisman,
    _poolQuagmireDruid,
    _poolQueensCommission,
    _poolQuintoriusHistoryChaser,
    _poolRadhaHeirToKeld,
    _poolRagingCougar,
    _poolRatcatcher,
    _poolRavagingHorde,
    _poolRecklessAssault,
    _poolReyhanLastOfTheAbzan,
    _poolRidgescaleTusker,
    _poolRishkarPeemaRenegade,
    _poolRottedHystrix,
    _poolRubyMedallion,
    _poolSazhsChocobo,
    _poolScarecrowGuide,
    _poolSearingFlesh,
    _poolShalaiAndHallar,
    _poolShamanicRevelation,
    _poolSheoldredsEdict,
    _poolSinisterSabotage,
    _poolSirShandlarOfEberyn,
    _poolSkyshipStalker,
    _poolSkysnareSpider,
    _poolSnowCoveredMountain,
    _poolSocialClimber,
    _poolSorcererOfTheFang,
    _poolSquirrelanoids,
    _poolStoicBuilder,
    _poolStoneRain,
    _poolStonehornChanter,
    _poolStormShaman,
    _poolStormcloudSpirit,
    _poolSubterraneanCavern,
    _poolSuddenStrike,
    _poolSultaiAscendancy,
    _poolSunCollaredRaptor,
    _poolSunkenHollow,
    _poolSurvivorOfKorlis,
    _poolSvyeluniteTemple,
    _poolSweettoothWitch,
    _poolTalasAirShip,
    _poolTalismanOfHierarchy,
    _poolTatyova,
    _poolTerritorialScythecat,
    _poolThaliaGuardianOfThraben,
    _poolTheEmperorOfPalamecia,
    _poolTheWhizzerClassicSpeedster,
    _poolThoughtVessel,
    _poolThrashingBrontodon,
    _poolTitansStrength,
    _poolTomeBlast,
    _poolTrainingCenter,
    _poolUndeadAugur,
    _poolViridianAcolyte,
    _poolViridianZealot,
    _poolVoyagingSatyr,
    _poolVulshokBerserker,
    _poolWaytaTrainerProdigy,
    _poolWildCantor,
    _poolZagothCrystal,
    _poolZephyrNet,
  ],
  tokens: [
    _tokensFaerieToken,
    _tokensIllusionTokenMinn,
    _tokensInsectTokenBlackGreen,
    _tokensTarmogoyfToken,
  ],
};

export default shard;
