// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.
// Run `npm run gen:cards -w engine` after adding or removing a card file.

import type { CardShard } from "../card-shards.js";

import _poolAIMBot from "../pool/a-i-m-bot.js";
import _poolAerieMystics from "../pool/aerie-mystics.js";
import _poolAhriman from "../pool/ahriman.js";
import _poolAkroanPhalanx from "../pool/akroan-phalanx.js";
import _poolAlabornTrooper from "../pool/alaborn-trooper.js";
import _poolAmuletOfVigor from "../pool/amulet-of-vigor.js";
import _poolAntiVenomHorrifyingHealer from "../pool/anti-venom-horrifying-healer.js";
import _poolAnvilwroughtRaptor from "../pool/anvilwrought-raptor.js";
import _poolArcaneFlight from "../pool/arcane-flight.js";
import _poolAssaultGriffin from "../pool/assault-griffin.js";
import _poolBarbtoothWurm from "../pool/barbtooth-wurm.js";
import _poolBattleHurda from "../pool/battle-hurda.js";
import _poolBeskirShieldmate from "../pool/beskir-shieldmate.js";
import _poolBladedPinions from "../pool/bladed-pinions.js";
import _poolBloodBairn from "../pool/blood-bairn.js";
import _poolBloodResearcher from "../pool/blood-researcher.js";
import _poolBogstomper from "../pool/bogstomper.js";
import _poolBondersEnclave from "../pool/bonders-enclave.js";
import _poolBorderlandRanger from "../pool/borderland-ranger.js";
import _poolBorosGarrison from "../pool/boros-garrison.js";
import _poolBrilliantPlan from "../pool/brilliant-plan.js";
import _poolCabarettiInitiate from "../pool/cabaretti-initiate.js";
import _poolCancel from "../pool/cancel.js";
import _poolCandlelightVigil from "../pool/candlelight-vigil.js";
import _poolCelebrityFencer from "../pool/celebrity-fencer.js";
import _poolCentaurSafeguard from "../pool/centaur-safeguard.js";
import _poolChantOfTheSkifsang from "../pool/chant-of-the-skifsang.js";
import _poolChromeCat from "../pool/chrome-cat.js";
import _poolCommercialDistrict from "../pool/commercial-district.js";
import _poolConsumptiveGoo from "../pool/consumptive-goo.js";
import _poolCryptRipper from "../pool/crypt-ripper.js";
import _poolCultistsStaff from "../pool/cultists-staff.js";
import _poolDeathHoodCobra from "../pool/death-hood-cobra.js";
import _poolDeconstruct from "../pool/deconstruct.js";
import _poolDeepAnalysis from "../pool/deep-analysis.js";
import _poolDereviEmpyrialTactician from "../pool/derevi-empyrial-tactician.js";
import _poolDevoutMonk from "../pool/devout-monk.js";
import _poolDocksideChef from "../pool/dockside-chef.js";
import _poolDrumhunter from "../pool/drumhunter.js";
import _poolDukharaPeafowl from "../pool/dukhara-peafowl.js";
import _poolEbonStronghold from "../pool/ebon-stronghold.js";
import _poolEcologistsTerrarium from "../pool/ecologists-terrarium.js";
import _poolElementalBond from "../pool/elemental-bond.js";
import _poolElvishLookout from "../pool/elvish-lookout.js";
import _poolEpicProportions from "../pool/epic-proportions.js";
import _poolErtaiWizardAdept from "../pool/ertai-wizard-adept.js";
import _poolEsperCharm from "../pool/esper-charm.js";
import _poolEssenceScatter from "../pool/essence-scatter.js";
import _poolExpedite from "../pool/expedite.js";
import _poolFalseDefeat from "../pool/false-defeat.js";
import _poolFellMire from "../pool/fell-mire.js";
import _poolFeralInvocation from "../pool/feral-invocation.js";
import _poolFlowstoneWyvern from "../pool/flowstone-wyvern.js";
import _poolForceOfSavagery from "../pool/force-of-savagery.js";
import _poolForgottenSentinel from "../pool/forgotten-sentinel.js";
import _poolFumeSpitter from "../pool/fume-spitter.js";
import _poolGhostSpectralSaboteur from "../pool/ghost-spectral-saboteur.js";
import _poolGiantScorpion from "../pool/giant-scorpion.js";
import _poolGladecoverScout from "../pool/gladecover-scout.js";
import _poolGoblinMountaineer from "../pool/goblin-mountaineer.js";
import _poolGrimclawBats from "../pool/grimclaw-bats.js";
import _poolHavenwoodBattleground from "../pool/havenwood-battleground.js";
import _poolHealerOfTheGlade from "../pool/healer-of-the-glade.js";
import _poolHeatRay from "../pool/heat-ray.js";
import _poolHeiBaiForestGuardian from "../pool/hei-bai-forest-guardian.js";
import _poolHengeGuardian from "../pool/henge-guardian.js";
import _poolHighAlert from "../pool/high-alert.js";
import _poolHobblefiend from "../pool/hobblefiend.js";
import _poolHonedKhopesh from "../pool/honed-khopesh.js";
import _poolHoodedKavu from "../pool/hooded-kavu.js";
import _poolHornOfRamos from "../pool/horn-of-ramos.js";
import _poolHussarPatrol from "../pool/hussar-patrol.js";
import _poolJungleShrine from "../pool/jungle-shrine.js";
import _poolKelinoreBat from "../pool/kelinore-bat.js";
import _poolKillMaimBurn from "../pool/kill-maim-burn.js";
import _poolKoboldTaskmaster from "../pool/kobold-taskmaster.js";
import _poolKoskunKeep from "../pool/koskun-keep.js";
import _poolKyoshiWarriors from "../pool/kyoshi-warriors.js";
import _poolLathnuSailback from "../pool/lathnu-sailback.js";
import _poolLeatherbackBaloth from "../pool/leatherback-baloth.js";
import _poolLeatherheadIronGator from "../pool/leatherhead-iron-gator.js";
import _poolLeoninSunStandard from "../pool/leonin-sun-standard.js";
import _poolLlanowarStalker from "../pool/llanowar-stalker.js";
import _poolLumengridWarden from "../pool/lumengrid-warden.js";
import _poolMagmaw from "../pool/magmaw.js";
import _poolMasterDecoy from "../pool/master-decoy.js";
import _poolMidnightHaunting from "../pool/midnight-haunting.js";
import _poolMoonlitWake from "../pool/moonlit-wake.js";
import _poolMosscoatGoriak from "../pool/mosscoat-goriak.js";
import _poolNegate from "../pool/negate.js";
import _poolObsianusGolem from "../pool/obsianus-golem.js";
import _poolOreskosSwiftclaw from "../pool/oreskos-swiftclaw.js";
import _poolOstiaryThrull from "../pool/ostiary-thrull.js";
import _poolPreordain from "../pool/preordain.js";
import _poolPreyUpon from "../pool/prey-upon.js";
import _poolPrimordialWurm from "../pool/primordial-wurm.js";
import _poolRageThrower from "../pool/rage-thrower.js";
import _poolRakdosCluestone from "../pool/rakdos-cluestone.js";
import _poolRamirezDepietro from "../pool/ramirez-depietro.js";
import _poolRecover from "../pool/recover.js";
import _poolRegathanFirecat from "../pool/regathan-firecat.js";
import _poolRiverMerfolk from "../pool/river-merfolk.js";
import _poolRodOfRuin from "../pool/rod-of-ruin.js";
import _poolSagesKnowledge from "../pool/sages-knowledge.js";
import _poolSangriteBacklash from "../pool/sangrite-backlash.js";
import _poolSavannahSage from "../pool/savannah-sage.js";
import _poolScionOfTheSwarm from "../pool/scion-of-the-swarm.js";
import _poolScrapyardSteelbreaker from "../pool/scrapyard-steelbreaker.js";
import _poolShivanOasis from "../pool/shivan-oasis.js";
import _poolSilverchaseFox from "../pool/silverchase-fox.js";
import _poolSkySpirit from "../pool/sky-spirit.js";
import _poolSkybridgeTowers from "../pool/skybridge-towers.js";
import _poolSkyhunterProwler from "../pool/skyhunter-prowler.js";
import _poolSlagstorm from "../pool/slagstorm.js";
import _poolSlinkingSkirge from "../pool/slinking-skirge.js";
import _poolSnappingCreeper from "../pool/snapping-creeper.js";
import _poolSokkaWolfCovesProtector from "../pool/sokka-wolf-coves-protector.js";
import _poolSoulreaperOfMogis from "../pool/soulreaper-of-mogis.js";
import _poolSoulswornJury from "../pool/soulsworn-jury.js";
import _poolSparkElemental from "../pool/spark-elemental.js";
import _poolSphinxMindbreaker from "../pool/sphinx-mindbreaker.js";
import _poolSpiritedCompanion from "../pool/spirited-companion.js";
import _poolSpurredWolverine from "../pool/spurred-wolverine.js";
import _poolStalkerHag from "../pool/stalker-hag.js";
import _poolStaunchShieldmate from "../pool/staunch-shieldmate.js";
import _poolSteadfastGuard from "../pool/steadfast-guard.js";
import _poolSteepleRoc from "../pool/steeple-roc.js";
import _poolStitchersSupplier from "../pool/stitchers-supplier.js";
import _poolStormSpirit from "../pool/storm-spirit.js";
import _poolStrengthOfThePack from "../pool/strength-of-the-pack.js";
import _poolSwornGuardian from "../pool/sworn-guardian.js";
import _poolSzarelGenesisShepherd from "../pool/szarel-genesis-shepherd.js";
import _poolTalionTheKindlyLord from "../pool/talion-the-kindly-lord.js";
import _poolTalismanOfIndulgence from "../pool/talisman-of-indulgence.js";
import _poolTempleOfEnlightenment from "../pool/temple-of-enlightenment.js";
import _poolTempleOfPlenty from "../pool/temple-of-plenty.js";
import _poolThantisTheWarweaver from "../pool/thantis-the-warweaver.js";
import _poolTheWanderingMinstrel from "../pool/the-wandering-minstrel.js";
import _poolThreeTreeRootweaver from "../pool/three-tree-rootweaver.js";
import _poolThunderbreakRegent from "../pool/thunderbreak-regent.js";
import _poolTolarianScholar from "../pool/tolarian-scholar.js";
import _poolTotemSpeaker from "../pool/totem-speaker.js";
import _poolToweringViewpoint from "../pool/towering-viewpoint.js";
import _poolTragicSlip from "../pool/tragic-slip.js";
import _poolTreeOfTales from "../pool/tree-of-tales.js";
import _poolTrueConviction from "../pool/true-conviction.js";
import _poolTrustyMachete from "../pool/trusty-machete.js";
import _poolUnderdarkBasilisk from "../pool/underdark-basilisk.js";
import _poolUnderworldRageHound from "../pool/underworld-rage-hound.js";
import _poolUniversalSolvent from "../pool/universal-solvent.js";
import _poolUnlicensedDisintegration from "../pool/unlicensed-disintegration.js";
import _poolVectisSilencers from "../pool/vectis-silencers.js";
import _poolVelaTheNightClad from "../pool/vela-the-night-clad.js";
import _poolVesselOfVolatility from "../pool/vessel-of-volatility.js";
import _poolVirulentEmissary from "../pool/virulent-emissary.js";
import _poolVisceraSeer from "../pool/viscera-seer.js";
import _poolVodalianMerchant from "../pool/vodalian-merchant.js";
import _poolWallOfStone from "../pool/wall-of-stone.js";
import _poolWarriorsHonor from "../pool/warriors-honor.js";
import _poolWaywardServant from "../pool/wayward-servant.js";
import _poolWitheringTorment from "../pool/withering-torment.js";
import _poolWoodlandCemetery from "../pool/woodland-cemetery.js";
import _poolYotianMedic from "../pool/yotian-medic.js";
import _poolZiatorasProvingGround from "../pool/ziatoras-proving-ground.js";
import _poolZodiacRabbit from "../pool/zodiac-rabbit.js";
import _tokensHumanToken from "../tokens/human-token.js";
import _tokensShrineToken from "../tokens/shrine-token.js";

const shard: CardShard = {
  pool: [
    _poolAIMBot,
    _poolAerieMystics,
    _poolAhriman,
    _poolAkroanPhalanx,
    _poolAlabornTrooper,
    _poolAmuletOfVigor,
    _poolAntiVenomHorrifyingHealer,
    _poolAnvilwroughtRaptor,
    _poolArcaneFlight,
    _poolAssaultGriffin,
    _poolBarbtoothWurm,
    _poolBattleHurda,
    _poolBeskirShieldmate,
    _poolBladedPinions,
    _poolBloodBairn,
    _poolBloodResearcher,
    _poolBogstomper,
    _poolBondersEnclave,
    _poolBorderlandRanger,
    _poolBorosGarrison,
    _poolBrilliantPlan,
    _poolCabarettiInitiate,
    _poolCancel,
    _poolCandlelightVigil,
    _poolCelebrityFencer,
    _poolCentaurSafeguard,
    _poolChantOfTheSkifsang,
    _poolChromeCat,
    _poolCommercialDistrict,
    _poolConsumptiveGoo,
    _poolCryptRipper,
    _poolCultistsStaff,
    _poolDeathHoodCobra,
    _poolDeconstruct,
    _poolDeepAnalysis,
    _poolDereviEmpyrialTactician,
    _poolDevoutMonk,
    _poolDocksideChef,
    _poolDrumhunter,
    _poolDukharaPeafowl,
    _poolEbonStronghold,
    _poolEcologistsTerrarium,
    _poolElementalBond,
    _poolElvishLookout,
    _poolEpicProportions,
    _poolErtaiWizardAdept,
    _poolEsperCharm,
    _poolEssenceScatter,
    _poolExpedite,
    _poolFalseDefeat,
    _poolFellMire,
    _poolFeralInvocation,
    _poolFlowstoneWyvern,
    _poolForceOfSavagery,
    _poolForgottenSentinel,
    _poolFumeSpitter,
    _poolGhostSpectralSaboteur,
    _poolGiantScorpion,
    _poolGladecoverScout,
    _poolGoblinMountaineer,
    _poolGrimclawBats,
    _poolHavenwoodBattleground,
    _poolHealerOfTheGlade,
    _poolHeatRay,
    _poolHeiBaiForestGuardian,
    _poolHengeGuardian,
    _poolHighAlert,
    _poolHobblefiend,
    _poolHonedKhopesh,
    _poolHoodedKavu,
    _poolHornOfRamos,
    _poolHussarPatrol,
    _poolJungleShrine,
    _poolKelinoreBat,
    _poolKillMaimBurn,
    _poolKoboldTaskmaster,
    _poolKoskunKeep,
    _poolKyoshiWarriors,
    _poolLathnuSailback,
    _poolLeatherbackBaloth,
    _poolLeatherheadIronGator,
    _poolLeoninSunStandard,
    _poolLlanowarStalker,
    _poolLumengridWarden,
    _poolMagmaw,
    _poolMasterDecoy,
    _poolMidnightHaunting,
    _poolMoonlitWake,
    _poolMosscoatGoriak,
    _poolNegate,
    _poolObsianusGolem,
    _poolOreskosSwiftclaw,
    _poolOstiaryThrull,
    _poolPreordain,
    _poolPreyUpon,
    _poolPrimordialWurm,
    _poolRageThrower,
    _poolRakdosCluestone,
    _poolRamirezDepietro,
    _poolRecover,
    _poolRegathanFirecat,
    _poolRiverMerfolk,
    _poolRodOfRuin,
    _poolSagesKnowledge,
    _poolSangriteBacklash,
    _poolSavannahSage,
    _poolScionOfTheSwarm,
    _poolScrapyardSteelbreaker,
    _poolShivanOasis,
    _poolSilverchaseFox,
    _poolSkySpirit,
    _poolSkybridgeTowers,
    _poolSkyhunterProwler,
    _poolSlagstorm,
    _poolSlinkingSkirge,
    _poolSnappingCreeper,
    _poolSokkaWolfCovesProtector,
    _poolSoulreaperOfMogis,
    _poolSoulswornJury,
    _poolSparkElemental,
    _poolSphinxMindbreaker,
    _poolSpiritedCompanion,
    _poolSpurredWolverine,
    _poolStalkerHag,
    _poolStaunchShieldmate,
    _poolSteadfastGuard,
    _poolSteepleRoc,
    _poolStitchersSupplier,
    _poolStormSpirit,
    _poolStrengthOfThePack,
    _poolSwornGuardian,
    _poolSzarelGenesisShepherd,
    _poolTalionTheKindlyLord,
    _poolTalismanOfIndulgence,
    _poolTempleOfEnlightenment,
    _poolTempleOfPlenty,
    _poolThantisTheWarweaver,
    _poolTheWanderingMinstrel,
    _poolThreeTreeRootweaver,
    _poolThunderbreakRegent,
    _poolTolarianScholar,
    _poolTotemSpeaker,
    _poolToweringViewpoint,
    _poolTragicSlip,
    _poolTreeOfTales,
    _poolTrueConviction,
    _poolTrustyMachete,
    _poolUnderdarkBasilisk,
    _poolUnderworldRageHound,
    _poolUniversalSolvent,
    _poolUnlicensedDisintegration,
    _poolVectisSilencers,
    _poolVelaTheNightClad,
    _poolVesselOfVolatility,
    _poolVirulentEmissary,
    _poolVisceraSeer,
    _poolVodalianMerchant,
    _poolWallOfStone,
    _poolWarriorsHonor,
    _poolWaywardServant,
    _poolWitheringTorment,
    _poolWoodlandCemetery,
    _poolYotianMedic,
    _poolZiatorasProvingGround,
    _poolZodiacRabbit,
  ],
  tokens: [
    _tokensHumanToken,
    _tokensShrineToken,
  ],
};

export default shard;
