// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.
// Run `npm run gen:cards -w engine` after adding or removing a card file.

import type { CardShard } from "../card-shards.js";

import _poolAdelineResplendentCathar from "../pool/adeline-resplendent-cathar.js";
import _poolAetherize from "../pool/aetherize.js";
import _poolAlabasterHostSanctifier from "../pool/alabaster-host-sanctifier.js";
import _poolAlexiosDeimosOfKosmos from "../pool/alexios-deimos-of-kosmos.js";
import _poolAlleyStrangler from "../pool/alley-strangler.js";
import _poolAngelOfRetribution from "../pool/angel-of-retribution.js";
import _poolAnowonTheRuinThief from "../pool/anowon-the-ruin-thief.js";
import _poolArabellaAbandonedDoll from "../pool/arabella-abandoned-doll.js";
import _poolArborAdherent from "../pool/arbor-adherent.js";
import _poolArchangel from "../pool/archangel.js";
import _poolArmoredGriffin from "../pool/armored-griffin.js";
import _poolAtog from "../pool/atog.js";
import _poolAugmentingAutomaton from "../pool/augmenting-automaton.js";
import _poolBallLightning from "../pool/ball-lightning.js";
import _poolBalothPrime from "../pool/baloth-prime.js";
import _poolBantBattlemage from "../pool/bant-battlemage.js";
import _poolBaralsExpertise from "../pool/barals-expertise.js";
import _poolBeamtownBeatstick from "../pool/beamtown-beatstick.js";
import _poolBecomeTheAvalanche from "../pool/become-the-avalanche.js";
import _poolBenalishKnight from "../pool/benalish-knight.js";
import _poolBlessedOrator from "../pool/blessed-orator.js";
import _poolBlindCreeper from "../pool/blind-creeper.js";
import _poolBombard from "../pool/bombard.js";
import _poolBountifulPromenade from "../pool/bountiful-promenade.js";
import _poolBruvacTheGrandiloquent from "../pool/bruvac-the-grandiloquent.js";
import _poolBulwarkGiant from "../pool/bulwark-giant.js";
import _poolBurrentonShieldBearers from "../pool/burrenton-shield-bearers.js";
import _poolBurrowing from "../pool/burrowing.js";
import _poolCallToMind from "../pool/call-to-mind.js";
import _poolCanopySpider from "../pool/canopy-spider.js";
import _poolCapitalCity from "../pool/capital-city.js";
import _poolCasualtiesOfWar from "../pool/casualties-of-war.js";
import _poolCentaurHealer from "../pool/centaur-healer.js";
import _poolCharcoalDiamond from "../pool/charcoal-diamond.js";
import _poolChasmSkulker from "../pool/chasm-skulker.js";
import _poolChimneyRabble from "../pool/chimney-rabble.js";
import _poolChordOfCalling from "../pool/chord-of-calling.js";
import _poolClanDefiance from "../pool/clan-defiance.js";
import _poolCloudchaserEagle from "../pool/cloudchaser-eagle.js";
import _poolConsider from "../pool/consider.js";
import _poolCopyArtifact from "../pool/copy-artifact.js";
import _poolCorruptCourtOfficial from "../pool/corrupt-court-official.js";
import _poolCrackTheEarth from "../pool/crack-the-earth.js";
import _poolCrypticCommand from "../pool/cryptic-command.js";
import _poolCuriosity from "../pool/curiosity.js";
import _poolDaggerclawImp from "../pool/daggerclaw-imp.js";
import _poolDaiLiCensor from "../pool/dai-li-censor.js";
import _poolDamnation from "../pool/damnation.js";
import _poolDarkHeartOfTheWood from "../pool/dark-heart-of-the-wood.js";
import _poolDawnOfHope from "../pool/dawn-of-hope.js";
import _poolDawnhartGeist from "../pool/dawnhart-geist.js";
import _poolDawnwingMarshal from "../pool/dawnwing-marshal.js";
import _poolDepthsOfDesire from "../pool/depths-of-desire.js";
import _poolDesertedBeach from "../pool/deserted-beach.js";
import _poolDesertedTemple from "../pool/deserted-temple.js";
import _poolDesynchronization from "../pool/desynchronization.js";
import _poolDictateOfTheTwinGods from "../pool/dictate-of-the-twin-gods.js";
import _poolDihadaBinderOfWills from "../pool/dihada-binder-of-wills.js";
import _poolDjinnOfTheLamp from "../pool/djinn-of-the-lamp.js";
import _poolDrainTheWell from "../pool/drain-the-well.js";
import _poolDrakusethMawOfFlames from "../pool/drakuseth-maw-of-flames.js";
import _poolDutifulServants from "../pool/dutiful-servants.js";
import _poolEmeriaTheSkyRuin from "../pool/emeria-the-sky-ruin.js";
import _poolEmpyreanEagle from "../pool/empyrean-eagle.js";
import _poolEshkiTemursRoar from "../pool/eshki-temurs-roar.js";
import _poolEtheriumSculptor from "../pool/etherium-sculptor.js";
import _poolEverybodyLives from "../pool/everybody-lives.js";
import _poolEyesOfTheBeholder from "../pool/eyes-of-the-beholder.js";
import _poolFelidarSovereign from "../pool/felidar-sovereign.js";
import _poolFireNationSoldier from "../pool/fire-nation-soldier.js";
import _poolFlashback from "../pool/flashback.js";
import _poolFlyingOctobot from "../pool/flying-octobot.js";
import _poolFortify from "../pool/fortify.js";
import _poolFountainOfRenewal from "../pool/fountain-of-renewal.js";
import _poolFrostMarsh from "../pool/frost-marsh.js";
import _poolFrozenShade from "../pool/frozen-shade.js";
import _poolFyndhornElves from "../pool/fyndhorn-elves.js";
import _poolGeistOfTheArchives from "../pool/geist-of-the-archives.js";
import _poolGhostlyPrison from "../pool/ghostly-prison.js";
import _poolGoblinGangLeader from "../pool/goblin-gang-leader.js";
import _poolGoblinRally from "../pool/goblin-rally.js";
import _poolGravitationalShift from "../pool/gravitational-shift.js";
import _poolGreyHavensNavigator from "../pool/grey-havens-navigator.js";
import _poolGrislySalvage from "../pool/grisly-salvage.js";
import _poolGroundbreaker from "../pool/groundbreaker.js";
import _poolGuardDuty from "../pool/guard-duty.js";
import _poolHighFaeTrickster from "../pool/high-fae-trickster.js";
import _poolHonestRutstein from "../pool/honest-rutstein.js";
import _poolHourOfReckoning from "../pool/hour-of-reckoning.js";
import _poolImprovisedArmor from "../pool/improvised-armor.js";
import _poolInfernoTitan from "../pool/inferno-titan.js";
import _poolInfuriate from "../pool/infuriate.js";
import _poolInsatiableAvarice from "../pool/insatiable-avarice.js";
import _poolJarvisEarthsMightiestButler from "../pool/jarvis-earths-mightiest-butler.js";
import _poolJinGitaxiasProgressTyrant from "../pool/jin-gitaxias-progress-tyrant.js";
import _poolJungleLion from "../pool/jungle-lion.js";
import _poolKujaGenomeSorcerer from "../pool/kuja-genome-sorcerer.js";
import _poolLathlissDragonQueen from "../pool/lathliss-dragon-queen.js";
import _poolLoamDryad from "../pool/loam-dryad.js";
import _poolLoransEscape from "../pool/lorans-escape.js";
import _poolLotlethGiant from "../pool/lotleth-giant.js";
import _poolLuminousAngel from "../pool/luminous-angel.js";
import _poolMarduBanner from "../pool/mardu-banner.js";
import _poolMaritimeGuard from "../pool/maritime-guard.js";
import _poolMarkedByHonor from "../pool/marked-by-honor.js";
import _poolMikokoroCenterOfTheSea from "../pool/mikokoro-center-of-the-sea.js";
import _poolMirkoObsessiveTheorist from "../pool/mirko-obsessive-theorist.js";
import _poolMoggSentry from "../pool/mogg-sentry.js";
import _poolMrFoxglove from "../pool/mr-foxglove.js";
import _poolMyriadLandscape from "../pool/myriad-landscape.js";
import _poolNaturalConnection from "../pool/natural-connection.js";
import _poolNeedlepeakSpider from "../pool/needlepeak-spider.js";
import _poolNightshadeDryad from "../pool/nightshade-dryad.js";
import _poolNightveilSprite from "../pool/nightveil-sprite.js";
import _poolObeliskOfAlara from "../pool/obelisk-of-alara.js";
import _poolObeliskOfBant from "../pool/obelisk-of-bant.js";
import _poolObsessiveStitcher from "../pool/obsessive-stitcher.js";
import _poolOminousAsylum from "../pool/ominous-asylum.js";
import _poolOracleOfNectars from "../pool/oracle-of-nectars.js";
import _poolOutpostSiege from "../pool/outpost-siege.js";
import _poolOvikaEnigmaGoliath from "../pool/ovika-enigma-goliath.js";
import _poolPaladinOfTheBloodstained from "../pool/paladin-of-the-bloodstained.js";
import _poolPardicWanderer from "../pool/pardic-wanderer.js";
import _poolPeerIntoTheAbyss from "../pool/peer-into-the-abyss.js";
import _poolPharikasMender from "../pool/pharikas-mender.js";
import _poolPhyrexianArena from "../pool/phyrexian-arena.js";
import _poolPhyrexianDenouncer from "../pool/phyrexian-denouncer.js";
import _poolPlagueBeetle from "../pool/plague-beetle.js";
import _poolPollywogProdigy from "../pool/pollywog-prodigy.js";
import _poolPrimalFrenzy from "../pool/primal-frenzy.js";
import _poolPrismaticVista from "../pool/prismatic-vista.js";
import _poolProsperTomeBound from "../pool/prosper-tome-bound.js";
import _poolQuezaAugurOfAgonies from "../pool/queza-augur-of-agonies.js";
import _poolQuicksilverFisher from "../pool/quicksilver-fisher.js";
import _poolRaggadraggaGoregutsBoss from "../pool/raggadragga-goreguts-boss.js";
import _poolRagingGoblin from "../pool/raging-goblin.js";
import _poolRainOfThorns from "../pool/rain-of-thorns.js";
import _poolRamunapRuins from "../pool/ramunap-ruins.js";
import _poolRankleMasterOfPranks from "../pool/rankle-master-of-pranks.js";
import _poolRedoubledStormsinger from "../pool/redoubled-stormsinger.js";
import _poolRiotGear from "../pool/riot-gear.js";
import _poolRiptideCrab from "../pool/riptide-crab.js";
import _poolRousingRead from "../pool/rousing-read.js";
import _poolRowanTreefolk from "../pool/rowan-treefolk.js";
import _poolSandbarMerfolk from "../pool/sandbar-merfolk.js";
import _poolSavageGorilla from "../pool/savage-gorilla.js";
import _poolSawInHalf from "../pool/saw-in-half.js";
import _poolScepterOfInsight from "../pool/scepter-of-insight.js";
import _poolScorchingSpear from "../pool/scorching-spear.js";
import _poolSearstepPathway from "../pool/searstep-pathway.js";
import _poolSecureTheWastes from "../pool/secure-the-wastes.js";
import _poolSetessanChampion from "../pool/setessan-champion.js";
import _poolSidarJabariOfZhalfir from "../pool/sidar-jabari-of-zhalfir.js";
import _poolSiegecraft from "../pool/siegecraft.js";
import _poolSigardaFontOfBlessings from "../pool/sigarda-font-of-blessings.js";
import _poolSilentObserver from "../pool/silent-observer.js";
import _poolSilverquillCampus from "../pool/silverquill-campus.js";
import _poolSizzle from "../pool/sizzle.js";
import _poolSkirsdagFlayer from "../pool/skirsdag-flayer.js";
import _poolSmolderingCrater from "../pool/smoldering-crater.js";
import _poolSnappingGnarlid from "../pool/snapping-gnarlid.js";
import _poolSoulboundGuardians from "../pool/soulbound-guardians.js";
import _poolSpectralProcession from "../pool/spectral-procession.js";
import _poolSpellseeker from "../pool/spellseeker.js";
import _poolSquirmingMass from "../pool/squirming-mass.js";
import _poolStadiumHeadliner from "../pool/stadium-headliner.js";
import _poolStormKilnArtist from "../pool/storm-kiln-artist.js";
import _poolSundownPass from "../pool/sundown-pass.js";
import _poolSunkenRuins from "../pool/sunken-ruins.js";
import _poolSwiftwaterCliffs from "../pool/swiftwater-cliffs.js";
import _poolSwordOfLightAndShadow from "../pool/sword-of-light-and-shadow.js";
import _poolTakenumaAbandonedMire from "../pool/takenuma-abandoned-mire.js";
import _poolTeeterpeakAmbusher from "../pool/teeterpeak-ambusher.js";
import _poolTelimtorsDarts from "../pool/telimtors-darts.js";
import _poolThopterEngineer from "../pool/thopter-engineer.js";
import _poolThrabenValiant from "../pool/thraben-valiant.js";
import _poolThreaten from "../pool/threaten.js";
import _poolThunderSpirit from "../pool/thunder-spirit.js";
import _poolTidechannelPathway from "../pool/tidechannel-pathway.js";
import _poolTirelessProvisioner from "../pool/tireless-provisioner.js";
import _poolTouchOfBrilliance from "../pool/touch-of-brilliance.js";
import _poolTraverseTheOutlands from "../pool/traverse-the-outlands.js";
import _poolTreeMonkey from "../pool/tree-monkey.js";
import _poolTurntimberGrove from "../pool/turntimber-grove.js";
import _poolTyrantsFamiliar from "../pool/tyrants-familiar.js";
import _poolUnbreathingHorde from "../pool/unbreathing-horde.js";
import _poolUnnerve from "../pool/unnerve.js";
import _poolUnrulyMob from "../pool/unruly-mob.js";
import _poolUpdraftElemental from "../pool/updraft-elemental.js";
import _poolVenomcrawler from "../pool/venomcrawler.js";
import _poolVizierOfTumblingSands from "../pool/vizier-of-tumbling-sands.js";
import _poolVolcanicHammer from "../pool/volcanic-hammer.js";
import _poolWallOfBlood from "../pool/wall-of-blood.js";
import _poolWallOfOmens from "../pool/wall-of-omens.js";
import _poolWelcomeTheDead from "../pool/welcome-the-dead.js";
import _poolWhipSergeant from "../pool/whip-sergeant.js";
import _poolWindDrake from "../pool/wind-drake.js";
import _poolWindfall from "../pool/windfall.js";
import _poolWingedCoatl from "../pool/winged-coatl.js";
import _poolWingedWords from "../pool/winged-words.js";
import _poolWoodlandMystic from "../pool/woodland-mystic.js";
import _poolZendikarResurgent from "../pool/zendikar-resurgent.js";
import _poolZhalfirinVoid from "../pool/zhalfirin-void.js";
import _poolZodiacMonkey from "../pool/zodiac-monkey.js";
import _tokensBeastToken33 from "../tokens/beast-token-3-3.js";
import _tokensBlueBirdToken from "../tokens/blue-bird-token.js";
import _tokensCitizenToken from "../tokens/citizen-token.js";
import _tokensDragonTokenFirebreathing from "../tokens/dragon-token-firebreathing.js";
import _tokensEldraziSpawnToken from "../tokens/eldrazi-spawn-token.js";
import _tokensHydraToken from "../tokens/hydra-token.js";
import _tokensJunkToken from "../tokens/junk-token.js";
import _tokensLanderToken from "../tokens/lander-token.js";
import _tokensMeteoriteToken from "../tokens/meteorite-token.js";
import _tokensWizardTokenGuff from "../tokens/wizard-token-guff.js";

const shard: CardShard = {
  pool: [
    _poolAdelineResplendentCathar,
    _poolAetherize,
    _poolAlabasterHostSanctifier,
    _poolAlexiosDeimosOfKosmos,
    _poolAlleyStrangler,
    _poolAngelOfRetribution,
    _poolAnowonTheRuinThief,
    _poolArabellaAbandonedDoll,
    _poolArborAdherent,
    _poolArchangel,
    _poolArmoredGriffin,
    _poolAtog,
    _poolAugmentingAutomaton,
    _poolBallLightning,
    _poolBalothPrime,
    _poolBantBattlemage,
    _poolBaralsExpertise,
    _poolBeamtownBeatstick,
    _poolBecomeTheAvalanche,
    _poolBenalishKnight,
    _poolBlessedOrator,
    _poolBlindCreeper,
    _poolBombard,
    _poolBountifulPromenade,
    _poolBruvacTheGrandiloquent,
    _poolBulwarkGiant,
    _poolBurrentonShieldBearers,
    _poolBurrowing,
    _poolCallToMind,
    _poolCanopySpider,
    _poolCapitalCity,
    _poolCasualtiesOfWar,
    _poolCentaurHealer,
    _poolCharcoalDiamond,
    _poolChasmSkulker,
    _poolChimneyRabble,
    _poolChordOfCalling,
    _poolClanDefiance,
    _poolCloudchaserEagle,
    _poolConsider,
    _poolCopyArtifact,
    _poolCorruptCourtOfficial,
    _poolCrackTheEarth,
    _poolCrypticCommand,
    _poolCuriosity,
    _poolDaggerclawImp,
    _poolDaiLiCensor,
    _poolDamnation,
    _poolDarkHeartOfTheWood,
    _poolDawnOfHope,
    _poolDawnhartGeist,
    _poolDawnwingMarshal,
    _poolDepthsOfDesire,
    _poolDesertedBeach,
    _poolDesertedTemple,
    _poolDesynchronization,
    _poolDictateOfTheTwinGods,
    _poolDihadaBinderOfWills,
    _poolDjinnOfTheLamp,
    _poolDrainTheWell,
    _poolDrakusethMawOfFlames,
    _poolDutifulServants,
    _poolEmeriaTheSkyRuin,
    _poolEmpyreanEagle,
    _poolEshkiTemursRoar,
    _poolEtheriumSculptor,
    _poolEverybodyLives,
    _poolEyesOfTheBeholder,
    _poolFelidarSovereign,
    _poolFireNationSoldier,
    _poolFlashback,
    _poolFlyingOctobot,
    _poolFortify,
    _poolFountainOfRenewal,
    _poolFrostMarsh,
    _poolFrozenShade,
    _poolFyndhornElves,
    _poolGeistOfTheArchives,
    _poolGhostlyPrison,
    _poolGoblinGangLeader,
    _poolGoblinRally,
    _poolGravitationalShift,
    _poolGreyHavensNavigator,
    _poolGrislySalvage,
    _poolGroundbreaker,
    _poolGuardDuty,
    _poolHighFaeTrickster,
    _poolHonestRutstein,
    _poolHourOfReckoning,
    _poolImprovisedArmor,
    _poolInfernoTitan,
    _poolInfuriate,
    _poolInsatiableAvarice,
    _poolJarvisEarthsMightiestButler,
    _poolJinGitaxiasProgressTyrant,
    _poolJungleLion,
    _poolKujaGenomeSorcerer,
    _poolLathlissDragonQueen,
    _poolLoamDryad,
    _poolLoransEscape,
    _poolLotlethGiant,
    _poolLuminousAngel,
    _poolMarduBanner,
    _poolMaritimeGuard,
    _poolMarkedByHonor,
    _poolMikokoroCenterOfTheSea,
    _poolMirkoObsessiveTheorist,
    _poolMoggSentry,
    _poolMrFoxglove,
    _poolMyriadLandscape,
    _poolNaturalConnection,
    _poolNeedlepeakSpider,
    _poolNightshadeDryad,
    _poolNightveilSprite,
    _poolObeliskOfAlara,
    _poolObeliskOfBant,
    _poolObsessiveStitcher,
    _poolOminousAsylum,
    _poolOracleOfNectars,
    _poolOutpostSiege,
    _poolOvikaEnigmaGoliath,
    _poolPaladinOfTheBloodstained,
    _poolPardicWanderer,
    _poolPeerIntoTheAbyss,
    _poolPharikasMender,
    _poolPhyrexianArena,
    _poolPhyrexianDenouncer,
    _poolPlagueBeetle,
    _poolPollywogProdigy,
    _poolPrimalFrenzy,
    _poolPrismaticVista,
    _poolProsperTomeBound,
    _poolQuezaAugurOfAgonies,
    _poolQuicksilverFisher,
    _poolRaggadraggaGoregutsBoss,
    _poolRagingGoblin,
    _poolRainOfThorns,
    _poolRamunapRuins,
    _poolRankleMasterOfPranks,
    _poolRedoubledStormsinger,
    _poolRiotGear,
    _poolRiptideCrab,
    _poolRousingRead,
    _poolRowanTreefolk,
    _poolSandbarMerfolk,
    _poolSavageGorilla,
    _poolSawInHalf,
    _poolScepterOfInsight,
    _poolScorchingSpear,
    _poolSearstepPathway,
    _poolSecureTheWastes,
    _poolSetessanChampion,
    _poolSidarJabariOfZhalfir,
    _poolSiegecraft,
    _poolSigardaFontOfBlessings,
    _poolSilentObserver,
    _poolSilverquillCampus,
    _poolSizzle,
    _poolSkirsdagFlayer,
    _poolSmolderingCrater,
    _poolSnappingGnarlid,
    _poolSoulboundGuardians,
    _poolSpectralProcession,
    _poolSpellseeker,
    _poolSquirmingMass,
    _poolStadiumHeadliner,
    _poolStormKilnArtist,
    _poolSundownPass,
    _poolSunkenRuins,
    _poolSwiftwaterCliffs,
    _poolSwordOfLightAndShadow,
    _poolTakenumaAbandonedMire,
    _poolTeeterpeakAmbusher,
    _poolTelimtorsDarts,
    _poolThopterEngineer,
    _poolThrabenValiant,
    _poolThreaten,
    _poolThunderSpirit,
    _poolTidechannelPathway,
    _poolTirelessProvisioner,
    _poolTouchOfBrilliance,
    _poolTraverseTheOutlands,
    _poolTreeMonkey,
    _poolTurntimberGrove,
    _poolTyrantsFamiliar,
    _poolUnbreathingHorde,
    _poolUnnerve,
    _poolUnrulyMob,
    _poolUpdraftElemental,
    _poolVenomcrawler,
    _poolVizierOfTumblingSands,
    _poolVolcanicHammer,
    _poolWallOfBlood,
    _poolWallOfOmens,
    _poolWelcomeTheDead,
    _poolWhipSergeant,
    _poolWindDrake,
    _poolWindfall,
    _poolWingedCoatl,
    _poolWingedWords,
    _poolWoodlandMystic,
    _poolZendikarResurgent,
    _poolZhalfirinVoid,
    _poolZodiacMonkey,
  ],
  tokens: [
    _tokensBeastToken33,
    _tokensBlueBirdToken,
    _tokensCitizenToken,
    _tokensDragonTokenFirebreathing,
    _tokensEldraziSpawnToken,
    _tokensHydraToken,
    _tokensJunkToken,
    _tokensLanderToken,
    _tokensMeteoriteToken,
    _tokensWizardTokenGuff,
  ],
};

export default shard;
