// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.
// Run `npm run gen:cards -w engine` after adding or removing a card file.

import type { CardShard } from "../card-shards.js";

import _poolAbyssalGorestalker from "../pool/abyssal-gorestalker.js";
import _poolAccessTunnel from "../pool/access-tunnel.js";
import _poolAncientTomb from "../pool/ancient-tomb.js";
import _poolArashinCleric from "../pool/arashin-cleric.js";
import _poolAvatarEnthusiasts from "../pool/avatar-enthusiasts.js";
import _poolBarbarianHorde from "../pool/barbarian-horde.js";
import _poolBenalishTrapper from "../pool/benalish-trapper.js";
import _poolBewilder from "../pool/bewilder.js";
import _poolBhaalsInvoker from "../pool/bhaals-invoker.js";
import _poolBirninZanaPlaza from "../pool/birnin-zana-plaza.js";
import _poolBlastingStation from "../pool/blasting-station.js";
import _poolBogNaughty from "../pool/bog-naughty.js";
import _poolBrimstoneDragon from "../pool/brimstone-dragon.js";
import _poolBuoyancy from "../pool/buoyancy.js";
import _poolCaelornaCoralTyrant from "../pool/caelorna-coral-tyrant.js";
import _poolCartographer from "../pool/cartographer.js";
import _poolCatharsCrusade from "../pool/cathars-crusade.js";
import _poolCausticRain from "../pool/caustic-rain.js";
import _poolChargingMonstrosaur from "../pool/charging-monstrosaur.js";
import _poolCloakedSiren from "../pool/cloaked-siren.js";
import _poolCoastalPeak from "../pool/coastal-peak.js";
import _poolContractKilling from "../pool/contract-killing.js";
import _poolCourierGriffin from "../pool/courier-griffin.js";
import _poolCowlProwler from "../pool/cowl-prowler.js";
import _poolCryptolithRite from "../pool/cryptolith-rite.js";
import _poolDaringApprentice from "../pool/daring-apprentice.js";
import _poolDarkRemedy from "../pool/dark-remedy.js";
import _poolDarkwaterCatacombs from "../pool/darkwater-catacombs.js";
import _poolDecanterOfEndlessWater from "../pool/decanter-of-endless-water.js";
import _poolDenyEntry from "../pool/deny-entry.js";
import _poolDevilthornFox from "../pool/devilthorn-fox.js";
import _poolDimensionX from "../pool/dimension-x.js";
import _poolDismiss from "../pool/dismiss.js";
import _poolDrossSkullbomb from "../pool/dross-skullbomb.js";
import _poolExsanguinate from "../pool/exsanguinate.js";
import _poolFabledPassage from "../pool/fabled-passage.js";
import _poolFireLordZuko from "../pool/fire-lord-zuko.js";
import _poolFlowstoneKavu from "../pool/flowstone-kavu.js";
import _poolFlyingDolphinFish from "../pool/flying-dolphin-fish.js";
import _poolFortifiedVillage from "../pool/fortified-village.js";
import _poolFugue from "../pool/fugue.js";
import _poolGenerousGift from "../pool/generous-gift.js";
import _poolGenesisUltimatum from "../pool/genesis-ultimatum.js";
import _poolGiantFly from "../pool/giant-fly.js";
import _poolGiantSpider from "../pool/giant-spider.js";
import _poolGildedLotus from "../pool/gilded-lotus.js";
import _poolGlassGolem from "../pool/glass-golem.js";
import _poolGoblinGlider from "../pool/goblin-glider.js";
import _poolGreatForestDruid from "../pool/great-forest-druid.js";
import _poolGreatHart from "../pool/great-hart.js";
import _poolGreelsCaress from "../pool/greels-caress.js";
import _poolGriffinDreamfinder from "../pool/griffin-dreamfinder.js";
import _poolGrimBauble from "../pool/grim-bauble.js";
import _poolGuardiansOfMeletis from "../pool/guardians-of-meletis.js";
import _poolHallowedFountain from "../pool/hallowed-fountain.js";
import _poolHandOfSilumgar from "../pool/hand-of-silumgar.js";
import _poolHavenwoodWurm from "../pool/havenwood-wurm.js";
import _poolHawkeaterMoth from "../pool/hawkeater-moth.js";
import _poolHieroglyphicIllumination from "../pool/hieroglyphic-illumination.js";
import _poolHighMarket from "../pool/high-market.js";
import _poolHorrorOfTheDim from "../pool/horror-of-the-dim.js";
import _poolImpale from "../pool/impale.js";
import _poolImplode from "../pool/implode.js";
import _poolInfernoJet from "../pool/inferno-jet.js";
import _poolInsidiousRoots from "../pool/insidious-roots.js";
import _poolInspiration from "../pool/inspiration.js";
import _poolInspiredSphinx from "../pool/inspired-sphinx.js";
import _poolInspiritFlagshipVessel from "../pool/inspirit-flagship-vessel.js";
import _poolIntangibleVirtue from "../pool/intangible-virtue.js";
import _poolIronrootTreefolk from "../pool/ironroot-treefolk.js";
import _poolIzzetChronarch from "../pool/izzet-chronarch.js";
import _poolJoustThrough from "../pool/joust-through.js";
import _poolKardurDoomscourge from "../pool/kardur-doomscourge.js";
import _poolKarokWrangler from "../pool/karok-wrangler.js";
import _poolKelsienThePlague from "../pool/kelsien-the-plague.js";
import _poolKillerWhale from "../pool/killer-whale.js";
import _poolKnightOfTheKeep from "../pool/knight-of-the-keep.js";
import _poolKykarWindsFury from "../pool/kykar-winds-fury.js";
import _poolLashOfMalice from "../pool/lash-of-malice.js";
import _poolLayWaste from "../pool/lay-waste.js";
import _poolLeap from "../pool/leap.js";
import _poolLifelink from "../pool/lifelink.js";
import _poolLoreWeaver from "../pool/lore-weaver.js";
import _poolLylaHolographicAssistant from "../pool/lyla-holographic-assistant.js";
import _poolMabel from "../pool/mabel.js";
import _poolMadcapSkills from "../pool/madcap-skills.js";
import _poolMagefireWings from "../pool/magefire-wings.js";
import _poolMakindiSliderunner from "../pool/makindi-sliderunner.js";
import _poolManicVandal from "../pool/manic-vandal.js";
import _poolMercilessExecutioner from "../pool/merciless-executioner.js";
import _poolMeticulousArchive from "../pool/meticulous-archive.js";
import _poolMineshaftSpider from "../pool/mineshaft-spider.js";
import _poolMiresGrasp from "../pool/mires-grasp.js";
import _poolMuckRats from "../pool/muck-rats.js";
import _poolNekusarTheMindrazer from "../pool/nekusar-the-mindrazer.js";
import _poolNephaliaSeakite from "../pool/nephalia-seakite.js";
import _poolNewBenalia from "../pool/new-benalia.js";
import _poolNightwingShade from "../pool/nightwing-shade.js";
import _poolNihilSpellbomb from "../pool/nihil-spellbomb.js";
import _poolOgreBerserker from "../pool/ogre-berserker.js";
import _poolOrzhovLocket from "../pool/orzhov-locket.js";
import _poolOutlawMedic from "../pool/outlaw-medic.js";
import _poolOwlbear from "../pool/owlbear.js";
import _poolPendulumOfPatterns from "../pool/pendulum-of-patterns.js";
import _poolPestilentWolf from "../pool/pestilent-wolf.js";
import _poolPiratePeddlers from "../pool/pirate-peddlers.js";
import _poolPlayfulShove from "../pool/playful-shove.js";
import _poolProsperousPirates from "../pool/prosperous-pirates.js";
import _poolPseudodragonFamiliar from "../pool/pseudodragon-familiar.js";
import _poolRecklessBrute from "../pool/reckless-brute.js";
import _poolRedElementalBlast from "../pool/red-elemental-blast.js";
import _poolResupply from "../pool/resupply.js";
import _poolRighteousCharge from "../pool/righteous-charge.js";
import _poolRipClanCrasher from "../pool/rip-clan-crasher.js";
import _poolRiteOfFlame from "../pool/rite-of-flame.js";
import _poolRiveteersOverlook from "../pool/riveteers-overlook.js";
import _poolRoguesPassage from "../pool/rogues-passage.js";
import _poolRowanScionOfWar from "../pool/rowan-scion-of-war.js";
import _poolRubbleReading from "../pool/rubble-reading.js";
import _poolSandblast from "../pool/sandblast.js";
import _poolSaruliCaretaker from "../pool/saruli-caretaker.js";
import _poolScavengerGrounds from "../pool/scavenger-grounds.js";
import _poolScorchedRusalka from "../pool/scorched-rusalka.js";
import _poolScreamPuff from "../pool/scream-puff.js";
import _poolScreechingDrake from "../pool/screeching-drake.js";
import _poolSecludedSteppe from "../pool/secluded-steppe.js";
import _poolSelesnyaSanctuary from "../pool/selesnya-sanctuary.js";
import _poolSerpentsPass from "../pool/serpents-pass.js";
import _poolSerraZealot from "../pool/serra-zealot.js";
import _poolShadowTheHedgehog from "../pool/shadow-the-hedgehog.js";
import _poolShadowmageInfiltrator from "../pool/shadowmage-infiltrator.js";
import _poolShefetDunes from "../pool/shefet-dunes.js";
import _poolShuEliteInfantry from "../pool/shu-elite-infantry.js";
import _poolShuko from "../pool/shuko.js";
import _poolSift from "../pool/sift.js";
import _poolSignInBlood from "../pool/sign-in-blood.js";
import _poolSkirmishRhino from "../pool/skirmish-rhino.js";
import _poolSkyshaper from "../pool/skyshaper.js";
import _poolSliverConstruct from "../pool/sliver-construct.js";
import _poolSoaringSeacliff from "../pool/soaring-seacliff.js";
import _poolSokkaTenaciousTactician from "../pool/sokka-tenacious-tactician.js";
import _poolSomberwaldDryad from "../pool/somberwald-dryad.js";
import _poolSramSeniorEdificer from "../pool/sram-senior-edificer.js";
import _poolStartFromScratch from "../pool/start-from-scratch.js";
import _poolStonyVoicedGoblins from "../pool/stony-voiced-goblins.js";
import _poolSunbladeSamurai from "../pool/sunblade-samurai.js";
import _poolSupportiveParents from "../pool/supportive-parents.js";
import _poolSurrakarMarauder from "../pool/surrakar-marauder.js";
import _poolTajuruSnarecaster from "../pool/tajuru-snarecaster.js";
import _poolTomakulHonorGuard from "../pool/tomakul-honor-guard.js";
import _poolTopanAscetic from "../pool/topan-ascetic.js";
import _poolTowerDrake from "../pool/tower-drake.js";
import _poolTradewindRider from "../pool/tradewind-rider.js";
import _poolUnsubtleMockery from "../pool/unsubtle-mockery.js";
import _poolUrborgDrake from "../pool/urborg-drake.js";
import _poolVectorImperialCapital from "../pool/vector-imperial-capital.js";
import _poolVigilance from "../pool/vigilance.js";
import _poolVisceridArmor from "../pool/viscerid-armor.js";
import _poolVolcanicDragon from "../pool/volcanic-dragon.js";
import _poolVoyagesEnd from "../pool/voyages-end.js";
import _poolVulshokHeartstoker from "../pool/vulshok-heartstoker.js";
import _poolWakingNightmare from "../pool/waking-nightmare.js";
import _poolWallOfMulch from "../pool/wall-of-mulch.js";
import _poolWarPriestOfThune from "../pool/war-priest-of-thune.js";
import _poolWarScreecher from "../pool/war-screecher.js";
import _poolWhirlwindOfThought from "../pool/whirlwind-of-thought.js";
import _poolWickerWitch from "../pool/wicker-witch.js";
import _poolWilsonRefinedGrizzly from "../pool/wilson-refined-grizzly.js";
import _poolWindScarredCrag from "../pool/wind-scarred-crag.js";
import _poolWingspanStride from "../pool/wingspan-stride.js";
import _poolWintersIntervention from "../pool/winters-intervention.js";
import _poolWyluliWolf from "../pool/wyluli-wolf.js";
import _poolYavimayaWurm from "../pool/yavimaya-wurm.js";
import _poolZombieGoliath from "../pool/zombie-goliath.js";
import _tokensServoToken from "../tokens/servo-token.js";

const shard: CardShard = {
  pool: [
    _poolAbyssalGorestalker,
    _poolAccessTunnel,
    _poolAncientTomb,
    _poolArashinCleric,
    _poolAvatarEnthusiasts,
    _poolBarbarianHorde,
    _poolBenalishTrapper,
    _poolBewilder,
    _poolBhaalsInvoker,
    _poolBirninZanaPlaza,
    _poolBlastingStation,
    _poolBogNaughty,
    _poolBrimstoneDragon,
    _poolBuoyancy,
    _poolCaelornaCoralTyrant,
    _poolCartographer,
    _poolCatharsCrusade,
    _poolCausticRain,
    _poolChargingMonstrosaur,
    _poolCloakedSiren,
    _poolCoastalPeak,
    _poolContractKilling,
    _poolCourierGriffin,
    _poolCowlProwler,
    _poolCryptolithRite,
    _poolDaringApprentice,
    _poolDarkRemedy,
    _poolDarkwaterCatacombs,
    _poolDecanterOfEndlessWater,
    _poolDenyEntry,
    _poolDevilthornFox,
    _poolDimensionX,
    _poolDismiss,
    _poolDrossSkullbomb,
    _poolExsanguinate,
    _poolFabledPassage,
    _poolFireLordZuko,
    _poolFlowstoneKavu,
    _poolFlyingDolphinFish,
    _poolFortifiedVillage,
    _poolFugue,
    _poolGenerousGift,
    _poolGenesisUltimatum,
    _poolGiantFly,
    _poolGiantSpider,
    _poolGildedLotus,
    _poolGlassGolem,
    _poolGoblinGlider,
    _poolGreatForestDruid,
    _poolGreatHart,
    _poolGreelsCaress,
    _poolGriffinDreamfinder,
    _poolGrimBauble,
    _poolGuardiansOfMeletis,
    _poolHallowedFountain,
    _poolHandOfSilumgar,
    _poolHavenwoodWurm,
    _poolHawkeaterMoth,
    _poolHieroglyphicIllumination,
    _poolHighMarket,
    _poolHorrorOfTheDim,
    _poolImpale,
    _poolImplode,
    _poolInfernoJet,
    _poolInsidiousRoots,
    _poolInspiration,
    _poolInspiredSphinx,
    _poolInspiritFlagshipVessel,
    _poolIntangibleVirtue,
    _poolIronrootTreefolk,
    _poolIzzetChronarch,
    _poolJoustThrough,
    _poolKardurDoomscourge,
    _poolKarokWrangler,
    _poolKelsienThePlague,
    _poolKillerWhale,
    _poolKnightOfTheKeep,
    _poolKykarWindsFury,
    _poolLashOfMalice,
    _poolLayWaste,
    _poolLeap,
    _poolLifelink,
    _poolLoreWeaver,
    _poolLylaHolographicAssistant,
    _poolMabel,
    _poolMadcapSkills,
    _poolMagefireWings,
    _poolMakindiSliderunner,
    _poolManicVandal,
    _poolMercilessExecutioner,
    _poolMeticulousArchive,
    _poolMineshaftSpider,
    _poolMiresGrasp,
    _poolMuckRats,
    _poolNekusarTheMindrazer,
    _poolNephaliaSeakite,
    _poolNewBenalia,
    _poolNightwingShade,
    _poolNihilSpellbomb,
    _poolOgreBerserker,
    _poolOrzhovLocket,
    _poolOutlawMedic,
    _poolOwlbear,
    _poolPendulumOfPatterns,
    _poolPestilentWolf,
    _poolPiratePeddlers,
    _poolPlayfulShove,
    _poolProsperousPirates,
    _poolPseudodragonFamiliar,
    _poolRecklessBrute,
    _poolRedElementalBlast,
    _poolResupply,
    _poolRighteousCharge,
    _poolRipClanCrasher,
    _poolRiteOfFlame,
    _poolRiveteersOverlook,
    _poolRoguesPassage,
    _poolRowanScionOfWar,
    _poolRubbleReading,
    _poolSandblast,
    _poolSaruliCaretaker,
    _poolScavengerGrounds,
    _poolScorchedRusalka,
    _poolScreamPuff,
    _poolScreechingDrake,
    _poolSecludedSteppe,
    _poolSelesnyaSanctuary,
    _poolSerpentsPass,
    _poolSerraZealot,
    _poolShadowTheHedgehog,
    _poolShadowmageInfiltrator,
    _poolShefetDunes,
    _poolShuEliteInfantry,
    _poolShuko,
    _poolSift,
    _poolSignInBlood,
    _poolSkirmishRhino,
    _poolSkyshaper,
    _poolSliverConstruct,
    _poolSoaringSeacliff,
    _poolSokkaTenaciousTactician,
    _poolSomberwaldDryad,
    _poolSramSeniorEdificer,
    _poolStartFromScratch,
    _poolStonyVoicedGoblins,
    _poolSunbladeSamurai,
    _poolSupportiveParents,
    _poolSurrakarMarauder,
    _poolTajuruSnarecaster,
    _poolTomakulHonorGuard,
    _poolTopanAscetic,
    _poolTowerDrake,
    _poolTradewindRider,
    _poolUnsubtleMockery,
    _poolUrborgDrake,
    _poolVectorImperialCapital,
    _poolVigilance,
    _poolVisceridArmor,
    _poolVolcanicDragon,
    _poolVoyagesEnd,
    _poolVulshokHeartstoker,
    _poolWakingNightmare,
    _poolWallOfMulch,
    _poolWarPriestOfThune,
    _poolWarScreecher,
    _poolWhirlwindOfThought,
    _poolWickerWitch,
    _poolWilsonRefinedGrizzly,
    _poolWindScarredCrag,
    _poolWingspanStride,
    _poolWintersIntervention,
    _poolWyluliWolf,
    _poolYavimayaWurm,
    _poolZombieGoliath,
  ],
  tokens: [
    _tokensServoToken,
  ],
};

export default shard;
