// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.
// Run `npm run gen:cards -w engine` after adding or removing a card file.

import type { CardShard } from "../card-shards.js";

import _poolAberrantReturn from "../pool/aberrant-return.js";
import _poolAbzanAscendancy from "../pool/abzan-ascendancy.js";
import _poolAetherHelix from "../pool/aether-helix.js";
import _poolAjanisChosen from "../pool/ajanis-chosen.js";
import _poolAlelaCunningConqueror from "../pool/alela-cunning-conqueror.js";
import _poolAngelicChorus from "../pool/angelic-chorus.js";
import _poolAngelsGrace from "../pool/angels-grace.js";
import _poolAnheloThePainter from "../pool/anhelo-the-painter.js";
import _poolAnkleBiter from "../pool/ankle-biter.js";
import _poolAshlingTheLimitless from "../pool/ashling-the-limitless.js";
import _poolAtarkaMonument from "../pool/atarka-monument.js";
import _poolAuroralProcession from "../pool/auroral-procession.js";
import _poolAvenSkirmisher from "../pool/aven-skirmisher.js";
import _poolAviationPioneer from "../pool/aviation-pioneer.js";
import _poolBaelothBarritylEntertainer from "../pool/baeloth-barrityl-entertainer.js";
import _poolBaronyVampire from "../pool/barony-vampire.js";
import _poolBarrinMasterWizard from "../pool/barrin-master-wizard.js";
import _poolBashToBits from "../pool/bash-to-bits.js";
import _poolBattlewandOak from "../pool/battlewand-oak.js";
import _poolBedrockTortoise from "../pool/bedrock-tortoise.js";
import _poolBiliousSkulldweller from "../pool/bilious-skulldweller.js";
import _poolBlackSunsZenith from "../pool/black-suns-zenith.js";
import _poolBlackWaltzNo3 from "../pool/black-waltz-no-3.js";
import _poolBlistergrub from "../pool/blistergrub.js";
import _poolBloodRites from "../pool/blood-rites.js";
import _poolBloodghast from "../pool/bloodghast.js";
import _poolBloodstainedMire from "../pool/bloodstained-mire.js";
import _poolBogWreckage from "../pool/bog-wreckage.js";
import _poolBoneToAsh from "../pool/bone-to-ash.js";
import _poolBonebreakerGiant from "../pool/bonebreaker-giant.js";
import _poolBoulderbornDragon from "../pool/boulderborn-dragon.js";
import _poolBraingeyser from "../pool/braingeyser.js";
import _poolBrainstorm from "../pool/brainstorm.js";
import _poolBristlingBackwoods from "../pool/bristling-backwoods.js";
import _poolCarnageTyrant from "../pool/carnage-tyrant.js";
import _poolCauldronOfSouls from "../pool/cauldron-of-souls.js";
import _poolCelestialPrism from "../pool/celestial-prism.js";
import _poolChainersEdict from "../pool/chainers-edict.js";
import _poolChakramRetriever from "../pool/chakram-retriever.js";
import _poolChardalynDragon from "../pool/chardalyn-dragon.js";
import _poolChasmDrake from "../pool/chasm-drake.js";
import _poolContradict from "../pool/contradict.js";
import _poolCranialPlating from "../pool/cranial-plating.js";
import _poolCrawlingSensation from "../pool/crawling-sensation.js";
import _poolCrimsonCaravaneer from "../pool/crimson-caravaneer.js";
import _poolCrimsonKobolds from "../pool/crimson-kobolds.js";
import _poolCrumblingNecropolis from "../pool/crumbling-necropolis.js";
import _poolCultistOfTheAbsolute from "../pool/cultist-of-the-absolute.js";
import _poolDaggerbackBasilisk from "../pool/daggerback-basilisk.js";
import _poolDailyBugleNewspaper from "../pool/daily-bugle-newspaper.js";
import _poolDakmorScorpion from "../pool/dakmor-scorpion.js";
import _poolDarksteelMyr from "../pool/darksteel-myr.js";
import _poolDauntlessSurvivor from "../pool/dauntless-survivor.js";
import _poolDeadbridgeShaman from "../pool/deadbridge-shaman.js";
import _poolDeafeningClarion from "../pool/deafening-clarion.js";
import _poolDefile from "../pool/defile.js";
import _poolDefiledCrypt from "../pool/defiled-crypt.js";
import _poolDelneyStreetwiseLookout from "../pool/delney-streetwise-lookout.js";
import _poolDesperateParry from "../pool/desperate-parry.js";
import _poolDiabolicIntent from "../pool/diabolic-intent.js";
import _poolDictateOfKarametra from "../pool/dictate-of-karametra.js";
import _poolDiscipleOfTeveshSzat from "../pool/disciple-of-tevesh-szat.js";
import _poolDoubleDown from "../pool/double-down.js";
import _poolDrakeHatchling from "../pool/drake-hatchling.js";
import _poolDreadPresence from "../pool/dread-presence.js";
import _poolDungeonShade from "../pool/dungeon-shade.js";
import _poolEarthRumble from "../pool/earth-rumble.js";
import _poolEbonyRhino from "../pool/ebony-rhino.js";
import _poolElderfangDisciple from "../pool/elderfang-disciple.js";
import _poolElvishWarrior from "../pool/elvish-warrior.js";
import _poolEmergeFromTheCocoon from "../pool/emerge-from-the-cocoon.js";
import _poolEngineRat from "../pool/engine-rat.js";
import _poolEsotericDuplicator from "../pool/esoteric-duplicator.js";
import _poolExcaliburSwordOfEden from "../pool/excalibur-sword-of-eden.js";
import _poolFabricate from "../pool/fabricate.js";
import _poolFaerieBladecrafter from "../pool/faerie-bladecrafter.js";
import _poolFatefulDiscovery from "../pool/fateful-discovery.js";
import _poolFelotharTheSteadfast from "../pool/felothar-the-steadfast.js";
import _poolFierceEmpath from "../pool/fierce-empath.js";
import _poolFiligreeCrawler from "../pool/filigree-crawler.js";
import _poolFlameLash from "../pool/flame-lash.js";
import _poolFlamekinHarbinger from "../pool/flamekin-harbinger.js";
import _poolFlankingTroops from "../pool/flanking-troops.js";
import _poolFlayedOne from "../pool/flayed-one.js";
import _poolForsakeTheWorldly from "../pool/forsake-the-worldly.js";
import _poolForsakenSanctuary from "../pool/forsaken-sanctuary.js";
import _poolFromBeyond from "../pool/from-beyond.js";
import _poolGaeasCradle from "../pool/gaeas-cradle.js";
import _poolGeodeRager from "../pool/geode-rager.js";
import _poolGhostQuarter from "../pool/ghost-quarter.js";
import _poolGiantCrab from "../pool/giant-crab.js";
import _poolGingerbreadCabin from "../pool/gingerbread-cabin.js";
import _poolGlenElendraArchmage from "../pool/glen-elendra-archmage.js";
import _poolGoblinAnarchomancer from "../pool/goblin-anarchomancer.js";
import _poolGoblinDeathraiders from "../pool/goblin-deathraiders.js";
import _poolGoblinPiledriver from "../pool/goblin-piledriver.js";
import _poolGoblinSpelunkers from "../pool/goblin-spelunkers.js";
import _poolGohnTownOfRuin from "../pool/gohn-town-of-ruin.js";
import _poolGondGate from "../pool/gond-gate.js";
import _poolGratefulApparition from "../pool/grateful-apparition.js";
import _poolGriffinSentinel from "../pool/griffin-sentinel.js";
import _poolGrimHireling from "../pool/grim-hireling.js";
import _poolGrislyTransformation from "../pool/grisly-transformation.js";
import _poolGruffTriplets from "../pool/gruff-triplets.js";
import _poolHammerheadMaggiaBoss from "../pool/hammerhead-maggia-boss.js";
import _poolHarabazDruid from "../pool/harabaz-druid.js";
import _poolHealerOfThePride from "../pool/healer-of-the-pride.js";
import _poolHeartwoodTreefolk from "../pool/heartwood-treefolk.js";
import _poolHerdGnarr from "../pool/herd-gnarr.js";
import _poolHerosDownfall from "../pool/heros-downfall.js";
import _poolHorizonOfProgress from "../pool/horizon-of-progress.js";
import _poolHornOfGreed from "../pool/horn-of-greed.js";
import _poolHornOfValhalla from "../pool/horn-of-valhalla.js";
import _poolHornetCobra from "../pool/hornet-cobra.js";
import _poolHulkingGoblin from "../pool/hulking-goblin.js";
import _poolHumongulus from "../pool/humongulus.js";
import _poolImposingVantasaur from "../pool/imposing-vantasaur.js";
import _poolIndrikStomphowler from "../pool/indrik-stomphowler.js";
import _poolInfectiousHorror from "../pool/infectious-horror.js";
import _poolInsurrection from "../pool/insurrection.js";
import _poolIntroductionToProphecy from "../pool/introduction-to-prophecy.js";
import _poolIroassChampion from "../pool/iroass-champion.js";
import _poolIroncladKrovod from "../pool/ironclad-krovod.js";
import _poolJenovaAncientCalamity from "../pool/jenova-ancient-calamity.js";
import _poolKarumonixTheRatKing from "../pool/karumonix-the-rat-king.js";
import _poolKeenSense from "../pool/keen-sense.js";
import _poolKheruGoldkeeper from "../pool/kheru-goldkeeper.js";
import _poolKingCheetah from "../pool/king-cheetah.js";
import _poolKlauthUnrivaledAncient from "../pool/klauth-unrivaled-ancient.js";
import _poolKnightErrant from "../pool/knight-errant.js";
import _poolKnightOfTheReliquary from "../pool/knight-of-the-reliquary.js";
import _poolKokushoTheEveningStar from "../pool/kokusho-the-evening-star.js";
import _poolKorvoldFaeCursedKing from "../pool/korvold-fae-cursed-king.js";
import _poolKozileksChanneler from "../pool/kozileks-channeler.js";
import _poolKudoKingAmongBears from "../pool/kudo-king-among-bears.js";
import _poolLampadOfDeathsVigil from "../pool/lampad-of-deaths-vigil.js";
import _poolLance from "../pool/lance.js";
import _poolLathrilBladeOfTheElves from "../pool/lathril-blade-of-the-elves.js";
import _poolLaughingJasperFlint from "../pool/laughing-jasper-flint.js";
import _poolLavaDart from "../pool/lava-dart.js";
import _poolLightningElemental from "../pool/lightning-elemental.js";
import _poolLordWindgrace from "../pool/lord-windgrace.js";
import _poolLoyalSubordinate from "../pool/loyal-subordinate.js";
import _poolMacabreWaltz from "../pool/macabre-waltz.js";
import _poolMagnifyingGlass from "../pool/magnifying-glass.js";
import _poolMalcolmKeenEyedNavigator from "../pool/malcolm-keen-eyed-navigator.js";
import _poolManaConfluence from "../pool/mana-confluence.js";
import _poolMarneusCalgar from "../pool/marneus-calgar.js";
import _poolMawcor from "../pool/mawcor.js";
import _poolMentalNote from "../pool/mental-note.js";
import _poolMindfulBiomancer from "../pool/mindful-biomancer.js";
import _poolNeverwinterDryad from "../pool/neverwinter-dryad.js";
import _poolNineFingersKeene from "../pool/nine-fingers-keene.js";
import _poolNirkanaAssassin from "../pool/nirkana-assassin.js";
import _poolNivMizzetVisionary from "../pool/niv-mizzet-visionary.js";
import _poolNotionThief from "../pool/notion-thief.js";
import _poolNyxWeaver from "../pool/nyx-weaver.js";
import _poolNyxbornColossus from "../pool/nyxborn-colossus.js";
import _poolOasisGardener from "../pool/oasis-gardener.js";
import _poolOdunosRiverTrawler from "../pool/odunos-river-trawler.js";
import _poolOrderOfMidnight from "../pool/order-of-midnight.js";
import _poolOvergrownTomb from "../pool/overgrown-tomb.js";
import _poolPastInFlames from "../pool/past-in-flames.js";
import _poolPathOfAncestry from "../pool/path-of-ancestry.js";
import _poolPestMascot from "../pool/pest-mascot.js";
import _poolPhyrexianGhoul from "../pool/phyrexian-ghoul.js";
import _poolPlatedGeopede from "../pool/plated-geopede.js";
import _poolPoisonTipArcher from "../pool/poison-tip-archer.js";
import _poolPrideGuardian from "../pool/pride-guardian.js";
import _poolPrimalHuntbeast from "../pool/primal-huntbeast.js";
import _poolPropheticPrism from "../pool/prophetic-prism.js";
import _poolProsperousInnkeeper from "../pool/prosperous-innkeeper.js";
import _poolProvokeTheTrolls from "../pool/provoke-the-trolls.js";
import _poolPutridLeech from "../pool/putrid-leech.js";
import _poolPyreticRitual from "../pool/pyretic-ritual.js";
import _poolQuandrixCampus from "../pool/quandrix-campus.js";
import _poolRagingRedcap from "../pool/raging-redcap.js";
import _poolRaidBombardment from "../pool/raid-bombardment.js";
import _poolRaisedByGiants from "../pool/raised-by-giants.js";
import _poolRangersLongbow from "../pool/rangers-longbow.js";
import _poolReckonersBargain from "../pool/reckoners-bargain.js";
import _poolResearchAssistant from "../pool/research-assistant.js";
import _poolRestInPeace from "../pool/rest-in-peace.js";
import _poolRestorationMagic from "../pool/restoration-magic.js";
import _poolRetreatToCoralhelm from "../pool/retreat-to-coralhelm.js";
import _poolRetreatToHagra from "../pool/retreat-to-hagra.js";
import _poolRetrofitterFoundry from "../pool/retrofitter-foundry.js";
import _poolRevitalizingRepast from "../pool/revitalizing-repast.js";
import _poolRevivingDose from "../pool/reviving-dose.js";
import _poolRidgeRannet from "../pool/ridge-rannet.js";
import _poolRootSliver from "../pool/root-sliver.js";
import _poolRubyDaringTracker from "../pool/ruby-daring-tracker.js";
import _poolRugOfSmothering from "../pool/rug-of-smothering.js";
import _poolRuneSealedWall from "../pool/rune-sealed-wall.js";
import _poolSaiMasterThopterist from "../pool/sai-master-thopterist.js";
import _poolSanctify from "../pool/sanctify.js";
import _poolSanguineMorass from "../pool/sanguine-morass.js";
import _poolSarkhansTriumph from "../pool/sarkhans-triumph.js";
import _poolScarbladeScout from "../pool/scarblade-scout.js";
import _poolScatteredGroves from "../pool/scattered-groves.js";
import _poolSeafloorOracle from "../pool/seafloor-oracle.js";
import _poolSeizanPerverterOfTruth from "../pool/seizan-perverter-of-truth.js";
import _poolSeizeTheDay from "../pool/seize-the-day.js";
import _poolShadowRift from "../pool/shadow-rift.js";
import _poolShadowyBackstreet from "../pool/shadowy-backstreet.js";
import _poolShieldWall from "../pool/shield-wall.js";
import _poolShimmeringWings from "../pool/shimmering-wings.js";
import _poolShivanReef from "../pool/shivan-reef.js";
import _poolShuGrainCaravan from "../pool/shu-grain-caravan.js";
import _poolSigiledSkink from "../pool/sigiled-skink.js";
import _poolSisterHospitaller from "../pool/sister-hospitaller.js";
import _poolSkyTerror from "../pool/sky-terror.js";
import _poolSlashOfTalons from "../pool/slash-of-talons.js";
import _poolSlaughterTheStrong from "../pool/slaughter-the-strong.js";
import _poolSlimebind from "../pool/slimebind.js";
import _poolSlitherBlade from "../pool/slither-blade.js";
import _poolSnowCoveredWastes from "../pool/snow-covered-wastes.js";
import _poolSongMadRuins from "../pool/song-mad-ruins.js";
import _poolSongMadTreachery from "../pool/song-mad-treachery.js";
import _poolSparringMummy from "../pool/sparring-mummy.js";
import _poolSpitFlame from "../pool/spit-flame.js";
import _poolSpringleafDrum from "../pool/springleaf-drum.js";
import _poolSproutingThrinax from "../pool/sprouting-thrinax.js";
import _poolSquirrelMob from "../pool/squirrel-mob.js";
import _poolSquirrelNest from "../pool/squirrel-nest.js";
import _poolStellaLeeWildCard from "../pool/stella-lee-wild-card.js";
import _poolSultaiSkullkeeper from "../pool/sultai-skullkeeper.js";
import _poolSummonBahamut from "../pool/summon-bahamut.js";
import _poolSuntailHawk from "../pool/suntail-hawk.js";
import _poolSurvivalOfTheFittest from "../pool/survival-of-the-fittest.js";
import _poolSwarmyardMassacre from "../pool/swarmyard-massacre.js";
import _poolSwoopingLookout from "../pool/swooping-lookout.js";
import _poolSwordOfBodyAndMind from "../pool/sword-of-body-and-mind.js";
import _poolSyphonMind from "../pool/syphon-mind.js";
import _poolTangledFlorahedron from "../pool/tangled-florahedron.js";
import _poolTelJiladJustice from "../pool/tel-jilad-justice.js";
import _poolTerisianMindbreaker from "../pool/terisian-mindbreaker.js";
import _poolTerminate from "../pool/terminate.js";
import _poolTheReaperKingNoMore from "../pool/the-reaper-king-no-more.js";
import _poolThievingVarmint from "../pool/thieving-varmint.js";
import _poolThirdPathIconoclast from "../pool/third-path-iconoclast.js";
import _poolThrorsMap from "../pool/thrors-map.js";
import _poolTigerClaws from "../pool/tiger-claws.js";
import _poolTipTheScales from "../pool/tip-the-scales.js";
import _poolTitaniasCommand from "../pool/titanias-command.js";
import _poolTobiasAndrion from "../pool/tobias-andrion.js";
import _poolTorturedExistence from "../pool/tortured-existence.js";
import _poolToweringTitan from "../pool/towering-titan.js";
import _poolToxicDeluge from "../pool/toxic-deluge.js";
import _poolTritonWaverider from "../pool/triton-waverider.js";
import _poolTrostaniThreeWhispers from "../pool/trostani-three-whispers.js";
import _poolTrustyPackbeast from "../pool/trusty-packbeast.js";
import _poolTwilightMire from "../pool/twilight-mire.js";
import _poolUlamogTheCeaselessHunger from "../pool/ulamog-the-ceaseless-hunger.js";
import _poolUnburiedEarthcarver from "../pool/unburied-earthcarver.js";
import _poolVampireChampion from "../pool/vampire-champion.js";
import _poolVaultSkirge from "../pool/vault-skirge.js";
import _poolVenomizedCat from "../pool/venomized-cat.js";
import _poolVergeRangers from "../pool/verge-rangers.js";
import _poolVexingGull from "../pool/vexing-gull.js";
import _poolViashinoBladescout from "../pool/viashino-bladescout.js";
import _poolVillageCannibals from "../pool/village-cannibals.js";
import _poolVitalizingWind from "../pool/vitalizing-wind.js";
import _poolVoiceOfTheProvinces from "../pool/voice-of-the-provinces.js";
import _poolVoiceOfVictory from "../pool/voice-of-victory.js";
import _poolVoltaicServant from "../pool/voltaic-servant.js";
import _poolWallOfJunk from "../pool/wall-of-junk.js";
import _poolWallOfTorches from "../pool/wall-of-torches.js";
import _poolWardenOfTheWoods from "../pool/warden-of-the-woods.js";
import _poolWeaverOfLightning from "../pool/weaver-of-lightning.js";
import _poolWheelOfFortune from "../pool/wheel-of-fortune.js";
import _poolWhispersilkCloak from "../pool/whispersilk-cloak.js";
import _poolWistfulSelkie from "../pool/wistful-selkie.js";
import _poolWitherAndBloom from "../pool/wither-and-bloom.js";
import _poolWorkshopAssistant from "../pool/workshop-assistant.js";
import _poolZephyrFalcon from "../pool/zephyr-falcon.js";
import _poolZofBloodbog from "../pool/zof-bloodbog.js";
import _tokensDragonTokenAvatarRoku from "../tokens/dragon-token-avatar-roku.js";
import _tokensSandWarriorToken from "../tokens/sand-warrior-token.js";
import _tokensSoldierToken from "../tokens/soldier-token.js";
import _tokensSpawnTokenSpawningPit from "../tokens/spawn-token-spawning-pit.js";
import _tokensWallToken13 from "../tokens/wall-token-1-3.js";
import _tokensZombieTokenGeralfVisionaryStitcher from "../tokens/zombie-token-geralf-visionary-stitcher.js";

const shard: CardShard = {
  pool: [
    _poolAberrantReturn,
    _poolAbzanAscendancy,
    _poolAetherHelix,
    _poolAjanisChosen,
    _poolAlelaCunningConqueror,
    _poolAngelicChorus,
    _poolAngelsGrace,
    _poolAnheloThePainter,
    _poolAnkleBiter,
    _poolAshlingTheLimitless,
    _poolAtarkaMonument,
    _poolAuroralProcession,
    _poolAvenSkirmisher,
    _poolAviationPioneer,
    _poolBaelothBarritylEntertainer,
    _poolBaronyVampire,
    _poolBarrinMasterWizard,
    _poolBashToBits,
    _poolBattlewandOak,
    _poolBedrockTortoise,
    _poolBiliousSkulldweller,
    _poolBlackSunsZenith,
    _poolBlackWaltzNo3,
    _poolBlistergrub,
    _poolBloodRites,
    _poolBloodghast,
    _poolBloodstainedMire,
    _poolBogWreckage,
    _poolBoneToAsh,
    _poolBonebreakerGiant,
    _poolBoulderbornDragon,
    _poolBraingeyser,
    _poolBrainstorm,
    _poolBristlingBackwoods,
    _poolCarnageTyrant,
    _poolCauldronOfSouls,
    _poolCelestialPrism,
    _poolChainersEdict,
    _poolChakramRetriever,
    _poolChardalynDragon,
    _poolChasmDrake,
    _poolContradict,
    _poolCranialPlating,
    _poolCrawlingSensation,
    _poolCrimsonCaravaneer,
    _poolCrimsonKobolds,
    _poolCrumblingNecropolis,
    _poolCultistOfTheAbsolute,
    _poolDaggerbackBasilisk,
    _poolDailyBugleNewspaper,
    _poolDakmorScorpion,
    _poolDarksteelMyr,
    _poolDauntlessSurvivor,
    _poolDeadbridgeShaman,
    _poolDeafeningClarion,
    _poolDefile,
    _poolDefiledCrypt,
    _poolDelneyStreetwiseLookout,
    _poolDesperateParry,
    _poolDiabolicIntent,
    _poolDictateOfKarametra,
    _poolDiscipleOfTeveshSzat,
    _poolDoubleDown,
    _poolDrakeHatchling,
    _poolDreadPresence,
    _poolDungeonShade,
    _poolEarthRumble,
    _poolEbonyRhino,
    _poolElderfangDisciple,
    _poolElvishWarrior,
    _poolEmergeFromTheCocoon,
    _poolEngineRat,
    _poolEsotericDuplicator,
    _poolExcaliburSwordOfEden,
    _poolFabricate,
    _poolFaerieBladecrafter,
    _poolFatefulDiscovery,
    _poolFelotharTheSteadfast,
    _poolFierceEmpath,
    _poolFiligreeCrawler,
    _poolFlameLash,
    _poolFlamekinHarbinger,
    _poolFlankingTroops,
    _poolFlayedOne,
    _poolForsakeTheWorldly,
    _poolForsakenSanctuary,
    _poolFromBeyond,
    _poolGaeasCradle,
    _poolGeodeRager,
    _poolGhostQuarter,
    _poolGiantCrab,
    _poolGingerbreadCabin,
    _poolGlenElendraArchmage,
    _poolGoblinAnarchomancer,
    _poolGoblinDeathraiders,
    _poolGoblinPiledriver,
    _poolGoblinSpelunkers,
    _poolGohnTownOfRuin,
    _poolGondGate,
    _poolGratefulApparition,
    _poolGriffinSentinel,
    _poolGrimHireling,
    _poolGrislyTransformation,
    _poolGruffTriplets,
    _poolHammerheadMaggiaBoss,
    _poolHarabazDruid,
    _poolHealerOfThePride,
    _poolHeartwoodTreefolk,
    _poolHerdGnarr,
    _poolHerosDownfall,
    _poolHorizonOfProgress,
    _poolHornOfGreed,
    _poolHornOfValhalla,
    _poolHornetCobra,
    _poolHulkingGoblin,
    _poolHumongulus,
    _poolImposingVantasaur,
    _poolIndrikStomphowler,
    _poolInfectiousHorror,
    _poolInsurrection,
    _poolIntroductionToProphecy,
    _poolIroassChampion,
    _poolIroncladKrovod,
    _poolJenovaAncientCalamity,
    _poolKarumonixTheRatKing,
    _poolKeenSense,
    _poolKheruGoldkeeper,
    _poolKingCheetah,
    _poolKlauthUnrivaledAncient,
    _poolKnightErrant,
    _poolKnightOfTheReliquary,
    _poolKokushoTheEveningStar,
    _poolKorvoldFaeCursedKing,
    _poolKozileksChanneler,
    _poolKudoKingAmongBears,
    _poolLampadOfDeathsVigil,
    _poolLance,
    _poolLathrilBladeOfTheElves,
    _poolLaughingJasperFlint,
    _poolLavaDart,
    _poolLightningElemental,
    _poolLordWindgrace,
    _poolLoyalSubordinate,
    _poolMacabreWaltz,
    _poolMagnifyingGlass,
    _poolMalcolmKeenEyedNavigator,
    _poolManaConfluence,
    _poolMarneusCalgar,
    _poolMawcor,
    _poolMentalNote,
    _poolMindfulBiomancer,
    _poolNeverwinterDryad,
    _poolNineFingersKeene,
    _poolNirkanaAssassin,
    _poolNivMizzetVisionary,
    _poolNotionThief,
    _poolNyxWeaver,
    _poolNyxbornColossus,
    _poolOasisGardener,
    _poolOdunosRiverTrawler,
    _poolOrderOfMidnight,
    _poolOvergrownTomb,
    _poolPastInFlames,
    _poolPathOfAncestry,
    _poolPestMascot,
    _poolPhyrexianGhoul,
    _poolPlatedGeopede,
    _poolPoisonTipArcher,
    _poolPrideGuardian,
    _poolPrimalHuntbeast,
    _poolPropheticPrism,
    _poolProsperousInnkeeper,
    _poolProvokeTheTrolls,
    _poolPutridLeech,
    _poolPyreticRitual,
    _poolQuandrixCampus,
    _poolRagingRedcap,
    _poolRaidBombardment,
    _poolRaisedByGiants,
    _poolRangersLongbow,
    _poolReckonersBargain,
    _poolResearchAssistant,
    _poolRestInPeace,
    _poolRestorationMagic,
    _poolRetreatToCoralhelm,
    _poolRetreatToHagra,
    _poolRetrofitterFoundry,
    _poolRevitalizingRepast,
    _poolRevivingDose,
    _poolRidgeRannet,
    _poolRootSliver,
    _poolRubyDaringTracker,
    _poolRugOfSmothering,
    _poolRuneSealedWall,
    _poolSaiMasterThopterist,
    _poolSanctify,
    _poolSanguineMorass,
    _poolSarkhansTriumph,
    _poolScarbladeScout,
    _poolScatteredGroves,
    _poolSeafloorOracle,
    _poolSeizanPerverterOfTruth,
    _poolSeizeTheDay,
    _poolShadowRift,
    _poolShadowyBackstreet,
    _poolShieldWall,
    _poolShimmeringWings,
    _poolShivanReef,
    _poolShuGrainCaravan,
    _poolSigiledSkink,
    _poolSisterHospitaller,
    _poolSkyTerror,
    _poolSlashOfTalons,
    _poolSlaughterTheStrong,
    _poolSlimebind,
    _poolSlitherBlade,
    _poolSnowCoveredWastes,
    _poolSongMadRuins,
    _poolSongMadTreachery,
    _poolSparringMummy,
    _poolSpitFlame,
    _poolSpringleafDrum,
    _poolSproutingThrinax,
    _poolSquirrelMob,
    _poolSquirrelNest,
    _poolStellaLeeWildCard,
    _poolSultaiSkullkeeper,
    _poolSummonBahamut,
    _poolSuntailHawk,
    _poolSurvivalOfTheFittest,
    _poolSwarmyardMassacre,
    _poolSwoopingLookout,
    _poolSwordOfBodyAndMind,
    _poolSyphonMind,
    _poolTangledFlorahedron,
    _poolTelJiladJustice,
    _poolTerisianMindbreaker,
    _poolTerminate,
    _poolTheReaperKingNoMore,
    _poolThievingVarmint,
    _poolThirdPathIconoclast,
    _poolThrorsMap,
    _poolTigerClaws,
    _poolTipTheScales,
    _poolTitaniasCommand,
    _poolTobiasAndrion,
    _poolTorturedExistence,
    _poolToweringTitan,
    _poolToxicDeluge,
    _poolTritonWaverider,
    _poolTrostaniThreeWhispers,
    _poolTrustyPackbeast,
    _poolTwilightMire,
    _poolUlamogTheCeaselessHunger,
    _poolUnburiedEarthcarver,
    _poolVampireChampion,
    _poolVaultSkirge,
    _poolVenomizedCat,
    _poolVergeRangers,
    _poolVexingGull,
    _poolViashinoBladescout,
    _poolVillageCannibals,
    _poolVitalizingWind,
    _poolVoiceOfTheProvinces,
    _poolVoiceOfVictory,
    _poolVoltaicServant,
    _poolWallOfJunk,
    _poolWallOfTorches,
    _poolWardenOfTheWoods,
    _poolWeaverOfLightning,
    _poolWheelOfFortune,
    _poolWhispersilkCloak,
    _poolWistfulSelkie,
    _poolWitherAndBloom,
    _poolWorkshopAssistant,
    _poolZephyrFalcon,
    _poolZofBloodbog,
  ],
  tokens: [
    _tokensDragonTokenAvatarRoku,
    _tokensSandWarriorToken,
    _tokensSoldierToken,
    _tokensSpawnTokenSpawningPit,
    _tokensWallToken13,
    _tokensZombieTokenGeralfVisionaryStitcher,
  ],
};

export default shard;
