// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.
// Run `npm run gen:cards -w engine` after adding or removing a card file.

import type { CardShard } from "../card-shards.js";

import _poolAccelerate from "../pool/accelerate.js";
import _poolAesiTyrantOfGyreStrait from "../pool/aesi-tyrant-of-gyre-strait.js";
import _poolAkroanJailer from "../pool/akroan-jailer.js";
import _poolAlmightyBrushwagg from "../pool/almighty-brushwagg.js";
import _poolAncientLumberknot from "../pool/ancient-lumberknot.js";
import _poolAncientZiggurat from "../pool/ancient-ziggurat.js";
import _poolArborElf from "../pool/arbor-elf.js";
import _poolArtfulTakedown from "../pool/artful-takedown.js";
import _poolArtificialEvolution from "../pool/artificial-evolution.js";
import _poolAshBarrens from "../pool/ash-barrens.js";
import _poolAtlaPalaniNestTender from "../pool/atla-palani-nest-tender.js";
import _poolAuramancer from "../pool/auramancer.js";
import _poolAvenArcher from "../pool/aven-archer.js";
import _poolBattleRageBlessing from "../pool/battle-rage-blessing.js";
import _poolBayFalcon from "../pool/bay-falcon.js";
import _poolBeastKinRanger from "../pool/beast-kin-ranger.js";
import _poolBeetlebackChief from "../pool/beetleback-chief.js";
import _poolBishopsSoldier from "../pool/bishops-soldier.js";
import _poolBlackWidowNatashaRomanoff from "../pool/black-widow-natasha-romanoff.js";
import _poolBlindPhantasm from "../pool/blind-phantasm.js";
import _poolBloodfellCaves from "../pool/bloodfell-caves.js";
import _poolBloodthirstyAerialist from "../pool/bloodthirsty-aerialist.js";
import _poolBoltHound from "../pool/bolt-hound.js";
import _poolBorosRecruit from "../pool/boros-recruit.js";
import _poolBoulderRush from "../pool/boulder-rush.js";
import _poolCarnivorousMossBeast from "../pool/carnivorous-moss-beast.js";
import _poolCartoucheOfKnowledge from "../pool/cartouche-of-knowledge.js";
import _poolCatOwl from "../pool/cat-owl.js";
import _poolCausticCaterpillar from "../pool/caustic-caterpillar.js";
import _poolCentaurCourser from "../pool/centaur-courser.js";
import _poolCentaurNurturer from "../pool/centaur-nurturer.js";
import _poolChargeThrough from "../pool/charge-through.js";
import _poolChildOfNight from "../pool/child-of-night.js";
import _poolCityPigeon from "../pool/city-pigeon.js";
import _poolCobbledWings from "../pool/cobbled-wings.js";
import _poolColdCaseCracker from "../pool/cold-case-cracker.js";
import _poolCraterize from "../pool/craterize.js";
import _poolCunningSparkmage from "../pool/cunning-sparkmage.js";
import _poolDazzlingRamparts from "../pool/dazzling-ramparts.js";
import _poolDeepwoodTantiv from "../pool/deepwood-tantiv.js";
import _poolDelightedHalfling from "../pool/delighted-halfling.js";
import _poolDesolateLighthouse from "../pool/desolate-lighthouse.js";
import _poolDragonTempest from "../pool/dragon-tempest.js";
import _poolDragonsEyeSentry from "../pool/dragons-eye-sentry.js";
import _poolDwarvenTrader from "../pool/dwarven-trader.js";
import _poolEmbraalGearSmasher from "../pool/embraal-gear-smasher.js";
import _poolEncroachingDragonstorm from "../pool/encroaching-dragonstorm.js";
import _poolEnlightenedTutor from "../pool/enlightened-tutor.js";
import _poolEssenceFlux from "../pool/essence-flux.js";
import _poolEternalWarrior from "../pool/eternal-warrior.js";
import _poolFaerieSeer from "../pool/faerie-seer.js";
import _poolFavorableWinds from "../pool/favorable-winds.js";
import _poolFeralFerocity from "../pool/feral-ferocity.js";
import _poolFistsOfTheAnvil from "../pool/fists-of-the-anvil.js";
import _poolFlamebornHellion from "../pool/flameborn-hellion.js";
import _poolFledglingGriffin from "../pool/fledgling-griffin.js";
import _poolFleetingImage from "../pool/fleeting-image.js";
import _poolFleetingMemories from "../pool/fleeting-memories.js";
import _poolFolkOfThePines from "../pool/folk-of-the-pines.js";
import _poolFomoriNomad from "../pool/fomori-nomad.js";
import _poolFoulOrchard from "../pool/foul-orchard.js";
import _poolFrilledOculus from "../pool/frilled-oculus.js";
import _poolFrilledSandwalla from "../pool/frilled-sandwalla.js";
import _poolFurycalmSnarl from "../pool/furycalm-snarl.js";
import _poolFutureFlight from "../pool/future-flight.js";
import _poolGlacialWall from "../pool/glacial-wall.js";
import _poolGlimmerBairn from "../pool/glimmer-bairn.js";
import _poolGlissaTheTraitor from "../pool/glissa-the-traitor.js";
import _poolGlitterfang from "../pool/glitterfang.js";
import _poolGrapeshot from "../pool/grapeshot.js";
import _poolGraspOfDarkness from "../pool/grasp-of-darkness.js";
import _poolGraveTitan from "../pool/grave-titan.js";
import _poolGravenCairns from "../pool/graven-cairns.js";
import _poolGruulCluestone from "../pool/gruul-cluestone.js";
import _poolGruulNodorog from "../pool/gruul-nodorog.js";
import _poolGuardianOfTheHalls from "../pool/guardian-of-the-halls.js";
import _poolGuulDrazMucklord from "../pool/guul-draz-mucklord.js";
import _poolHematiteGolem from "../pool/hematite-golem.js";
import _poolHomaridExplorer from "../pool/homarid-explorer.js";
import _poolHulkingCyclops from "../pool/hulking-cyclops.js";
import _poolIkraShidiqiTheUsurper from "../pool/ikra-shidiqi-the-usurper.js";
import _poolImmolatingSouleater from "../pool/immolating-souleater.js";
import _poolImperiousInkmage from "../pool/imperious-inkmage.js";
import _poolIndathaTriome from "../pool/indatha-triome.js";
import _poolInspiredSprite from "../pool/inspired-sprite.js";
import _poolInvasionReinforcements from "../pool/invasion-reinforcements.js";
import _poolInventorsFair from "../pool/inventors-fair.js";
import _poolInvisibleStalker from "../pool/invisible-stalker.js";
import _poolIpnuRivulet from "../pool/ipnu-rivulet.js";
import _poolJungleWeaver from "../pool/jungle-weaver.js";
import _poolKataraHeroicHealer from "../pool/katara-heroic-healer.js";
import _poolKazanduValley from "../pool/kazandu-valley.js";
import _poolKnightOfTheSkywardEye from "../pool/knight-of-the-skyward-eye.js";
import _poolKorSkyClimber from "../pool/kor-sky-climber.js";
import _poolKraulWarrior from "../pool/kraul-warrior.js";
import _poolLadyCaleria from "../pool/lady-caleria.js";
import _poolLibrary from "../pool/library.js";
import _poolLifecreedDuo from "../pool/lifecreed-duo.js";
import _poolLiquimetalTorque from "../pool/liquimetal-torque.js";
import _poolLongtuskCub from "../pool/longtusk-cub.js";
import _poolLoxodonLineBreaker from "../pool/loxodon-line-breaker.js";
import _poolLynx from "../pool/lynx.js";
import _poolMaalfeldTwins from "../pool/maalfeld-twins.js";
import _poolMalakirRebirth from "../pool/malakir-rebirth.js";
import _poolMerfolkSkydiver from "../pool/merfolk-skydiver.js";
import _poolMillstone from "../pool/millstone.js";
import _poolMundasVanguard from "../pool/mundas-vanguard.js";
import _poolMyrTurbine from "../pool/myr-turbine.js";
import _poolNaturalize from "../pool/naturalize.js";
import _poolNaturesChant from "../pool/natures-chant.js";
import _poolNocturnalFeeder from "../pool/nocturnal-feeder.js";
import _poolNoxiousNewt from "../pool/noxious-newt.js";
import _poolOctoprophet from "../pool/octoprophet.js";
import _poolOmegaMyr from "../pool/omega-myr.js";
import _poolOneWithTheWind from "../pool/one-with-the-wind.js";
import _poolOnulet from "../pool/onulet.js";
import _poolPalladiumMyr from "../pool/palladium-myr.js";
import _poolPardicCollaborator from "../pool/pardic-collaborator.js";
import _poolPhantomWarrior from "../pool/phantom-warrior.js";
import _poolPhyrexianDefiler from "../pool/phyrexian-defiler.js";
import _poolProwcatcherSpecialist from "../pool/prowcatcher-specialist.js";
import _poolRabanastreRoyalCity from "../pool/rabanastre-royal-city.js";
import _poolRagingBull from "../pool/raging-bull.js";
import _poolRegalUnicorn from "../pool/regal-unicorn.js";
import _poolRelicSloth from "../pool/relic-sloth.js";
import _poolRemand from "../pool/remand.js";
import _poolRhysticStudy from "../pool/rhystic-study.js";
import _poolRiverglidePathway from "../pool/riverglide-pathway.js";
import _poolRonomUnicorn from "../pool/ronom-unicorn.js";
import _poolRootboundCrag from "../pool/rootbound-crag.js";
import _poolSacredFoundry from "../pool/sacred-foundry.js";
import _poolScatterTheSeeds from "../pool/scatter-the-seeds.js";
import _poolSelesnyaGuildmage from "../pool/selesnya-guildmage.js";
import _poolSenateCourier from "../pool/senate-courier.js";
import _poolShatteredSanctum from "../pool/shattered-sanctum.js";
import _poolShipwreckMarsh from "../pool/shipwreck-marsh.js";
import _poolShrink from "../pool/shrink.js";
import _poolSkybladeOfTheLegion from "../pool/skyblade-of-the-legion.js";
import _poolSkyshroudFalcon from "../pool/skyshroud-falcon.js";
import _poolSleddingOtterPenguin from "../pool/sledding-otter-penguin.js";
import _poolSlinzaTheSpikedStampede from "../pool/slinza-the-spiked-stampede.js";
import _poolSmaugTheGreatCalamity from "../pool/smaug-the-great-calamity.js";
import _poolSmolderingMarsh from "../pool/smoldering-marsh.js";
import _poolSpinedKarok from "../pool/spined-karok.js";
import _poolSpinningWheel from "../pool/spinning-wheel.js";
import _poolSprout from "../pool/sprout.js";
import _poolStoneHavenMedic from "../pool/stone-haven-medic.js";
import _poolStripMine from "../pool/strip-mine.js";
import _poolSunshotMilitia from "../pool/sunshot-militia.js";
import _poolSurgeConductor from "../pool/surge-conductor.js";
import _poolTalasScout from "../pool/talas-scout.js";
import _poolTalismanOfResilience from "../pool/talisman-of-resilience.js";
import _poolTempleOfPower from "../pool/temple-of-power.js";
import _poolTemptingWitch from "../pool/tempting-witch.js";
import _poolTemurBanner from "../pool/temur-banner.js";
import _poolTemurTawnyback from "../pool/temur-tawnyback.js";
import _poolTerohsFaithful from "../pool/terohs-faithful.js";
import _poolTheFalconSamWilson from "../pool/the-falcon-sam-wilson.js";
import _poolTheLocustGod from "../pool/the-locust-god.js";
import _poolThrabenPurebloods from "../pool/thraben-purebloods.js";
import _poolThraxodemon from "../pool/thraxodemon.js";
import _poolThunderingTanadon from "../pool/thundering-tanadon.js";
import _poolTimidShieldbearer from "../pool/timid-shieldbearer.js";
import _poolToadstoolAdmirer from "../pool/toadstool-admirer.js";
import _poolTukatongueThallid from "../pool/tukatongue-thallid.js";
import _poolTunnelingGeopede from "../pool/tunneling-geopede.js";
import _poolTurtleSeals from "../pool/turtle-seals.js";
import _poolTwinscrollShaman from "../pool/twinscroll-shaman.js";
import _poolTwistedExperiment from "../pool/twisted-experiment.js";
import _poolUlvenwaldMysteries from "../pool/ulvenwald-mysteries.js";
import _poolUnlivingLegionnaire from "../pool/unliving-legionnaire.js";
import _poolUnmake from "../pool/unmake.js";
import _poolUnrulyCatapult from "../pool/unruly-catapult.js";
import _poolVenerableMonk from "../pool/venerable-monk.js";
import _poolVerminGorger from "../pool/vermin-gorger.js";
import _poolVeteranSwordsmith from "../pool/veteran-swordsmith.js";
import _poolViashinoFangtail from "../pool/viashino-fangtail.js";
import _poolVictorysEnvoy from "../pool/victorys-envoy.js";
import _poolVillageRites from "../pool/village-rites.js";
import _poolViridianEmissary from "../pool/viridian-emissary.js";
import _poolWallOfGranite from "../pool/wall-of-granite.js";
import _poolWallOfHeat from "../pool/wall-of-heat.js";
import _poolWallOfLava from "../pool/wall-of-lava.js";
import _poolWarlordsAxe from "../pool/warlords-axe.js";
import _poolWaterTribeCaptain from "../pool/water-tribe-captain.js";
import _poolWizardsSchool from "../pool/wizards-school.js";
import _poolXyrisTheWrithingStorm from "../pool/xyris-the-writhing-storm.js";
import _poolZodiacHorse from "../pool/zodiac-horse.js";
import _tokensBlackDeathtouchSnakeToken from "../tokens/black-deathtouch-snake-token.js";
import _tokensInsectToken from "../tokens/insect-token.js";
import _tokensLifelinkVampireToken from "../tokens/lifelink-vampire-token.js";
import _tokensPhyrexianWurmLifelink from "../tokens/phyrexian-wurm-lifelink.js";
import _tokensSoldierArtifactToken from "../tokens/soldier-artifact-token.js";

const shard: CardShard = {
  pool: [
    _poolAccelerate,
    _poolAesiTyrantOfGyreStrait,
    _poolAkroanJailer,
    _poolAlmightyBrushwagg,
    _poolAncientLumberknot,
    _poolAncientZiggurat,
    _poolArborElf,
    _poolArtfulTakedown,
    _poolArtificialEvolution,
    _poolAshBarrens,
    _poolAtlaPalaniNestTender,
    _poolAuramancer,
    _poolAvenArcher,
    _poolBattleRageBlessing,
    _poolBayFalcon,
    _poolBeastKinRanger,
    _poolBeetlebackChief,
    _poolBishopsSoldier,
    _poolBlackWidowNatashaRomanoff,
    _poolBlindPhantasm,
    _poolBloodfellCaves,
    _poolBloodthirstyAerialist,
    _poolBoltHound,
    _poolBorosRecruit,
    _poolBoulderRush,
    _poolCarnivorousMossBeast,
    _poolCartoucheOfKnowledge,
    _poolCatOwl,
    _poolCausticCaterpillar,
    _poolCentaurCourser,
    _poolCentaurNurturer,
    _poolChargeThrough,
    _poolChildOfNight,
    _poolCityPigeon,
    _poolCobbledWings,
    _poolColdCaseCracker,
    _poolCraterize,
    _poolCunningSparkmage,
    _poolDazzlingRamparts,
    _poolDeepwoodTantiv,
    _poolDelightedHalfling,
    _poolDesolateLighthouse,
    _poolDragonTempest,
    _poolDragonsEyeSentry,
    _poolDwarvenTrader,
    _poolEmbraalGearSmasher,
    _poolEncroachingDragonstorm,
    _poolEnlightenedTutor,
    _poolEssenceFlux,
    _poolEternalWarrior,
    _poolFaerieSeer,
    _poolFavorableWinds,
    _poolFeralFerocity,
    _poolFistsOfTheAnvil,
    _poolFlamebornHellion,
    _poolFledglingGriffin,
    _poolFleetingImage,
    _poolFleetingMemories,
    _poolFolkOfThePines,
    _poolFomoriNomad,
    _poolFoulOrchard,
    _poolFrilledOculus,
    _poolFrilledSandwalla,
    _poolFurycalmSnarl,
    _poolFutureFlight,
    _poolGlacialWall,
    _poolGlimmerBairn,
    _poolGlissaTheTraitor,
    _poolGlitterfang,
    _poolGrapeshot,
    _poolGraspOfDarkness,
    _poolGraveTitan,
    _poolGravenCairns,
    _poolGruulCluestone,
    _poolGruulNodorog,
    _poolGuardianOfTheHalls,
    _poolGuulDrazMucklord,
    _poolHematiteGolem,
    _poolHomaridExplorer,
    _poolHulkingCyclops,
    _poolIkraShidiqiTheUsurper,
    _poolImmolatingSouleater,
    _poolImperiousInkmage,
    _poolIndathaTriome,
    _poolInspiredSprite,
    _poolInvasionReinforcements,
    _poolInventorsFair,
    _poolInvisibleStalker,
    _poolIpnuRivulet,
    _poolJungleWeaver,
    _poolKataraHeroicHealer,
    _poolKazanduValley,
    _poolKnightOfTheSkywardEye,
    _poolKorSkyClimber,
    _poolKraulWarrior,
    _poolLadyCaleria,
    _poolLibrary,
    _poolLifecreedDuo,
    _poolLiquimetalTorque,
    _poolLongtuskCub,
    _poolLoxodonLineBreaker,
    _poolLynx,
    _poolMaalfeldTwins,
    _poolMalakirRebirth,
    _poolMerfolkSkydiver,
    _poolMillstone,
    _poolMundasVanguard,
    _poolMyrTurbine,
    _poolNaturalize,
    _poolNaturesChant,
    _poolNocturnalFeeder,
    _poolNoxiousNewt,
    _poolOctoprophet,
    _poolOmegaMyr,
    _poolOneWithTheWind,
    _poolOnulet,
    _poolPalladiumMyr,
    _poolPardicCollaborator,
    _poolPhantomWarrior,
    _poolPhyrexianDefiler,
    _poolProwcatcherSpecialist,
    _poolRabanastreRoyalCity,
    _poolRagingBull,
    _poolRegalUnicorn,
    _poolRelicSloth,
    _poolRemand,
    _poolRhysticStudy,
    _poolRiverglidePathway,
    _poolRonomUnicorn,
    _poolRootboundCrag,
    _poolSacredFoundry,
    _poolScatterTheSeeds,
    _poolSelesnyaGuildmage,
    _poolSenateCourier,
    _poolShatteredSanctum,
    _poolShipwreckMarsh,
    _poolShrink,
    _poolSkybladeOfTheLegion,
    _poolSkyshroudFalcon,
    _poolSleddingOtterPenguin,
    _poolSlinzaTheSpikedStampede,
    _poolSmaugTheGreatCalamity,
    _poolSmolderingMarsh,
    _poolSpinedKarok,
    _poolSpinningWheel,
    _poolSprout,
    _poolStoneHavenMedic,
    _poolStripMine,
    _poolSunshotMilitia,
    _poolSurgeConductor,
    _poolTalasScout,
    _poolTalismanOfResilience,
    _poolTempleOfPower,
    _poolTemptingWitch,
    _poolTemurBanner,
    _poolTemurTawnyback,
    _poolTerohsFaithful,
    _poolTheFalconSamWilson,
    _poolTheLocustGod,
    _poolThrabenPurebloods,
    _poolThraxodemon,
    _poolThunderingTanadon,
    _poolTimidShieldbearer,
    _poolToadstoolAdmirer,
    _poolTukatongueThallid,
    _poolTunnelingGeopede,
    _poolTurtleSeals,
    _poolTwinscrollShaman,
    _poolTwistedExperiment,
    _poolUlvenwaldMysteries,
    _poolUnlivingLegionnaire,
    _poolUnmake,
    _poolUnrulyCatapult,
    _poolVenerableMonk,
    _poolVerminGorger,
    _poolVeteranSwordsmith,
    _poolViashinoFangtail,
    _poolVictorysEnvoy,
    _poolVillageRites,
    _poolViridianEmissary,
    _poolWallOfGranite,
    _poolWallOfHeat,
    _poolWallOfLava,
    _poolWarlordsAxe,
    _poolWaterTribeCaptain,
    _poolWizardsSchool,
    _poolXyrisTheWrithingStorm,
    _poolZodiacHorse,
  ],
  tokens: [
    _tokensBlackDeathtouchSnakeToken,
    _tokensInsectToken,
    _tokensLifelinkVampireToken,
    _tokensPhyrexianWurmLifelink,
    _tokensSoldierArtifactToken,
  ],
};

export default shard;
