// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.
// Run `npm run gen:cards -w engine` after adding or removing a card file.

import type { CardShard } from "../card-shards.js";

import _poolAbandonedOutpost from "../pool/abandoned-outpost.js";
import _poolAjaniCallerOfThePride from "../pool/ajani-caller-of-the-pride.js";
import _poolAlabornCavalier from "../pool/alaborn-cavalier.js";
import _poolAmaranthineWall from "../pool/amaranthine-wall.js";
import _poolAmbushViper from "../pool/ambush-viper.js";
import _poolAngelicPage from "../pool/angelic-page.js";
import _poolArcticTreeline from "../pool/arctic-treeline.js";
import _poolArdentRecruit from "../pool/ardent-recruit.js";
import _poolAtreusImpulsiveSon from "../pool/atreus-impulsive-son.js";
import _poolAttendedSocialite from "../pool/attended-socialite.js";
import _poolAvengersHangar from "../pool/avengers-hangar.js";
import _poolBastionEnforcer from "../pool/bastion-enforcer.js";
import _poolBattlewiseValor from "../pool/battlewise-valor.js";
import _poolBaylenTheHaymaker from "../pool/baylen-the-haymaker.js";
import _poolBirdsOfParadise from "../pool/birds-of-paradise.js";
import _poolBoggartBog from "../pool/boggart-bog.js";
import _poolBondedFetch from "../pool/bonded-fetch.js";
import _poolBorosCharm from "../pool/boros-charm.js";
import _poolBurlfistOak from "../pool/burlfist-oak.js";
import _poolBurrowingRazormaw from "../pool/burrowing-razormaw.js";
import _poolCascadeBluffs from "../pool/cascade-bluffs.js";
import _poolCharge from "../pool/charge.js";
import _poolCheckpointOfficer from "../pool/checkpoint-officer.js";
import _poolChitinousCloak from "../pool/chitinous-cloak.js";
import _poolCitywideBust from "../pool/citywide-bust.js";
import _poolCleansingNova from "../pool/cleansing-nova.js";
import _poolCleverLumimancer from "../pool/clever-lumimancer.js";
import _poolCogworkWrestler from "../pool/cogwork-wrestler.js";
import _poolConcordiaPegasus from "../pool/concordia-pegasus.js";
import _poolContaminatedAquifer from "../pool/contaminated-aquifer.js";
import _poolContrabandKingpin from "../pool/contraband-kingpin.js";
import _poolCrashThrough from "../pool/crash-through.js";
import _poolCrosissAttendant from "../pool/crosiss-attendant.js";
import _poolCurioVendor from "../pool/curio-vendor.js";
import _poolCursedFlesh from "../pool/cursed-flesh.js";
import _poolDarigaazsCharm from "../pool/darigaazs-charm.js";
import _poolDarkthicketWolf from "../pool/darkthicket-wolf.js";
import _poolDeadapult from "../pool/deadapult.js";
import _poolDecoyPloy from "../pool/decoy-ploy.js";
import _poolDiregrafCaptain from "../pool/diregraf-captain.js";
import _poolDiversionaryTactics from "../pool/diversionary-tactics.js";
import _poolDraugrRecruiter from "../pool/draugr-recruiter.js";
import _poolDrogskolReaver from "../pool/drogskol-reaver.js";
import _poolDromadPurebred from "../pool/dromad-purebred.js";
import _poolDrossProwler from "../pool/dross-prowler.js";
import _poolDryadArbor from "../pool/dryad-arbor.js";
import _poolEagerFirstYear from "../pool/eager-first-year.js";
import _poolEatToExtinction from "../pool/eat-to-extinction.js";
import _poolEfficientConstruction from "../pool/efficient-construction.js";
import _poolElspethSunsChampion from "../pool/elspeth-suns-champion.js";
import _poolEmblemOfTheWarmind from "../pool/emblem-of-the-warmind.js";
import _poolEnterTheGodEternals from "../pool/enter-the-god-eternals.js";
import _poolFearOfSurveillance from "../pool/fear-of-surveillance.js";
import _poolFeatherOfFlight from "../pool/feather-of-flight.js";
import _poolFervor from "../pool/fervor.js";
import _poolFlameSpirit from "../pool/flame-spirit.js";
import _poolFriendlyGhost from "../pool/friendly-ghost.js";
import _poolGallowsWarden from "../pool/gallows-warden.js";
import _poolGavonyTrapper from "../pool/gavony-trapper.js";
import _poolGiantGrowth from "../pool/giant-growth.js";
import _poolGiftOfOrzhova from "../pool/gift-of-orzhova.js";
import _poolGlitteringMassif from "../pool/glittering-massif.js";
import _poolGloomPangolin from "../pool/gloom-pangolin.js";
import _poolGoldmireBridge from "../pool/goldmire-bridge.js";
import _poolGongagaReactorTown from "../pool/gongaga-reactor-town.js";
import _poolGoroGoroAndSatoru from "../pool/goro-goro-and-satoru.js";
import _poolGrandArbiterAugustinIv from "../pool/grand-arbiter-augustin-iv.js";
import _poolGrimBounty from "../pool/grim-bounty.js";
import _poolGroundskeeper from "../pool/groundskeeper.js";
import _poolHangedExecutioner from "../pool/hanged-executioner.js";
import _poolHashepOasis from "../pool/hashep-oasis.js";
import _poolHeadlessHorseman from "../pool/headless-horseman.js";
import _poolHedgeMaze from "../pool/hedge-maze.js";
import _poolHornedTurtle from "../pool/horned-turtle.js";
import _poolHornetNest from "../pool/hornet-nest.js";
import _poolHushwoodVerge from "../pool/hushwood-verge.js";
import _poolIndulgentTormentor from "../pool/indulgent-tormentor.js";
import _poolInfernalGrasp from "../pool/infernal-grasp.js";
import _poolIronTuskElephant from "../pool/iron-tusk-elephant.js";
import _poolIronWill from "../pool/iron-will.js";
import _poolIzzetGuildgate from "../pool/izzet-guildgate.js";
import _poolJhovallRider from "../pool/jhovall-rider.js";
import _poolKamahlPitFighter from "../pool/kamahl-pit-fighter.js";
import _poolKilnFiend from "../pool/kiln-fiend.js";
import _poolKratosStoicFather from "../pool/kratos-stoic-father.js";
import _poolLandTax from "../pool/land-tax.js";
import _poolLashOfTheWhip from "../pool/lash-of-the-whip.js";
import _poolLeoninSnarecaster from "../pool/leonin-snarecaster.js";
import _poolLetterOfAcceptance from "../pool/letter-of-acceptance.js";
import _poolMacetailHystrodon from "../pool/macetail-hystrodon.js";
import _poolMagmaJet from "../pool/magma-jet.js";
import _poolMinnWilyIllusionist from "../pool/minn-wily-illusionist.js";
import _poolMistgatePathway from "../pool/mistgate-pathway.js";
import _poolMollyHayesRunaway from "../pool/molly-hayes-runaway.js";
import _poolMomentOfTriumph from "../pool/moment-of-triumph.js";
import _poolMonkIdealist from "../pool/monk-idealist.js";
import _poolNemaSiltlurker from "../pool/nema-siltlurker.js";
import _poolNestRobber from "../pool/nest-robber.js";
import _poolNimanaSkydancer from "../pool/nimana-skydancer.js";
import _poolObyraDreamingDuelist from "../pool/obyra-dreaming-duelist.js";
import _poolOgreSentry from "../pool/ogre-sentry.js";
import _poolOldGnawbone from "../pool/old-gnawbone.js";
import _poolPhyrexianVault from "../pool/phyrexian-vault.js";
import _poolPrimevalShambler from "../pool/primeval-shambler.js";
import _poolPullFromTomorrow from "../pool/pull-from-tomorrow.js";
import _poolPyreCharger from "../pool/pyre-charger.js";
import _poolQueenMarchesa from "../pool/queen-marchesa.js";
import _poolQuickStudy from "../pool/quick-study.js";
import _poolRainOfTears from "../pool/rain-of-tears.js";
import _poolRavos from "../pool/ravos.js";
import _poolReadTheBones from "../pool/read-the-bones.js";
import _poolResoluteWatchdog from "../pool/resolute-watchdog.js";
import _poolRishadanDockhand from "../pool/rishadan-dockhand.js";
import _poolRiverBear from "../pool/river-bear.js";
import _poolRootOut from "../pool/root-out.js";
import _poolRustMonster from "../pool/rust-monster.js";
import _poolSabertoothWyvern from "../pool/sabertooth-wyvern.js";
import _poolSabretoothTiger from "../pool/sabretooth-tiger.js";
import _poolScarwoodTreefolk from "../pool/scarwood-treefolk.js";
import _poolScouredBarrens from "../pool/scoured-barrens.js";
import _poolSeafloorDebris from "../pool/seafloor-debris.js";
import _poolSewnEyeDrake from "../pool/sewn-eye-drake.js";
import _poolShieldsMight from "../pool/shields-might.js";
import _poolShock from "../pool/shock.js";
import _poolShoreLurker from "../pool/shore-lurker.js";
import _poolSkyshroudTroopers from "../pool/skyshroud-troopers.js";
import _poolSnarlingWolf from "../pool/snarling-wolf.js";
import _poolSonicTheHedgehog from "../pool/sonic-the-hedgehog.js";
import _poolSoulOfTheHarvest from "../pool/soul-of-the-harvest.js";
import _poolSoulbladeDjinn from "../pool/soulblade-djinn.js";
import _poolSoulsAttendant from "../pool/souls-attendant.js";
import _poolSparkJolt from "../pool/spark-jolt.js";
import _poolSpectralFlight from "../pool/spectral-flight.js";
import _poolSpiderRexDaringDino from "../pool/spider-rex-daring-dino.js";
import _poolSpinedWurm from "../pool/spined-wurm.js";
import _poolSpireGarden from "../pool/spire-garden.js";
import _poolStarlightInvoker from "../pool/starlight-invoker.js";
import _poolSteadfastPaladin from "../pool/steadfast-paladin.js";
import _poolSteepleCreeper from "../pool/steeple-creeper.js";
import _poolSteppeLynx from "../pool/steppe-lynx.js";
import _poolStewardOfValeron from "../pool/steward-of-valeron.js";
import _poolSummitProwler from "../pool/summit-prowler.js";
import _poolSwiftbladeVindicator from "../pool/swiftblade-vindicator.js";
import _poolTaintedIsle from "../pool/tainted-isle.js";
import _poolTatteredApparition from "../pool/tattered-apparition.js";
import _poolThaumaturgesFamiliar from "../pool/thaumaturges-familiar.js";
import _poolThePrismaticBridge from "../pool/the-prismatic-bridge.js";
import _poolThreeVisits from "../pool/three-visits.js";
import _poolThunderingFalls from "../pool/thundering-falls.js";
import _poolThunderingRebuke from "../pool/thundering-rebuke.js";
import _poolTideSkimmer from "../pool/tide-skimmer.js";
import _poolTurntimberAscetic from "../pool/turntimber-ascetic.js";
import _poolUktabiFaerie from "../pool/uktabi-faerie.js";
import _poolUnholyOfficiant from "../pool/unholy-officiant.js";
import _poolUnknownShores from "../pool/unknown-shores.js";
import _poolUnsummon from "../pool/unsummon.js";
import _poolVeiledShade from "../pool/veiled-shade.js";
import _poolVigilanteJustice from "../pool/vigilante-justice.js";
import _poolVizierOfTheScorpion from "../pool/vizier-of-the-scorpion.js";
import _poolWailingGhoul from "../pool/wailing-ghoul.js";
import _poolWallOfWater from "../pool/wall-of-water.js";
import _poolWarChariot from "../pool/war-chariot.js";
import _poolWayfarersBauble from "../pool/wayfarers-bauble.js";
import _poolWeb from "../pool/web.js";
import _poolWeldfastWingsmith from "../pool/weldfast-wingsmith.js";
import _poolWildColos from "../pool/wild-colos.js";
import _poolWillowFaerie from "../pool/willow-faerie.js";
import _poolWinterSoldierBuckyBarnes from "../pool/winter-soldier-bucky-barnes.js";
import _poolWitchsFamiliar from "../pool/witchs-familiar.js";
import _poolWizenedCenn from "../pool/wizened-cenn.js";
import _poolWolfsbaneHighlandHero from "../pool/wolfsbane-highland-hero.js";
import _poolWoodlandDruid from "../pool/woodland-druid.js";
import _poolYahenniUndyingPartisan from "../pool/yahenni-undying-partisan.js";
import _poolYawningFissure from "../pool/yawning-fissure.js";
import _poolYevasForcemage from "../pool/yevas-forcemage.js";
import _poolZealousGuardian from "../pool/zealous-guardian.js";
import _poolZodiacPig from "../pool/zodiac-pig.js";
import _poolZombify from "../pool/zombify.js";
import _tokensBeastToken from "../tokens/beast-token.js";
import _tokensCatBeastToken from "../tokens/cat-beast-token.js";
import _tokensEldraziToken from "../tokens/eldrazi-token.js";
import _tokensFungusTokenCantBlock from "../tokens/fungus-token-cant-block.js";
import _tokensKnightToken from "../tokens/knight-token.js";
import _tokensMoloidToken from "../tokens/moloid-token.js";
import _tokensRedSpiritTokenMenace from "../tokens/red-spirit-token-menace.js";

const shard: CardShard = {
  pool: [
    _poolAbandonedOutpost,
    _poolAjaniCallerOfThePride,
    _poolAlabornCavalier,
    _poolAmaranthineWall,
    _poolAmbushViper,
    _poolAngelicPage,
    _poolArcticTreeline,
    _poolArdentRecruit,
    _poolAtreusImpulsiveSon,
    _poolAttendedSocialite,
    _poolAvengersHangar,
    _poolBastionEnforcer,
    _poolBattlewiseValor,
    _poolBaylenTheHaymaker,
    _poolBirdsOfParadise,
    _poolBoggartBog,
    _poolBondedFetch,
    _poolBorosCharm,
    _poolBurlfistOak,
    _poolBurrowingRazormaw,
    _poolCascadeBluffs,
    _poolCharge,
    _poolCheckpointOfficer,
    _poolChitinousCloak,
    _poolCitywideBust,
    _poolCleansingNova,
    _poolCleverLumimancer,
    _poolCogworkWrestler,
    _poolConcordiaPegasus,
    _poolContaminatedAquifer,
    _poolContrabandKingpin,
    _poolCrashThrough,
    _poolCrosissAttendant,
    _poolCurioVendor,
    _poolCursedFlesh,
    _poolDarigaazsCharm,
    _poolDarkthicketWolf,
    _poolDeadapult,
    _poolDecoyPloy,
    _poolDiregrafCaptain,
    _poolDiversionaryTactics,
    _poolDraugrRecruiter,
    _poolDrogskolReaver,
    _poolDromadPurebred,
    _poolDrossProwler,
    _poolDryadArbor,
    _poolEagerFirstYear,
    _poolEatToExtinction,
    _poolEfficientConstruction,
    _poolElspethSunsChampion,
    _poolEmblemOfTheWarmind,
    _poolEnterTheGodEternals,
    _poolFearOfSurveillance,
    _poolFeatherOfFlight,
    _poolFervor,
    _poolFlameSpirit,
    _poolFriendlyGhost,
    _poolGallowsWarden,
    _poolGavonyTrapper,
    _poolGiantGrowth,
    _poolGiftOfOrzhova,
    _poolGlitteringMassif,
    _poolGloomPangolin,
    _poolGoldmireBridge,
    _poolGongagaReactorTown,
    _poolGoroGoroAndSatoru,
    _poolGrandArbiterAugustinIv,
    _poolGrimBounty,
    _poolGroundskeeper,
    _poolHangedExecutioner,
    _poolHashepOasis,
    _poolHeadlessHorseman,
    _poolHedgeMaze,
    _poolHornedTurtle,
    _poolHornetNest,
    _poolHushwoodVerge,
    _poolIndulgentTormentor,
    _poolInfernalGrasp,
    _poolIronTuskElephant,
    _poolIronWill,
    _poolIzzetGuildgate,
    _poolJhovallRider,
    _poolKamahlPitFighter,
    _poolKilnFiend,
    _poolKratosStoicFather,
    _poolLandTax,
    _poolLashOfTheWhip,
    _poolLeoninSnarecaster,
    _poolLetterOfAcceptance,
    _poolMacetailHystrodon,
    _poolMagmaJet,
    _poolMinnWilyIllusionist,
    _poolMistgatePathway,
    _poolMollyHayesRunaway,
    _poolMomentOfTriumph,
    _poolMonkIdealist,
    _poolNemaSiltlurker,
    _poolNestRobber,
    _poolNimanaSkydancer,
    _poolObyraDreamingDuelist,
    _poolOgreSentry,
    _poolOldGnawbone,
    _poolPhyrexianVault,
    _poolPrimevalShambler,
    _poolPullFromTomorrow,
    _poolPyreCharger,
    _poolQueenMarchesa,
    _poolQuickStudy,
    _poolRainOfTears,
    _poolRavos,
    _poolReadTheBones,
    _poolResoluteWatchdog,
    _poolRishadanDockhand,
    _poolRiverBear,
    _poolRootOut,
    _poolRustMonster,
    _poolSabertoothWyvern,
    _poolSabretoothTiger,
    _poolScarwoodTreefolk,
    _poolScouredBarrens,
    _poolSeafloorDebris,
    _poolSewnEyeDrake,
    _poolShieldsMight,
    _poolShock,
    _poolShoreLurker,
    _poolSkyshroudTroopers,
    _poolSnarlingWolf,
    _poolSonicTheHedgehog,
    _poolSoulOfTheHarvest,
    _poolSoulbladeDjinn,
    _poolSoulsAttendant,
    _poolSparkJolt,
    _poolSpectralFlight,
    _poolSpiderRexDaringDino,
    _poolSpinedWurm,
    _poolSpireGarden,
    _poolStarlightInvoker,
    _poolSteadfastPaladin,
    _poolSteepleCreeper,
    _poolSteppeLynx,
    _poolStewardOfValeron,
    _poolSummitProwler,
    _poolSwiftbladeVindicator,
    _poolTaintedIsle,
    _poolTatteredApparition,
    _poolThaumaturgesFamiliar,
    _poolThePrismaticBridge,
    _poolThreeVisits,
    _poolThunderingFalls,
    _poolThunderingRebuke,
    _poolTideSkimmer,
    _poolTurntimberAscetic,
    _poolUktabiFaerie,
    _poolUnholyOfficiant,
    _poolUnknownShores,
    _poolUnsummon,
    _poolVeiledShade,
    _poolVigilanteJustice,
    _poolVizierOfTheScorpion,
    _poolWailingGhoul,
    _poolWallOfWater,
    _poolWarChariot,
    _poolWayfarersBauble,
    _poolWeb,
    _poolWeldfastWingsmith,
    _poolWildColos,
    _poolWillowFaerie,
    _poolWinterSoldierBuckyBarnes,
    _poolWitchsFamiliar,
    _poolWizenedCenn,
    _poolWolfsbaneHighlandHero,
    _poolWoodlandDruid,
    _poolYahenniUndyingPartisan,
    _poolYawningFissure,
    _poolYevasForcemage,
    _poolZealousGuardian,
    _poolZodiacPig,
    _poolZombify,
  ],
  tokens: [
    _tokensBeastToken,
    _tokensCatBeastToken,
    _tokensEldraziToken,
    _tokensFungusTokenCantBlock,
    _tokensKnightToken,
    _tokensMoloidToken,
    _tokensRedSpiritTokenMenace,
  ],
};

export default shard;
