// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.
// Run `npm run gen:cards -w engine` after adding or removing a card file.

import type { CardShard } from "../card-shards.js";

import _poolAbrade from "../pool/abrade.js";
import _poolAdmiralBrassUnsinkable from "../pool/admiral-brass-unsinkable.js";
import _poolAdunOakenshield from "../pool/adun-oakenshield.js";
import _poolAetherAdept from "../pool/aether-adept.js";
import _poolAgentOfShauku from "../pool/agent-of-shauku.js";
import _poolAggravatedAssault from "../pool/aggravated-assault.js";
import _poolAidTheFallen from "../pool/aid-the-fallen.js";
import _poolAkoumHellkite from "../pool/akoum-hellkite.js";
import _poolAlabasterMage from "../pool/alabaster-mage.js";
import _poolAlertShuInfantry from "../pool/alert-shu-infantry.js";
import _poolAlphaTyrranax from "../pool/alpha-tyrranax.js";
import _poolAmbushParatrooper from "../pool/ambush-paratrooper.js";
import _poolAnzragTheQuakeMole from "../pool/anzrag-the-quake-mole.js";
import _poolAuraBlast from "../pool/aura-blast.js";
import _poolAzoriusLocket from "../pool/azorius-locket.js";
import _poolAzusaLostButSeeking from "../pool/azusa-lost-but-seeking.js";
import _poolBalduvianBarbarians from "../pool/balduvian-barbarians.js";
import _poolBarrenMoor from "../pool/barren-moor.js";
import _poolBattleflySwarm from "../pool/battlefly-swarm.js";
import _poolBenthicBehemoth from "../pool/benthic-behemoth.js";
import _poolBitterTriumph from "../pool/bitter-triumph.js";
import _poolBladetuskBoar from "../pool/bladetusk-boar.js";
import _poolBlindingSouleater from "../pool/blinding-souleater.js";
import _poolBloodbondVampire from "../pool/bloodbond-vampire.js";
import _poolBloodfireMentor from "../pool/bloodfire-mentor.js";
import _poolBlowOffSteam from "../pool/blow-off-steam.js";
import _poolBonecallerCleric from "../pool/bonecaller-cleric.js";
import _poolBountifulLandscape from "../pool/bountiful-landscape.js";
import _poolBraidwoodCup from "../pool/braidwood-cup.js";
import _poolBranchloftPathway from "../pool/branchloft-pathway.js";
import _poolBywayCourier from "../pool/byway-courier.js";
import _poolCabalEvangel from "../pool/cabal-evangel.js";
import _poolCallTheGatewatch from "../pool/call-the-gatewatch.js";
import _poolCarnageAltar from "../pool/carnage-altar.js";
import _poolCatharCommando from "../pool/cathar-commando.js";
import _poolCloakOfTheBat from "../pool/cloak-of-the-bat.js";
import _poolCompositeGolem from "../pool/composite-golem.js";
import _poolContemplation from "../pool/contemplation.js";
import _poolCoralCommando from "../pool/coral-commando.js";
import _poolCorpseBlockade from "../pool/corpse-blockade.js";
import _poolCrookclawElder from "../pool/crookclaw-elder.js";
import _poolCrystalGrotto from "../pool/crystal-grotto.js";
import _poolCursebreak from "../pool/cursebreak.js";
import _poolDarksteelAxe from "../pool/darksteel-axe.js";
import _poolDavenantArcher from "../pool/davenant-archer.js";
import _poolDeathsprout from "../pool/deathsprout.js";
import _poolDeception from "../pool/deception.js";
import _poolDesertCerodon from "../pool/desert-cerodon.js";
import _poolDevkarinDissident from "../pool/devkarin-dissident.js";
import _poolDevouringDeep from "../pool/devouring-deep.js";
import _poolDispersingOrb from "../pool/dispersing-orb.js";
import _poolDisruptingScepter from "../pool/disrupting-scepter.js";
import _poolDruidLyrist from "../pool/druid-lyrist.js";
import _poolDruidOfTheCowl from "../pool/druid-of-the-cowl.js";
import _poolDuneDiviner from "../pool/dune-diviner.js";
import _poolDwarvenProvisioner from "../pool/dwarven-provisioner.js";
import _poolElderleafMentor from "../pool/elderleaf-mentor.js";
import _poolElephantAmbush from "../pool/elephant-ambush.js";
import _poolElfswornGiant from "../pool/elfsworn-giant.js";
import _poolElvishVanguard from "../pool/elvish-vanguard.js";
import _poolEsperSentinel from "../pool/esper-sentinel.js";
import _poolFallajiChaindancer from "../pool/fallaji-chaindancer.js";
import _poolFerociousCharge from "../pool/ferocious-charge.js";
import _poolFireDrake from "../pool/fire-drake.js";
import _poolFireUrchin from "../pool/fire-urchin.js";
import _poolFrostOgre from "../pool/frost-ogre.js";
import _poolGlaringAegis from "../pool/glaring-aegis.js";
import _poolGoldenTailDisciple from "../pool/golden-tail-disciple.js";
import _poolGolgariRotwurm from "../pool/golgari-rotwurm.js";
import _poolGraniticTitan from "../pool/granitic-titan.js";
import _poolGreenweaverDruid from "../pool/greenweaver-druid.js";
import _poolGristleGrinner from "../pool/gristle-grinner.js";
import _poolHagiMob from "../pool/hagi-mob.js";
import _poolHarmattanEfreet from "../pool/harmattan-efreet.js";
import _poolHarvesttideAssailant from "../pool/harvesttide-assailant.js";
import _poolHighspireMantis from "../pool/highspire-mantis.js";
import _poolHinterlandHarbor from "../pool/hinterland-harbor.js";
import _poolHinterlandSanctifier from "../pool/hinterland-sanctifier.js";
import _poolHitMonkey from "../pool/hit-monkey.js";
import _poolHolyStrength from "../pool/holy-strength.js";
import _poolIceridgeSerpent from "../pool/iceridge-serpent.js";
import _poolIndomitableAncients from "../pool/indomitable-ancients.js";
import _poolJayemdaeTome from "../pool/jayemdae-tome.js";
import _poolJonIrenicusShatteredOne from "../pool/jon-irenicus-shattered-one.js";
import _poolJwariScuttler from "../pool/jwari-scuttler.js";
import _poolKinsbaileSkirmisher from "../pool/kinsbaile-skirmisher.js";
import _poolKomodoRhino from "../pool/komodo-rhino.js";
import _poolKwainItinerantMeddler from "../pool/kwain-itinerant-meddler.js";
import _poolKyrenNegotiations from "../pool/kyren-negotiations.js";
import _poolLeaveInTheDust from "../pool/leave-in-the-dust.js";
import _poolLlanowarEnvoy from "../pool/llanowar-envoy.js";
import _poolLongBodiedGreyDog from "../pool/long-bodied-grey-dog.js";
import _poolLotusField from "../pool/lotus-field.js";
import _poolMagetasBoon from "../pool/magetas-boon.js";
import _poolMalakirCullblade from "../pool/malakir-cullblade.js";
import _poolMemnite from "../pool/memnite.js";
import _poolMercurialGeists from "../pool/mercurial-geists.js";
import _poolMesaFalcon from "../pool/mesa-falcon.js";
import _poolMidnightReaper from "../pool/midnight-reaper.js";
import _poolMindStone from "../pool/mind-stone.js";
import _poolMorskaUnderseaSleuth from "../pool/morska-undersea-sleuth.js";
import _poolMountainBandit from "../pool/mountain-bandit.js";
import _poolMysticRetrieval from "../pool/mystic-retrieval.js";
import _poolMythicProportions from "../pool/mythic-proportions.js";
import _poolNaturesClaim from "../pool/natures-claim.js";
import _poolNightveilPredator from "../pool/nightveil-predator.js";
import _poolOakhameRanger from "../pool/oakhame-ranger.js";
import _poolObeliskOfEsper from "../pool/obelisk-of-esper.js";
import _poolOpenTheArmory from "../pool/open-the-armory.js";
import _poolOphiomancer from "../pool/ophiomancer.js";
import _poolOverflowingBasin from "../pool/overflowing-basin.js";
import _poolOverrun from "../pool/overrun.js";
import _poolOxiddaDaredevil from "../pool/oxidda-daredevil.js";
import _poolPathToExile from "../pool/path-to-exile.js";
import _poolPhantomMonster from "../pool/phantom-monster.js";
import _poolPierceStrider from "../pool/pierce-strider.js";
import _poolPilgrimOfTheFires from "../pool/pilgrim-of-the-fires.js";
import _poolPreemptiveStrike from "../pool/preemptive-strike.js";
import _poolPrimalDruid from "../pool/primal-druid.js";
import _poolProfessorsWarning from "../pool/professors-warning.js";
import _poolPygmyAllosaurus from "../pool/pygmy-allosaurus.js";
import _poolRagingKavu from "../pool/raging-kavu.js";
import _poolRangingRaptors from "../pool/ranging-raptors.js";
import _poolRaucousTheater from "../pool/raucous-theater.js";
import _poolRefocus from "../pool/refocus.js";
import _poolRemoveSoul from "../pool/remove-soul.js";
import _poolRepulsorRays from "../pool/repulsor-rays.js";
import _poolReturnedCentaur from "../pool/returned-centaur.js";
import _poolRighteousAvengers from "../pool/righteous-avengers.js";
import _poolRishadanPort from "../pool/rishadan-port.js";
import _poolRisingPopulace from "../pool/rising-populace.js";
import _poolRoofstalkerWight from "../pool/roofstalker-wight.js";
import _poolSalvagerOfSecrets from "../pool/salvager-of-secrets.js";
import _poolSandsOfDelirium from "../pool/sands-of-delirium.js";
import _poolSeaEagle from "../pool/sea-eagle.js";
import _poolSeaScryer from "../pool/sea-scryer.js";
import _poolSeasonalRitual from "../pool/seasonal-ritual.js";
import _poolSeersLantern from "../pool/seers-lantern.js";
import _poolSegovianAngel from "../pool/segovian-angel.js";
import _poolSellerOfSongbirds from "../pool/seller-of-songbirds.js";
import _poolSerpentsGift from "../pool/serpents-gift.js";
import _poolShoreKeeper from "../pool/shore-keeper.js";
import _poolShriekOfDread from "../pool/shriek-of-dread.js";
import _poolSilentDeparture from "../pool/silent-departure.js";
import _poolSilverMyr from "../pool/silver-myr.js";
import _poolSkyswirlHarrier from "../pool/skyswirl-harrier.js";
import _poolSlagwurmArmor from "../pool/slagwurm-armor.js";
import _poolSmelt from "../pool/smelt.js";
import _poolSoulShred from "../pool/soul-shred.js";
import _poolSpiritOfMalevolence from "../pool/spirit-of-malevolence.js";
import _poolSulfurousMire from "../pool/sulfurous-mire.js";
import _poolSyphonFuel from "../pool/syphon-fuel.js";
import _poolTalasWarrior from "../pool/talas-warrior.js";
import _poolTalismanOfImpulse from "../pool/talisman-of-impulse.js";
import _poolTeeteringPeaks from "../pool/teetering-peaks.js";
import _poolTemmetNaktamunsWill from "../pool/temmet-naktamuns-will.js";
import _poolTemurDevotee from "../pool/temur-devotee.js";
import _poolThaliasLancers from "../pool/thalias-lancers.js";
import _poolTheAutonomousFurnace from "../pool/the-autonomous-furnace.js";
import _poolThroneOfGeth from "../pool/throne-of-geth.js";
import _poolTidehollowStrix from "../pool/tidehollow-strix.js";
import _poolTocasiasDigSite from "../pool/tocasias-dig-site.js";
import _poolTuktukRubblefort from "../pool/tuktuk-rubblefort.js";
import _poolUnflinchingCourage from "../pool/unflinching-courage.js";
import _poolUnhallowedPhalanx from "../pool/unhallowed-phalanx.js";
import _poolUrborgVolcano from "../pool/urborg-volcano.js";
import _poolUsherOfTheFallen from "../pool/usher-of-the-fallen.js";
import _poolUtvaraHellkite from "../pool/utvara-hellkite.js";
import _poolValakutPredator from "../pool/valakut-predator.js";
import _poolVerdigris from "../pool/verdigris.js";
import _poolVerduranEnchantress from "../pool/verduran-enchantress.js";
import _poolVernalFen from "../pool/vernal-fen.js";
import _poolVisionSkeins from "../pool/vision-skeins.js";
import _poolVithianRenegades from "../pool/vithian-renegades.js";
import _poolWatchwolf from "../pool/watchwolf.js";
import _poolWellWornSpatula from "../pool/well-worn-spatula.js";
import _poolWhipSilk from "../pool/whip-silk.js";
import _poolWildOx from "../pool/wild-ox.js";
import _poolWindSpirit from "../pool/wind-spirit.js";
import _poolWitherbloomApprentice from "../pool/witherbloom-apprentice.js";
import _poolWorldlyTutor from "../pool/worldly-tutor.js";
import _poolWreckingCrew from "../pool/wrecking-crew.js";
import _poolYavimayaCoast from "../pool/yavimaya-coast.js";
import _poolZodiacOx from "../pool/zodiac-ox.js";
import _poolZoralineCosmosCaller from "../pool/zoraline-cosmos-caller.js";
import _poolZuranOrb from "../pool/zuran-orb.js";
import _tokensCatWarriorToken from "../tokens/cat-warrior-token.js";
import _tokensFoodToken from "../tokens/food-token.js";
import _tokensThopterToken from "../tokens/thopter-token.js";

const shard: CardShard = {
  pool: [
    _poolAbrade,
    _poolAdmiralBrassUnsinkable,
    _poolAdunOakenshield,
    _poolAetherAdept,
    _poolAgentOfShauku,
    _poolAggravatedAssault,
    _poolAidTheFallen,
    _poolAkoumHellkite,
    _poolAlabasterMage,
    _poolAlertShuInfantry,
    _poolAlphaTyrranax,
    _poolAmbushParatrooper,
    _poolAnzragTheQuakeMole,
    _poolAuraBlast,
    _poolAzoriusLocket,
    _poolAzusaLostButSeeking,
    _poolBalduvianBarbarians,
    _poolBarrenMoor,
    _poolBattleflySwarm,
    _poolBenthicBehemoth,
    _poolBitterTriumph,
    _poolBladetuskBoar,
    _poolBlindingSouleater,
    _poolBloodbondVampire,
    _poolBloodfireMentor,
    _poolBlowOffSteam,
    _poolBonecallerCleric,
    _poolBountifulLandscape,
    _poolBraidwoodCup,
    _poolBranchloftPathway,
    _poolBywayCourier,
    _poolCabalEvangel,
    _poolCallTheGatewatch,
    _poolCarnageAltar,
    _poolCatharCommando,
    _poolCloakOfTheBat,
    _poolCompositeGolem,
    _poolContemplation,
    _poolCoralCommando,
    _poolCorpseBlockade,
    _poolCrookclawElder,
    _poolCrystalGrotto,
    _poolCursebreak,
    _poolDarksteelAxe,
    _poolDavenantArcher,
    _poolDeathsprout,
    _poolDeception,
    _poolDesertCerodon,
    _poolDevkarinDissident,
    _poolDevouringDeep,
    _poolDispersingOrb,
    _poolDisruptingScepter,
    _poolDruidLyrist,
    _poolDruidOfTheCowl,
    _poolDuneDiviner,
    _poolDwarvenProvisioner,
    _poolElderleafMentor,
    _poolElephantAmbush,
    _poolElfswornGiant,
    _poolElvishVanguard,
    _poolEsperSentinel,
    _poolFallajiChaindancer,
    _poolFerociousCharge,
    _poolFireDrake,
    _poolFireUrchin,
    _poolFrostOgre,
    _poolGlaringAegis,
    _poolGoldenTailDisciple,
    _poolGolgariRotwurm,
    _poolGraniticTitan,
    _poolGreenweaverDruid,
    _poolGristleGrinner,
    _poolHagiMob,
    _poolHarmattanEfreet,
    _poolHarvesttideAssailant,
    _poolHighspireMantis,
    _poolHinterlandHarbor,
    _poolHinterlandSanctifier,
    _poolHitMonkey,
    _poolHolyStrength,
    _poolIceridgeSerpent,
    _poolIndomitableAncients,
    _poolJayemdaeTome,
    _poolJonIrenicusShatteredOne,
    _poolJwariScuttler,
    _poolKinsbaileSkirmisher,
    _poolKomodoRhino,
    _poolKwainItinerantMeddler,
    _poolKyrenNegotiations,
    _poolLeaveInTheDust,
    _poolLlanowarEnvoy,
    _poolLongBodiedGreyDog,
    _poolLotusField,
    _poolMagetasBoon,
    _poolMalakirCullblade,
    _poolMemnite,
    _poolMercurialGeists,
    _poolMesaFalcon,
    _poolMidnightReaper,
    _poolMindStone,
    _poolMorskaUnderseaSleuth,
    _poolMountainBandit,
    _poolMysticRetrieval,
    _poolMythicProportions,
    _poolNaturesClaim,
    _poolNightveilPredator,
    _poolOakhameRanger,
    _poolObeliskOfEsper,
    _poolOpenTheArmory,
    _poolOphiomancer,
    _poolOverflowingBasin,
    _poolOverrun,
    _poolOxiddaDaredevil,
    _poolPathToExile,
    _poolPhantomMonster,
    _poolPierceStrider,
    _poolPilgrimOfTheFires,
    _poolPreemptiveStrike,
    _poolPrimalDruid,
    _poolProfessorsWarning,
    _poolPygmyAllosaurus,
    _poolRagingKavu,
    _poolRangingRaptors,
    _poolRaucousTheater,
    _poolRefocus,
    _poolRemoveSoul,
    _poolRepulsorRays,
    _poolReturnedCentaur,
    _poolRighteousAvengers,
    _poolRishadanPort,
    _poolRisingPopulace,
    _poolRoofstalkerWight,
    _poolSalvagerOfSecrets,
    _poolSandsOfDelirium,
    _poolSeaEagle,
    _poolSeaScryer,
    _poolSeasonalRitual,
    _poolSeersLantern,
    _poolSegovianAngel,
    _poolSellerOfSongbirds,
    _poolSerpentsGift,
    _poolShoreKeeper,
    _poolShriekOfDread,
    _poolSilentDeparture,
    _poolSilverMyr,
    _poolSkyswirlHarrier,
    _poolSlagwurmArmor,
    _poolSmelt,
    _poolSoulShred,
    _poolSpiritOfMalevolence,
    _poolSulfurousMire,
    _poolSyphonFuel,
    _poolTalasWarrior,
    _poolTalismanOfImpulse,
    _poolTeeteringPeaks,
    _poolTemmetNaktamunsWill,
    _poolTemurDevotee,
    _poolThaliasLancers,
    _poolTheAutonomousFurnace,
    _poolThroneOfGeth,
    _poolTidehollowStrix,
    _poolTocasiasDigSite,
    _poolTuktukRubblefort,
    _poolUnflinchingCourage,
    _poolUnhallowedPhalanx,
    _poolUrborgVolcano,
    _poolUsherOfTheFallen,
    _poolUtvaraHellkite,
    _poolValakutPredator,
    _poolVerdigris,
    _poolVerduranEnchantress,
    _poolVernalFen,
    _poolVisionSkeins,
    _poolVithianRenegades,
    _poolWatchwolf,
    _poolWellWornSpatula,
    _poolWhipSilk,
    _poolWildOx,
    _poolWindSpirit,
    _poolWitherbloomApprentice,
    _poolWorldlyTutor,
    _poolWreckingCrew,
    _poolYavimayaCoast,
    _poolZodiacOx,
    _poolZoralineCosmosCaller,
    _poolZuranOrb,
  ],
  tokens: [
    _tokensCatWarriorToken,
    _tokensFoodToken,
    _tokensThopterToken,
  ],
};

export default shard;
