// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.
// Run `npm run gen:cards -w engine` after adding or removing a card file.

import type { CardShard } from "../card-shards.js";

import _poolAbbeyMatron from "../pool/abbey-matron.js";
import _poolAetherHub from "../pool/aether-hub.js";
import _poolAkkiRockspeaker from "../pool/akki-rockspeaker.js";
import _poolAlignedHeart from "../pool/aligned-heart.js";
import _poolAlpineMeadow from "../pool/alpine-meadow.js";
import _poolAncientCarp from "../pool/ancient-carp.js";
import _poolAncientCrab from "../pool/ancient-crab.js";
import _poolAngelOfDespair from "../pool/angel-of-despair.js";
import _poolAnuridMurkdiver from "../pool/anurid-murkdiver.js";
import _poolArcboundRavager from "../pool/arcbound-ravager.js";
import _poolArchaeomender from "../pool/archaeomender.js";
import _poolArmsDealer from "../pool/arms-dealer.js";
import _poolAttrition from "../pool/attrition.js";
import _poolAudacity from "../pool/audacity.js";
import _poolBadgermoleCub from "../pool/badgermole-cub.js";
import _poolBarbaryApes from "../pool/barbary-apes.js";
import _poolBarbedServitor from "../pool/barbed-servitor.js";
import _poolBattlemagesBracers from "../pool/battlemages-bracers.js";
import _poolBeaconOfUnrest from "../pool/beacon-of-unrest.js";
import _poolBehindTheScenes from "../pool/behind-the-scenes.js";
import _poolBerserkersOfBloodRidge from "../pool/berserkers-of-blood-ridge.js";
import _poolBigMotherMouser from "../pool/big-mother-mouser.js";
import _poolBladeSplicer from "../pool/blade-splicer.js";
import _poolBlaze from "../pool/blaze.js";
import _poolBloodVassal from "../pool/blood-vassal.js";
import _poolBlueSunsZenith from "../pool/blue-suns-zenith.js";
import _poolBonehoard from "../pool/bonehoard.js";
import _poolBoomerang from "../pool/boomerang.js";
import _poolBorderPatrol from "../pool/border-patrol.js";
import _poolBorosGuildmage from "../pool/boros-guildmage.js";
import _poolBraidsArisenNightmare from "../pool/braids-arisen-nightmare.js";
import _poolBreedingPool from "../pool/breeding-pool.js";
import _poolBrittleEffigy from "../pool/brittle-effigy.js";
import _poolCabalRitual from "../pool/cabal-ritual.js";
import _poolCabarettiCourtyard from "../pool/cabaretti-courtyard.js";
import _poolCallerOfGales from "../pool/caller-of-gales.js";
import _poolCamaraderie from "../pool/camaraderie.js";
import _poolCapashenTemplar from "../pool/capashen-templar.js";
import _poolCathedralSanctifier from "../pool/cathedral-sanctifier.js";
import _poolChainsOfCustody from "../pool/chains-of-custody.js";
import _poolChaosChanneler from "../pool/chaos-channeler.js";
import _poolChosenByHeliod from "../pool/chosen-by-heliod.js";
import _poolCircleOfPower from "../pool/circle-of-power.js";
import _poolCitanulStalwart from "../pool/citanul-stalwart.js";
import _poolCivicStalwart from "../pool/civic-stalwart.js";
import _poolClifftopRetreat from "../pool/clifftop-retreat.js";
import _poolClockworkDrawbridge from "../pool/clockwork-drawbridge.js";
import _poolConduitOfWorlds from "../pool/conduit-of-worlds.js";
import _poolCordialVampire from "../pool/cordial-vampire.js";
import _poolCripplingFear from "../pool/crippling-fear.js";
import _poolCrystallineCrawler from "../pool/crystalline-crawler.js";
import _poolCunningRhetoric from "../pool/cunning-rhetoric.js";
import _poolCuratorsWard from "../pool/curators-ward.js";
import _poolCuriosityCrafter from "../pool/curiosity-crafter.js";
import _poolDarksteelForge from "../pool/darksteel-forge.js";
import _poolDawnsireSunstarDreadnought from "../pool/dawnsire-sunstar-dreadnought.js";
import _poolDemystify from "../pool/demystify.js";
import _poolDevoteeOfStrength from "../pool/devotee-of-strength.js";
import _poolDimirGuildmage from "../pool/dimir-guildmage.js";
import _poolDiningRoom from "../pool/dining-room.js";
import _poolDispatch from "../pool/dispatch.js";
import _poolDivineTransformation from "../pool/divine-transformation.js";
import _poolDivineVerdict from "../pool/divine-verdict.js";
import _poolDranaLiberatorOfMalakir from "../pool/drana-liberator-of-malakir.js";
import _poolDreadSummons from "../pool/dread-summons.js";
import _poolEarthquakeDragon from "../pool/earthquake-dragon.js";
import _poolEidolonOfPhilosophy from "../pool/eidolon-of-philosophy.js";
import _poolElectricRevelation from "../pool/electric-revelation.js";
import _poolElvishRegrower from "../pool/elvish-regrower.js";
import _poolEnduringCourage from "../pool/enduring-courage.js";
import _poolEnduringVitality from "../pool/enduring-vitality.js";
import _poolEpicureOfBlood from "../pool/epicure-of-blood.js";
import _poolFacetReader from "../pool/facet-reader.js";
import _poolFanaticOfRhonas from "../pool/fanatic-of-rhonas.js";
import _poolFaramirStewardOfGondor from "../pool/faramir-steward-of-gondor.js";
import _poolFarhavenElf from "../pool/farhaven-elf.js";
import _poolFiendArtisan from "../pool/fiend-artisan.js";
import _poolFieryIslet from "../pool/fiery-islet.js";
import _poolFloodPlain from "../pool/flood-plain.js";
import _poolFontOfFertility from "../pool/font-of-fertility.js";
import _poolForatog from "../pool/foratog.js";
import _poolForsakenDrifters from "../pool/forsaken-drifters.js";
import _poolFracture from "../pool/fracture.js";
import _poolFranticStrength from "../pool/frantic-strength.js";
import _poolFrenziedRage from "../pool/frenzied-rage.js";
import _poolGaiusVanBaelsar from "../pool/gaius-van-baelsar.js";
import _poolGarruksGorehorn from "../pool/garruks-gorehorn.js";
import _poolGethsGrimoire from "../pool/geths-grimoire.js";
import _poolGhirapurOsprey from "../pool/ghirapur-osprey.js";
import _poolGiantStrength from "../pool/giant-strength.js";
import _poolGiftOfTheViper from "../pool/gift-of-the-viper.js";
import _poolGildedGoose from "../pool/gilded-goose.js";
import _poolGimliCounterOfKills from "../pool/gimli-counter-of-kills.js";
import _poolGoShintaiOfLifesOrigin from "../pool/go-shintai-of-lifes-origin.js";
import _poolGoblinChieftain from "../pool/goblin-chieftain.js";
import _poolGoddricCloakedReveler from "../pool/goddric-cloaked-reveler.js";
import _poolGolbezCrystalCollector from "../pool/golbez-crystal-collector.js";
import _poolGoliathSphinx from "../pool/goliath-sphinx.js";
import _poolGorillaWarrior from "../pool/gorilla-warrior.js";
import _poolGrapplingSundew from "../pool/grappling-sundew.js";
import _poolGraypeltRefuge from "../pool/graypelt-refuge.js";
import _poolGrazingWhiptail from "../pool/grazing-whiptail.js";
import _poolGreatsword from "../pool/greatsword.js";
import _poolGrowthSpiral from "../pool/growth-spiral.js";
import _poolGryffVanguard from "../pool/gryff-vanguard.js";
import _poolGuildlessCommons from "../pool/guildless-commons.js";
import _poolGutlessGhoul from "../pool/gutless-ghoul.js";
import _poolHallowedHaunting from "../pool/hallowed-haunting.js";
import _poolHearthfireHobgoblin from "../pool/hearthfire-hobgoblin.js";
import _poolHeatedDebate from "../pool/heated-debate.js";
import _poolHedronScrabbler from "../pool/hedron-scrabbler.js";
import _poolHelmOfAwakening from "../pool/helm-of-awakening.js";
import _poolHeraldOfSlaanesh from "../pool/herald-of-slaanesh.js";
import _poolHeraldicBanner from "../pool/heraldic-banner.js";
import _poolHitchclawRecluse from "../pool/hitchclaw-recluse.js";
import _poolHoardRobber from "../pool/hoard-robber.js";
import _poolHoardSmelterDragon from "../pool/hoard-smelter-dragon.js";
import _poolHookHauntDrifter from "../pool/hook-haunt-drifter.js";
import _poolHovermyr from "../pool/hovermyr.js";
import _poolHullBreach from "../pool/hull-breach.js";
import _poolInallaArchmageRitualist from "../pool/inalla-archmage-ritualist.js";
import _poolIndulgingPatrician from "../pool/indulging-patrician.js";
import _poolInevitableDefeat from "../pool/inevitable-defeat.js";
import _poolInspiringOverseer from "../pool/inspiring-overseer.js";
import _poolIntoTheNorth from "../pool/into-the-north.js";
import _poolIntrudingSoulrager from "../pool/intruding-soulrager.js";
import _poolInvasionTactics from "../pool/invasion-tactics.js";
import _poolJaceMemoryAdept from "../pool/jace-memory-adept.js";
import _poolJacesScrutiny from "../pool/jaces-scrutiny.js";
import _poolJadeMage from "../pool/jade-mage.js";
import _poolJayasGreeting from "../pool/jayas-greeting.js";
import _poolJhoirasFamiliar from "../pool/jhoiras-familiar.js";
import _poolJinSakaiGhostOfTsushima from "../pool/jin-sakai-ghost-of-tsushima.js";
import _poolKangeesLieutenant from "../pool/kangees-lieutenant.js";
import _poolKedissEmberclawFamiliar from "../pool/kediss-emberclaw-familiar.js";
import _poolKetriaCrystal from "../pool/ketria-crystal.js";
import _poolKhalniGarden from "../pool/khalni-garden.js";
import _poolKillerBees from "../pool/killer-bees.js";
import _poolKirdApe from "../pool/kird-ape.js";
import _poolKithkinBillyrider from "../pool/kithkin-billyrider.js";
import _poolKoboldsOfKherKeep from "../pool/kobolds-of-kher-keep.js";
import _poolKyrenGlider from "../pool/kyren-glider.js";
import _poolLadyOctopusInspiredInventor from "../pool/lady-octopus-inspired-inventor.js";
import _poolLegolasGreenleaf from "../pool/legolas-greenleaf.js";
import _poolLeoninSkyhunter from "../pool/leonin-skyhunter.js";
import _poolLeshracsRite from "../pool/leshracs-rite.js";
import _poolLilianasSteward from "../pool/lilianas-steward.js";
import _poolLlanowarVanguard from "../pool/llanowar-vanguard.js";
import _poolLoamdraggerGiant from "../pool/loamdragger-giant.js";
import _poolManaCylix from "../pool/mana-cylix.js";
import _poolMaraudingMako from "../pool/marauding-mako.js";
import _poolMercilessEnforcers from "../pool/merciless-enforcers.js";
import _poolMirrorImage from "../pool/mirror-image.js";
import _poolMistcutterHydra from "../pool/mistcutter-hydra.js";
import _poolMistyPalmsOasis from "../pool/misty-palms-oasis.js";
import _poolMmmenonUthrosExile from "../pool/mmmenon-uthros-exile.js";
import _poolMondrakGloryDominus from "../pool/mondrak-glory-dominus.js";
import _poolMonologueTax from "../pool/monologue-tax.js";
import _poolMonssGoblinRaiders from "../pool/monss-goblin-raiders.js";
import _poolMoonriseCleric from "../pool/moonrise-cleric.js";
import _poolMoriokReaver from "../pool/moriok-reaver.js";
import _poolMossDiamond from "../pool/moss-diamond.js";
import _poolMossdog from "../pool/mossdog.js";
import _poolMoxTantalite from "../pool/mox-tantalite.js";
import _poolMusterTheDeparted from "../pool/muster-the-departed.js";
import _poolMyPrecious from "../pool/my-precious.js";
import _poolMysidianElder from "../pool/mysidian-elder.js";
import _poolMysticForge from "../pool/mystic-forge.js";
import _poolMysticGate from "../pool/mystic-gate.js";
import _poolNessianCourser from "../pool/nessian-courser.js";
import _poolNighthaze from "../pool/nighthaze.js";
import _poolNivMizzetTheFiremind from "../pool/niv-mizzet-the-firemind.js";
import _poolNogiDracoZealot from "../pool/nogi-draco-zealot.js";
import _poolNullElementalBlast from "../pool/null-elemental-blast.js";
import _poolNutrientBlock from "../pool/nutrient-block.js";
import _poolOakenform from "../pool/oakenform.js";
import _poolOkosAccomplices from "../pool/okos-accomplices.js";
import _poolOmoQueenOfVesuva from "../pool/omo-queen-of-vesuva.js";
import _poolOneWithTheMachine from "../pool/one-with-the-machine.js";
import _poolOpalineUnicorn from "../pool/opaline-unicorn.js";
import _poolOrmendahlProfanePrince from "../pool/ormendahl-profane-prince.js";
import _poolOrzhovBasilica from "../pool/orzhov-basilica.js";
import _poolOuroboroid from "../pool/ouroboroid.js";
import _poolParadiseMantle from "../pool/paradise-mantle.js";
import _poolPearlEarImperialAdvisor from "../pool/pearl-ear-imperial-advisor.js";
import _poolPelakkaWurm from "../pool/pelakka-wurm.js";
import _poolPerennialBehemoth from "../pool/perennial-behemoth.js";
import _poolPestInfestation from "../pool/pest-infestation.js";
import _poolPestilentKathari from "../pool/pestilent-kathari.js";
import _poolPharikasChosen from "../pool/pharikas-chosen.js";
import _poolPhyrexianRebirth from "../pool/phyrexian-rebirth.js";
import _poolPlanarGenesis from "../pool/planar-genesis.js";
import _poolPlatedSeastrider from "../pool/plated-seastrider.js";
import _poolPriestOfIroas from "../pool/priest-of-iroas.js";
import _poolPrimalMight from "../pool/primal-might.js";
import _poolPrismariCharm from "../pool/prismari-charm.js";
import _poolQuilledSlagwurm from "../pool/quilled-slagwurm.js";
import _poolRadiantGrove from "../pool/radiant-grove.js";
import _poolRadiantSummit from "../pool/radiant-summit.js";
import _poolRaffCapashenShipsMage from "../pool/raff-capashen-ships-mage.js";
import _poolRakdosSignet from "../pool/rakdos-signet.js";
import _poolRallyTheRanks from "../pool/rally-the-ranks.js";
import _poolRavineRaider from "../pool/ravine-raider.js";
import _poolRecumbentBliss from "../pool/recumbent-bliss.js";
import _poolRevelsongHorn from "../pool/revelsong-horn.js";
import _poolRevengeOfTheRats from "../pool/revenge-of-the-rats.js";
import _poolRibCageSpider from "../pool/rib-cage-spider.js";
import _poolRitualOfRejuvenation from "../pool/ritual-of-rejuvenation.js";
import _poolRiverKaijin from "../pool/river-kaijin.js";
import _poolRootriderFaun from "../pool/rootrider-faun.js";
import _poolRuinCrab from "../pool/ruin-crab.js";
import _poolSageOfTheInwardEye from "../pool/sage-of-the-inward-eye.js";
import _poolSanctumOfFruitfulHarvest from "../pool/sanctum-of-fruitful-harvest.js";
import _poolSaprazzanHeir from "../pool/saprazzan-heir.js";
import _poolSatyrWayfinder from "../pool/satyr-wayfinder.js";
import _poolSchoolOfTheUnseen from "../pool/school-of-the-unseen.js";
import _poolScorchingMissile from "../pool/scorching-missile.js";
import _poolScourgeOfTheThrone from "../pool/scourge-of-the-throne.js";
import _poolScrawlingCrawler from "../pool/scrawling-crawler.js";
import _poolScuteMob from "../pool/scute-mob.js";
import _poolSearchlightGeist from "../pool/searchlight-geist.js";
import _poolSejiriRefuge from "../pool/sejiri-refuge.js";
import _poolSepulchralPrimordial from "../pool/sepulchral-primordial.js";
import _poolSerpentineKavu from "../pool/serpentine-kavu.js";
import _poolShamblingStrider from "../pool/shambling-strider.js";
import _poolShieldOfTheOversoul from "../pool/shield-of-the-oversoul.js";
import _poolShiningAerosaur from "../pool/shining-aerosaur.js";
import _poolShoreUp from "../pool/shore-up.js";
import _poolShowOfValor from "../pool/show-of-valor.js";
import _poolSidarKondoOfJamuraa from "../pool/sidar-kondo-of-jamuraa.js";
import _poolSiegeMastodon from "../pool/siege-mastodon.js";
import _poolSiegeVeteran from "../pool/siege-veteran.js";
import _poolSigilOfSleep from "../pool/sigil-of-sleep.js";
import _poolSireOfSevenDeaths from "../pool/sire-of-seven-deaths.js";
import _poolSistersOfTheFlame from "../pool/sisters-of-the-flame.js";
import _poolSkyEelSchool from "../pool/sky-eel-school.js";
import _poolSkyclaveCleric from "../pool/skyclave-cleric.js";
import _poolSkyhunterSkirmisher from "../pool/skyhunter-skirmisher.js";
import _poolSlingGangLieutenant from "../pool/sling-gang-lieutenant.js";
import _poolSlipOnTheRing from "../pool/slip-on-the-ring.js";
import _poolSliverHivelord from "../pool/sliver-hivelord.js";
import _poolSomnomancer from "../pool/somnomancer.js";
import _poolSongOfFreyalise from "../pool/song-of-freyalise.js";
import _poolSorinRavenousNeonate from "../pool/sorin-ravenous-neonate.js";
import _poolSowingMycospawn from "../pool/sowing-mycospawn.js";
import _poolSpinnerOfSouls from "../pool/spinner-of-souls.js";
import _poolSpiritMantle from "../pool/spirit-mantle.js";
import _poolSporecrownThallid from "../pool/sporecrown-thallid.js";
import _poolSporemound from "../pool/sporemound.js";
import _poolSpringsageRitual from "../pool/springsage-ritual.js";
import _poolSquallDrifter from "../pool/squall-drifter.js";
import _poolStaffOfNin from "../pool/staff-of-nin.js";
import _poolSteelshapersGift from "../pool/steelshapers-gift.js";
import _poolStomperCub from "../pool/stomper-cub.js";
import _poolStormfistCrusader from "../pool/stormfist-crusader.js";
import _poolStreetbreakerWurm from "../pool/streetbreaker-wurm.js";
import _poolStrengthOfTheHarvest from "../pool/strength-of-the-harvest.js";
import _poolSummonPrimalOdin from "../pool/summon-primal-odin.js";
import _poolSunderingGrowth from "../pool/sundering-growth.js";
import _poolSweepingCleave from "../pool/sweeping-cleave.js";
import _poolSwordOfTheAnimist from "../pool/sword-of-the-animist.js";
import _poolSwornCompanions from "../pool/sworn-companions.js";
import _poolTaintedWood from "../pool/tainted-wood.js";
import _poolTalrandsInvocation from "../pool/talrands-invocation.js";
import _poolTanglespanBridgeworks from "../pool/tanglespan-bridgeworks.js";
import _poolTearAsunder from "../pool/tear-asunder.js";
import _poolTempestTechnique from "../pool/tempest-technique.js";
import _poolTenzaGodosMaul from "../pool/tenza-godos-maul.js";
import _poolTerrorOfThePeaks from "../pool/terror-of-the-peaks.js";
import _poolTetsukoUmezawaFugitive from "../pool/tetsuko-umezawa-fugitive.js";
import _poolThaliaHereticCathar from "../pool/thalia-heretic-cathar.js";
import _poolTheBeamtownBullies from "../pool/the-beamtown-bullies.js";
import _poolThornscapeApprentice from "../pool/thornscape-apprentice.js";
import _poolThunderfootBaloth from "../pool/thunderfoot-baloth.js";
import _poolTimeOfNeed from "../pool/time-of-need.js";
import _poolTombOfTheSpiritDragon from "../pool/tomb-of-the-spirit-dragon.js";
import _poolTophGreatestEarthbender from "../pool/toph-greatest-earthbender.js";
import _poolTowerOfCalamities from "../pool/tower-of-calamities.js";
import _poolTowerWinder from "../pool/tower-winder.js";
import _poolTrainedOrgg from "../pool/trained-orgg.js";
import _poolTranquilExpanse from "../pool/tranquil-expanse.js";
import _poolTranscendentEnvoy from "../pool/transcendent-envoy.js";
import _poolTundraWall from "../pool/tundra-wall.js";
import _poolTwoHeadedHunter from "../pool/two-headed-hunter.js";
import _poolTyroxSauridTyrant from "../pool/tyrox-saurid-tyrant.js";
import _poolUndeadWarchief from "../pool/undead-warchief.js";
import _poolUndergroundMortuary from "../pool/underground-mortuary.js";
import _poolUnfriendlyFire from "../pool/unfriendly-fire.js";
import _poolUrabrasksForge from "../pool/urabrasks-forge.js";
import _poolUrborgElf from "../pool/urborg-elf.js";
import _poolUrnOfGodfire from "../pool/urn-of-godfire.js";
import _poolUthrosTitanicGodcore from "../pool/uthros-titanic-godcore.js";
import _poolVaultOfWhispers from "../pool/vault-of-whispers.js";
import _poolViashinoSlaughtermaster from "../pool/viashino-slaughtermaster.js";
import _poolVincentVengefulAtoner from "../pool/vincent-vengeful-atoner.js";
import _poolVodalianHypnotist from "../pool/vodalian-hypnotist.js";
import _poolWatcherOfTheWayside from "../pool/watcher-of-the-wayside.js";
import _poolWaterfallAerialist from "../pool/waterfall-aerialist.js";
import _poolWaywardGiant from "../pool/wayward-giant.js";
import _poolWhiptongueHydra from "../pool/whiptongue-hydra.js";
import _poolWieldingTheGreenDragon from "../pool/wielding-the-green-dragon.js";
import _poolWildJhovall from "../pool/wild-jhovall.js";
import _poolWirewoodSymbiote from "../pool/wirewood-symbiote.js";
import _poolWishcoinCrab from "../pool/wishcoin-crab.js";
import _poolWithinRange from "../pool/within-range.js";
import _poolYevaNaturesHerald from "../pool/yeva-natures-herald.js";
import _poolYouFindTheVillainsLair from "../pool/you-find-the-villains-lair.js";
import _poolZetalpaPrimalDawn from "../pool/zetalpa-primal-dawn.js";
import _poolZombieMaster from "../pool/zombie-master.js";
import _tokens22BlackBirdToken from "../tokens/2-2-black-bird-token.js";
import _tokensDragonTokenDragonbackAssault from "../tokens/dragon-token-dragonback-assault.js";
import _tokensElementalToken from "../tokens/elemental-token.js";
import _tokensGreenElementalToken22 from "../tokens/green-elemental-token-2-2.js";
import _tokensHeroTokenBlackMagesRod from "../tokens/hero-token-black-mages-rod.js";
import _tokensNecronWarriorToken from "../tokens/necron-warrior-token.js";
import _tokensOgreToken from "../tokens/ogre-token.js";
import _tokensSnailToken from "../tokens/snail-token.js";
import _tokensSpiderToken22Reach from "../tokens/spider-token-2-2-reach.js";
import _tokensWarriorTokenVigilance from "../tokens/warrior-token-vigilance.js";
import _tokensWolfTokenGarrukCursedHuntsman from "../tokens/wolf-token-garruk-cursed-huntsman.js";

const shard: CardShard = {
  pool: [
    _poolAbbeyMatron,
    _poolAetherHub,
    _poolAkkiRockspeaker,
    _poolAlignedHeart,
    _poolAlpineMeadow,
    _poolAncientCarp,
    _poolAncientCrab,
    _poolAngelOfDespair,
    _poolAnuridMurkdiver,
    _poolArcboundRavager,
    _poolArchaeomender,
    _poolArmsDealer,
    _poolAttrition,
    _poolAudacity,
    _poolBadgermoleCub,
    _poolBarbaryApes,
    _poolBarbedServitor,
    _poolBattlemagesBracers,
    _poolBeaconOfUnrest,
    _poolBehindTheScenes,
    _poolBerserkersOfBloodRidge,
    _poolBigMotherMouser,
    _poolBladeSplicer,
    _poolBlaze,
    _poolBloodVassal,
    _poolBlueSunsZenith,
    _poolBonehoard,
    _poolBoomerang,
    _poolBorderPatrol,
    _poolBorosGuildmage,
    _poolBraidsArisenNightmare,
    _poolBreedingPool,
    _poolBrittleEffigy,
    _poolCabalRitual,
    _poolCabarettiCourtyard,
    _poolCallerOfGales,
    _poolCamaraderie,
    _poolCapashenTemplar,
    _poolCathedralSanctifier,
    _poolChainsOfCustody,
    _poolChaosChanneler,
    _poolChosenByHeliod,
    _poolCircleOfPower,
    _poolCitanulStalwart,
    _poolCivicStalwart,
    _poolClifftopRetreat,
    _poolClockworkDrawbridge,
    _poolConduitOfWorlds,
    _poolCordialVampire,
    _poolCripplingFear,
    _poolCrystallineCrawler,
    _poolCunningRhetoric,
    _poolCuratorsWard,
    _poolCuriosityCrafter,
    _poolDarksteelForge,
    _poolDawnsireSunstarDreadnought,
    _poolDemystify,
    _poolDevoteeOfStrength,
    _poolDimirGuildmage,
    _poolDiningRoom,
    _poolDispatch,
    _poolDivineTransformation,
    _poolDivineVerdict,
    _poolDranaLiberatorOfMalakir,
    _poolDreadSummons,
    _poolEarthquakeDragon,
    _poolEidolonOfPhilosophy,
    _poolElectricRevelation,
    _poolElvishRegrower,
    _poolEnduringCourage,
    _poolEnduringVitality,
    _poolEpicureOfBlood,
    _poolFacetReader,
    _poolFanaticOfRhonas,
    _poolFaramirStewardOfGondor,
    _poolFarhavenElf,
    _poolFiendArtisan,
    _poolFieryIslet,
    _poolFloodPlain,
    _poolFontOfFertility,
    _poolForatog,
    _poolForsakenDrifters,
    _poolFracture,
    _poolFranticStrength,
    _poolFrenziedRage,
    _poolGaiusVanBaelsar,
    _poolGarruksGorehorn,
    _poolGethsGrimoire,
    _poolGhirapurOsprey,
    _poolGiantStrength,
    _poolGiftOfTheViper,
    _poolGildedGoose,
    _poolGimliCounterOfKills,
    _poolGoShintaiOfLifesOrigin,
    _poolGoblinChieftain,
    _poolGoddricCloakedReveler,
    _poolGolbezCrystalCollector,
    _poolGoliathSphinx,
    _poolGorillaWarrior,
    _poolGrapplingSundew,
    _poolGraypeltRefuge,
    _poolGrazingWhiptail,
    _poolGreatsword,
    _poolGrowthSpiral,
    _poolGryffVanguard,
    _poolGuildlessCommons,
    _poolGutlessGhoul,
    _poolHallowedHaunting,
    _poolHearthfireHobgoblin,
    _poolHeatedDebate,
    _poolHedronScrabbler,
    _poolHelmOfAwakening,
    _poolHeraldOfSlaanesh,
    _poolHeraldicBanner,
    _poolHitchclawRecluse,
    _poolHoardRobber,
    _poolHoardSmelterDragon,
    _poolHookHauntDrifter,
    _poolHovermyr,
    _poolHullBreach,
    _poolInallaArchmageRitualist,
    _poolIndulgingPatrician,
    _poolInevitableDefeat,
    _poolInspiringOverseer,
    _poolIntoTheNorth,
    _poolIntrudingSoulrager,
    _poolInvasionTactics,
    _poolJaceMemoryAdept,
    _poolJacesScrutiny,
    _poolJadeMage,
    _poolJayasGreeting,
    _poolJhoirasFamiliar,
    _poolJinSakaiGhostOfTsushima,
    _poolKangeesLieutenant,
    _poolKedissEmberclawFamiliar,
    _poolKetriaCrystal,
    _poolKhalniGarden,
    _poolKillerBees,
    _poolKirdApe,
    _poolKithkinBillyrider,
    _poolKoboldsOfKherKeep,
    _poolKyrenGlider,
    _poolLadyOctopusInspiredInventor,
    _poolLegolasGreenleaf,
    _poolLeoninSkyhunter,
    _poolLeshracsRite,
    _poolLilianasSteward,
    _poolLlanowarVanguard,
    _poolLoamdraggerGiant,
    _poolManaCylix,
    _poolMaraudingMako,
    _poolMercilessEnforcers,
    _poolMirrorImage,
    _poolMistcutterHydra,
    _poolMistyPalmsOasis,
    _poolMmmenonUthrosExile,
    _poolMondrakGloryDominus,
    _poolMonologueTax,
    _poolMonssGoblinRaiders,
    _poolMoonriseCleric,
    _poolMoriokReaver,
    _poolMossDiamond,
    _poolMossdog,
    _poolMoxTantalite,
    _poolMusterTheDeparted,
    _poolMyPrecious,
    _poolMysidianElder,
    _poolMysticForge,
    _poolMysticGate,
    _poolNessianCourser,
    _poolNighthaze,
    _poolNivMizzetTheFiremind,
    _poolNogiDracoZealot,
    _poolNullElementalBlast,
    _poolNutrientBlock,
    _poolOakenform,
    _poolOkosAccomplices,
    _poolOmoQueenOfVesuva,
    _poolOneWithTheMachine,
    _poolOpalineUnicorn,
    _poolOrmendahlProfanePrince,
    _poolOrzhovBasilica,
    _poolOuroboroid,
    _poolParadiseMantle,
    _poolPearlEarImperialAdvisor,
    _poolPelakkaWurm,
    _poolPerennialBehemoth,
    _poolPestInfestation,
    _poolPestilentKathari,
    _poolPharikasChosen,
    _poolPhyrexianRebirth,
    _poolPlanarGenesis,
    _poolPlatedSeastrider,
    _poolPriestOfIroas,
    _poolPrimalMight,
    _poolPrismariCharm,
    _poolQuilledSlagwurm,
    _poolRadiantGrove,
    _poolRadiantSummit,
    _poolRaffCapashenShipsMage,
    _poolRakdosSignet,
    _poolRallyTheRanks,
    _poolRavineRaider,
    _poolRecumbentBliss,
    _poolRevelsongHorn,
    _poolRevengeOfTheRats,
    _poolRibCageSpider,
    _poolRitualOfRejuvenation,
    _poolRiverKaijin,
    _poolRootriderFaun,
    _poolRuinCrab,
    _poolSageOfTheInwardEye,
    _poolSanctumOfFruitfulHarvest,
    _poolSaprazzanHeir,
    _poolSatyrWayfinder,
    _poolSchoolOfTheUnseen,
    _poolScorchingMissile,
    _poolScourgeOfTheThrone,
    _poolScrawlingCrawler,
    _poolScuteMob,
    _poolSearchlightGeist,
    _poolSejiriRefuge,
    _poolSepulchralPrimordial,
    _poolSerpentineKavu,
    _poolShamblingStrider,
    _poolShieldOfTheOversoul,
    _poolShiningAerosaur,
    _poolShoreUp,
    _poolShowOfValor,
    _poolSidarKondoOfJamuraa,
    _poolSiegeMastodon,
    _poolSiegeVeteran,
    _poolSigilOfSleep,
    _poolSireOfSevenDeaths,
    _poolSistersOfTheFlame,
    _poolSkyEelSchool,
    _poolSkyclaveCleric,
    _poolSkyhunterSkirmisher,
    _poolSlingGangLieutenant,
    _poolSlipOnTheRing,
    _poolSliverHivelord,
    _poolSomnomancer,
    _poolSongOfFreyalise,
    _poolSorinRavenousNeonate,
    _poolSowingMycospawn,
    _poolSpinnerOfSouls,
    _poolSpiritMantle,
    _poolSporecrownThallid,
    _poolSporemound,
    _poolSpringsageRitual,
    _poolSquallDrifter,
    _poolStaffOfNin,
    _poolSteelshapersGift,
    _poolStomperCub,
    _poolStormfistCrusader,
    _poolStreetbreakerWurm,
    _poolStrengthOfTheHarvest,
    _poolSummonPrimalOdin,
    _poolSunderingGrowth,
    _poolSweepingCleave,
    _poolSwordOfTheAnimist,
    _poolSwornCompanions,
    _poolTaintedWood,
    _poolTalrandsInvocation,
    _poolTanglespanBridgeworks,
    _poolTearAsunder,
    _poolTempestTechnique,
    _poolTenzaGodosMaul,
    _poolTerrorOfThePeaks,
    _poolTetsukoUmezawaFugitive,
    _poolThaliaHereticCathar,
    _poolTheBeamtownBullies,
    _poolThornscapeApprentice,
    _poolThunderfootBaloth,
    _poolTimeOfNeed,
    _poolTombOfTheSpiritDragon,
    _poolTophGreatestEarthbender,
    _poolTowerOfCalamities,
    _poolTowerWinder,
    _poolTrainedOrgg,
    _poolTranquilExpanse,
    _poolTranscendentEnvoy,
    _poolTundraWall,
    _poolTwoHeadedHunter,
    _poolTyroxSauridTyrant,
    _poolUndeadWarchief,
    _poolUndergroundMortuary,
    _poolUnfriendlyFire,
    _poolUrabrasksForge,
    _poolUrborgElf,
    _poolUrnOfGodfire,
    _poolUthrosTitanicGodcore,
    _poolVaultOfWhispers,
    _poolViashinoSlaughtermaster,
    _poolVincentVengefulAtoner,
    _poolVodalianHypnotist,
    _poolWatcherOfTheWayside,
    _poolWaterfallAerialist,
    _poolWaywardGiant,
    _poolWhiptongueHydra,
    _poolWieldingTheGreenDragon,
    _poolWildJhovall,
    _poolWirewoodSymbiote,
    _poolWishcoinCrab,
    _poolWithinRange,
    _poolYevaNaturesHerald,
    _poolYouFindTheVillainsLair,
    _poolZetalpaPrimalDawn,
    _poolZombieMaster,
  ],
  tokens: [
    _tokens22BlackBirdToken,
    _tokensDragonTokenDragonbackAssault,
    _tokensElementalToken,
    _tokensGreenElementalToken22,
    _tokensHeroTokenBlackMagesRod,
    _tokensNecronWarriorToken,
    _tokensOgreToken,
    _tokensSnailToken,
    _tokensSpiderToken22Reach,
    _tokensWarriorTokenVigilance,
    _tokensWolfTokenGarrukCursedHuntsman,
  ],
};

export default shard;
