// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.
// Run `npm run gen:cards -w engine` after adding or removing a card file.

import type { CardShard } from "../card-shards.js";

import _poolAangAtTheCrossroads from "../pool/aang-at-the-crossroads.js";
import _poolAlpineWatchdog from "../pool/alpine-watchdog.js";
import _poolArchwingDragon from "../pool/archwing-dragon.js";
import _poolArmoredWhirlTurtle from "../pool/armored-whirl-turtle.js";
import _poolAronBenaliasRuin from "../pool/aron-benalias-ruin.js";
import _poolArrogantVampire from "../pool/arrogant-vampire.js";
import _poolAvenWindMage from "../pool/aven-wind-mage.js";
import _poolAzlaskTheSwellingScourge from "../pool/azlask-the-swelling-scourge.js";
import _poolBalaGedSanctuary from "../pool/bala-ged-sanctuary.js";
import _poolBallistaSquad from "../pool/ballista-squad.js";
import _poolBeastmasterAscension from "../pool/beastmaster-ascension.js";
import _poolBlackMarketConnections from "../pool/black-market-connections.js";
import _poolBoonOfEmrakul from "../pool/boon-of-emrakul.js";
import _poolBrawnAmadeusCho from "../pool/brawn-amadeus-cho.js";
import _poolBronzeWalrus from "../pool/bronze-walrus.js";
import _poolBurstOfSpeed from "../pool/burst-of-speed.js";
import _poolCacklingFiend from "../pool/cackling-fiend.js";
import _poolCarnivorousPlant from "../pool/carnivorous-plant.js";
import _poolChainReaction from "../pool/chain-reaction.js";
import _poolChandrasMagmutt from "../pool/chandras-magmutt.js";
import _poolChromaticLantern from "../pool/chromatic-lantern.js";
import _poolClavilenoFirstOfTheBlessed from "../pool/clavileno-first-of-the-blessed.js";
import _poolCommonBond from "../pool/common-bond.js";
import _poolConclaveTribunal from "../pool/conclave-tribunal.js";
import _poolConviction from "../pool/conviction.js";
import _poolCouriersCapsule from "../pool/couriers-capsule.js";
import _poolCravenGiant from "../pool/craven-giant.js";
import _poolDaggerfangDuo from "../pool/daggerfang-duo.js";
import _poolDarkNourishment from "../pool/dark-nourishment.js";
import _poolDeathgreeter from "../pool/deathgreeter.js";
import _poolDeduce from "../pool/deduce.js";
import _poolDegaDisciple from "../pool/dega-disciple.js";
import _poolDesperateBloodseeker from "../pool/desperate-bloodseeker.js";
import _poolDranasChosen from "../pool/dranas-chosen.js";
import _poolElvishDoomsayer from "../pool/elvish-doomsayer.js";
import _poolEmmessiTome from "../pool/emmessi-tome.js";
import _poolErase from "../pool/erase.js";
import _poolFalseSummoning from "../pool/false-summoning.js";
import _poolFarewell from "../pool/farewell.js";
import _poolFelidarRetreat from "../pool/felidar-retreat.js";
import _poolFestivalCrasher from "../pool/festival-crasher.js";
import _poolFireLitThicket from "../pool/fire-lit-thicket.js";
import _poolFleetingEffigy from "../pool/fleeting-effigy.js";
import _poolFrontierBivouac from "../pool/frontier-bivouac.js";
import _poolFrostwindInvoker from "../pool/frostwind-invoker.js";
import _poolGevScaledScorch from "../pool/gev-scaled-scorch.js";
import _poolGiganticBigBear from "../pool/gigantic-big-bear.js";
import _poolGliderKids from "../pool/glider-kids.js";
import _poolGloriousCharge from "../pool/glorious-charge.js";
import _poolGoblinSurprise from "../pool/goblin-surprise.js";
import _poolGreaterTanuki from "../pool/greater-tanuki.js";
import _poolGruesomeDeformity from "../pool/gruesome-deformity.js";
import _poolGruulTurf from "../pool/gruul-turf.js";
import _poolGutShot from "../pool/gut-shot.js";
import _poolHappyHoganDauntlessDriver from "../pool/happy-hogan-dauntless-driver.js";
import _poolHardWonJitte from "../pool/hard-won-jitte.js";
import _poolHeadwaterSentries from "../pool/headwater-sentries.js";
import _poolHellkitePunisher from "../pool/hellkite-punisher.js";
import _poolHengegatePathway from "../pool/hengegate-pathway.js";
import _poolHighPriestOfPenance from "../pool/high-priest-of-penance.js";
import _poolHighlandForest from "../pool/highland-forest.js";
import _poolHillcomberGiant from "../pool/hillcomber-giant.js";
import _poolHoneyMammoth from "../pool/honey-mammoth.js";
import _poolImperialRecruiter from "../pool/imperial-recruiter.js";
import _poolIridescentBlademaster from "../pool/iridescent-blademaster.js";
import _poolJasperaSentinel from "../pool/jaspera-sentinel.js";
import _poolJetmirNexusOfRevels from "../pool/jetmir-nexus-of-revels.js";
import _poolKeeperOfTheNineGales from "../pool/keeper-of-the-nine-gales.js";
import _poolKiorasDambreaker from "../pool/kioras-dambreaker.js";
import _poolKodamaOfTheNorthTree from "../pool/kodama-of-the-north-tree.js";
import _poolLibraryLarcenist from "../pool/library-larcenist.js";
import _poolLoomingShade from "../pool/looming-shade.js";
import _poolLordOfChange from "../pool/lord-of-change.js";
import _poolLowlandGiant from "../pool/lowland-giant.js";
import _poolLoxodonConvert from "../pool/loxodon-convert.js";
import _poolLoxodonSergeant from "../pool/loxodon-sergeant.js";
import _poolLukeCageHeroForHire from "../pool/luke-cage-hero-for-hire.js";
import _poolLysAlanaHuntmaster from "../pool/lys-alana-huntmaster.js";
import _poolMarwynTheNurturer from "../pool/marwyn-the-nurturer.js";
import _poolMerfolkSecretkeeper from "../pool/merfolk-secretkeeper.js";
import _poolMesaEnchantress from "../pool/mesa-enchantress.js";
import _poolMessengerDrake from "../pool/messenger-drake.js";
import _poolMisguidedRage from "../pool/misguided-rage.js";
import _poolMonoistSentry from "../pool/monoist-sentry.js";
import _poolMorphicPool from "../pool/morphic-pool.js";
import _poolMsBumbleflower from "../pool/ms-bumbleflower.js";
import _poolMurmuringPhantasm from "../pool/murmuring-phantasm.js";
import _poolMyrRetriever from "../pool/myr-retriever.js";
import _poolNagaEternal from "../pool/naga-eternal.js";
import _poolNoxiousRevival from "../pool/noxious-revival.js";
import _poolObeliskOfGrixis from "../pool/obelisk-of-grixis.js";
import _poolOrazcaRaptor from "../pool/orazca-raptor.js";
import _poolOrzhovSignet from "../pool/orzhov-signet.js";
import _poolParallelLives from "../pool/parallel-lives.js";
import _poolPathOfAngersFlame from "../pool/path-of-angers-flame.js";
import _poolPheresBandCentaurs from "../pool/pheres-band-centaurs.js";
import _poolPhyrexianHulk from "../pool/phyrexian-hulk.js";
import _poolPhyrexianWalker from "../pool/phyrexian-walker.js";
import _poolPotionOfHealing from "../pool/potion-of-healing.js";
import _poolPromisingVein from "../pool/promising-vein.js";
import _poolPyreHound from "../pool/pyre-hound.js";
import _poolRainOfRevelation from "../pool/rain-of-revelation.js";
import _poolRaiseTheAlarm from "../pool/raise-the-alarm.js";
import _poolRakshasaDebaser from "../pool/rakshasa-debaser.js";
import _poolRathiTrapper from "../pool/rathi-trapper.js";
import _poolRazortoothRats from "../pool/razortooth-rats.js";
import _poolRedHerring from "../pool/red-herring.js";
import _poolRendmawCreakingNest from "../pool/rendmaw-creaking-nest.js";
import _poolRipchainRazorkin from "../pool/ripchain-razorkin.js";
import _poolRustwingFalcon from "../pool/rustwing-falcon.js";
import _poolSceneOfTheCrime from "../pool/scene-of-the-crime.js";
import _poolScrubland from "../pool/scrubland.js";
import _poolSeethingSong from "../pool/seething-song.js";
import _poolSelesnyaLocket from "../pool/selesnya-locket.js";
import _poolSeparatistVoidmage from "../pool/separatist-voidmage.js";
import _poolShieldMate from "../pool/shield-mate.js";
import _poolShinenOfFlightsWings from "../pool/shinen-of-flights-wings.js";
import _poolSilentAttendant from "../pool/silent-attendant.js";
import _poolSkyRuinDrake from "../pool/sky-ruin-drake.js";
import _poolSlinkingSerpent from "../pool/slinking-serpent.js";
import _poolSpikedBaloth from "../pool/spiked-baloth.js";
import _poolStampedingScurryfoot from "../pool/stampeding-scurryfoot.js";
import _poolStandFirm from "../pool/stand-firm.js";
import _poolStandingStones from "../pool/standing-stones.js";
import _poolStoneDocent from "../pool/stone-docent.js";
import _poolStormcallerOfKeranos from "../pool/stormcaller-of-keranos.js";
import _poolStudentOfOjutai from "../pool/student-of-ojutai.js";
import _poolSubmergedBoneyard from "../pool/submerged-boneyard.js";
import _poolSunastianFalconer from "../pool/sunastian-falconer.js";
import _poolSwordOfFeastAndFamine from "../pool/sword-of-feast-and-famine.js";
import _poolSylvokReplica from "../pool/sylvok-replica.js";
import _poolSymbioticBeast from "../pool/symbiotic-beast.js";
import _poolTanglebloom from "../pool/tanglebloom.js";
import _poolTanglepoolBridge from "../pool/tanglepool-bridge.js";
import _poolTerrorOfTheFairgrounds from "../pool/terror-of-the-fairgrounds.js";
import _poolThornwoodFalls from "../pool/thornwood-falls.js";
import _poolThrivingGrove from "../pool/thriving-grove.js";
import _poolTomBombadil from "../pool/tom-bombadil.js";
import _poolTorstenVonUrsus from "../pool/torsten-von-ursus.js";
import _poolTortoiseFormation from "../pool/tortoise-formation.js";
import _poolTrapmakersSnare from "../pool/trapmakers-snare.js";
import _poolTrueLovesKiss from "../pool/true-loves-kiss.js";
import _poolTundra from "../pool/tundra.js";
import _poolTurbulentFen from "../pool/turbulent-fen.js";
import _poolUndeadMinotaur from "../pool/undead-minotaur.js";
import _poolUnholyStrength from "../pool/unholy-strength.js";
import _poolValorousSteed from "../pool/valorous-steed.js";
import _poolVesperGhoul from "../pool/vesper-ghoul.js";
import _poolVesselOfEphemera from "../pool/vessel-of-ephemera.js";
import _poolViridescentBog from "../pool/viridescent-bog.js";
import _poolVoraciousNull from "../pool/voracious-null.js";
import _poolWarrenSoultrader from "../pool/warren-soultrader.js";
import _poolWaterElemental from "../pool/water-elemental.js";
import _poolWaterloggedGrove from "../pool/waterlogged-grove.js";
import _poolWeightOfMemory from "../pool/weight-of-memory.js";
import _poolWeldfastMonitor from "../pool/weldfast-monitor.js";
import _poolWillOfTheSultai from "../pool/will-of-the-sultai.js";
import _tokensPhyrexianGoblinToken from "../tokens/phyrexian-goblin-token.js";

const shard: CardShard = {
  pool: [
    _poolAangAtTheCrossroads,
    _poolAlpineWatchdog,
    _poolArchwingDragon,
    _poolArmoredWhirlTurtle,
    _poolAronBenaliasRuin,
    _poolArrogantVampire,
    _poolAvenWindMage,
    _poolAzlaskTheSwellingScourge,
    _poolBalaGedSanctuary,
    _poolBallistaSquad,
    _poolBeastmasterAscension,
    _poolBlackMarketConnections,
    _poolBoonOfEmrakul,
    _poolBrawnAmadeusCho,
    _poolBronzeWalrus,
    _poolBurstOfSpeed,
    _poolCacklingFiend,
    _poolCarnivorousPlant,
    _poolChainReaction,
    _poolChandrasMagmutt,
    _poolChromaticLantern,
    _poolClavilenoFirstOfTheBlessed,
    _poolCommonBond,
    _poolConclaveTribunal,
    _poolConviction,
    _poolCouriersCapsule,
    _poolCravenGiant,
    _poolDaggerfangDuo,
    _poolDarkNourishment,
    _poolDeathgreeter,
    _poolDeduce,
    _poolDegaDisciple,
    _poolDesperateBloodseeker,
    _poolDranasChosen,
    _poolElvishDoomsayer,
    _poolEmmessiTome,
    _poolErase,
    _poolFalseSummoning,
    _poolFarewell,
    _poolFelidarRetreat,
    _poolFestivalCrasher,
    _poolFireLitThicket,
    _poolFleetingEffigy,
    _poolFrontierBivouac,
    _poolFrostwindInvoker,
    _poolGevScaledScorch,
    _poolGiganticBigBear,
    _poolGliderKids,
    _poolGloriousCharge,
    _poolGoblinSurprise,
    _poolGreaterTanuki,
    _poolGruesomeDeformity,
    _poolGruulTurf,
    _poolGutShot,
    _poolHappyHoganDauntlessDriver,
    _poolHardWonJitte,
    _poolHeadwaterSentries,
    _poolHellkitePunisher,
    _poolHengegatePathway,
    _poolHighPriestOfPenance,
    _poolHighlandForest,
    _poolHillcomberGiant,
    _poolHoneyMammoth,
    _poolImperialRecruiter,
    _poolIridescentBlademaster,
    _poolJasperaSentinel,
    _poolJetmirNexusOfRevels,
    _poolKeeperOfTheNineGales,
    _poolKiorasDambreaker,
    _poolKodamaOfTheNorthTree,
    _poolLibraryLarcenist,
    _poolLoomingShade,
    _poolLordOfChange,
    _poolLowlandGiant,
    _poolLoxodonConvert,
    _poolLoxodonSergeant,
    _poolLukeCageHeroForHire,
    _poolLysAlanaHuntmaster,
    _poolMarwynTheNurturer,
    _poolMerfolkSecretkeeper,
    _poolMesaEnchantress,
    _poolMessengerDrake,
    _poolMisguidedRage,
    _poolMonoistSentry,
    _poolMorphicPool,
    _poolMsBumbleflower,
    _poolMurmuringPhantasm,
    _poolMyrRetriever,
    _poolNagaEternal,
    _poolNoxiousRevival,
    _poolObeliskOfGrixis,
    _poolOrazcaRaptor,
    _poolOrzhovSignet,
    _poolParallelLives,
    _poolPathOfAngersFlame,
    _poolPheresBandCentaurs,
    _poolPhyrexianHulk,
    _poolPhyrexianWalker,
    _poolPotionOfHealing,
    _poolPromisingVein,
    _poolPyreHound,
    _poolRainOfRevelation,
    _poolRaiseTheAlarm,
    _poolRakshasaDebaser,
    _poolRathiTrapper,
    _poolRazortoothRats,
    _poolRedHerring,
    _poolRendmawCreakingNest,
    _poolRipchainRazorkin,
    _poolRustwingFalcon,
    _poolSceneOfTheCrime,
    _poolScrubland,
    _poolSeethingSong,
    _poolSelesnyaLocket,
    _poolSeparatistVoidmage,
    _poolShieldMate,
    _poolShinenOfFlightsWings,
    _poolSilentAttendant,
    _poolSkyRuinDrake,
    _poolSlinkingSerpent,
    _poolSpikedBaloth,
    _poolStampedingScurryfoot,
    _poolStandFirm,
    _poolStandingStones,
    _poolStoneDocent,
    _poolStormcallerOfKeranos,
    _poolStudentOfOjutai,
    _poolSubmergedBoneyard,
    _poolSunastianFalconer,
    _poolSwordOfFeastAndFamine,
    _poolSylvokReplica,
    _poolSymbioticBeast,
    _poolTanglebloom,
    _poolTanglepoolBridge,
    _poolTerrorOfTheFairgrounds,
    _poolThornwoodFalls,
    _poolThrivingGrove,
    _poolTomBombadil,
    _poolTorstenVonUrsus,
    _poolTortoiseFormation,
    _poolTrapmakersSnare,
    _poolTrueLovesKiss,
    _poolTundra,
    _poolTurbulentFen,
    _poolUndeadMinotaur,
    _poolUnholyStrength,
    _poolValorousSteed,
    _poolVesperGhoul,
    _poolVesselOfEphemera,
    _poolViridescentBog,
    _poolVoraciousNull,
    _poolWarrenSoultrader,
    _poolWaterElemental,
    _poolWaterloggedGrove,
    _poolWeightOfMemory,
    _poolWeldfastMonitor,
    _poolWillOfTheSultai,
  ],
  tokens: [
    _tokensPhyrexianGoblinToken,
  ],
};

export default shard;
