// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.
// Run `npm run gen:cards -w engine` after adding or removing a card file.

import type { CardShard } from "../card-shards.js";

import _poolAangAirNomad from "../pool/aang-air-nomad.js";
import _poolAbzanFalconer from "../pool/abzan-falconer.js";
import _poolAccursedDuneyard from "../pool/accursed-duneyard.js";
import _poolAkkiAvalanchers from "../pool/akki-avalanchers.js";
import _poolAkoumHellhound from "../pool/akoum-hellhound.js";
import _poolAlabasterKirin from "../pool/alabaster-kirin.js";
import _poolAnglerDrake from "../pool/angler-drake.js";
import _poolArgivianFind from "../pool/argivian-find.js";
import _poolAtsushiTheBlazingSky from "../pool/atsushi-the-blazing-sky.js";
import _poolAzimaetDrake from "../pool/azimaet-drake.js";
import _poolBayou from "../pool/bayou.js";
import _poolBenthicGiant from "../pool/benthic-giant.js";
import _poolBladeOfTheSixthPride from "../pool/blade-of-the-sixth-pride.js";
import _poolBlightstepPathway from "../pool/blightstep-pathway.js";
import _poolBloodMoney from "../pool/blood-money.js";
import _poolBloodtallowCandle from "../pool/bloodtallow-candle.js";
import _poolBoltwave from "../pool/boltwave.js";
import _poolBondBeetle from "../pool/bond-beetle.js";
import _poolBoneMiser from "../pool/bone-miser.js";
import _poolBrainWeevil from "../pool/brain-weevil.js";
import _poolBrenardGingerSculptor from "../pool/brenard-ginger-sculptor.js";
import _poolCanopyBaloth from "../pool/canopy-baloth.js";
import _poolCanyonSlough from "../pool/canyon-slough.js";
import _poolCapashenKnight from "../pool/capashen-knight.js";
import _poolCarrionScreecher from "../pool/carrion-screecher.js";
import _poolChandraAcolyteOfFlame from "../pool/chandra-acolyte-of-flame.js";
import _poolCliffsideLookout from "../pool/cliffside-lookout.js";
import _poolCompulsiveResearch from "../pool/compulsive-research.js";
import _poolConcentrate from "../pool/concentrate.js";
import _poolConcentratedFire from "../pool/concentrated-fire.js";
import _poolConjurersCloset from "../pool/conjurers-closet.js";
import _poolContingencyPlan from "../pool/contingency-plan.js";
import _poolCopperLonglegs from "../pool/copper-longlegs.js";
import _poolCropRotation from "../pool/crop-rotation.js";
import _poolCrowdFavorites from "../pool/crowd-favorites.js";
import _poolCrystalQuarry from "../pool/crystal-quarry.js";
import _poolCutthroatContender from "../pool/cutthroat-contender.js";
import _poolCybermenSquadron from "../pool/cybermen-squadron.js";
import _poolDemonicCounsel from "../pool/demonic-counsel.js";
import _poolDespark from "../pool/despark.js";
import _poolDivingGriffin from "../pool/diving-griffin.js";
import _poolDoranBesiegedByTime from "../pool/doran-besieged-by-time.js";
import _poolDragonmasterOutcast from "../pool/dragonmaster-outcast.js";
import _poolDreamstoneHedron from "../pool/dreamstone-hedron.js";
import _poolDromarsAttendant from "../pool/dromars-attendant.js";
import _poolDrownInShapelessness from "../pool/drown-in-shapelessness.js";
import _poolDryadOfTheIlysianGrove from "../pool/dryad-of-the-ilysian-grove.js";
import _poolDynamicSoar from "../pool/dynamic-soar.js";
import _poolEliminateTheCompetition from "../pool/eliminate-the-competition.js";
import _poolElvishMystic from "../pool/elvish-mystic.js";
import _poolErinisGloomStalker from "../pool/erinis-gloom-stalker.js";
import _poolExaltedSunborn from "../pool/exalted-sunborn.js";
import _poolExecutionersCapsule from "../pool/executioners-capsule.js";
import _poolEzuriClawOfProgress from "../pool/ezuri-claw-of-progress.js";
import _poolFatefulEnd from "../pool/fateful-end.js";
import _poolFelixFiveBoots from "../pool/felix-five-boots.js";
import _poolFetidImp from "../pool/fetid-imp.js";
import _poolFireAmbush from "../pool/fire-ambush.js";
import _poolFirebornKnight from "../pool/fireborn-knight.js";
import _poolFlameJet from "../pool/flame-jet.js";
import _poolFloodhound from "../pool/floodhound.js";
import _poolFlowstoneGiant from "../pool/flowstone-giant.js";
import _poolForebodingRuins from "../pool/foreboding-ruins.js";
import _poolForecastingFortuneTeller from "../pool/forecasting-fortune-teller.js";
import _poolFortressCrab from "../pool/fortress-crab.js";
import _poolFyndhornElder from "../pool/fyndhorn-elder.js";
import _poolGanaxAstralHunter from "../pool/ganax-astral-hunter.js";
import _poolGavonyTownship from "../pool/gavony-township.js";
import _poolGazeOfGranite from "../pool/gaze-of-granite.js";
import _poolGeyserGlider from "../pool/geyser-glider.js";
import _poolGhostLitNourisher from "../pool/ghost-lit-nourisher.js";
import _poolGiantOctopus from "../pool/giant-octopus.js";
import _poolGideonsReproach from "../pool/gideons-reproach.js";
import _poolGigantosaurus from "../pool/gigantosaurus.js";
import _poolGnottvoldRecluse from "../pool/gnottvold-recluse.js";
import _poolGoForTheThroat from "../pool/go-for-the-throat.js";
import _poolGoblinBrigand from "../pool/goblin-brigand.js";
import _poolGoblinSledder from "../pool/goblin-sledder.js";
import _poolGolgariCharm from "../pool/golgari-charm.js";
import _poolGolgariLonglegs from "../pool/golgari-longlegs.js";
import _poolGolgariRotFarm from "../pool/golgari-rot-farm.js";
import _poolGraniteGargoyle from "../pool/granite-gargoyle.js";
import _poolGrapplerSpider from "../pool/grappler-spider.js";
import _poolGratuitousViolence from "../pool/gratuitous-violence.js";
import _poolGrimoireOfTheDead from "../pool/grimoire-of-the-dead.js";
import _poolGruulGuildmage from "../pool/gruul-guildmage.js";
import _poolHamatoNinpo from "../pool/hamato-ninpo.js";
import _poolHavenOfTheSpiritDragon from "../pool/haven-of-the-spirit-dragon.js";
import _poolHealersFlock from "../pool/healers-flock.js";
import _poolHighlandWeald from "../pool/highland-weald.js";
import _poolHillGiant from "../pool/hill-giant.js";
import _poolHonor from "../pool/honor.js";
import _poolIrenicussVileDuplication from "../pool/irenicuss-vile-duplication.js";
import _poolIronMyr from "../pool/iron-myr.js";
import _poolIzzetCluestone from "../pool/izzet-cluestone.js";
import _poolJhovallQueen from "../pool/jhovall-queen.js";
import _poolJungleHollow from "../pool/jungle-hollow.js";
import _poolKetramoseTheNewDawn from "../pool/ketramose-the-new-dawn.js";
import _poolKetriaTriome from "../pool/ketria-triome.js";
import _poolKiloApogeeMind from "../pool/kilo-apogee-mind.js";
import _poolKitchen from "../pool/kitchen.js";
import _poolLanternKami from "../pool/lantern-kami.js";
import _poolLarderZombie from "../pool/larder-zombie.js";
import _poolLawlessBroker from "../pool/lawless-broker.js";
import _poolLazotepReaver from "../pool/lazotep-reaver.js";
import _poolLegionStronghold from "../pool/legion-stronghold.js";
import _poolLeoninWarleader from "../pool/leonin-warleader.js";
import _poolLierDiscipleOfTheDrowned from "../pool/lier-disciple-of-the-drowned.js";
import _poolLightningRigCrew from "../pool/lightning-rig-crew.js";
import _poolLoranOfTheThirdPath from "../pool/loran-of-the-third-path.js";
import _poolLoreholdPledgemage from "../pool/lorehold-pledgemage.js";
import _poolLothoCorruptShirriff from "../pool/lotho-corrupt-shirriff.js";
import _poolMaggotTherapy from "../pool/maggot-therapy.js";
import _poolMakeshiftMunitions from "../pool/makeshift-munitions.js";
import _poolMarshLurker from "../pool/marsh-lurker.js";
import _poolMeanderingRiver from "../pool/meandering-river.js";
import _poolMindbreakTrap from "../pool/mindbreak-trap.js";
import _poolMirrormade from "../pool/mirrormade.js";
import _poolMisshapenFiend from "../pool/misshapen-fiend.js";
import _poolMoaningSpirit from "../pool/moaning-spirit.js";
import _poolMortuaryMire from "../pool/mortuary-mire.js";
import _poolMothriderPatrol from "../pool/mothrider-patrol.js";
import _poolMuldrothaTheGravetide from "../pool/muldrotha-the-gravetide.js";
import _poolMysteriosPhantasm from "../pool/mysterios-phantasm.js";
import _poolNaturalEnd from "../pool/natural-end.js";
import _poolNearheathChaplain from "../pool/nearheath-chaplain.js";
import _poolNebelgastBeguiler from "../pool/nebelgast-beguiler.js";
import _poolNecropolisFiend from "../pool/necropolis-fiend.js";
import _poolNiblisOfTheUrn from "../pool/niblis-of-the-urn.js";
import _poolNimbusOfTheIsles from "../pool/nimbus-of-the-isles.js";
import _poolNourish from "../pool/nourish.js";
import _poolNoxiousGroodion from "../pool/noxious-groodion.js";
import _poolNyxFleeceRam from "../pool/nyx-fleece-ram.js";
import _poolObscuraInitiate from "../pool/obscura-initiate.js";
import _poolOrdinaryBear from "../pool/ordinary-bear.js";
import _poolPiranhaMarsh from "../pool/piranha-marsh.js";
import _poolRakdosTrumpeter from "../pool/rakdos-trumpeter.js";
import _poolRapaciousDragon from "../pool/rapacious-dragon.js";
import _poolRathsEdge from "../pool/raths-edge.js";
import _poolRayOfDistortion from "../pool/ray-of-distortion.js";
import _poolRazakethsRite from "../pool/razakeths-rite.js";
import _poolReapTheSeagraf from "../pool/reap-the-seagraf.js";
import _poolRescind from "../pool/rescind.js";
import _poolReunionOfTheHouse from "../pool/reunion-of-the-house.js";
import _poolSangromancer from "../pool/sangromancer.js";
import _poolSarkhansCatharsis from "../pool/sarkhans-catharsis.js";
import _poolSavageHunger from "../pool/savage-hunger.js";
import _poolScionOfUgin from "../pool/scion-of-ugin.js";
import _poolSealOfCleansing from "../pool/seal-of-cleansing.js";
import _poolSealOfPrimordium from "../pool/seal-of-primordium.js";
import _poolSeasideHaven from "../pool/seaside-haven.js";
import _poolSeedbornMuse from "../pool/seedborn-muse.js";
import _poolSelflessSpirit from "../pool/selfless-spirit.js";
import _poolSheoldredTheApocalypse from "../pool/sheoldred-the-apocalypse.js";
import _poolSilverbackApe from "../pool/silverback-ape.js";
import _poolSilvercoatLion from "../pool/silvercoat-lion.js";
import _poolSkateboard from "../pool/skateboard.js";
import _poolSkorpekhDestroyer from "../pool/skorpekh-destroyer.js";
import _poolSliverOverlord from "../pool/sliver-overlord.js";
import _poolSlumReaper from "../pool/slum-reaper.js";
import _poolSnakeBasket from "../pool/snake-basket.js";
import _poolSokenzanCrucibleOfDefiance from "../pool/sokenzan-crucible-of-defiance.js";
import _poolSoulGuideLantern from "../pool/soul-guide-lantern.js";
import _poolSoulWarden from "../pool/soul-warden.js";
import _poolSpellscornCoven from "../pool/spellscorn-coven.js";
import _poolSproutingGoblin from "../pool/sprouting-goblin.js";
import _poolStormriderSpirit from "../pool/stormrider-spirit.js";
import _poolStripedBears from "../pool/striped-bears.js";
import _poolSulfurousSprings from "../pool/sulfurous-springs.js";
import _poolSultaiBanner from "../pool/sultai-banner.js";
import _poolSupplyDrop from "../pool/supply-drop.js";
import _poolSwabGoblin from "../pool/swab-goblin.js";
import _poolSwamp from "../pool/swamp.js";
import _poolSymbioticElf from "../pool/symbiotic-elf.js";
import _poolTalismanOfCreativity from "../pool/talisman-of-creativity.js";
import _poolTangleSpider from "../pool/tangle-spider.js";
import _poolTenementCrasher from "../pool/tenement-crasher.js";
import _poolTenthDistrictGuard from "../pool/tenth-district-guard.js";
import _poolTerrainElemental from "../pool/terrain-elemental.js";
import _poolTerrasymbiosis from "../pool/terrasymbiosis.js";
import _poolTerritorialHammerskull from "../pool/territorial-hammerskull.js";
import _poolTheTerrorOfSerpentsPass from "../pool/the-terror-of-serpents-pass.js";
import _poolThinkTwice from "../pool/think-twice.js";
import _poolThornLieutenant from "../pool/thorn-lieutenant.js";
import _poolThunderwolfCavalry from "../pool/thunderwolf-cavalry.js";
import _poolTidepoolTurtle from "../pool/tidepool-turtle.js";
import _poolTreasonousOgre from "../pool/treasonous-ogre.js";
import _poolTreasureCruise from "../pool/treasure-cruise.js";
import _poolTundraWolves from "../pool/tundra-wolves.js";
import _poolTymorasInvoker from "../pool/tymoras-invoker.js";
import _poolUnmarkedGrave from "../pool/unmarked-grave.js";
import _poolVampireSoulcaller from "../pool/vampire-soulcaller.js";
import _poolViashinoGrappler from "../pool/viashino-grappler.js";
import _poolViashivanDragon from "../pool/viashivan-dragon.js";
import _poolVileEntomber from "../pool/vile-entomber.js";
import _poolVinelasherKudzu from "../pool/vinelasher-kudzu.js";
import _poolVolcanoImp from "../pool/volcano-imp.js";
import _poolVolrathsGardens from "../pool/volraths-gardens.js";
import _poolWardenOfTheEye from "../pool/warden-of-the-eye.js";
import _poolWeatherseedElf from "../pool/weatherseed-elf.js";
import _poolWorthyKnight from "../pool/worthy-knight.js";
import _poolWurmcoilEngine from "../pool/wurmcoil-engine.js";
import _poolYoungPyromancer from "../pool/young-pyromancer.js";
import _poolZuranSpellcaster from "../pool/zuran-spellcaster.js";
import _tokensDragonToken55 from "../tokens/dragon-token-5-5.js";
import _tokensGoatToken from "../tokens/goat-token.js";
import _tokensGoblinToken from "../tokens/goblin-token.js";
import _tokensHumanClericToken from "../tokens/human-cleric-token.js";
import _tokensMonkToken from "../tokens/monk-token.js";
import _tokensRedWarriorToken from "../tokens/red-warrior-token.js";
import _tokensSlugToken from "../tokens/slug-token.js";
import _tokensSpiritTokenHeiBai from "../tokens/spirit-token-hei-bai.js";
import _tokensSquirrelToken from "../tokens/squirrel-token.js";

const shard: CardShard = {
  pool: [
    _poolAangAirNomad,
    _poolAbzanFalconer,
    _poolAccursedDuneyard,
    _poolAkkiAvalanchers,
    _poolAkoumHellhound,
    _poolAlabasterKirin,
    _poolAnglerDrake,
    _poolArgivianFind,
    _poolAtsushiTheBlazingSky,
    _poolAzimaetDrake,
    _poolBayou,
    _poolBenthicGiant,
    _poolBladeOfTheSixthPride,
    _poolBlightstepPathway,
    _poolBloodMoney,
    _poolBloodtallowCandle,
    _poolBoltwave,
    _poolBondBeetle,
    _poolBoneMiser,
    _poolBrainWeevil,
    _poolBrenardGingerSculptor,
    _poolCanopyBaloth,
    _poolCanyonSlough,
    _poolCapashenKnight,
    _poolCarrionScreecher,
    _poolChandraAcolyteOfFlame,
    _poolCliffsideLookout,
    _poolCompulsiveResearch,
    _poolConcentrate,
    _poolConcentratedFire,
    _poolConjurersCloset,
    _poolContingencyPlan,
    _poolCopperLonglegs,
    _poolCropRotation,
    _poolCrowdFavorites,
    _poolCrystalQuarry,
    _poolCutthroatContender,
    _poolCybermenSquadron,
    _poolDemonicCounsel,
    _poolDespark,
    _poolDivingGriffin,
    _poolDoranBesiegedByTime,
    _poolDragonmasterOutcast,
    _poolDreamstoneHedron,
    _poolDromarsAttendant,
    _poolDrownInShapelessness,
    _poolDryadOfTheIlysianGrove,
    _poolDynamicSoar,
    _poolEliminateTheCompetition,
    _poolElvishMystic,
    _poolErinisGloomStalker,
    _poolExaltedSunborn,
    _poolExecutionersCapsule,
    _poolEzuriClawOfProgress,
    _poolFatefulEnd,
    _poolFelixFiveBoots,
    _poolFetidImp,
    _poolFireAmbush,
    _poolFirebornKnight,
    _poolFlameJet,
    _poolFloodhound,
    _poolFlowstoneGiant,
    _poolForebodingRuins,
    _poolForecastingFortuneTeller,
    _poolFortressCrab,
    _poolFyndhornElder,
    _poolGanaxAstralHunter,
    _poolGavonyTownship,
    _poolGazeOfGranite,
    _poolGeyserGlider,
    _poolGhostLitNourisher,
    _poolGiantOctopus,
    _poolGideonsReproach,
    _poolGigantosaurus,
    _poolGnottvoldRecluse,
    _poolGoForTheThroat,
    _poolGoblinBrigand,
    _poolGoblinSledder,
    _poolGolgariCharm,
    _poolGolgariLonglegs,
    _poolGolgariRotFarm,
    _poolGraniteGargoyle,
    _poolGrapplerSpider,
    _poolGratuitousViolence,
    _poolGrimoireOfTheDead,
    _poolGruulGuildmage,
    _poolHamatoNinpo,
    _poolHavenOfTheSpiritDragon,
    _poolHealersFlock,
    _poolHighlandWeald,
    _poolHillGiant,
    _poolHonor,
    _poolIrenicussVileDuplication,
    _poolIronMyr,
    _poolIzzetCluestone,
    _poolJhovallQueen,
    _poolJungleHollow,
    _poolKetramoseTheNewDawn,
    _poolKetriaTriome,
    _poolKiloApogeeMind,
    _poolKitchen,
    _poolLanternKami,
    _poolLarderZombie,
    _poolLawlessBroker,
    _poolLazotepReaver,
    _poolLegionStronghold,
    _poolLeoninWarleader,
    _poolLierDiscipleOfTheDrowned,
    _poolLightningRigCrew,
    _poolLoranOfTheThirdPath,
    _poolLoreholdPledgemage,
    _poolLothoCorruptShirriff,
    _poolMaggotTherapy,
    _poolMakeshiftMunitions,
    _poolMarshLurker,
    _poolMeanderingRiver,
    _poolMindbreakTrap,
    _poolMirrormade,
    _poolMisshapenFiend,
    _poolMoaningSpirit,
    _poolMortuaryMire,
    _poolMothriderPatrol,
    _poolMuldrothaTheGravetide,
    _poolMysteriosPhantasm,
    _poolNaturalEnd,
    _poolNearheathChaplain,
    _poolNebelgastBeguiler,
    _poolNecropolisFiend,
    _poolNiblisOfTheUrn,
    _poolNimbusOfTheIsles,
    _poolNourish,
    _poolNoxiousGroodion,
    _poolNyxFleeceRam,
    _poolObscuraInitiate,
    _poolOrdinaryBear,
    _poolPiranhaMarsh,
    _poolRakdosTrumpeter,
    _poolRapaciousDragon,
    _poolRathsEdge,
    _poolRayOfDistortion,
    _poolRazakethsRite,
    _poolReapTheSeagraf,
    _poolRescind,
    _poolReunionOfTheHouse,
    _poolSangromancer,
    _poolSarkhansCatharsis,
    _poolSavageHunger,
    _poolScionOfUgin,
    _poolSealOfCleansing,
    _poolSealOfPrimordium,
    _poolSeasideHaven,
    _poolSeedbornMuse,
    _poolSelflessSpirit,
    _poolSheoldredTheApocalypse,
    _poolSilverbackApe,
    _poolSilvercoatLion,
    _poolSkateboard,
    _poolSkorpekhDestroyer,
    _poolSliverOverlord,
    _poolSlumReaper,
    _poolSnakeBasket,
    _poolSokenzanCrucibleOfDefiance,
    _poolSoulGuideLantern,
    _poolSoulWarden,
    _poolSpellscornCoven,
    _poolSproutingGoblin,
    _poolStormriderSpirit,
    _poolStripedBears,
    _poolSulfurousSprings,
    _poolSultaiBanner,
    _poolSupplyDrop,
    _poolSwabGoblin,
    _poolSwamp,
    _poolSymbioticElf,
    _poolTalismanOfCreativity,
    _poolTangleSpider,
    _poolTenementCrasher,
    _poolTenthDistrictGuard,
    _poolTerrainElemental,
    _poolTerrasymbiosis,
    _poolTerritorialHammerskull,
    _poolTheTerrorOfSerpentsPass,
    _poolThinkTwice,
    _poolThornLieutenant,
    _poolThunderwolfCavalry,
    _poolTidepoolTurtle,
    _poolTreasonousOgre,
    _poolTreasureCruise,
    _poolTundraWolves,
    _poolTymorasInvoker,
    _poolUnmarkedGrave,
    _poolVampireSoulcaller,
    _poolViashinoGrappler,
    _poolViashivanDragon,
    _poolVileEntomber,
    _poolVinelasherKudzu,
    _poolVolcanoImp,
    _poolVolrathsGardens,
    _poolWardenOfTheEye,
    _poolWeatherseedElf,
    _poolWorthyKnight,
    _poolWurmcoilEngine,
    _poolYoungPyromancer,
    _poolZuranSpellcaster,
  ],
  tokens: [
    _tokensDragonToken55,
    _tokensGoatToken,
    _tokensGoblinToken,
    _tokensHumanClericToken,
    _tokensMonkToken,
    _tokensRedWarriorToken,
    _tokensSlugToken,
    _tokensSpiritTokenHeiBai,
    _tokensSquirrelToken,
  ],
};

export default shard;
