import { defineCard } from "../define.js";

// EDHREC rank 5608.
//
// Rulings:
//   [2023-09-01] You don't have to spend the two mana on the same spell.
//   [2023-09-01] You can spend mana generated by Troyan on any part of the cost of a spell that
//     contains {X} in its mana cost. You're not limited to spending it only on the {X} part.

export default defineCard({
  name: "Troyan, Gutsy Explorer",
  manaCost: "{1}{G}{U}",
  colors: ["U", "G"],
  supertypes: ["legendary"],
  types: ["creature"],
  subtypes: ["Vedalken", "Scout"],
  power: 1,
  toughness: 3,
  text: "{T}: Add {G}{U}. Spend this mana only to cast spells with mana value 5 or greater or spells with {X} in their mana costs.\n{U}, {T}: Draw a card, then discard a card.",
  activated: [
    {
      cost: { mana: null, tap: true },
      targets: [],
      // Helga, Skittish Seer's restriction, over any spell: a spell's mana
      // value on the stack counts its chosen X (rule 202.3e).
      effect: {
        kind: "add-mana",
        mana: { all: ["G", "U"] },
        amount: 1,
        spendOnly: {
          spell: { anyOf: [{ manaValue: { op: "gte", n: 5 } }, { xInManaCost: true }] },
          text: "Spend this mana only to cast spells with mana value 5 or greater or spells with {X} in their mana costs.",
        },
      },
      resolve: null,
      text: "{T}: Add {G}{U}. Spend this mana only to cast spells with mana value 5 or greater or spells with {X} in their mana costs.",
    },
    {
      cost: { mana: "{U}", tap: true },
      targets: [],
      effect: {
        kind: "sequence",
        effects: [{ kind: "draw", amount: 1 }, { kind: "discard", target: "you", amount: 1 }],
      },
      resolve: null,
      text: "{U}, {T}: Draw a card, then discard a card.",
    },
  ],
});
