// Write src/ui/keywordIconPaths.ts: each keyword icon's outline from the Mana
// font's SVG version (node_modules/mana-font/fonts/mana.svg), with the centre
// of its ink, so `KeywordIcon` can draw it as an inline SVG centred exactly
// in its circle.
//
//   node client/scripts/keyword-icons.mjs
//
// Drawn as text, a 13px keyword circle put its glyph up to a pixel and a half
// off centre, differently at each size, because a browser rounds small
// text's baseline to the pixel; an SVG path is placed by geometry and stays
// centred at any size. The ink's bounds are measured by a real browser,
// off the pixels each outline paints (see below). Which glyph
// each keyword is comes from `src/ui/abilityIcons.ts`'s KEYWORD_GLYPH, so
// re-run this when that table changes or mana-font is upgraded.

import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const require = createRequire(join(HERE, '..', 'package.json'))
const { chromium } = require('playwright')

const ICONS = join(HERE, '..', 'src', 'ui', 'abilityIcons.ts')
const FONT = require.resolve('mana-font/fonts/mana.svg')
const OUT = join(HERE, '..', 'src', 'ui', 'keywordIconPaths.ts')

// keyword -> glyph, off the table the board uses.
const icons = readFileSync(ICONS, 'utf8')
const start = icons.indexOf('export const KEYWORD_GLYPH')
const table = icons.slice(start, icons.indexOf('\n}\n', start))
const glyphs = [...table.matchAll(/^\s*'?([a-z-]+)'?:\s*'(.)',/gmu)].map(([, keyword, glyph]) => ({
  keyword,
  code: glyph.codePointAt(0),
}))

// glyph code point -> outline. One decimal place of a 1024-unit em is far
// below a pixel at any size an icon is drawn, and halves the data.
const font = readFileSync(FONT, 'utf8')
// A rounded number keeps its separators: SVG runs numbers together, with a
// minus sign or a second decimal point as the only break ("5.2-0.04" is two
// numbers, "1.0.5" too). So a negative that rounds to 0, which prints as "0",
// gets a space before it where its sign was, and a number that loses its
// decimal point ("1.0" to "1") gets one after it if a ".5" or a digit follows.
const round = (d) =>
  d.replace(/-?\d*\.\d+/g, (n, at, all) => {
    let r = String(Math.round(Number(n) * 10) / 10)
    if (n.startsWith('-') && !r.startsWith('-')) r = ` ${r}`
    return /[.\d]/.test(all[at + n.length] ?? '') ? `${r} ` : r
  })
for (const g of glyphs) {
  const tag = font.match(new RegExp(`<glyph[^>]*unicode="&#x${g.code.toString(16)};"[^>]*/>`, 'i'))
  const d = tag?.[0].match(/ d="([^"]*)"/)?.[1]
  if (d === undefined) throw new Error(`mana.svg has no outline for ${g.keyword} (U+${g.code.toString(16)})`)
  g.d = round(d)
}

const browser = await chromium.launch()
const page = await browser.newPage()
// The bounds of what each outline actually paints: filled onto a canvas a
// font unit to the pixel and read back, rather than `getBBox`, which counts
// a counter-shape or a cancelled-out piece that paints nothing (deathtouch,
// haste, islandwalk and riot came out up to a pixel off by it).
const boxes = await page.evaluate(
  (paths) =>
    paths.map((d) => {
      const pad = 128
      const canvas = document.createElement('canvas')
      canvas.width = 1024 + 2 * pad
      canvas.height = 1024 + 2 * pad
      const ctx = canvas.getContext('2d', { willReadFrequently: true })
      // Font units, y up, the em box at (pad, pad): row r is y = 1024 + pad - r.
      ctx.setTransform(1, 0, 0, -1, pad, 1024 + pad - 64)
      ctx.fill(new Path2D(d))
      const { data, width, height } = ctx.getImageData(0, 0, canvas.width, canvas.height)
      let x0 = width, x1 = -1, y0 = height, y1 = -1
      for (let y = 0; y < height; y += 1) {
        for (let x = 0; x < width; x += 1) {
          if (data[(y * width + x) * 4 + 3] >= 128) {
            if (x < x0) x0 = x
            if (x > x1) x1 = x
            if (y < y0) y0 = y
            if (y > y1) y1 = y
          }
        }
      }
      // Back to font units: x = col - pad, y = (1024 + pad - 64) - row.
      return { x: x0 - pad, y: 1024 + pad - 64 - (y1 + 1), width: x1 + 1 - x0, height: y1 + 1 - y0 }
    }),
  glyphs.map((g) => g.d),
)
await browser.close()

const entries = glyphs.map((g, i) => {
  const b = boxes[i]
  // The font's y axis points up; KeywordIcon flips it, so the ink centre it
  // needs is (cx, -cy).
  const cx = Math.round((b.x + b.width / 2) * 10) / 10
  const cy = Math.round((b.y + b.height / 2) * 10) / 10
  return `  ${/^[a-z]+$/.test(g.keyword) ? g.keyword : `'${g.keyword}'`}: { cx: ${cx}, cy: ${cy}, d: '${g.d}' },`
})

writeFileSync(
  OUT,
  `// Generated by scripts/keyword-icons.mjs from mana-font's mana.svg — don't edit by hand.
import type { Keyword } from 'engine/client'

/** Each keyword icon's outline in the Mana font's units (1024 to the em, y
 * up), and the centre of its ink, for \`KeywordIcon\`. A \`Record\` over the
 * engine's \`Keyword\` union, as \`KEYWORD_GLYPH\` is. */
export const KEYWORD_ICON: Record<Keyword, { readonly cx: number; readonly cy: number; readonly d: string }> = {
${entries.join('\n')}
}
`,
)
console.log(`wrote ${glyphs.length} keyword icons to ${OUT}`)
