/**
 * Regenerates `src/cards/generated.ts` — the barrel that imports every card
 * file under `src/cards/pool/` and `src/cards/tokens/` and collects their
 * default exports into `BUILTIN_CARDS`.
 *
 * The two directories are also kept as their own exports (`POOL_CARDS` /
 * `TOKEN_CARDS`), because the directory is the only place that knows a
 * definition is a *token* rather than a card — nothing on `CardDefinition`
 * records it, and the old "the name contains 'Token'" guess was never
 * something a real card name couldn't trip. `cards/classify.ts` reads them.
 *
 * Run via `npm run gen:cards -w engine` (also wired as a `prebuild` step so a
 * fresh checkout always has an up-to-date `generated.ts`). The file is checked
 * in so `tsc`, tests, and the demo scripts work without a generate step.
 *
 * Deliberately dumb: one file = one card = one default export. A card's own
 * `.name` is the registry key; the filename only needs to be unique.
 */

import { readdirSync, writeFileSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const CARDS_DIR = fileURLToPath(new URL("../src/cards/", import.meta.url));
const OUT_FILE = path.join(CARDS_DIR, "generated.ts");
const SUBDIRS = ["pool", "tokens"];

/** `lightning-bolt` -> `_lightningBolt` (leading `_` dodges keywords / digits).
 * Any character that isn't a letter or digit (a comma, apostrophe, space in a
 * filename) is dropped after the `-`-to-camelCase pass, so a stray one can't
 * produce a broken identifier. The `.name` field, not the filename, is the
 * registry key — so this only needs to be unique, which `collect()` checks. */
function identifier(basename) {
  const camel = basename.replace(/[-_\s]+([a-z0-9])/gi, (_, c) => c.toUpperCase());
  return `_${camel.replace(/[^A-Za-z0-9]/g, "")}`;
}

function collect() {
  const bySub = new Map(SUBDIRS.map((sub) => [sub, []]));
  for (const sub of SUBDIRS) {
    const dir = path.join(CARDS_DIR, sub);
    const files = readdirSync(dir)
      .filter((f) => f.endsWith(".ts") && !f.endsWith(".test.ts"))
      .sort();
    for (const file of files) {
      const base = file.slice(0, -3);
      bySub.get(sub).push({ id: identifier(`${sub}-${base}`), spec: `./${sub}/${base}.js` });
    }
  }
  return bySub;
}

function render(bySub) {
  const all = SUBDIRS.flatMap((sub) => bySub.get(sub));
  const imports = all.map((e) => `import ${e.id} from "${e.spec}";`).join("\n");
  const list = (entries) => entries.map((e) => `  ${e.id},`).join("\n");
  return (
    "// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.\n" +
    "// Run `npm run gen:cards -w engine` after adding or removing a card file.\n\n" +
    'import type { CardDefinition } from "./define.js";\n\n' +
    `${imports}\n\n` +
    "/** Real Magic cards — every file under `pool/`. */\n" +
    `export const POOL_CARDS: readonly CardDefinition[] = [\n${list(bySub.get("pool"))}\n];\n\n` +
    "/** Token definitions — every file under `tokens/`. Registered like any\n" +
    " * other card (a `create-token` effect names one), but not a card: never\n" +
    " * deck-legal, and hidden from the card library by default. */\n" +
    `export const TOKEN_CARDS: readonly CardDefinition[] = [\n${list(bySub.get("tokens"))}\n];\n\n` +
    "/** The built-in card pool — every file under `pool/` and `tokens/`. */\n" +
    "export const BUILTIN_CARDS: readonly CardDefinition[] = [...POOL_CARDS, ...TOKEN_CARDS];\n"
  );
}

const collected = collect();
const count = SUBDIRS.reduce((n, sub) => n + collected.get(sub).length, 0);
const source = render(collected);
const existing = (() => {
  try {
    return readFileSync(OUT_FILE, "utf8");
  } catch {
    return null;
  }
})();

if (existing === source) {
  console.log(`cards/generated.ts already up to date (${count} cards)`);
} else {
  writeFileSync(OUT_FILE, source, "utf8");
  console.log(`wrote cards/generated.ts (${count} cards)`);
}
