/**
 * Regenerates `src/cards/generated.ts` — the barrel that imports every card
 * file under `src/cards/pool/` and `src/cards/tokens/` and collects their
 * default exports into `BUILTIN_CARDS`.
 *
 * Run via `npm run gen:cards -w engine` (also wired as a `prebuild` step so a
 * fresh checkout always has an up-to-date `generated.ts`). The file is checked
 * in so `tsc`, tests, and the demo scripts work without a generate step.
 *
 * Deliberately dumb: one file = one card = one default export. A card's own
 * `.name` is the registry key; the filename only needs to be unique.
 */

import { readdirSync, writeFileSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const CARDS_DIR = fileURLToPath(new URL("../src/cards/", import.meta.url));
const OUT_FILE = path.join(CARDS_DIR, "generated.ts");
const SUBDIRS = ["pool", "tokens"];

/** `lightning-bolt` -> `_lightningBolt` (leading `_` dodges keywords / digits).
 * Any character that isn't a letter or digit (a comma, apostrophe, space in a
 * filename) is dropped after the `-`-to-camelCase pass, so a stray one can't
 * produce a broken identifier. The `.name` field, not the filename, is the
 * registry key — so this only needs to be unique, which `collect()` checks. */
function identifier(basename) {
  const camel = basename.replace(/[-_\s]+([a-z0-9])/gi, (_, c) => c.toUpperCase());
  return `_${camel.replace(/[^A-Za-z0-9]/g, "")}`;
}

function collect() {
  const entries = [];
  for (const sub of SUBDIRS) {
    const dir = path.join(CARDS_DIR, sub);
    const files = readdirSync(dir)
      .filter((f) => f.endsWith(".ts") && !f.endsWith(".test.ts"))
      .sort();
    for (const file of files) {
      const base = file.slice(0, -3);
      entries.push({ id: identifier(`${sub}-${base}`), spec: `./${sub}/${base}.js` });
    }
  }
  return entries;
}

function render(entries) {
  const imports = entries.map((e) => `import ${e.id} from "${e.spec}";`).join("\n");
  const list = entries.map((e) => `  ${e.id},`).join("\n");
  return (
    "// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.\n" +
    "// Run `npm run gen:cards -w engine` after adding or removing a card file.\n\n" +
    'import type { CardDefinition } from "./define.js";\n\n' +
    `${imports}\n\n` +
    "/** The built-in card pool — every file under `pool/` and `tokens/`. */\n" +
    `export const BUILTIN_CARDS: readonly CardDefinition[] = [\n${list}\n];\n`
  );
}

const source = render(collect());
const existing = (() => {
  try {
    return readFileSync(OUT_FILE, "utf8");
  } catch {
    return null;
  }
})();

if (existing === source) {
  console.log(`cards/generated.ts already up to date (${collect().length} cards)`);
} else {
  writeFileSync(OUT_FILE, source, "utf8");
  console.log(`wrote cards/generated.ts (${collect().length} cards)`);
}
