/**
 * The alternate names cards are printed under (Scryfall's `flavor_name` —
 * Final Fantasy's "Princess Sarah" for Azusa, Lost but Seeking), each mapped
 * to the card's name in the pool. **Generated** — run
 * `npm run gen:flavor-names -w engine`; do not edit by hand.
 *
 * A flavor name is printed in place of the card's name and nothing else
 * changes: it's the same card (rule 201.2, the Oracle name is the card's
 * name). So a decklist or a search that uses one means the card.
 */

export const FLAVOR_NAMES: Readonly<Record<string, string>> = {
  "'Tis But a Scratch!": "Dismember",
  "A Promise Fulfilled": "Light Up the Stage",
  "Aang's Shelter": "Teferi's Protection",
  "Aang, Ascendant Airbender": "Serra Ascendant",
  "Abraham Van Helsing": "Savior of Ollenbock",
  "Absolutely Accurate Actor": "Phantasmal Image",
  "Absorb into Time": "Temporal Extortion",
  "Abundant Groot": "Abundant Growth",
  "Adamantium Bonding Tank": "The Ozolith",
  "Aerith's Curaga Magic": "Heroic Intervention",
  "African Swallow": "Birds of Paradise",
  "Aggro Amalgam": "Voracious Hydra",
  "Air Shoes": "Swiftfoot Boots",
  "All-Seeing Toby": "Sovereign Okinec Ahau",
  "Altaïr, Brotherhood Mentor": "Kelsien, the Plague",
  "Amunet, Tyrants' End": "Queen Marchesa",
  "Anguirus, Armored Killer": "Gemrazer",
  "Anima": "Grief",
  "Answer the Call": "Eladamri's Call",
  "Archaeon the Everchosen": "Najeela, the Blade-Blossom",
  "Archangel of Tunes": "Archangel of Thune",
  "Ardyn Izunia": "Varragoth, Bloodsky Sire",
  "Argonath, Pillars of the Kings": "The Ozolith",
  "Armiger Unleashed": "Forge Anew",
  "Ash, Destined Survivor": "Puresteel Paladin",
  "Assaultron Invader": "Walking Ballista",
  "Astral Titan": "Primeval Titan",
  "Atsu, Ghost of Yōtei": "Tetsuko Umezawa, Fugitive",
  "Avatar Sanctuary": "Cryptolith Rite",
  "Avengers Monitoring Station": "Herald's Horn",
  "Awesome Android": "Containment Construct",
  "Azula, Flame of Ember Island": "Diaochan, Artful Beauty",
  "Babygodzilla, Ruin Reborn": "Pollywog Symbiote",
  "Backstage Monitor": "Tigereye Cameo",
  "Bag End": "Horizon Canopy",
  "Balamb Garden": "Command Beacon",
  "Balin's Tomb": "Ancient Tomb",
  "Barnabas Tharmr": "Kraum, Ludevic's Opus",
  "Baron Rivalry": "Deadly Dispute",
  "Barrow-Downs": "Bojuka Bog",
  "Bartz Klauser": "Winota, Joiner of Forces",
  "Basim, Master Assassin": "Ramses, Assassin Lord",
  "Bast's Blessing": "Primal Vigor",
  "Battle Bus": "Smuggler's Copter",
  "Battle Cat, Fighting Tiger": "Fortune, Loyal Steed",
  "Battle Royale": "Triumph of the Hordes",
  "Battle at the Big Bridge": "Fatal Push",
  "Battle of Olympus": "World at War",
  "Battra, Dark Destroyer": "Dirge Bat",
  "Beast Man, Savage Henchman": "Kona, Rescue Beastie",
  "Beholder's Charm Ray": "Bribery",
  "Beholder's Death Ray": "Snuff Out",
  "Beholder's Disintegration Ray": "Fire Covenant",
  "Beholder's Enervation Ray": "Defile",
  "Beholder's Fear Ray": "Drown in the Loch",
  "Beholder's Paralyzing Ray": "Oubliette",
  "Beholder's Petrification Ray": "Blood Money",
  "Beholder's Sleep Ray": "Stifle",
  "Beholder's Slowing Ray": "Delay",
  "Beholder's Telekinetic Ray": "Fling",
  "Benedikta Harman": "Ishai, Ojutai Dragonspeaker",
  "Benny, Platinum Thief": "Tinybones, Trinket Thief",
  "Bherna Huntmaster": "Imperial Recruiter",
  "Bhujerba, Floating City": "City of Brass",
  "Big Slime": "Mitotic Slime",
  "Bio-Quartz Spacegodzilla": "Brokkos, Apex of Forever",
  "Biollante, Plant Beast Form": "Nethroi, Apex of Death",
  "Black Panther's Claws": "Hammer of Nazahn",
  "Black Panther's Redirection": "Narset's Reversal",
  "Blessing of the Oracle": "Akroma's Will",
  "Bloodbender's Rise": "Bloodchief Ascension",
  "Bone Throne": "Throne of the God-Pharaoh",
  "Boogie Bomb": "Pyrite Spellbomb",
  "Both Down": "Bone Splinters",
  "Bow, Master Archer": "Hajar, Loyal Bodyguard",
  "Brachiosaurus": "Colossal Dreadmaw",
  "Brachydios, Brutish Indigo": "Kalamax, the Stormsire",
  "Bridge of Khazad-dûm": "Ensnaring Bridge",
  "Bring Out Your Dead!": "Buried Alive",
  "Bucklebury Ferry": "Oboro, Palace in the Clouds",
  "Buttercup, Provincial Princess": "Sisay, Weatherlight Captain",
  "Cabin of the Dead": "Field of the Dead",
  "Call Out the Goblins!": "Boggart Shenanigans",
  "Calliope's Song": "Seething Song",
  "Captain America's Aid": "Sigarda's Aid",
  "Caras Galadhon": "Tranquil Thicket",
  "Cascade of Song": "Halo Fountain",
  "Casket of Native Earth": "Edgar, Charmed Groom",
  "Cast-Off Consort": "Bloodletter of Aclazotz",
  "Castle Dracula": "Voldaren Estate",
  "Castle Ravenloft": "Voldaren Estate",
  "Castle Shimura": "Eiganjo Castle",
  "Castle of Aaargh": "Dark Depths",
  "Catra, Force Captain": "Kutzil, Malamet Exemplar",
  "Cecil Harvey": "Tymna the Weaver",
  "Centurion of the Marked": "Lord of the Undead",
  "Champion of Kotoko": "Champion of Lambholt",
  "Chancla relámpago": "Lightning Greaves",
  "Chaos Emerald": "Lotus Petal",
  "Chaos Theory": "Chaos Warp",
  "Chaotic Chaotician": "Laboratory Maniac",
  "Chucky": "Kardur, Doomscourge",
  "Clive Rosfield": "Vial Smasher the Fierce",
  "Clive's Invictus Blade": "Blade of Selves",
  "Cloud Strife": "Najeela, the Blade-Blossom",
  "Cloud's Buster Sword": "Umezawa's Jitte",
  "Colonel John Jameson": "Huntmaster of the Fells",
  "Community Center": "Fountainport",
  "Cordyceps Excision": "Cabal Ritual",
  "Cordyceps Rat King": "Mycoloth",
  "Count Dracula": "Sorin the Mirthless",
  "Cow-tapult": "Goblin Bombardment",
  "Cozy Headphones": "Paradise Mantle",
  "Crack the Vault": "Grim Tutor",
  "Crimson Moonlight": "Blind Obedience",
  "Croft Manor": "Command Tower",
  "Crystal of Altar Cave": "Chromatic Lantern",
  "Custom Caravan Deck": "The Deck of Many Things",
  "Cybertron": "Command Tower",
  "Da Vulcha": "Skysovereign, Consul Flagship",
  "Dance Battle": "Dance of Many",
  "Dance with Goblins": "Dance with Calamity",
  "Darkness of Eternity": "Dark Ritual",
  "Dawn Warriors' Legacy": "Mizzix's Mastery",
  "Denting Blows": "Krosan Grip",
  "Destoroyah, Perfect Lifeform": "Everquill Phoenix",
  "Destroy the Dead": "Vanquish the Horde",
  "Diabolos, Guardian Force": "Death's Shadow",
  "Doc Ock, Armed and Dangerous": "Lorthos, the Tidemaker",
  "Dogmeat, Constant Companion": "Yoshimaru, Ever Faithful",
  "Dol Amroth": "Minamo, School at Water's Edge",
  "Donnie's Bō": "Shadowspear",
  "Doom Variant": "Roaming Throne",
  "Doors of Indecision": "Thran Temporal Gateway",
  "Dorat, the Perfect Pet": "Sprite Dragon",
  "Dr. Ian Malcolm": "Atla Palani, Nest Tender",
  "Dr. John Seward": "Torens, Fist of the Angels",
  "Dracula the Voyager": "Edgar, Charmed Groom",
  "Dracula's Tomb": "Phyrexian Tower",
  "Dracula, Blood Immortal": "Falkenrath Forebear",
  "Dracula, Lord of Bats": "Voldaren Bloodcaster",
  "Dracula, Lord of Blood": "Voldaren Bloodcaster",
  "Dragon of Mount Gulg": "Ancient Copper Dragon",
  "Dual-Bladed Hunter": "Grand Abolisher",
  "Dwight Schrute, Hay King": "Heliod, Sun-Crowned",
  "Dwight o' Lantern": "Reaper King",
  "Dwight's Weapon Stash": "Steelshaper's Gift",
  "Dwight, Assistant (to the) King": "Baral, Chief of Compliance",
  "Earth Rumble Triumph": "Return of the Wildspeaker",
  "Earth's Mightiest Emblem": "Arcane Signet",
  "Ecto-1": "Unlicensed Hearse",
  "Eddie the Judge": "Bruvac the Grandiloquent",
  "Eddie, Ghost of the Navigator": "Captain N'ghathrod",
  "Eddie, Lord of Light": "Nekusar, the Mindrazer",
  "Edea Kramer": "Teferi, Mage of Zhalfir",
  "Edoras, Capital of Rohan": "Hammerheim",
  "Edward, Jackdaw Captain": "Admiral Beckett Brass",
  "Egg Hammer": "Myr Battlesphere",
  "Eivor, Raven Clan Champion": "Najeela, the Blade-Blossom",
  "El Dorado Sarcophagus": "Whip of Erebos",
  "Elektra, Deadly Assassin": "Massacre Girl",
  "Elessar, the Elfstone": "Cloudstone Curio",
  "Ellie's Rage": "Dictate of Erebos",
  "Emet-Selch, Ascian": "K'rrik, Son of Yawgmoth",
  "Encore Electromancer": "Snapcaster Mage",
  "Endwalker": "Brainstorm",
  "Erebor Heirloom": "Fellwar Stone",
  "Escape Containment": "Incarnation Technique",
  "European Swallow": "Birds of Paradise",
  "Evil Warriors' Shroud": "Necrogen Mists",
  "Evil-Lyn, Evil Warrior Goddess": "Ertai Resurrected",
  "FAS-BOR7 Horus": "Blightsteel Colossus",
  "Fal'Cie Paradise": "Carpet of Flowers",
  "Fangorn Forest": "Yavimaya, Cradle of Growth",
  "Fatalis, the Black Dragon": "Ziatora, the Incinerator",
  "Feral Felix": "Barrowgoyf",
  "Fezzik, Rhyming Giant": "Brion Stoutarm",
  "Fiends of Darkest Night": "Henrika Domnathi",
  "Fire Nation Tank Train": "Noxious Gearhulk",
  "Firion, Swordmaster": "Sram, Senior Edificer",
  "Fog Crawler": "Vigor",
  "Franklin's Finality": "Annie Joins Up",
  "Frenzy of the Fireys": "Delayed Blast Fireball",
  "Freya, Queen of the Valkyries": "Iroas, God of Victory",
  "Friends to the End": "Twinflame",
  "Gaia's Dark Hammer": "Colossus Hammer",
  "Galaxy Sword": "Sword of Forge and Frontier",
  "Garfield and Odie, Best Buds": "Rin and Seri, Inseparable",
  "Garnet Til Alexandros 17th": "Loran of the Third Path",
  "Gary, the Snail": "Toxrill, the Corrosive",
  "Ghal Maraz, the Great Shatterer": "Loxodon Warhammer",
  "Ghazghkull, Prophet of the Waaagh!": "Zurgo Helmsmasher",
  "Ghidorah, King of the Cosmos": "Illuna, Apex of Wishes",
  "Ghost Trap": "Soul-Guide Lantern",
  "Ghostbuster's Patch": "Boros Charm",
  "Giant of Babil": "Traxos, Scourge of Kroog",
  "Gigan, Cyberclaw Terror": "Gyruda, Doom of Depths",
  "Gilgamesh, Weapon Collector": "Godo, Bandit Warlord",
  "Gimme, Gimme, Gimme!": "Shiny Impetus",
  "Glittering Caves of Aglarond": "Gemstone Caverns",
  "Goblin Cradle-Thieves": "Goblin Rabblemaster",
  "Godzilla, Doom Inevitable": "Yidaro, Wandering Monster",
  "Godzilla, King of the Monsters": "Zilortha, Strength Incarnate",
  "Godzilla, Primeval Champion": "Titanoth Rex",
  "Golbez, Clad In Darkness": "Syr Konrad, the Grim",
  "Gore Magala, Dark Eclipse": "Razaketh, the Foulblooded",
  "Grandma's Scroll": "Merchant Scroll",
  "Green Dragon Inn": "Homeward Path",
  "Grimm Fate": "Beast Within",
  "Gromp": "Spore Frog",
  "Hades Grip": "Sulfuric Vortex",
  "Hadoken": "Lightning Bolt",
  "Hang In There": "Ponder",
  "Harker's Journal": "Investigator's Journal",
  "Harker's Obsessive Inquiry": "Jacob Hauken, Inspector",
  "He-Man, Champion of Eternia": "Winota, Joiner of Forces",
  "Heart of the Explorer": "Search for Azcanta",
  "Heart of the Mountain": "Arcane Signet",
  "Heaven-Sent Marvel": "Archangel of Thune",
  "Helm's Deep": "Shinka, the Bloodsoaked Keep",
  "Henneth Annûn": "Reflecting Pool",
  "Heralds of the Shredder": "Vigor",
  "Hero of Hoarfrost Reach": "Archaeomancer",
  "Hero of Light": "Adeline, Resplendent Cathar",
  "Herugrim, Sword of Rohan": "Sword of Hearth and Home",
  "Hoggle, Heart in Conflict": "Wort, Boggart Auntie",
  "Hope's Aero Magic": "Cyclonic Rift",
  "Hugo Kupka": "Bruse Tarl, Boorish Herder",
  "Humongous Fungus": "Corpsejack Menace",
  "Hunger of the Ancient One": "Exquisite Blood",
  "Huu's Reach": "Kodama's Reach",
  "I Hate Mondays": "Beast Within",
  "I've Brought You a Gift": "Trinisphere",
  "Ian, Convalescent Charmer": "Tasigur, the Golden Fang",
  "Ifrit": "Fury",
  "Indominus Rex": "Polyraptor",
  "Inigo, Avenging Swordsman": "Samut, Voice of Dissent",
  "Inn of the Prancing Pony": "Pillar of the Paruns",
  "Intergalactic Wrestling": "Possibility Storm",
  "Iron Spider, Civil Warrior": "Alibou, Ancient Witness",
  "Isengard, Saruman's Fortress": "Boseiju, Who Shelters All",
  "Jareth, Goblin King": "Muxus, Goblin Grandee",
  "Joe Fixit's Expertise": "Rishkar's Expertise",
  "Jonathan Harker": "Jacob Hauken, Inspector",
  "Joo Dee, Public Servant": "Sakashima of a Thousand Faces",
  "Joshua Graham, Burned Man": "Isshin, Two Heavens as One",
  "Joshua Rosfield": "Rograkh, Son of Rohgahh",
  "Junimo Farmhands": "Sylvan Caryatid",
  "KAITO, Mysterious Maestro": "Jace, Unraveler of Secrets",
  "KING OF WOLVES": "Tovolar, Dire Overlord",
  "Katsuichi's Peace": "Felidar Retreat",
  "Kefka Palazzo": "Purphoros, God of the Forge",
  "Kefka's Tower": "Bolas's Citadel",
  "Khan, Engineered Evil": "Sheoldred, the Apocalypse",
  "Killer Rabbit of Caerbannog": "Kezzerdrix",
  "King Caesar, Ancient Guardian": "Huntmaster Liger",
  "King Caesar, Awoken Titan": "Snapdax, Apex of the Hunt",
  "Kings Bay Clock Tower": "Midnight Clock",
  "Kitezh, Sunken City": "Academy Ruins",
  "Knights of San d'Oria": "Ranger-Captain of Eos",
  "Knowby's Incantation": "Zombie Apocalypse",
  "Knuckles's Gloves": "The Reaver Cleaver",
  "Krang's Android": "Triskelion",
  "Kratos' Rage": "Pyrohemia",
  "Krobus": "Academy Manufactor",
  "Kuja, Mage Manufacturer": "Inalla, Archmage Ritualist",
  "Kushala Daora's Fury": "Snap",
  "La Madre Tierra": "Xenagos, God of Revels",
  "La abuela, siempre generosa": "Tireless Provisioner",
  "La abundancia de Yucahú": "Sylvan Library",
  "La danza del pueblo": "Expressive Iteration",
  "Lady Loki's Manifestation": "Titan of Littjara",
  "Lagiacrus, Lord of the Seas": "Nezahal, Primal Tide",
  "Len and Rin, Harmony Incarnate": "The Royal Scions",
  "Leo's Katana": "Sword of Sinew and Steel",
  "Lifelong Friendship": "Eladamri's Call",
  "Lightning, Lone Commando": "Isshin, Two Heavens as One",
  "Linda, Kandarian Queen": "Varina, Lich Queen",
  "Lofi Cat": "Felidar Guardian",
  "Loki's Double": "Spark Double",
  "Luca Stadium": "Strixhaven Stadium",
  "Lucky Purple Memento": "Puca's Mischief",
  "Lucy Westenra": "Innocent Traveler",
  "Lucy, Arisen Vampire": "Innocent Traveler",
  "Ludo, Rock Caller": "Kogla, the Titan Ape",
  "Luka, the Traveling Sound": "Liliana of the Dark Realms",
  "Lórien Brooch": "Trailblazer's Boots",
  "MEIKO, Explosive Entertainer": "Chandra, Flamecaller",
  "Magus Sisters": "Endurance",
  "Makari the Lucky Grot": "Krenko, Tin Street Kingpin",
  "Malcolm's Mercurial Mirth": "Tasha's Hideous Laughter",
  "Man Ray, Eco Avenger": "Deepglow Skate",
  "Man-At-Arms, Master Tactician": "Bruenor Battlehammer",
  "Man-E-Faces, Actor of Eternia": "Sakashima the Impostor",
  "Man-Thing, Marsh Protector": "Bristly Bill, Spine Sower",
  "Man-Wolf": "Huntmaster of the Fells",
  "Marauding Mutagen": "Acidic Slime",
  "Master Emerald Shrine": "Command Tower",
  "Master Weaver, Web Protector": "Arasta of the Endless Web",
  "Master Xande": "Venser, Shaper Savant",
  "Mayor Tong of Chin Village": "Drannith Magistrate",
  "Mechagodzilla, Battle Fortress": "Hangarback Walker",
  "Mechagodzilla, the Weapon": "Crystalline Giant",
  "Meduseld, Golden Hall of Edoras": "Castle Ardenvale",
  "Megatron": "Blightsteel Colossus",
  "Memories of Nibelheim": "Stroke of Midnight",
  "Merciless Poisoning": "Toxic Deluge",
  "Mermaid's Pendant": "Wedding Ring",
  "Meteorfall": "Star of Extinction",
  "Miku's Spark": "Chandra's Ignition",
  "Miku, Child of Song": "Child of Alara",
  "Miku, Divine Diva": "Elspeth Tirel",
  "Miku, Font of Pop": "Giada, Font of Hope",
  "Miku, Lost but Singing": "Azusa, Lost but Seeking",
  "Miku, Queen Electric": "Brago, King Eternal",
  "Miku, Song of the People": "Trostani, Selesnya's Voice",
  "Miku, Voice Over All": "Shalai, Voice of Plenty",
  "Miku, Voice of Power": "Freyalise, Llanowar's Fury",
  "Miku, the Complete Performer": "Vorinclex, Voice of Hunger",
  "Miku, the Renowned": "Feather, the Redeemed",
  "Mimir's Ancient Wisdom": "Teferi's Ageless Insight",
  "Mina Harker": "Thalia, Guardian of Thraben",
  "Minas Morgul": "Cabal Coffers",
  "Minwu, Rebellion Strategist": "Mangara, the Diplomat",
  "Miracle Max, Unemployed": "Marchesa, the Black Rose",
  "Mirelurk Hatchling": "Ruin Crab",
  "Mister Sinister, Hubris Unbound": "Endrek Sahr, Master Breeder",
  "Miyamoto Usagi": "Baylen, the Haymaker",
  "Mondo Gecko, Esquire": "Kediss, Emberclaw Familiar",
  "Monica, the Marvel": "Aurelia, the Warleader",
  "Monkey, Awakened to Emptiness": "Kibo, Uktabi Prince",
  "Morgul-Knife": "Shadowspear",
  "Mothman Egg": "Mesmeric Orb",
  "Mothra's Great Cocoon": "Mysterious Egg",
  "Mothra, Supersonic Queen": "Luminous Broodmoth",
  "Mr. Krabs, Penny Pincher": "Charix, the Raging Isle",
  "Mutanimals United": "Triumph of the Hordes",
  "Mysterious Blood Illness": "Vampires' Vengeance",
  "NOT A WOLF": "Tovolar, Dire Overlord",
  "Nargacuga Stalker": "Grim Haruspex",
  "Nargacuga, Ever-Present Shadow": "Wasitora, Nekoru Queen",
  "Neave Blacktalon": "Danitha Capashen, Paragon",
  "Nergigante, Herald of Destruction": "Vaevictis Asmadi, the Dire",
  "Newfound Adventure": "Farseek",
  "Nightfeeder's Visitation": "Night's Whisper",
  "Noctis Lucis Caelum": "Kenrith, the Returned King",
  "Noctis's Death Magic": "Damn",
  "Optimus Prime": "Darksteel Colossus",
  "Orbital Vibranium Bomb": "Scourglass",
  "Ork Kommando": "Merciless Executioner",
  "Orko, Trollan Magician": "Delina, Wild Mage",
  "Ororo Borealis": "Manamorphose",
  "Orphan, Cocoon fal'Cie": "Muldrotha, the Gravetide",
  "Osgiliath, Fallen Capital": "Kor Haven",
  "Panic on Amity Island": "Descent into Avernus",
  "Panther Idol": "Mind's Eye",
  "Panthor, Savage Cat": "The Gitrog, Ravenous Ride",
  "Paradise Chocobo": "Birds of Paradise",
  "Pastor da Selva": "Ancient Greenwarden",
  "Patchwork Chucky": "Stuffy Doll",
  "Paths of the Dead": "Cavern of Souls",
  "Patrick Star": "Barktooth Warbeard",
  "Patriotic Shield": "Sword of Fire and Ice",
  "Pelican Town": "Homeward Path",
  "Perfect Defense": "Defense of the Heart",
  "Pierre's Truce": "Dawn's Truce",
  "Pigsy of the Eight Precepts": "Ilharg, the Raze-Boar",
  "Piko Piko Hammer": "Hammer of Nazahn",
  "Plankton, Tiny Tyrant": "Skrelv, Defector Mite",
  "Play Pals Factory": "Genesis Chamber",
  "Porom's Silence Magic": "Silence",
  "Post the Enchanter": "Zur the Enchanter",
  "Post's Citadel": "Bolas's Citadel",
  "Post's Sigil": "Leshrac's Sigil",
  "Post, Son of Rich": "K'rrik, Son of Yawgmoth",
  "Power Sneakers": "Lightning Greaves",
  "Prime Mirelurk Queen": "Hullbreaker Horror",
  "Primogenesis": "Feed the Swarm",
  "Princess Sarah": "Azusa, Lost but Seeking",
  "Prophetic Beginning": "Preordain",
  "Quincey Harker": "Reclusive Taxidermist",
  "Quite a Merry Gathering": "Tocasia's Welcome",
  "Raise Repulsor Shields": "Raise the Palisade",
  "Rally the Evil Warriors": "Breach the Multiverse",
  "Raph's Jitte": "Umezawa's Jitte",
  "Rathalos, King of the Skies": "Drakuseth, Maw of Flames",
  "Re-Roll": "Rewind",
  "Recyclops, Eco-friendly": "Garruk Relentless",
  "Recyclops, Nature's Vengeance": "Garruk Relentless",
  "Redhorn Pass": "Mouth of Ronom",
  "Regalla's Wrath": "Tarrian's Soulcleaver",
  "Renfield, Delusional Minion": "Eruth, Tormented Prophet",
  "Rescue in the 13th Hour": "Timely Ward",
  "Ring of Barahir": "Sword of the Animist",
  "Rodan, Titan of Winged Fury": "Vadrok, Apex of Thunder",
  "Rodents of Unusual Size": "Pack Rat",
  "Ronin's Arsenal": "Conqueror's Flail",
  "Round Two": "Seize the Day",
  "Royal Serpent": "Atsushi, the Blazing Sky",
  "Ruzka, Terror of Point Lookout": "Ayula, Queen Among Bears",
  "S.H.I.E.L.D. Spy Satellite": "Fellwar Stone",
  "Sandy Cheeks, Martial Astronaut": "Toski, Bearer of Secrets",
  "Sandy, Awakened to Purity": "Kazuul, Tyrant of the Cliffs",
  "Sarah, Champion to the Lost": "Jodah, the Unifier",
  "Scrounging Deathclaw": "Tarmogoyf",
  "Search for the Frozen Esper": "Nature's Claim",
  "Search the Count's Castle": "Thirst for Discovery",
  "Sephiroth, the Savior": "Atraxa, Grand Unifier",
  "Seymour Guado": "Kinnan, Bonder Prodigy",
  "Shadowbringers": "Dovin's Veto",
  "Shaft of Hands": "Rogue's Passage",
  "Shantotto's Coercion": "Diabolic Intent",
  "Shards of Narsil": "Thorn of Amethyst",
  "She-Ra, Princess of Power": "Sisay, Weatherlight Captain",
  "Sheldon, the Commander": "Ruhan of the Fomori",
  "Shelob, Whose Lair Is Death": "Ishkanah, Grafwidow",
  "Shield of War and Peace": "Sword of War and Peace",
  "Shiva": "Subtlety",
  "Shovel of Decapitation": "Colossus Hammer",
  "Shredder, Criminal Mastermind": "Higure, the Still Wind",
  "Shrinking Storm": "Wrath of God",
  "Shu Jing Meteorite": "Fellwar Stone",
  "Sir Bedivere's Scales": "Ashnod's Altar",
  "Sisters of the Undead": "Olivia, Crimson Bride",
  "Skeletor's Villainous Glee": "Tasha's Hideous Laughter",
  "Skeletor, Lord of Destruction": "Tinybones, the Pickpocket",
  "Skybreaker, Sword of Bashenga": "Sword of the Animist",
  "Slash Clone": "Steelbane Hydra",
  "Slash, Evil Turtle from Dimension X": "Pirated Copy",
  "Slimed": "Trickbind",
  "Slimer and Stay Puft": "Yargle and Multani",
  "Slimer's Feast": "Windfall",
  "Slimer, Voracious Apparition": "The Mimeoplasm",
  "Snowman Starfield": "Starfield of Nyx",
  "Song of the Barbarous Beast": "Village Rites",
  "Sorry, Jack . . . Chucky's Back": "Phyrexian Reclamation",
  "Spacegodzilla, Death Corona": "Void Beckoner",
  "Specimen 73": "Hornet Queen",
  "Spider-Gwen, Web-Warrior": "Najeela, the Blade-Blossom",
  "Spinosaurus": "Regisaur Alpha",
  "Spira's Punishment": "Day of Judgment",
  "Splinter of the Shadows": "Ashcoat of the Shadow Swarm",
  "Splinter, Vengeful Sensei": "Ink-Eyes, Servant of Oni",
  "SpongeBob SquarePants": "Jodah, the Unifier",
  "Squall Leonhart": "Danitha Capashen, Paragon",
  "Squidward, Sarcastic Snob": "Grazilaxx, Illithid Scholar",
  "Stampeding Brutes": "Rampaging Baloths",
  "Stardrake": "Scourge of the Throne",
  "Stay with Me": "Rhystic Study",
  "Storm's Will": "Jeska's Will",
  "Storms of Yamatai": "Anger of the Gods",
  "Suki of the Kyoshi Warriors": "Captain Sisay",
  "Summoner's Rift": "Command Tower",
  "Sunset Sarsaparilla Machine": "Nuka-Cola Vending Machine",
  "Supply Llama": "Etherium Sculptor",
  "Swift Wind, Steed of She-Ra": "Emiel the Blessed",
  "Sword of Power": "Sword of War and Peace",
  "T'Challa's Protection": "Teferi's Protection",
  "T-60 Power Armor": "T-45 Power Armor",
  "Talk to the Paw": "Orim's Chant",
  "Teela, Warrior Goddess": "Samut, Voice of Dissent",
  "Terra Branford": "Urza, Lord High Artificer",
  "The AllSpark": "Doubling Cube",
  "The Ball": "Fellwar Stone",
  "The Banyan Tree": "The Great Henge",
  "The Blades of Chaos Bond": "Rite of Flame",
  "The Boy in the Iceberg": "Dark Depths",
  "The Bridge of Death": "Door to Nothingness",
  "The Cleaners": "Leveler",
  "The Cloudsea Djinn": "Nyxbloom Ancient",
  "The Cube": "Planar Bridge",
  "The Dead Marshes": "Urborg, Tomb of Yawgmoth",
  "The Devil Strahd": "Strefan, Maurer Progenitor",
  "The Emperor, Hell Tyrant": "Yawgmoth, Thran Physician",
  "The Five Arrive": "Genesis Ultimatum",
  "The Goblin King's Offer": "Tempt with Discovery",
  "The Grass-Cutting Sword": "Sunforger",
  "The Grim Whisper": "Bow of Nylea",
  "The Hexcore": "Thran Dynamo",
  "The Imperial City of Archades": "Wall of Omens",
  "The Kidnapping of Toby": "Claim the Firstborn",
  "The Labyrinth": "Maze of Ith",
  "The Lost Valley": "Search for Azcanta",
  "The Mechanist, Tactical Tinkerer": "Lita, Mechanical Engineer",
  "The Monstrous Serpent": "Koma, Cosmos Serpent",
  "The Party Tree": "The Great Henge",
  "The Platinum Chip": "Caged Sun",
  "The Rage of Yian Garuga": "Mizzium Mortars",
  "The Shadow Lord": "Gix, Yawgmoth Praetor",
  "The Sorceress, Heroic Guardian": "Derevi, Empyrial Tactician",
  "The Spire": "Command Tower",
  "The Strahl": "Smuggler's Copter",
  "The Three Weird Sisters": "Henrika Domnathi",
  "The Watcher's Warning": "Mind's Dilation",
  "The Welcoming Committee": "Kynaios and Tiro of Meletis",
  "The Wiseman, Eccentric Oracle": "Shigeki, Jukai Visionary",
  "The Worm, Sagely Guide": "Kami of the Crescent Moon",
  "Three Rings for the Elven-Kings": "Rings of Brighthearth",
  "Throw Team-Mate": "Fling",
  "Thrum of the Vestige": "Lightning Bolt",
  "Thunderjaw": "Meteor Golem",
  "Théoden, Strength Restored": "Kenrith, the Returned King",
  "Tidus's Brotherhood Sword": "Sword of Truth and Justice",
  "Tidus, Zanarkand Fayth": "Thrasios, Triton Hero",
  "Tiffany, Bride of Chucky": "Varragoth, Bloodsky Sire",
  "Tim the Enchanter": "Prodigal Sorcerer",
  "To the Crystal Tower": "Cryptic Command",
  "Torgal, Clive's Companion": "Yoshimaru, Ever Faithful",
  "Tornado, Sonic's Biplane": "Weatherlight",
  "Total Containment Failure": "Living End",
  "Totec's Spear": "Shadowspear",
  "Touchdown!": "Approach of the Second Sun",
  "Tower of Cirith Ungol": "Urborg",
  "Tower of Rasmodius": "Command Tower",
  "Toxic Sheepsquatch": "Gemrazer",
  "Trap Jaw, Wizard of Weapons": "Tetsuo, Imperial Champion",
  "Treebeard, Eldest of Ents": "Doran, the Siege Tower",
  "Triceratops": "Wayward Swordtooth",
  "Tripitaka, Seeker from Tang": "Dosan the Falling Leaf",
  "Tyrannosaurus Rex": "Etali, Primal Storm",
  "Under Jareth's Spell": "Chronomantic Escape",
  "Unseat the Usurper": "Praetor's Grasp",
  "Unstable Harmonics": "Rhystic Study",
  "Vaan, Aspiring Sky Pirate": "Captain Lannery Storm",
  "Valley Farmstead": "Yavimaya, Cradle of Growth",
  "Valley of Gorgoroth": "Wasteland",
  "Van Helsing's Holy Ward": "Circle of Confinement",
  "Vana'diel Adventurers": "Laboratory Maniac",
  "Vault Boy, Cap Collector": "Grand Arbiter Augustin IV",
  "Vayne Carudas Solidor": "Fynn, the Fangbearer",
  "Velkhana, Silver Sovereign": "Amareth, the Lustrous",
  "Velociraptor": "Rampaging Ferocidon",
  "Venom, King in Black": "Skithiryx, the Blight Dragon",
  "Vibranium Dynamo": "Thran Dynamo",
  "Vivi's Thunder Magic": "Lightning Bolt",
  "Vizzini, Criminal Mastermind": "Baral, Chief of Compliance",
  "Volcano of Roku's Island": "Valakut, the Molten Pinnacle",
  "Wakandan Skyscraper": "Karn's Bastion",
  "Wakandan War Panther": "Fleecemane Lion",
  "Warrior of Light": "Jodah, the Unifier",
  "We Want . . . A SHRUBBERY!": "Three Visits",
  "Weathertop": "Deserted Temple",
  "West Tek Tyrant": "Grave Titan",
  "Westley, Dread Pirate Roberts": "Fynn, the Fangbearer",
  "White Tower of Ecthelion": "Karakas",
  "Widow-Making Infiltrator": "Dauthi Voidwalker",
  "Wild Rose Rebellion": "Counterspell",
  "Ya viene el coco": "Tibalt's Trickery",
  "Yojimbo": "Solitude",
  "You're Gonna Need a Bigger Boat": "Abrade",
  "Yuffie Kisaragi": "Yuriko, the Tiger's Shadow",
  "Yuna's Holy Magic": "Prismatic Ending",
  "Yuna's Sending Staff": "Staff of the Storyteller",
  "Zidane Tribal": "Ragavan, Nimble Pilferer",
  "Zinogre, Lord of Lightning": "Sarulf, Realm Eater",
  "Zombie Captain America": "Wilhelt, the Rotcleaver",
  "Zombie Giant-Man": "Vogar, Necropolis Tyrant",
  "Zombie Scarlet Witch": "Varina, Lich Queen",
  "Zombie Thor": "God-Eternal Bontu",
  "Zuko, Redeemed": "Rhys the Redeemed",
  "フェイタリズム": "Arcane Denial",
  "仲間を導くもの、ガルク": "Pack Leader",
  "魔女の予見": "Force of Negation",
};

const BY_LOWER = new Map(Object.entries(FLAVOR_NAMES).map(([flavor, name]) => [flavor.toLowerCase(), name]));

/** The pool name a flavor name stands for, ignoring case, or `null` when
 * `name` isn't one. */
export const nameForFlavorName = (name: string): string | null =>
  BY_LOWER.get(name.trim().toLowerCase()) ?? null;

let byCard: Map<string, string[]> | null = null;

/** Every flavor name `cardName` (its pool name) is printed under. */
export const flavorNamesOf = (cardName: string): readonly string[] => {
  if (byCard === null) {
    byCard = new Map();
    for (const [flavor, name] of Object.entries(FLAVOR_NAMES)) {
      const list = byCard.get(name);
      if (list === undefined) byCard.set(name, [flavor]);
      else list.push(flavor);
    }
  }
  return byCard.get(cardName) ?? [];
};
