// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.
// Run `npm run gen:cards -w engine` after adding or removing a card file.

import type { CardDefinition } from "./define.js";

import _poolAbrade from "./pool/abrade.js";
import _poolActOfTreason from "./pool/act-of-treason.js";
import _poolAdarkarWastes from "./pool/adarkar-wastes.js";
import _poolAftermathAnalyst from "./pool/aftermath-analyst.js";
import _poolAggravatedAssault from "./pool/aggravated-assault.js";
import _poolAjanisPridemate from "./pool/ajanis-pridemate.js";
import _poolAmbushViper from "./pool/ambush-viper.js";
import _poolAmuletOfVigor from "./pool/amulet-of-vigor.js";
import _poolAnOfferYouCantRefuse from "./pool/an-offer-you-cant-refuse.js";
import _poolAnafenzaTheForemost from "./pool/anafenza-the-foremost.js";
import _poolAncientTomb from "./pool/ancient-tomb.js";
import _poolAngelicEdict from "./pool/angelic-edict.js";
import _poolArcaneSignet from "./pool/arcane-signet.js";
import _poolArdentRecruit from "./pool/ardent-recruit.js";
import _poolAridMesa from "./pool/arid-mesa.js";
import _poolArtificialEvolution from "./pool/artificial-evolution.js";
import _poolAshnodsAltar from "./pool/ashnods-altar.js";
import _poolAtarkaWorldRender from "./pool/atarka-world-render.js";
import _poolAtraxaPraetorsVoice from "./pool/atraxa-praetors-voice.js";
import _poolAustereCommand from "./pool/austere-command.js";
import _poolAyaraFirstOfLocthwain from "./pool/ayara-first-of-locthwain.js";
import _poolBaithookAngler from "./pool/baithook-angler.js";
import _poolBattlefieldForge from "./pool/battlefield-forge.js";
import _poolBeanstalkGiant from "./pool/beanstalk-giant.js";
import _poolBeastWithin from "./pool/beast-within.js";
import _poolBeholdTheMultiverse from "./pool/behold-the-multiverse.js";
import _poolBirdsOfParadise from "./pool/birds-of-paradise.js";
import _poolBlackChocobo from "./pool/black-chocobo.js";
import _poolBlasphemousAct from "./pool/blasphemous-act.js";
import _poolBlaze from "./pool/blaze.js";
import _poolBlightning from "./pool/blightning.js";
import _poolBlinkmothNexus from "./pool/blinkmoth-nexus.js";
import _poolBloodArtist from "./pool/blood-artist.js";
import _poolBloodCrypt from "./pool/blood-crypt.js";
import _poolBloodbraidElf from "./pool/bloodbraid-elf.js";
import _poolBloodlineKeeper from "./pool/bloodline-keeper.js";
import _poolBloodstainedMire from "./pool/bloodstained-mire.js";
import _poolBloodthroneVampire from "./pool/bloodthrone-vampire.js";
import _poolBoggartBrute from "./pool/boggart-brute.js";
import _poolBojukaBog from "./pool/bojuka-bog.js";
import _poolBonesplitter from "./pool/bonesplitter.js";
import _poolBoomerang from "./pool/boomerang.js";
import _poolBoseijuWhoEndures from "./pool/boseiju-who-endures.js";
import _poolBountifulLandscape from "./pool/bountiful-landscape.js";
import _poolBreedingPool from "./pool/breeding-pool.js";
import _poolBristlyBillSpineSower from "./pool/bristly-bill-spine-sower.js";
import _poolBruseTarlBoorishHerder from "./pool/bruse-tarl-boorish-herder.js";
import _poolBrushland from "./pool/brushland.js";
import _poolCabarettiCourtyard from "./pool/cabaretti-courtyard.js";
import _poolCanopyVista from "./pool/canopy-vista.js";
import _poolCarnageTyrant from "./pool/carnage-tyrant.js";
import _poolCavesOfKoilos from "./pool/caves-of-koilos.js";
import _poolChandraAcolyteOfFlame from "./pool/chandra-acolyte-of-flame.js";
import _poolChromaticLantern from "./pool/chromatic-lantern.js";
import _poolCinderElemental from "./pool/cinder-elemental.js";
import _poolCinderGlade from "./pool/cinder-glade.js";
import _poolCityOfBrass from "./pool/city-of-brass.js";
import _poolClifftopRetreat from "./pool/clifftop-retreat.js";
import _poolClone from "./pool/clone.js";
import _poolColossalDreadmaw from "./pool/colossal-dreadmaw.js";
import _poolCombatThresher from "./pool/combat-thresher.js";
import _poolCommandTower from "./pool/command-tower.js";
import _poolCommercialDistrict from "./pool/commercial-district.js";
import _poolConsider from "./pool/consider.js";
import _poolContentiousPlan from "./pool/contentious-plan.js";
import _poolCounterspell from "./pool/counterspell.js";
import _poolCraterhoofBehemoth from "./pool/craterhoof-behemoth.js";
import _poolCrawWurm from "./pool/craw-wurm.js";
import _poolCropRotation from "./pool/crop-rotation.js";
import _poolCryptolithRite from "./pool/cryptolith-rite.js";
import _poolCyclonicRift from "./pool/cyclonic-rift.js";
import _poolDamn from "./pool/damn.js";
import _poolDamnation from "./pool/damnation.js";
import _poolDarkRitual from "./pool/dark-ritual.js";
import _poolDarksteelMyr from "./pool/darksteel-myr.js";
import _poolDeadlyDispute from "./pool/deadly-dispute.js";
import _poolDeadlyRollick from "./pool/deadly-rollick.js";
import _poolDefenseOfTheHeart from "./pool/defense-of-the-heart.js";
import _poolDemonicTutor from "./pool/demonic-tutor.js";
import _poolDiabolicEdict from "./pool/diabolic-edict.js";
import _poolDisenchant from "./pool/disenchant.js";
import _poolDoomBlade from "./pool/doom-blade.js";
import _poolDoublingSeason from "./pool/doubling-season.js";
import _poolDragonTempest from "./pool/dragon-tempest.js";
import _poolDragonskullSummit from "./pool/dragonskull-summit.js";
import _poolDragonspeakerShaman from "./pool/dragonspeaker-shaman.js";
import _poolDrownedCatacomb from "./pool/drowned-catacomb.js";
import _poolEiganjoSeatOfTheEmpire from "./pool/eiganjo-seat-of-the-empire.js";
import _poolElspethSunsChampion from "./pool/elspeth-suns-champion.js";
import _poolElvishMystic from "./pool/elvish-mystic.js";
import _poolElvishVisionary from "./pool/elvish-visionary.js";
import _poolEmmaraSoulOfTheAccord from "./pool/emmara-soul-of-the-accord.js";
import _poolEncroachingDragonstorm from "./pool/encroaching-dragonstorm.js";
import _poolEssenceFlux from "./pool/essence-flux.js";
import _poolEssenceScatter from "./pool/essence-scatter.js";
import _poolEternalWitness from "./pool/eternal-witness.js";
import _poolEvolvingWilds from "./pool/evolving-wilds.js";
import _poolFaithlessLooting from "./pool/faithless-looting.js";
import _poolFanaticOfRhonas from "./pool/fanatic-of-rhonas.js";
import _poolFarseek from "./pool/farseek.js";
import _poolFencingAce from "./pool/fencing-ace.js";
import _poolFertileFootsteps from "./pool/fertile-footsteps.js";
import _poolFesteringThicket from "./pool/festering-thicket.js";
import _poolFierceGuardianship from "./pool/fierce-guardianship.js";
import _poolFinaleOfDevastation from "./pool/finale-of-devastation.js";
import _poolFireball from "./pool/fireball.js";
import _poolFlameJavelin from "./pool/flame-javelin.js";
import _poolFlawlessManeuver from "./pool/flawless-maneuver.js";
import _poolFleshbagMarauder from "./pool/fleshbag-marauder.js";
import _poolFloodedStrand from "./pool/flooded-strand.js";
import _poolFog from "./pool/fog.js";
import _poolForest from "./pool/forest.js";
import _poolFoundryInspector from "./pool/foundry-inspector.js";
import _poolFrontierBivouac from "./pool/frontier-bivouac.js";
import _poolFumeSpitter from "./pool/fume-spitter.js";
import _poolGanaxAstralHunter from "./pool/ganax-astral-hunter.js";
import _poolGarrukWildspeaker from "./pool/garruk-wildspeaker.js";
import _poolGarruksUprising from "./pool/garruks-uprising.js";
import _poolGazeOfGranite from "./pool/gaze-of-granite.js";
import _poolGenerousGift from "./pool/generous-gift.js";
import _poolGenesisUltimatum from "./pool/genesis-ultimatum.js";
import _poolGiantGrowth from "./pool/giant-growth.js";
import _poolGiantSpider from "./pool/giant-spider.js";
import _poolGlacialFortress from "./pool/glacial-fortress.js";
import _poolGladecoverScout from "./pool/gladecover-scout.js";
import _poolGloriousAnthem from "./pool/glorious-anthem.js";
import _poolGoblinChieftain from "./pool/goblin-chieftain.js";
import _poolGoblinRaider from "./pool/goblin-raider.js";
import _poolGodlessShrine from "./pool/godless-shrine.js";
import _poolGrapeshot from "./pool/grapeshot.js";
import _poolGravePact from "./pool/grave-pact.js";
import _poolGreed from "./pool/greed.js";
import _poolGrizzlyBears from "./pool/grizzly-bears.js";
import _poolGutShot from "./pool/gut-shot.js";
import _poolHallowedFountain from "./pool/hallowed-fountain.js";
import _poolHarrow from "./pool/harrow.js";
import _poolHarvesttideAssailant from "./pool/harvesttide-assailant.js";
import _poolHarvesttideInfiltrator from "./pool/harvesttide-infiltrator.js";
import _poolHeroicIntervention from "./pool/heroic-intervention.js";
import _poolHillGiant from "./pool/hill-giant.js";
import _poolHinterlandHarbor from "./pool/hinterland-harbor.js";
import _poolHistoryOfBenalia from "./pool/history-of-benalia.js";
import _poolHolyStrength from "./pool/holy-strength.js";
import _poolHookHauntDrifter from "./pool/hook-haunt-drifter.js";
import _poolHourOfReckoning from "./pool/hour-of-reckoning.js";
import _poolHypnoticSpecter from "./pool/hypnotic-specter.js";
import _poolIcetillExplorer from "./pool/icetill-explorer.js";
import _poolIgnobleHierarch from "./pool/ignoble-hierarch.js";
import _poolInfernalGrasp from "./pool/infernal-grasp.js";
import _poolInvisibleStalker from "./pool/invisible-stalker.js";
import _poolIridescentVinelasher from "./pool/iridescent-vinelasher.js";
import _poolIsland from "./pool/island.js";
import _poolIsolatedChapel from "./pool/isolated-chapel.js";
import _poolJuggernaut from "./pool/juggernaut.js";
import _poolJump from "./pool/jump.js";
import _poolKalonianHydra from "./pool/kalonian-hydra.js";
import _poolKarplusanForest from "./pool/karplusan-forest.js";
import _poolKazanduMammoth from "./pool/kazandu-mammoth.js";
import _poolKazanduValley from "./pool/kazandu-valley.js";
import _poolKessigWolfRun from "./pool/kessig-wolf-run.js";
import _poolKioraBehemothBeckoner from "./pool/kiora-behemoth-beckoner.js";
import _poolKirdApe from "./pool/kird-ape.js";
import _poolKolaghansCommand from "./pool/kolaghans-command.js";
import _poolKorvoldFaeCursedKing from "./pool/korvold-fae-cursed-king.js";
import _poolLathlissDragonQueen from "./pool/lathliss-dragon-queen.js";
import _poolLevitation from "./pool/levitation.js";
import _poolLightningBolt from "./pool/lightning-bolt.js";
import _poolLightningGreaves from "./pool/lightning-greaves.js";
import _poolLlanowarElves from "./pool/llanowar-elves.js";
import _poolLlanowarWastes from "./pool/llanowar-wastes.js";
import _poolLongtuskCub from "./pool/longtusk-cub.js";
import _poolLordOfExtinction from "./pool/lord-of-extinction.js";
import _poolLordOfLineage from "./pool/lord-of-lineage.js";
import _poolLotusCobra from "./pool/lotus-cobra.js";
import _poolLotusField from "./pool/lotus-field.js";
import _poolLotusPetal from "./pool/lotus-petal.js";
import _poolLure from "./pool/lure.js";
import _poolMagmaquake from "./pool/magmaquake.js";
import _poolManOWar from "./pool/man-o-war.js";
import _poolManaConfluence from "./pool/mana-confluence.js";
import _poolManifoldKey from "./pool/manifold-key.js";
import _poolMarshFlats from "./pool/marsh-flats.js";
import _poolMendingHands from "./pool/mending-hands.js";
import _poolMiirymSentinelWyrm from "./pool/miirym-sentinel-wyrm.js";
import _poolMindControl from "./pool/mind-control.js";
import _poolMindRot from "./pool/mind-rot.js";
import _poolMindStone from "./pool/mind-stone.js";
import _poolMishrasFactory from "./pool/mishras-factory.js";
import _poolMistyRainforest from "./pool/misty-rainforest.js";
import _poolMoleManMoloidMaster from "./pool/mole-man-moloid-master.js";
import _poolMonasterySwiftspear from "./pool/monastery-swiftspear.js";
import _poolMortivore from "./pool/mortivore.js";
import _poolMountain from "./pool/mountain.js";
import _poolMudbuttonTorchrunner from "./pool/mudbutton-torchrunner.js";
import _poolNaturalize from "./pool/naturalize.js";
import _poolNaturesLore from "./pool/natures-lore.js";
import _poolNegate from "./pool/negate.js";
import _poolNotionThief from "./pool/notion-thief.js";
import _poolObNixilisTheFallen from "./pool/ob-nixilis-the-fallen.js";
import _poolOldGnawbone from "./pool/old-gnawbone.js";
import _poolOpt from "./pool/opt.js";
import _poolOracleOfMulDaya from "./pool/oracle-of-mul-daya.js";
import _poolOrcishLumberjack from "./pool/orcish-lumberjack.js";
import _poolOtawaraSoaringCity from "./pool/otawara-soaring-city.js";
import _poolOvergrownTomb from "./pool/overgrown-tomb.js";
import _poolPacifism from "./pool/pacifism.js";
import _poolPhyrexianArena from "./pool/phyrexian-arena.js";
import _poolPlains from "./pool/plains.js";
import _poolPollutedDelta from "./pool/polluted-delta.js";
import _poolPrairieStream from "./pool/prairie-stream.js";
import _poolPreordain from "./pool/preordain.js";
import _poolPreyUpon from "./pool/prey-upon.js";
import _poolPrincessSarah from "./pool/princess-sarah.js";
import _poolProdigalSorcerer from "./pool/prodigal-sorcerer.js";
import _poolProsperousInnkeeper from "./pool/prosperous-innkeeper.js";
import _poolPyroclasm from "./pool/pyroclasm.js";
import _poolRabidBite from "./pool/rabid-bite.js";
import _poolRagingGoblin from "./pool/raging-goblin.js";
import _poolRaiseTheAlarm from "./pool/raise-the-alarm.js";
import _poolRakdosCharm from "./pool/rakdos-charm.js";
import _poolRampagingBaloths from "./pool/rampaging-baloths.js";
import _poolRampantGrowth from "./pool/rampant-growth.js";
import _poolRamunapExcavator from "./pool/ramunap-excavator.js";
import _poolRapidHybridization from "./pool/rapid-hybridization.js";
import _poolRaucousTheater from "./pool/raucous-theater.js";
import _poolRegrowth from "./pool/regrowth.js";
import _poolRestInPeace from "./pool/rest-in-peace.js";
import _poolRiftBolt from "./pool/rift-bolt.js";
import _poolRiveteersOverlook from "./pool/riveteers-overlook.js";
import _poolRockfallVale from "./pool/rockfall-vale.js";
import _poolRoguesPassage from "./pool/rogues-passage.js";
import _poolRootboundCrag from "./pool/rootbound-crag.js";
import _poolRumblingBaloth from "./pool/rumbling-baloth.js";
import _poolRydiaSummonerOfMist from "./pool/rydia-summoner-of-mist.js";
import _poolSabotender from "./pool/sabotender.js";
import _poolSacredFoundry from "./pool/sacred-foundry.js";
import _poolSakuraTribeElder from "./pool/sakura-tribe-elder.js";
import _poolSawInHalf from "./pool/saw-in-half.js";
import _poolScaldingTarn from "./pool/scalding-tarn.js";
import _poolScourgeOfValkas from "./pool/scourge-of-valkas.js";
import _poolScuteSwarm from "./pool/scute-swarm.js";
import _poolSerraAngel from "./pool/serra-angel.js";
import _poolShelteredThicket from "./pool/sheltered-thicket.js";
import _poolShivanReef from "./pool/shivan-reef.js";
import _poolSidequestRaiseAChocobo from "./pool/sidequest-raise-a-chocobo.js";
import _poolSimicCharm from "./pool/simic-charm.js";
import _poolSmolderingMarsh from "./pool/smoldering-marsh.js";
import _poolSnapcasterMage from "./pool/snapcaster-mage.js";
import _poolSolRing from "./pool/sol-ring.js";
import _poolSolemnSimulacrum from "./pool/solemn-simulacrum.js";
import _poolSoulWarden from "./pool/soul-warden.js";
import _poolSplendidReclamation from "./pool/splendid-reclamation.js";
import _poolStarfieldVocalist from "./pool/starfield-vocalist.js";
import _poolSteamVents from "./pool/steam-vents.js";
import _poolStompingGround from "./pool/stomping-ground.js";
import _poolSulfurFalls from "./pool/sulfur-falls.js";
import _poolSulfurousSprings from "./pool/sulfurous-springs.js";
import _poolSummonTitan from "./pool/summon-titan.js";
import _poolSunkenHollow from "./pool/sunken-hollow.js";
import _poolSunpetalGrove from "./pool/sunpetal-grove.js";
import _poolSwamp from "./pool/swamp.js";
import _poolSwiftfootBoots from "./pool/swiftfoot-boots.js";
import _poolSylvanSafekeeper from "./pool/sylvan-safekeeper.js";
import _poolTakenumaAbandonedMire from "./pool/takenuma-abandoned-mire.js";
import _poolTalismanOfConviction from "./pool/talisman-of-conviction.js";
import _poolTalismanOfCreativity from "./pool/talisman-of-creativity.js";
import _poolTalismanOfCuriosity from "./pool/talisman-of-curiosity.js";
import _poolTalismanOfDominance from "./pool/talisman-of-dominance.js";
import _poolTalismanOfHierarchy from "./pool/talisman-of-hierarchy.js";
import _poolTalismanOfImpulse from "./pool/talisman-of-impulse.js";
import _poolTalismanOfIndulgence from "./pool/talisman-of-indulgence.js";
import _poolTalismanOfProgress from "./pool/talisman-of-progress.js";
import _poolTalismanOfResilience from "./pool/talisman-of-resilience.js";
import _poolTalismanOfUnity from "./pool/talisman-of-unity.js";
import _poolTanaTheBloodsower from "./pool/tana-the-bloodsower.js";
import _poolTannukMemorialEnsign from "./pool/tannuk-memorial-ensign.js";
import _poolTearAsunder from "./pool/tear-asunder.js";
import _poolTempleGarden from "./pool/temple-garden.js";
import _poolTempleOfAbandon from "./pool/temple-of-abandon.js";
import _poolTempleOfMystery from "./pool/temple-of-mystery.js";
import _poolTemurAscendancy from "./pool/temur-ascendancy.js";
import _poolTemurBattlecrier from "./pool/temur-battlecrier.js";
import _poolTerramorphicExpanse from "./pool/terramorphic-expanse.js";
import _poolTerrorOfThePeaks from "./pool/terror-of-the-peaks.js";
import _poolThaliaGuardianOfThraben from "./pool/thalia-guardian-of-thraben.js";
import _poolThievingMagpie from "./pool/thieving-magpie.js";
import _poolThornOfTheBlackRose from "./pool/thorn-of-the-black-rose.js";
import _poolThreaten from "./pool/threaten.js";
import _poolThreeVisits from "./pool/three-visits.js";
import _poolTimeWarp from "./pool/time-warp.js";
import _poolTirelessProvisioner from "./pool/tireless-provisioner.js";
import _poolTomeScour from "./pool/tome-scour.js";
import _poolTranquilThicket from "./pool/tranquil-thicket.js";
import _poolTurbulentFen from "./pool/turbulent-fen.js";
import _poolTurnToFrog from "./pool/turn-to-frog.js";
import _poolTwincast from "./pool/twincast.js";
import _poolTyphoidRats from "./pool/typhoid-rats.js";
import _poolUndergroundMortuary from "./pool/underground-mortuary.js";
import _poolUndergroundRiver from "./pool/underground-river.js";
import _poolUnderworldRageHound from "./pool/underworld-rage-hound.js";
import _poolUnnaturalGrowth from "./pool/unnatural-growth.js";
import _poolUnsummon from "./pool/unsummon.js";
import _poolUreniOfTheUnwritten from "./pool/ureni-of-the-unwritten.js";
import _poolUrzasIncubator from "./pool/urzas-incubator.js";
import _poolUtvaraHellkite from "./pool/utvara-hellkite.js";
import _poolVampireNighthawk from "./pool/vampire-nighthawk.js";
import _poolVandalblast from "./pool/vandalblast.js";
import _poolVerdantCatacombs from "./pool/verdant-catacombs.js";
import _poolVernalFen from "./pool/vernal-fen.js";
import _poolVoltCharge from "./pool/volt-charge.js";
import _poolWalkingBallista from "./pool/walking-ballista.js";
import _poolWallOfWood from "./pool/wall-of-wood.js";
import _poolWateryGrave from "./pool/watery-grave.js";
import _poolWayfarersBauble from "./pool/wayfarers-bauble.js";
import _poolWerebear from "./pool/werebear.js";
import _poolWhiteKnight from "./pool/white-knight.js";
import _poolWillOfTheSultai from "./pool/will-of-the-sultai.js";
import _poolWiltLeafCavaliers from "./pool/wilt-leaf-cavaliers.js";
import _poolWindsweptHeath from "./pool/windswept-heath.js";
import _poolWoodedFoothills from "./pool/wooded-foothills.js";
import _poolWoodlandCemetery from "./pool/woodland-cemetery.js";
import _poolWorldShaper from "./pool/world-shaper.js";
import _poolWrathOfGod from "./pool/wrath-of-god.js";
import _poolWurmcoilEngine from "./pool/wurmcoil-engine.js";
import _poolYavimayaCoast from "./pool/yavimaya-coast.js";
import _poolZulaportCutthroat from "./pool/zulaport-cutthroat.js";
import _poolZuranOrb from "./pool/zuran-orb.js";
import _tokensBeastToken33 from "./tokens/beast-token-3-3.js";
import _tokensBeastToken from "./tokens/beast-token.js";
import _tokensChocoboBirdToken from "./tokens/chocobo-bird-token.js";
import _tokensDragonToken55 from "./tokens/dragon-token-5-5.js";
import _tokensDragonToken66 from "./tokens/dragon-token-6-6.js";
import _tokensElementalToken from "./tokens/elemental-token.js";
import _tokensElephantToken from "./tokens/elephant-token.js";
import _tokensFoodToken from "./tokens/food-token.js";
import _tokensFrogLizardToken from "./tokens/frog-lizard-token.js";
import _tokensInsectToken from "./tokens/insect-token.js";
import _tokensKnightToken from "./tokens/knight-token.js";
import _tokensLifelinkSoldierToken from "./tokens/lifelink-soldier-token.js";
import _tokensMoloidToken from "./tokens/moloid-token.js";
import _tokensPhyrexianWurmDeathtouch from "./tokens/phyrexian-wurm-deathtouch.js";
import _tokensPhyrexianWurmLifelink from "./tokens/phyrexian-wurm-lifelink.js";
import _tokensSaprolingToken from "./tokens/saproling-token.js";
import _tokensSoldierToken from "./tokens/soldier-token.js";
import _tokensTreasureToken from "./tokens/treasure-token.js";
import _tokensVampireToken from "./tokens/vampire-token.js";

/** The built-in card pool — every file under `pool/` and `tokens/`. */
export const BUILTIN_CARDS: readonly CardDefinition[] = [
  _poolAbrade,
  _poolActOfTreason,
  _poolAdarkarWastes,
  _poolAftermathAnalyst,
  _poolAggravatedAssault,
  _poolAjanisPridemate,
  _poolAmbushViper,
  _poolAmuletOfVigor,
  _poolAnOfferYouCantRefuse,
  _poolAnafenzaTheForemost,
  _poolAncientTomb,
  _poolAngelicEdict,
  _poolArcaneSignet,
  _poolArdentRecruit,
  _poolAridMesa,
  _poolArtificialEvolution,
  _poolAshnodsAltar,
  _poolAtarkaWorldRender,
  _poolAtraxaPraetorsVoice,
  _poolAustereCommand,
  _poolAyaraFirstOfLocthwain,
  _poolBaithookAngler,
  _poolBattlefieldForge,
  _poolBeanstalkGiant,
  _poolBeastWithin,
  _poolBeholdTheMultiverse,
  _poolBirdsOfParadise,
  _poolBlackChocobo,
  _poolBlasphemousAct,
  _poolBlaze,
  _poolBlightning,
  _poolBlinkmothNexus,
  _poolBloodArtist,
  _poolBloodCrypt,
  _poolBloodbraidElf,
  _poolBloodlineKeeper,
  _poolBloodstainedMire,
  _poolBloodthroneVampire,
  _poolBoggartBrute,
  _poolBojukaBog,
  _poolBonesplitter,
  _poolBoomerang,
  _poolBoseijuWhoEndures,
  _poolBountifulLandscape,
  _poolBreedingPool,
  _poolBristlyBillSpineSower,
  _poolBruseTarlBoorishHerder,
  _poolBrushland,
  _poolCabarettiCourtyard,
  _poolCanopyVista,
  _poolCarnageTyrant,
  _poolCavesOfKoilos,
  _poolChandraAcolyteOfFlame,
  _poolChromaticLantern,
  _poolCinderElemental,
  _poolCinderGlade,
  _poolCityOfBrass,
  _poolClifftopRetreat,
  _poolClone,
  _poolColossalDreadmaw,
  _poolCombatThresher,
  _poolCommandTower,
  _poolCommercialDistrict,
  _poolConsider,
  _poolContentiousPlan,
  _poolCounterspell,
  _poolCraterhoofBehemoth,
  _poolCrawWurm,
  _poolCropRotation,
  _poolCryptolithRite,
  _poolCyclonicRift,
  _poolDamn,
  _poolDamnation,
  _poolDarkRitual,
  _poolDarksteelMyr,
  _poolDeadlyDispute,
  _poolDeadlyRollick,
  _poolDefenseOfTheHeart,
  _poolDemonicTutor,
  _poolDiabolicEdict,
  _poolDisenchant,
  _poolDoomBlade,
  _poolDoublingSeason,
  _poolDragonTempest,
  _poolDragonskullSummit,
  _poolDragonspeakerShaman,
  _poolDrownedCatacomb,
  _poolEiganjoSeatOfTheEmpire,
  _poolElspethSunsChampion,
  _poolElvishMystic,
  _poolElvishVisionary,
  _poolEmmaraSoulOfTheAccord,
  _poolEncroachingDragonstorm,
  _poolEssenceFlux,
  _poolEssenceScatter,
  _poolEternalWitness,
  _poolEvolvingWilds,
  _poolFaithlessLooting,
  _poolFanaticOfRhonas,
  _poolFarseek,
  _poolFencingAce,
  _poolFertileFootsteps,
  _poolFesteringThicket,
  _poolFierceGuardianship,
  _poolFinaleOfDevastation,
  _poolFireball,
  _poolFlameJavelin,
  _poolFlawlessManeuver,
  _poolFleshbagMarauder,
  _poolFloodedStrand,
  _poolFog,
  _poolForest,
  _poolFoundryInspector,
  _poolFrontierBivouac,
  _poolFumeSpitter,
  _poolGanaxAstralHunter,
  _poolGarrukWildspeaker,
  _poolGarruksUprising,
  _poolGazeOfGranite,
  _poolGenerousGift,
  _poolGenesisUltimatum,
  _poolGiantGrowth,
  _poolGiantSpider,
  _poolGlacialFortress,
  _poolGladecoverScout,
  _poolGloriousAnthem,
  _poolGoblinChieftain,
  _poolGoblinRaider,
  _poolGodlessShrine,
  _poolGrapeshot,
  _poolGravePact,
  _poolGreed,
  _poolGrizzlyBears,
  _poolGutShot,
  _poolHallowedFountain,
  _poolHarrow,
  _poolHarvesttideAssailant,
  _poolHarvesttideInfiltrator,
  _poolHeroicIntervention,
  _poolHillGiant,
  _poolHinterlandHarbor,
  _poolHistoryOfBenalia,
  _poolHolyStrength,
  _poolHookHauntDrifter,
  _poolHourOfReckoning,
  _poolHypnoticSpecter,
  _poolIcetillExplorer,
  _poolIgnobleHierarch,
  _poolInfernalGrasp,
  _poolInvisibleStalker,
  _poolIridescentVinelasher,
  _poolIsland,
  _poolIsolatedChapel,
  _poolJuggernaut,
  _poolJump,
  _poolKalonianHydra,
  _poolKarplusanForest,
  _poolKazanduMammoth,
  _poolKazanduValley,
  _poolKessigWolfRun,
  _poolKioraBehemothBeckoner,
  _poolKirdApe,
  _poolKolaghansCommand,
  _poolKorvoldFaeCursedKing,
  _poolLathlissDragonQueen,
  _poolLevitation,
  _poolLightningBolt,
  _poolLightningGreaves,
  _poolLlanowarElves,
  _poolLlanowarWastes,
  _poolLongtuskCub,
  _poolLordOfExtinction,
  _poolLordOfLineage,
  _poolLotusCobra,
  _poolLotusField,
  _poolLotusPetal,
  _poolLure,
  _poolMagmaquake,
  _poolManOWar,
  _poolManaConfluence,
  _poolManifoldKey,
  _poolMarshFlats,
  _poolMendingHands,
  _poolMiirymSentinelWyrm,
  _poolMindControl,
  _poolMindRot,
  _poolMindStone,
  _poolMishrasFactory,
  _poolMistyRainforest,
  _poolMoleManMoloidMaster,
  _poolMonasterySwiftspear,
  _poolMortivore,
  _poolMountain,
  _poolMudbuttonTorchrunner,
  _poolNaturalize,
  _poolNaturesLore,
  _poolNegate,
  _poolNotionThief,
  _poolObNixilisTheFallen,
  _poolOldGnawbone,
  _poolOpt,
  _poolOracleOfMulDaya,
  _poolOrcishLumberjack,
  _poolOtawaraSoaringCity,
  _poolOvergrownTomb,
  _poolPacifism,
  _poolPhyrexianArena,
  _poolPlains,
  _poolPollutedDelta,
  _poolPrairieStream,
  _poolPreordain,
  _poolPreyUpon,
  _poolPrincessSarah,
  _poolProdigalSorcerer,
  _poolProsperousInnkeeper,
  _poolPyroclasm,
  _poolRabidBite,
  _poolRagingGoblin,
  _poolRaiseTheAlarm,
  _poolRakdosCharm,
  _poolRampagingBaloths,
  _poolRampantGrowth,
  _poolRamunapExcavator,
  _poolRapidHybridization,
  _poolRaucousTheater,
  _poolRegrowth,
  _poolRestInPeace,
  _poolRiftBolt,
  _poolRiveteersOverlook,
  _poolRockfallVale,
  _poolRoguesPassage,
  _poolRootboundCrag,
  _poolRumblingBaloth,
  _poolRydiaSummonerOfMist,
  _poolSabotender,
  _poolSacredFoundry,
  _poolSakuraTribeElder,
  _poolSawInHalf,
  _poolScaldingTarn,
  _poolScourgeOfValkas,
  _poolScuteSwarm,
  _poolSerraAngel,
  _poolShelteredThicket,
  _poolShivanReef,
  _poolSidequestRaiseAChocobo,
  _poolSimicCharm,
  _poolSmolderingMarsh,
  _poolSnapcasterMage,
  _poolSolRing,
  _poolSolemnSimulacrum,
  _poolSoulWarden,
  _poolSplendidReclamation,
  _poolStarfieldVocalist,
  _poolSteamVents,
  _poolStompingGround,
  _poolSulfurFalls,
  _poolSulfurousSprings,
  _poolSummonTitan,
  _poolSunkenHollow,
  _poolSunpetalGrove,
  _poolSwamp,
  _poolSwiftfootBoots,
  _poolSylvanSafekeeper,
  _poolTakenumaAbandonedMire,
  _poolTalismanOfConviction,
  _poolTalismanOfCreativity,
  _poolTalismanOfCuriosity,
  _poolTalismanOfDominance,
  _poolTalismanOfHierarchy,
  _poolTalismanOfImpulse,
  _poolTalismanOfIndulgence,
  _poolTalismanOfProgress,
  _poolTalismanOfResilience,
  _poolTalismanOfUnity,
  _poolTanaTheBloodsower,
  _poolTannukMemorialEnsign,
  _poolTearAsunder,
  _poolTempleGarden,
  _poolTempleOfAbandon,
  _poolTempleOfMystery,
  _poolTemurAscendancy,
  _poolTemurBattlecrier,
  _poolTerramorphicExpanse,
  _poolTerrorOfThePeaks,
  _poolThaliaGuardianOfThraben,
  _poolThievingMagpie,
  _poolThornOfTheBlackRose,
  _poolThreaten,
  _poolThreeVisits,
  _poolTimeWarp,
  _poolTirelessProvisioner,
  _poolTomeScour,
  _poolTranquilThicket,
  _poolTurbulentFen,
  _poolTurnToFrog,
  _poolTwincast,
  _poolTyphoidRats,
  _poolUndergroundMortuary,
  _poolUndergroundRiver,
  _poolUnderworldRageHound,
  _poolUnnaturalGrowth,
  _poolUnsummon,
  _poolUreniOfTheUnwritten,
  _poolUrzasIncubator,
  _poolUtvaraHellkite,
  _poolVampireNighthawk,
  _poolVandalblast,
  _poolVerdantCatacombs,
  _poolVernalFen,
  _poolVoltCharge,
  _poolWalkingBallista,
  _poolWallOfWood,
  _poolWateryGrave,
  _poolWayfarersBauble,
  _poolWerebear,
  _poolWhiteKnight,
  _poolWillOfTheSultai,
  _poolWiltLeafCavaliers,
  _poolWindsweptHeath,
  _poolWoodedFoothills,
  _poolWoodlandCemetery,
  _poolWorldShaper,
  _poolWrathOfGod,
  _poolWurmcoilEngine,
  _poolYavimayaCoast,
  _poolZulaportCutthroat,
  _poolZuranOrb,
  _tokensBeastToken33,
  _tokensBeastToken,
  _tokensChocoboBirdToken,
  _tokensDragonToken55,
  _tokensDragonToken66,
  _tokensElementalToken,
  _tokensElephantToken,
  _tokensFoodToken,
  _tokensFrogLizardToken,
  _tokensInsectToken,
  _tokensKnightToken,
  _tokensLifelinkSoldierToken,
  _tokensMoloidToken,
  _tokensPhyrexianWurmDeathtouch,
  _tokensPhyrexianWurmLifelink,
  _tokensSaprolingToken,
  _tokensSoldierToken,
  _tokensTreasureToken,
  _tokensVampireToken,
];
