// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.
// Run `npm run gen:cards -w engine` after adding or removing a card file.

import type { CardDefinition } from "./define.js";

import _poolActOfTreason from "./pool/act-of-treason.js";
import _poolAmbushViper from "./pool/ambush-viper.js";
import _poolAngelicEdict from "./pool/angelic-edict.js";
import _poolArtificialEvolution from "./pool/artificial-evolution.js";
import _poolAshmarkMarduVanguard from "./pool/ashmark-mardu-vanguard.js";
import _poolBlaze from "./pool/blaze.js";
import _poolBlightning from "./pool/blightning.js";
import _poolBlinkmothNexus from "./pool/blinkmoth-nexus.js";
import _poolBloodthroneVampire from "./pool/bloodthrone-vampire.js";
import _poolBoggartBrute from "./pool/boggart-brute.js";
import _poolBonesplitter from "./pool/bonesplitter.js";
import _poolBoomerang from "./pool/boomerang.js";
import _poolClone from "./pool/clone.js";
import _poolContentiousPlan from "./pool/contentious-plan.js";
import _poolCounterspell from "./pool/counterspell.js";
import _poolCrawWurm from "./pool/craw-wurm.js";
import _poolDarksteelMyr from "./pool/darksteel-myr.js";
import _poolDeliberateCourse from "./pool/deliberate-course.js";
import _poolDisenchant from "./pool/disenchant.js";
import _poolDoomBlade from "./pool/doom-blade.js";
import _poolDoublingSeason from "./pool/doubling-season.js";
import _poolElvishVisionary from "./pool/elvish-visionary.js";
import _poolEssenceScatter from "./pool/essence-scatter.js";
import _poolExplorersInsight from "./pool/explorers-insight.js";
import _poolFencingAce from "./pool/fencing-ace.js";
import _poolFireball from "./pool/fireball.js";
import _poolFog from "./pool/fog.js";
import _poolForest from "./pool/forest.js";
import _poolFumeSpitter from "./pool/fume-spitter.js";
import _poolGiantGrowth from "./pool/giant-growth.js";
import _poolGiantSpider from "./pool/giant-spider.js";
import _poolGladecoverScout from "./pool/gladecover-scout.js";
import _poolGloriousAnthem from "./pool/glorious-anthem.js";
import _poolGoblinChieftain from "./pool/goblin-chieftain.js";
import _poolGoblinRaider from "./pool/goblin-raider.js";
import _poolGraveRecall from "./pool/grave-recall.js";
import _poolGrizzlyBears from "./pool/grizzly-bears.js";
import _poolHillGiant from "./pool/hill-giant.js";
import _poolHolyStrength from "./pool/holy-strength.js";
import _poolHypnoticSpecter from "./pool/hypnotic-specter.js";
import _poolIsland from "./pool/island.js";
import _poolJump from "./pool/jump.js";
import _poolLevitation from "./pool/levitation.js";
import _poolLightningBolt from "./pool/lightning-bolt.js";
import _poolLlanowarElves from "./pool/llanowar-elves.js";
import _poolLordOfExtinction from "./pool/lord-of-extinction.js";
import _poolManOWar from "./pool/man-o-war.js";
import _poolMindControl from "./pool/mind-control.js";
import _poolMindRot from "./pool/mind-rot.js";
import _poolMishrasFactory from "./pool/mishras-factory.js";
import _poolMonasterySwiftspear from "./pool/monastery-swiftspear.js";
import _poolMortivore from "./pool/mortivore.js";
import _poolMossbackDragon from "./pool/mossback-dragon.js";
import _poolMountain from "./pool/mountain.js";
import _poolNaturalize from "./pool/naturalize.js";
import _poolNegate from "./pool/negate.js";
import _poolOracleOfMulDaya from "./pool/oracle-of-mul-daya.js";
import _poolPhyrexianArena from "./pool/phyrexian-arena.js";
import _poolPlains from "./pool/plains.js";
import _poolPreyUpon from "./pool/prey-upon.js";
import _poolProdigalSorcerer from "./pool/prodigal-sorcerer.js";
import _poolRabidBite from "./pool/rabid-bite.js";
import _poolRagingGoblin from "./pool/raging-goblin.js";
import _poolRaiseTheAlarm from "./pool/raise-the-alarm.js";
import _poolRestInPeace from "./pool/rest-in-peace.js";
import _poolRumblingBaloth from "./pool/rumbling-baloth.js";
import _poolSerraAngel from "./pool/serra-angel.js";
import _poolSwamp from "./pool/swamp.js";
import _poolThievingMagpie from "./pool/thieving-magpie.js";
import _poolThreaten from "./pool/threaten.js";
import _poolTomeScour from "./pool/tome-scour.js";
import _poolTranquilThicket from "./pool/tranquil-thicket.js";
import _poolTurnToFrog from "./pool/turn-to-frog.js";
import _poolTyphoidRats from "./pool/typhoid-rats.js";
import _poolUnsummon from "./pool/unsummon.js";
import _poolUreniOfTheUnwritten from "./pool/ureni-of-the-unwritten.js";
import _poolVampireNighthawk from "./pool/vampire-nighthawk.js";
import _poolVengefulGhoul from "./pool/vengeful-ghoul.js";
import _poolVoltCharge from "./pool/volt-charge.js";
import _poolWalkingBallista from "./pool/walking-ballista.js";
import _poolWallOfWood from "./pool/wall-of-wood.js";
import _poolWhiteKnight from "./pool/white-knight.js";
import _poolWildwoodSentinel from "./pool/wildwood-sentinel.js";
import _poolWurmcoilEngine from "./pool/wurmcoil-engine.js";
import _tokensPhyrexianWurmDeathtouch from "./tokens/phyrexian-wurm-deathtouch.js";
import _tokensPhyrexianWurmLifelink from "./tokens/phyrexian-wurm-lifelink.js";
import _tokensSoldierToken from "./tokens/soldier-token.js";

/** The built-in card pool — every file under `pool/` and `tokens/`. */
export const BUILTIN_CARDS: readonly CardDefinition[] = [
  _poolActOfTreason,
  _poolAmbushViper,
  _poolAngelicEdict,
  _poolArtificialEvolution,
  _poolAshmarkMarduVanguard,
  _poolBlaze,
  _poolBlightning,
  _poolBlinkmothNexus,
  _poolBloodthroneVampire,
  _poolBoggartBrute,
  _poolBonesplitter,
  _poolBoomerang,
  _poolClone,
  _poolContentiousPlan,
  _poolCounterspell,
  _poolCrawWurm,
  _poolDarksteelMyr,
  _poolDeliberateCourse,
  _poolDisenchant,
  _poolDoomBlade,
  _poolDoublingSeason,
  _poolElvishVisionary,
  _poolEssenceScatter,
  _poolExplorersInsight,
  _poolFencingAce,
  _poolFireball,
  _poolFog,
  _poolForest,
  _poolFumeSpitter,
  _poolGiantGrowth,
  _poolGiantSpider,
  _poolGladecoverScout,
  _poolGloriousAnthem,
  _poolGoblinChieftain,
  _poolGoblinRaider,
  _poolGraveRecall,
  _poolGrizzlyBears,
  _poolHillGiant,
  _poolHolyStrength,
  _poolHypnoticSpecter,
  _poolIsland,
  _poolJump,
  _poolLevitation,
  _poolLightningBolt,
  _poolLlanowarElves,
  _poolLordOfExtinction,
  _poolManOWar,
  _poolMindControl,
  _poolMindRot,
  _poolMishrasFactory,
  _poolMonasterySwiftspear,
  _poolMortivore,
  _poolMossbackDragon,
  _poolMountain,
  _poolNaturalize,
  _poolNegate,
  _poolOracleOfMulDaya,
  _poolPhyrexianArena,
  _poolPlains,
  _poolPreyUpon,
  _poolProdigalSorcerer,
  _poolRabidBite,
  _poolRagingGoblin,
  _poolRaiseTheAlarm,
  _poolRestInPeace,
  _poolRumblingBaloth,
  _poolSerraAngel,
  _poolSwamp,
  _poolThievingMagpie,
  _poolThreaten,
  _poolTomeScour,
  _poolTranquilThicket,
  _poolTurnToFrog,
  _poolTyphoidRats,
  _poolUnsummon,
  _poolUreniOfTheUnwritten,
  _poolVampireNighthawk,
  _poolVengefulGhoul,
  _poolVoltCharge,
  _poolWalkingBallista,
  _poolWallOfWood,
  _poolWhiteKnight,
  _poolWildwoodSentinel,
  _poolWurmcoilEngine,
  _tokensPhyrexianWurmDeathtouch,
  _tokensPhyrexianWurmLifelink,
  _tokensSoldierToken,
];
