/**
 * Card definitions and the registry that resolves a card name to its printed
 * characteristics.
 *
 * This module is now a thin barrel — the real content lives in `cards/`:
 *   - `cards/define.ts`   — the `CardDefinition` shape + `defineCard` builder
 *   - `cards/helpers.ts`  — `basicLand`, `manaTapAbility`, `landProduces`
 *   - `cards/registry.ts` — `CardRegistry`, `createDefaultRegistry`
 *   - `cards/generated.ts`— `BUILTIN_CARDS`, stitched from one file per card
 *     under `cards/pool/` and `cards/tokens/` (regenerated by
 *     `scripts/gen-cards.mjs`, run as a `prebuild` step)
 *
 * Everything is re-exported here so existing `import … from "./cards.js"`
 * sites elsewhere in the engine are unaffected.
 */

export * from "./cards/define.js";
export * from "./cards/helpers.js";
export * from "./cards/registry.js";
export { BUILTIN_CARDS } from "./cards/generated.js";
