/**
 * The starter decks: the five 2022 Starter Commander Decks (MTGJSON set code
 * `SCD`), each a real, format-legal 100-card Commander deck.
 *
 * Two consumers: `server/src/decks.ts`'s `SEATS` (a room's fallback deck for
 * a seat nobody brought their own deck to, and every bot's deck) and the
 * client's deck builder (offered as ready-made "starter decks" to play as-is
 * or duplicate and edit) — lives here, in the engine, so both share one
 * source of truth instead of each keeping its own copy.
 *
 * **Substitutions.** Each deck's `printed` list is the decklist exactly as
 * printed. A card the engine doesn't implement yet is swapped out through that
 * deck's `substitutions` table rather than edited out of the list, so the
 * printed list stays the record of what the real deck is. Each substitute was
 * hand-picked to stay inside the commander's colour identity, not duplicate a
 * card already in the deck (singleton), and fill the same role at a similar
 * mana value — see `docs/plans/precon-decks.md`.
 *
 * **To revert one** once its card is implemented, delete its entry from the
 * table. `sample-decks.test.ts` fails for any substitution whose original is
 * now implemented, so none can outlive the reason for it.
 */

export interface PreconSubstitution {
  /** The printed card the engine doesn't implement yet. */
  readonly original: string;
  /** The implemented card playing in its slot. */
  readonly substitute: string;
  /** Why this card: the role it shares with the original. */
  readonly reason: string;
}

export interface SampleDeck {
  readonly name: string;
  readonly commander?: string;
  /** What the deck plays: `printed` with `substitutions` applied. */
  readonly cards: readonly string[];
  /** One line on what the deck does. */
  readonly description?: string;
  /** The 99 exactly as printed, for a real precon. */
  readonly printed?: readonly string[];
  readonly substitutions?: readonly PreconSubstitution[];
}

const list = (entries: readonly (readonly [string, number])[]): string[] =>
  entries.flatMap(([name, count]) => Array<string>(count).fill(name));

const sub = (original: string, substitute: string, reason: string): PreconSubstitution => ({
  original,
  substitute,
  reason,
});

function precon(deck: {
  readonly name: string;
  readonly commander: string;
  readonly description: string;
  readonly printed: readonly (readonly [string, number])[];
  readonly substitutions: readonly PreconSubstitution[];
}): SampleDeck {
  const printed = list(deck.printed);
  const swap = new Map(deck.substitutions.map((s) => [s.original, s.substitute]));
  for (const original of swap.keys()) {
    if (!printed.includes(original)) {
      throw new Error(`${deck.name}: substitution for ${original}, which isn't in the printed list`);
    }
  }
  return {
    name: deck.name,
    commander: deck.commander,
    description: deck.description,
    printed,
    substitutions: deck.substitutions,
    cards: printed.map((name) => swap.get(name) ?? name),
  };
}

export const SAMPLE_DECKS: readonly SampleDeck[] = [
  precon({
    name: "Draconic Destruction",
    commander: "Atarka, World Render",
    description: "Red-green Dragons: ramp into big fliers and burn.",
    printed: [
      ["Akoum Hellkite", 1],
      ["Chain Reaction", 1],
      ["Crucible of Fire", 1],
      ["Demanding Dragon", 1],
      ["Dragonkin Berserker", 1],
      ["Dragonmaster Outcast", 1],
      ["Drakuseth, Maw of Flames", 1],
      ["Dream Pillager", 1],
      ["Flameblast Dragon", 1],
      ["Hoard-Smelter Dragon", 1],
      ["Magmaquake", 1],
      ["Mordant Dragon", 1],
      ["Runehorn Hellkite", 1],
      ["Sarkhan, the Dragonspeaker", 1],
      ["Scourge of Valkas", 1],
      ["Spit Flame", 1],
      ["Sweltering Suns", 1],
      ["Thunderbreak Regent", 1],
      ["Thundermaw Hellkite", 1],
      ["Tyrant's Familiar", 1],
      ["Verix Bladewing", 1],
      ["Foe-Razer Regent", 1],
      ["Frontier Siege", 1],
      ["Hunter's Prowess", 1],
      ["Primal Might", 1],
      ["Shamanic Revelation", 1],
      ["Clan Defiance", 1],
      ["Harbinger of the Hunt", 1],
      ["Dragon's Hoard", 1],
      ["Steel Hellkite", 1],
      ["Cinder Glade", 1],
      ["Game Trail", 1],
      ["Haven of the Spirit Dragon", 1],
      ["Temple of Abandon", 1],
      ["Dragon Mage", 1],
      ["Dragon Tempest", 1],
      ["Dragonlord's Servant", 1],
      ["Dragonspeaker Shaman", 1],
      ["Furnace Whelp", 1],
      ["Provoke the Trolls", 1],
      ["Rapacious Dragon", 1],
      ["Unleash Fury", 1],
      ["Vandalblast", 1],
      ["Beast Within", 1],
      ["Blossoming Defense", 1],
      ["Cultivate", 1],
      ["Drumhunter", 1],
      ["Elemental Bond", 1],
      ["Garruk's Uprising", 1],
      ["Harmonize", 1],
      ["Hunter's Insight", 1],
      ["Loaming Shaman", 1],
      ["Return to Nature", 1],
      ["Sakura-Tribe Elder", 1],
      ["Draconic Disciple", 1],
      ["Fires of Yavimaya", 1],
      ["Savage Ventmaw", 1],
      ["Arcane Signet", 1],
      ["Atarka Monument", 1],
      ["Commander's Sphere", 1],
      ["Sol Ring", 1],
      ["Swiftfoot Boots", 1],
      ["Talisman of Impulse", 1],
      ["Command Tower", 1],
      ["Kazandu Refuge", 1],
      ["Path of Ancestry", 1],
      ["Rugged Highlands", 1],
      ["Shivan Oasis", 1],
      ["Timber Gorge", 1],
      ["Mountain", 18],
      ["Forest", 12],
    ],
    substitutions: [
      sub(
        "Sarkhan, the Dragonspeaker",
        "Garruk Wildspeaker",
        "Green planeswalker that makes creatures and has an overrun finisher.",
      ),
      sub(
        "Foe-Razer Regent",
        "Old Gnawbone",
        "Seven-mana green flying Dragon.",
      ),
      sub(
        "Savage Ventmaw",
        "Lathliss, Dragon Queen",
        "Six-mana flying Dragon.",
      ),
      sub(
        "Loaming Shaman",
        "Scavenging Ooze",
        "Cheap green creature that interacts with graveyards.",
      ),
      sub(
        "Haven of the Spirit Dragon",
        "Kessig Wolf Run",
        "Utility land that taps for colorless.",
      ),
    ],
  }),
  precon({
    name: "Chaos Incarnate",
    commander: "Kardur, Doomscourge",
    description: "Black-red chaos: goad, punisher effects and symmetric damage.",
    printed: [
      ["Archfiend of Depravity", 1],
      ["Bloodgift Demon", 1],
      ["Deadly Tempest", 1],
      ["Dredge the Mire", 1],
      ["Ob Nixilis Reignited", 1],
      ["Profane Command", 1],
      ["Rakshasa Debaser", 1],
      ["Reign of the Pit", 1],
      ["Sangromancer", 1],
      ["Scythe Specter", 1],
      ["Sepulchral Primordial", 1],
      ["Soul Shatter", 1],
      ["Titan Hunter", 1],
      ["Blasphemous Act", 1],
      ["Brash Taunter", 1],
      ["Chaos Warp", 1],
      ["Combustible Gearhulk", 1],
      ["Dictate of the Twin Gods", 1],
      ["Fiery Confluence", 1],
      ["Geode Rager", 1],
      ["Kazuul, Tyrant of the Cliffs", 1],
      ["Magmatic Force", 1],
      ["Sunbird's Invocation", 1],
      ["Tectonic Giant", 1],
      ["Wild Ricochet", 1],
      ["Wildfire Devils", 1],
      ["Kaervek the Merciless", 1],
      ["Spiteful Visions", 1],
      ["Stormfist Crusader", 1],
      ["Theater of Horrors", 1],
      ["Coveted Jewel", 1],
      ["Solemn Simulacrum", 1],
      ["Foreboding Ruins", 1],
      ["Smoldering Marsh", 1],
      ["Stensia Bloodhall", 1],
      ["Temple of Malice", 1],
      ["Ambition's Cost", 1],
      ["Feed the Swarm", 1],
      ["Indulgent Tormentor", 1],
      ["Read the Bones", 1],
      ["Sign in Blood", 1],
      ["Syphon Mind", 1],
      ["Vampire Nighthawk", 1],
      ["Abrade", 1],
      ["Explosion of Riches", 1],
      ["Guttersnipe", 1],
      ["Hate Mirage", 1],
      ["Mana Geyser", 1],
      ["Thermo-Alchemist", 1],
      ["Breath of Malfegor", 1],
      ["Rakdos Charm", 1],
      ["Terminate", 1],
      ["Unlicensed Disintegration", 1],
      ["Arcane Signet", 1],
      ["Burnished Hart", 1],
      ["Commander's Sphere", 1],
      ["Lightning Greaves", 1],
      ["Nihil Spellbomb", 1],
      ["Rakdos Signet", 1],
      ["Sol Ring", 1],
      ["Talisman of Indulgence", 1],
      ["Wayfarer's Bauble", 1],
      ["Worn Powerstone", 1],
      ["Akoum Refuge", 1],
      ["Bloodfell Caves", 1],
      ["Cinder Barrens", 1],
      ["Command Tower", 1],
      ["Molten Slagheap", 1],
      ["Myriad Landscape", 1],
      ["Urborg Volcano", 1],
      ["Swamp", 15],
      ["Mountain", 14],
    ],
    substitutions: [
      sub(
        "Deadly Tempest",
        "Damnation",
        "Destroy-all-creatures sorcery.",
      ),
      sub(
        "Dredge the Mire",
        "Victimize",
        "Reanimation sorcery.",
      ),
      sub(
        "Ob Nixilis Reignited",
        "Ob Nixilis, the Fallen",
        "Same-cost black Ob Nixilis that drains life; the only implemented black-red planeswalker is a three-mana Chandra.",
      ),
      sub(
        "Profane Command",
        "Kolaghan's Command",
        "Modal black-red Command with a recursion mode.",
      ),
      sub(
        "Reign of the Pit",
        "Fleshbag Marauder",
        "Each player sacrifices a creature.",
      ),
      sub(
        "Scythe Specter",
        "Hypnotic Specter",
        "Flying Specter that makes opponents discard.",
      ),
      sub(
        "Sepulchral Primordial",
        "Overseer of the Damned",
        "Seven-mana black top-end with an enters-the-battlefield payoff.",
      ),
      sub(
        "Soul Shatter",
        "Diabolic Edict",
        "Instant-speed edict.",
      ),
      sub(
        "Chaos Warp",
        "Infernal Grasp",
        "Cheap instant removal.",
      ),
      sub(
        "Combustible Gearhulk",
        "Demanding Dragon",
        "Punisher creature: the opponent picks the lesser evil.",
      ),
      sub(
        "Fiery Confluence",
        "Chain Reaction",
        "Four-mana red sweeper.",
      ),
      sub(
        "Sunbird's Invocation",
        "Phyrexian Arena",
        "Card-advantage enchantment.",
      ),
      sub(
        "Wild Ricochet",
        "Act of Treason",
        "Uses an opponent's resources against them.",
      ),
      sub(
        "Wildfire Devils",
        "Cinder Elemental",
        "Four-mana red creature that turns into damage.",
      ),
      sub(
        "Spiteful Visions",
        "Greed",
        "Four-mana card-draw enchantment paid for in life.",
      ),
      sub(
        "Coveted Jewel",
        "Hedron Archive",
        "Mana rock that cashes in for cards.",
      ),
      sub(
        "Syphon Mind",
        "Blightning",
        "Makes opponents discard.",
      ),
      sub(
        "Explosion of Riches",
        "Fireball",
        "Top-end damage spell aimed at opponents.",
      ),
      sub(
        "Molten Slagheap",
        "Sulfurous Springs",
        "Land that makes both colours.",
      ),
      sub(
        "Myriad Landscape",
        "Evolving Wilds",
        "Sacrifice-to-fetch basic land.",
      ),
    ],
  }),
  precon({
    name: "First Flight",
    commander: "Isperia, Supreme Judge",
    description: "White-blue fliers: evasive creatures, card draw and countermagic.",
    printed: [
      ["Archon of Redemption", 1],
      ["Cartographer's Hawk", 1],
      ["Cleansing Nova", 1],
      ["Emeria Angel", 1],
      ["Gideon Jura", 1],
      ["Hanged Executioner", 1],
      ["Remorseful Cleric", 1],
      ["Sephara, Sky's Blade", 1],
      ["Steel-Plume Marshal", 1],
      ["Storm Herd", 1],
      ["True Conviction", 1],
      ["Angler Turtle", 1],
      ["Bident of Thassa", 1],
      ["Diluvian Primordial", 1],
      ["Ever-Watching Threshold", 1],
      ["Faerie Formation", 1],
      ["Gravitational Shift", 1],
      ["Inspired Sphinx", 1],
      ["Sharding Sphinx", 1],
      ["Sphinx of Enlightenment", 1],
      ["Windreader Sphinx", 1],
      ["Absorb", 1],
      ["Skycat Sovereign", 1],
      ["Sphinx's Revelation", 1],
      ["Time Wipe", 1],
      ["Moorland Haunt", 1],
      ["Port Town", 1],
      ["Prairie Stream", 1],
      ["Temple of Enlightenment", 1],
      ["Aven Gagglemaster", 1],
      ["Banishing Light", 1],
      ["Condemn", 1],
      ["Crush Contraband", 1],
      ["Disenchant", 1],
      ["Generous Gift", 1],
      ["Kangee's Lieutenant", 1],
      ["Rally of Wings", 1],
      ["Soul Snare", 1],
      ["Swords to Plowshares", 1],
      ["Vow of Duty", 1],
      ["Aetherize", 1],
      ["Counterspell", 1],
      ["Favorable Winds", 1],
      ["Negate", 1],
      ["Tide Skimmer", 1],
      ["Warden of Evos Isle", 1],
      ["Winged Words", 1],
      ["Cloudblazer", 1],
      ["Empyrean Eagle", 1],
      ["Jubilant Skybonder", 1],
      ["Kangee, Sky Warden", 1],
      ["Migratory Route", 1],
      ["Staggering Insight", 1],
      ["Thunderclap Wyvern", 1],
      ["Arcane Signet", 1],
      ["Azorius Signet", 1],
      ["Commander's Sphere", 1],
      ["Hedron Archive", 1],
      ["Pilgrim's Eye", 1],
      ["Sky Diamond", 1],
      ["Skyscanner", 1],
      ["Sol Ring", 1],
      ["Talisman of Progress", 1],
      ["Thought Vessel", 1],
      ["Coastal Tower", 1],
      ["Command Tower", 1],
      ["Meandering River", 1],
      ["Sejiri Refuge", 1],
      ["Tranquil Cove", 1],
      ["Plains", 15],
      ["Island", 15],
    ],
    substitutions: [
      sub(
        "Cartographer's Hawk",
        "Baithook Angler",
        "Two-drop that comes back as a flier.",
      ),
      sub(
        "Gideon Jura",
        "Ajani, Caller of the Pride",
        "White planeswalker; its -3 grants flying.",
      ),
      sub(
        "Angler Turtle",
        "Serra Angel",
        "Large creature, and a flier, which Isperia rewards.",
      ),
      sub(
        "Diluvian Primordial",
        "Steel Hellkite",
        "Large flying finisher.",
      ),
      sub(
        "Moorland Haunt",
        "Blinkmoth Nexus",
        "Utility land that makes a flier.",
      ),
      sub(
        "Jubilant Skybonder",
        "Thieving Magpie",
        "Blue flier that draws cards.",
      ),
    ],
  }),
  precon({
    name: "Token Triumph",
    commander: "Emmara, Soul of the Accord",
    description: "Green-white tokens: go wide, then pump the team.",
    printed: [
      ["Ajani, Caller of the Pride", 1],
      ["Citywide Bust", 1],
      ["Commander's Insignia", 1],
      ["Dawn of Hope", 1],
      ["Dictate of Heliod", 1],
      ["Felidar Retreat", 1],
      ["Hour of Reckoning", 1],
      ["Mentor of the Meek", 1],
      ["White Sun's Zenith", 1],
      ["Champion of Lambholt", 1],
      ["Citanul Hierophants", 1],
      ["Collective Unconscious", 1],
      ["Harvest Season", 1],
      ["Hornet Nest", 1],
      ["Hornet Queen", 1],
      ["Rishkar, Peema Renegade", 1],
      ["Scavenging Ooze", 1],
      ["Thunderfoot Baloth", 1],
      ["Verdant Force", 1],
      ["Aura Mutation", 1],
      ["Camaraderie", 1],
      ["Collective Blessing", 1],
      ["Dauntless Escort", 1],
      ["March of the Multitudes", 1],
      ["Trostani Discordant", 1],
      ["Idol of Oblivion", 1],
      ["Slate of Ancestry", 1],
      ["Canopy Vista", 1],
      ["Fortified Village", 1],
      ["Temple of Plenty", 1],
      ["Conclave Tribunal", 1],
      ["Devouring Light", 1],
      ["Path to Exile", 1],
      ["Rootborn Defenses", 1],
      ["Valor in Akros", 1],
      ["Avacyn's Pilgrim", 1],
      ["Curse of Bounty", 1],
      ["Eternal Witness", 1],
      ["Farhaven Elf", 1],
      ["Great Oak Guardian", 1],
      ["Harmonize", 1],
      ["Jade Mage", 1],
      ["Jaspera Sentinel", 1],
      ["Karametra's Favor", 1],
      ["Leafkin Druid", 1],
      ["Loyal Guardian", 1],
      ["Nissa's Expedition", 1],
      ["Nullmage Shepherd", 1],
      ["Overrun", 1],
      ["Overwhelming Instinct", 1],
      ["Presence of Gond", 1],
      ["Reclamation Sage", 1],
      ["Scatter the Seeds", 1],
      ["Sporemound", 1],
      ["Voice of Many", 1],
      ["Maja, Bretagard Protector", 1],
      ["Selesnya Evangel", 1],
      ["Selesnya Guildmage", 1],
      ["Sylvan Reclamation", 1],
      ["Arcane Signet", 1],
      ["Commander's Sphere", 1],
      ["Sol Ring", 1],
      ["Talisman of Unity", 1],
      ["Blossoming Sands", 1],
      ["Command Tower", 1],
      ["Elfhame Palace", 1],
      ["Graypelt Refuge", 1],
      ["Holdout Settlement", 1],
      ["Tranquil Expanse", 1],
      ["Vitu-Ghazi, the City-Tree", 1],
      ["Forest", 15],
      ["Plains", 14],
    ],
    substitutions: [
      sub(
        "Champion of Lambholt",
        "Hanged Executioner",
        "Three-mana creature that goes wide.",
      ),
      sub(
        "Trostani Discordant",
        "Glorious Anthem",
        "The anthem half of Trostani.",
      ),
      sub(
        "Curse of Bounty",
        "Raise the Alarm",
        "Two-mana token maker.",
      ),
    ],
  }),
  precon({
    name: "Grave Danger",
    commander: "Gisa and Geralf",
    description: "Blue-black Zombies: mill, recursion and sacrifice payoffs.",
    printed: [
      ["Geralf's Mindcrusher", 1],
      ["Laboratory Drudge", 1],
      ["Army of the Damned", 1],
      ["Cemetery Reaper", 1],
      ["Champion of the Perished", 1],
      ["Crippling Fear", 1],
      ["Gravespawn Sovereign", 1],
      ["Josu Vess, Lich Knight", 1],
      ["Liliana, Untouched by Death", 1],
      ["Liliana's Mastery", 1],
      ["Liliana's Standard Bearer", 1],
      ["Midnight Reaper", 1],
      ["Necromantic Selection", 1],
      ["Necrotic Hex", 1],
      ["Open the Graves", 1],
      ["Overseer of the Damned", 1],
      ["Scourge of Nel Toth", 1],
      ["Unbreathing Horde", 1],
      ["Zombie Apocalypse", 1],
      ["Enter the God-Eternals", 1],
      ["Havengul Lich", 1],
      ["Undermine", 1],
      ["Vela the Night-Clad", 1],
      ["Grimoire of the Dead", 1],
      ["Choked Estuary", 1],
      ["Sunken Hollow", 1],
      ["Temple of Deceit", 1],
      ["Deep Analysis", 1],
      ["Distant Melody", 1],
      ["Eternal Skylord", 1],
      ["Lazotep Plating", 1],
      ["Sinister Sabotage", 1],
      ["Cruel Revival", 1],
      ["Curse of Disturbance", 1],
      ["Feed the Swarm", 1],
      ["Fleshbag Marauder", 1],
      ["Gray Merchant of Asphodel", 1],
      ["Lazotep Reaver", 1],
      ["Liliana's Devotee", 1],
      ["Lord of the Accursed", 1],
      ["Lotleth Giant", 1],
      ["Loyal Subordinate", 1],
      ["Mire Triton", 1],
      ["Murder", 1],
      ["Spark Reaper", 1],
      ["Syphon Flesh", 1],
      ["Undead Augur", 1],
      ["Vampiric Rites", 1],
      ["Vengeful Dead", 1],
      ["Victimize", 1],
      ["Vizier of the Scorpion", 1],
      ["Withered Wretch", 1],
      ["Diregraf Captain", 1],
      ["Gleaming Overseer", 1],
      ["Pilfered Plans", 1],
      ["Arcane Signet", 1],
      ["Commander's Sphere", 1],
      ["Dimir Signet", 1],
      ["Heraldic Banner", 1],
      ["Sol Ring", 1],
      ["Talisman of Dominance", 1],
      ["Unstable Obelisk", 1],
      ["Wayfarer's Bauble", 1],
      ["Command Tower", 1],
      ["Dismal Backwater", 1],
      ["Jwar Isle Refuge", 1],
      ["Salt Marsh", 1],
      ["Submerged Boneyard", 1],
      ["Island", 13],
      ["Swamp", 18],
    ],
    substitutions: [
      sub(
        "Liliana, Untouched by Death",
        "Mortivore",
        "Four-mana black card that grows with graveyards; no blue-black planeswalker is implemented.",
      ),
      sub(
        "Necromantic Selection",
        "Damnation",
        "Destroy-all-creatures sorcery.",
      ),
      sub(
        "Scourge of Nel Toth",
        "Rakshasa Debaser",
        "Six-mana black finisher that returns creatures from graveyards to the battlefield.",
      ),
      sub(
        "Unbreathing Horde",
        "Vampire Nighthawk",
        "Three-mana black creature.",
      ),
      sub(
        "Havengul Lich",
        "Bloodgift Demon",
        "Five-mana value creature.",
      ),
      sub(
        "Grimoire of the Dead",
        "Slate of Ancestry",
        "Four-mana late-game artifact.",
      ),
      sub(
        "Curse of Disturbance",
        "Phyrexian Arena",
        "Three-mana black enchantment.",
      ),
      sub(
        "Syphon Flesh",
        "Diabolic Edict",
        "Makes an opponent sacrifice a creature.",
      ),
    ],
  }),
];
