/**
 * The starter decks: real, format-legal 100-card Commander precons. First the
 * five Tarkir: Dragonstorm Commander decks (2025, MTGJSON set code `TDC`),
 * the bots' defaults since 2026-09-30, two of them flagged `bench`; then
 * (2026-10-02) the five 2022 Starter Commander Decks (`SCD`) they replaced and
 * four more picked as nearest complete among WotC's Commander precons:
 * Tramplesaurus Rex and Reign of Dragons (`FDC`), Family Matters (`BLC`) and
 * World Shaper (`EOC`).
 *
 * **`bench`.** The bot tooling (`engine/scripts/bot-seating.mjs`) seats only
 * `BENCH_DECKS`, so a benchmark measures the bots on the same decks from one
 * run to the next; the rest are starter decks for players and bot seats. Flag
 * a deck once a deck-against-deck run shows it holds its own when identical
 * bots play it — a deck that loses every game measures nothing about a bot.
 * Since 2026-10-03 (the user's call, after `docs/plans/deck-autopsies.md`'s
 * re-run): Abzan Armor, Jeskai Striker, Reign of Dragons and Token Triumph.
 * Temur Roar (71%) and Mardu Surge (12.5%) stay starter decks but off the
 * bench; the two in their place keep a Dragon deck and a token deck on it.
 *
 * Two consumers: `server/src/decks.ts`'s `SEATS` (a room's fallback deck for
 * a seat nobody brought their own deck to, and every bot's deck) and the
 * client's deck builder (offered as ready-made "starter decks" to play as-is
 * or duplicate and edit) — lives here, in the engine, so both share one
 * source of truth instead of each keeping its own copy.
 *
 * **Substitutions.** Each deck's `printed` list is the decklist exactly as
 * printed. A card the engine doesn't implement yet is swapped out through that
 * deck's `substitutions` table rather than edited out of the list, so the
 * printed list stays the record of what the real deck is. Each substitute was
 * picked to stay inside the commander's colour identity, not duplicate a card
 * already in the deck (singleton), and fill the same role at a similar mana
 * value — a Dragon for a Dragon in Temur Roar, a wall for a wall in Abzan
 * Armor — see `docs/plans/precon-decks.md`.
 *
 * **To revert one** once its card is implemented, delete its entry from the
 * table. `sample-decks.test.ts` fails for any substitution whose original is
 * now implemented, so none can outlive the reason for it.
 */

export interface PreconSubstitution {
  /** The printed card the engine doesn't implement yet. */
  readonly original: string;
  /** The implemented card playing in its slot. */
  readonly substitute: string;
  /** Why this card: the role it shares with the original. */
  readonly reason: string;
}

export interface SampleDeck {
  readonly name: string;
  /** In the bots' benchmark pool (`BENCH_DECKS`) — see the header. */
  readonly bench?: boolean;
  readonly commanders?: readonly string[];
  /** What the deck plays: `printed` with `substitutions` applied. */
  readonly cards: readonly string[];
  /** One line on what the deck does. */
  readonly description?: string;
  /** The 99 exactly as printed, for a real precon. */
  readonly printed?: readonly string[];
  readonly substitutions?: readonly PreconSubstitution[];
}

const list = (entries: readonly (readonly [string, number])[]): string[] =>
  entries.flatMap(([name, count]) => Array<string>(count).fill(name));

const sub = (original: string, substitute: string, reason: string): PreconSubstitution => ({
  original,
  substitute,
  reason,
});

function precon(deck: {
  readonly name: string;
  readonly bench?: boolean;
  readonly commander: string;
  readonly description: string;
  readonly printed: readonly (readonly [string, number])[];
  readonly substitutions: readonly PreconSubstitution[];
}): SampleDeck {
  const printed = list(deck.printed);
  const swap = new Map(deck.substitutions.map((s) => [s.original, s.substitute]));
  for (const original of swap.keys()) {
    if (!printed.includes(original)) {
      throw new Error(`${deck.name}: substitution for ${original}, which isn't in the printed list`);
    }
  }
  return {
    name: deck.name,
    ...(deck.bench === true ? { bench: true } : {}),
    commanders: [deck.commander],
    description: deck.description,
    printed,
    substitutions: deck.substitutions,
    cards: printed.map((name) => swap.get(name) ?? name),
  };
}

export const SAMPLE_DECKS: readonly SampleDeck[] = [
  precon({
    name: "Temur Roar",
    commander: "Ureni of the Unwritten",
    description: "Temur Dragons: ramp, then Ureni digs Dragons out of the library onto the battlefield.",
    printed: [
      ["Arcane Signet", 1],
      ["Atarka, World Render", 1],
      ["Atsushi, the Blazing Sky", 1],
      ["Beast Within", 1],
      ["Become the Avalanche", 1],
      ["Blasphemous Act", 1],
      ["Bountiful Landscape", 1],
      ["Breaching Dragonstorm", 1],
      ["Broodcaller Scourge", 1],
      ["Chaos Warp", 1],
      ["Cinder Glade", 1],
      ["Command Tower", 1],
      ["Deceptive Frostkite", 1],
      ["Draconic Lore", 1],
      ["Dragon Tempest", 1],
      ["Dragon's Hoard", 1],
      ["Dragonlord Atarka", 1],
      ["Dragonlord's Servant", 1],
      ["Dragonmaster Outcast", 1],
      ["Elemental Bond", 1],
      ["Encroaching Dragonstorm", 1],
      ["Eshki, Temur's Roar", 1],
      ["Evolving Wilds", 1],
      ["Exotic Orchard", 1],
      ["Farseek", 1],
      ["Fellwar Stone", 1],
      ["Flooded Grove", 1],
      ["Forest", 5],
      ["Frontier Bivouac", 1],
      ["Frontier Siege", 1],
      ["Gadrak, the Crown-Scourge", 1],
      ["Glorybringer", 1],
      ["Hammerhead Tyrant", 1],
      ["Harbinger of the Hunt", 1],
      ["Haven of the Spirit Dragon", 1],
      ["Hellkite Courser", 1],
      ["Hinterland Harbor", 1],
      ["Island", 3],
      ["Karplusan Forest", 1],
      ["Keiga, the Tide Star", 1],
      ["Kessig Wolf Run", 1],
      ["Kodama's Reach", 1],
      ["Lathliss, Dragon Queen", 1],
      ["Leyline Tyrant", 1],
      ["Migration Path", 1],
      ["Mossfire Valley", 1],
      ["Mosswort Bridge", 1],
      ["Mountain", 6],
      ["Nesting Dragon", 1],
      ["Nogi, Draco-Zealot", 1],
      ["Opportunistic Dragon", 1],
      ["Parapet Thrasher", 1],
      ["Path of Ancestry", 1],
      ["Rapacious Dragon", 1],
      ["Rapid Hybridization", 1],
      ["Reality Shift", 1],
      ["Reflections of Littjara", 1],
      ["Rockfall Vale", 1],
      ["Rootbound Crag", 1],
      ["Sarkhan, Soul Aflame", 1],
      ["Scourge of the Throne", 1],
      ["Selvala's Stampede", 1],
      ["Sheltered Thicket", 1],
      ["Shivan Reef", 1],
      ["Skarrgan Hellkite", 1],
      ["Sol Ring", 1],
      ["Spit Flame", 1],
      ["Steel Hellkite", 1],
      ["Storm's Wrath", 1],
      ["Stormbreath Dragon", 1],
      ["Stormshriek Feral", 1],
      ["Sulfur Falls", 1],
      ["Talisman of Creativity", 1],
      ["Talisman of Impulse", 1],
      ["Taurean Mauler", 1],
      ["Temple of Abandon", 1],
      ["Temple of Mystery", 1],
      ["Temple of the Dragon Queen", 1],
      ["Temur Ascendancy", 1],
      ["Territorial Hellkite", 1],
      ["Thunderbreak Regent", 1],
      ["Thundermane Dragon", 1],
      ["Vengeful Ancestor", 1],
      ["Verix Bladewing", 1],
      ["Whirlwing Stormbrood", 1],
      ["Will of the Temur", 1],
      ["Yavimaya Coast", 1],
      ["Zenith Festival", 1],
    ],
    substitutions: [
      sub("Hellkite Courser", "Rorix Bladewing", "Six-mana red flying Dragon with haste."),
      sub("Leyline Tyrant", "Archwing Dragon", "Four-mana red flying Dragon."),
      sub("Opportunistic Dragon", "Skyship Stalker", "Four-mana red flying Dragon."),
      sub("Reality Shift", "Resculpt", "Two-mana instant: removal, creature removal."),
      sub("Sarkhan, Soul Aflame", "Goreclaw, Terror of Qal Sisma", "Makes the deck's big creatures cheaper."),
      sub("Scourge of the Throne", "Savage Ventmaw", "Six-mana red-green flying Dragon that rewards attacking."),
      sub("Selvala's Stampede", "Kodama of the East Tree", "Six-mana sorcery: puts creatures onto the battlefield, ramp."),
      sub("Temple of the Dragon Queen", "Game Trail", "Land that makes the deck's colours."),
      sub("Territorial Hellkite", "Young Red Dragon", "Four-mana red Dragon."),
      sub("Zenith Festival", "Reckless Impulse", "Two-mana sorcery: impulse draw, card advantage."),
    ],
  }),
  precon({
    name: "Sultai Arisen",
    // Off the bench (2026-10-02): about 11% under v1 and v2 alike in the
    // deck-against-deck run — a strong deck the bots can't pilot (self-mill,
    // lands and creatures back from the graveyard), so it measured nothing.
    commander: "Teval, the Balanced Scale",
    description: "Sultai graveyard: mill yourself, bring lands and creatures back, and make Zombies as cards leave the graveyard.",
    printed: [
      ["Afterlife from the Loam", 1],
      ["Amphin Mutineer", 1],
      ["Arcane Signet", 1],
      ["Avenger of Zendikar", 1],
      ["Casualties of War", 1],
      ["Cephalid Coliseum", 1],
      ["Colossal Grave-Reaver", 1],
      ["Command Beacon", 1],
      ["Command Tower", 1],
      ["Conduit of Worlds", 1],
      ["Consuming Aberration", 1],
      ["Contaminated Aquifer", 1],
      ["Crawling Sensation", 1],
      ["Crypt of Agadeem", 1],
      ["Cultivate", 1],
      ["Darkwater Catacombs", 1],
      ["Dauthi Voidwalker", 1],
      ["Disciple of Bolas", 1],
      ["Diviner of Mist", 1],
      ["Dreamroot Cascade", 1],
      ["Drownyard Temple", 1],
      ["Essence Anchor", 1],
      ["Exotic Orchard", 1],
      ["Farseek", 1],
      ["Fetid Pools", 1],
      ["Floral Evoker", 1],
      ["Forbidden Alchemy", 1],
      ["Foreboding Landscape", 1],
      ["Forest", 6],
      ["Golgari Rot Farm", 1],
      ["Grapple with the Past", 1],
      ["Gravecrawler", 1],
      ["Grisly Salvage", 1],
      ["Harrow", 1],
      ["Haunted Mire", 1],
      ["Hedron Crab", 1],
      ["Hinterland Harbor", 1],
      ["Island", 4],
      ["Jarad, Golgari Lich Lord", 1],
      ["Junji, the Midnight Sky", 1],
      ["Kishla Skimmer", 1],
      ["Kotis, Sibsig Champion", 1],
      ["Lethal Scheme", 1],
      ["Life from the Loam", 1],
      ["Living Death", 1],
      ["Llanowar Wastes", 1],
      ["Lord of Extinction", 1],
      ["Lord of the Forsaken", 1],
      ["Memorial to Folly", 1],
      ["Meren of Clan Nel Toth", 1],
      ["Millikin", 1],
      ["Multani, Yavimaya's Avatar", 1],
      ["Myriad Landscape", 1],
      ["Necromantic Selection", 1],
      ["Necropolis Fiend", 1],
      ["Noxious Gearhulk", 1],
      ["Nyx Weaver", 1],
      ["Ob Nixilis, the Fallen", 1],
      ["Opulent Palace", 1],
      ["Phyrexian Reclamation", 1],
      ["Putrefy", 1],
      ["Rampant Growth", 1],
      ["Reassembling Skeleton", 1],
      ["River Kelpie", 1],
      ["Sakura-Tribe Elder", 1],
      ["Satyr Wayfinder", 1],
      ["Shigeki, Jukai Visionary", 1],
      ["Skull Prophet", 1],
      ["Sol Ring", 1],
      ["Springbloom Druid", 1],
      ["Steward of the Harvest", 1],
      ["Stitcher's Supplier", 1],
      ["Sunken Hollow", 1],
      ["Swamp", 5],
      ["Tasigur, the Golden Fang", 1],
      ["Tear Asunder", 1],
      ["Temple of Malady", 1],
      ["Terramorphic Expanse", 1],
      ["Teval's Judgment", 1],
      ["Timeless Witness", 1],
      ["Treasure Cruise", 1],
      ["Victimize", 1],
      ["Welcome the Dead", 1],
      ["Will of the Sultai", 1],
      ["Woe Strider", 1],
      ["Wonder", 1],
      ["Woodland Cemetery", 1],
    ],
    substitutions: [
      sub("Afterlife from the Loam", "Reanimate", "Reanimates a creature from any graveyard."),
      sub("Colossal Grave-Reaver", "Archon of Cruelty", "Eight-mana creature: attack trigger, evasive creature."),
      sub("Command Beacon", "Path of Ancestry", "Land: commander payoff, utility land."),
      sub("Consuming Aberration", "Umbris, Fear Manifest", "Five-mana creature: mill."),
      sub("Dauthi Voidwalker", "Scavenging Ooze", "Two-mana creature: graveyard hate."),
      sub("Disciple of Bolas", "Thallid Soothsayer", "Turns a sacrificed creature into cards."),
      sub("Essence Anchor", "Rune-Sealed Wall", "Three-mana artifact: self-mill, library manipulation."),
      sub("Gravecrawler", "Bloodghast", "Cheap black creature that keeps coming back from the graveyard."),
      sub("Lethal Scheme", "Hero's Downfall", "Instant-speed creature or planeswalker removal."),
      sub("Life from the Loam", "Grim Discovery", "Two-mana sorcery: land recursion, regrowth."),
      sub("Living Death", "Rise Again", "Five-mana sorcery: reanimation, recursion."),
      sub("Lord of the Forsaken", "Mindscour Dragon", "Six-mana creature: mill, self-mill."),
      sub("Multani, Yavimaya's Avatar", "Lumra, Bellow of the Woods", "Six-mana creature: recursion."),
      sub("Necropolis Fiend", "Black Dragon", "Nine-mana creature: removal, evasive creature."),
      sub("Shigeki, Jukai Visionary", "Coiling Oracle", "Two-mana creature: extra land, ramp."),
      sub("Steward of the Harvest", "Cemetery Reaper", "Four-mana creature."),
      sub("Tasigur, the Golden Fang", "Barrow Witches", "Six-mana creature: regrowth, recursion."),
      sub("Teval's Judgment", "Black Market Connections", "Three-mana enchantment: Treasure maker, modal."),
      sub("Welcome the Dead", "Deep Analysis", "Four-mana sorcery: card draw for life, card draw."),
      sub("Wonder", "Pixie Queen", "Four-mana creature: gives flying, evasion."),
    ],
  }),
  precon({
    name: "Abzan Armor",
    bench: true,
    commander: "Felothar the Steadfast",
    description: "Abzan walls: defenders and high-toughness creatures that attack and deal damage by toughness.",
    printed: [
      ["Access Tunnel", 1],
      ["Anguished Unmaking", 1],
      ["Arasta of the Endless Web", 1],
      ["Arbor Adherent", 1],
      ["Arboreal Grazer", 1],
      ["Arcane Signet", 1],
      ["Assault Formation", 1],
      ["Axebane Guardian", 1],
      ["Baldin, Century Herdmaster", 1],
      ["Behind the Scenes", 1],
      ["Betor, Ancestor's Voice", 1],
      ["Blight Pile", 1],
      ["Bojuka Bog", 1],
      ["Canopy Gargantuan", 1],
      ["Canopy Vista", 1],
      ["Carven Caryatid", 1],
      ["Colfenor's Urn", 1],
      ["Command Tower", 1],
      ["Crashing Drawbridge", 1],
      ["Deceptive Landscape", 1],
      ["Despark", 1],
      ["Dragonlord Dromoka", 1],
      ["Evolving Wilds", 1],
      ["Exotic Orchard", 1],
      ["Expel the Interlopers", 1],
      ["Faeburrow Elder", 1],
      ["Feed the Swarm", 1],
      ["Forest", 7],
      ["Fortified Village", 1],
      ["Hornet Nest", 1],
      ["Ikra Shidiqi, the Usurper", 1],
      ["Indomitable Ancients", 1],
      ["Indulging Patrician", 1],
      ["Infernal Grasp", 1],
      ["Isolated Chapel", 1],
      ["Jaddi Offshoot", 1],
      ["Jaws of Defeat", 1],
      ["Nyx-Fleece Ram", 1],
      ["Orzhov Signet", 1],
      ["Overgrown Battlement", 1],
      ["Overgrown Farmland", 1],
      ["Path of Ancestry", 1],
      ["Plains", 6],
      ["Protector of the Wastes", 1],
      ["Radiant Grove", 1],
      ["Rampart Architect", 1],
      ["Reunion of the House", 1],
      ["Rhox Faithmender", 1],
      ["Sandsteppe Citadel", 1],
      ["Seedborn Muse", 1],
      ["Selesnya Signet", 1],
      ["Shadrix Silverquill", 1],
      ["Shalai, Voice of Plenty", 1],
      ["Sidar Kondo of Jamuraa", 1],
      ["Slaughter the Strong", 1],
      ["Sol Ring", 1],
      ["Staff of Compleation", 1],
      ["Sungrass Prairie", 1],
      ["Sunpetal Grove", 1],
      ["Swamp", 5],
      ["Swiftfoot Boots", 1],
      ["Swords to Plowshares", 1],
      ["Sylvan Caryatid", 1],
      ["Temple of Malady", 1],
      ["Temple of Plenty", 1],
      ["Temple of Silence", 1],
      ["Tip the Scales", 1],
      ["Tower Defense", 1],
      ["Towering Titan", 1],
      ["Tree of Redemption", 1],
      ["Twilight Mire", 1],
      ["Wakestone Gargoyle", 1],
      ["Walking Bulwark", 1],
      ["Wall of Blossoms", 1],
      ["Wall of Limbs", 1],
      ["Wall of Omens", 1],
      ["Wall of Reverence", 1],
      ["Wall of Roots", 1],
      ["Weathered Sentinels", 1],
      ["Welcoming Vampire", 1],
      ["Will of the Abzan", 1],
      ["Wingmantle Chaplain", 1],
      ["Woodland Cemetery", 1],
      ["Zetalpa, Primal Dawn", 1],
    ],
    substitutions: [
      sub("Baldin, Century Herdmaster", "Syr Alin, the Lion's Claw", "Six-mana creature: team pump, attack trigger."),
      sub("Canopy Gargantuan", "Old Gnawbone", "Seven-mana green Dragon."),
      sub("Colfenor's Urn", "Resurrection Orb", "Three-mana artifact: protection."),
      sub("Shadrix Silverquill", "Archangel of Thune", "Five-mana white flier that grows the team."),
      sub("Slaughter the Strong", "Citywide Bust", "Three-mana sorcery: sweeper, creature removal."),
      sub("Tip the Scales", "Toxic Deluge", "Three-mana sorcery: removal, sweeper."),
      sub("Tree of Redemption", "Ancient Lumberknot", "Four-mana creature that deals damage by toughness."),
      sub("Wall of Roots", "Vine Trellis", "Two-mana creature: mana creature, ramp."),
      sub("Weathered Sentinels", "Guardians of Meletis", "Three-mana artifact defender with high toughness."),
      sub("Will of the Abzan", "Breath of Life", "Four-mana sorcery: reanimation, recursion."),
    ],
  }),
  precon({
    name: "Mardu Surge",
    commander: "Zurgo Stormrender",
    description: "Mardu tokens: attack wide with tokens and cash them in as they leave.",
    printed: [
      ["Abrade", 1],
      ["Adeline, Resplendent Cathar", 1],
      ["Ainok Strike Leader", 1],
      ["Angel of Invention", 1],
      ["Arcane Signet", 1],
      ["Aron, Benalia's Ruin", 1],
      ["Bastion of Remembrance", 1],
      ["Battlefield Forge", 1],
      ["Beetleback Chief", 1],
      ["Bitter Triumph", 1],
      ["Blade of Selves", 1],
      ["Bojuka Bog", 1],
      ["Bone Devourer", 1],
      ["Canyon Slough", 1],
      ["Castle Ardenvale", 1],
      ["Castle Embereth", 1],
      ["Caves of Koilos", 1],
      ["Chittering Witch", 1],
      ["Clifftop Retreat", 1],
      ["Command Tower", 1],
      ["Commander's Insignia", 1],
      ["Deadly Dispute", 1],
      ["Divine Visitation", 1],
      ["Dragonskull Summit", 1],
      ["Eliminate the Competition", 1],
      ["Emeria Angel", 1],
      ["Exotic Orchard", 1],
      ["Fellwar Stone", 1],
      ["Fetid Heath", 1],
      ["Gix, Yawgmoth Praetor", 1],
      ["Goldlust Triad", 1],
      ["Goldnight Commander", 1],
      ["Grand Crescendo", 1],
      ["Grenzo, Havoc Raiser", 1],
      ["Hero of Bladehold", 1],
      ["Hour of Reckoning", 1],
      ["Idol of Oblivion", 1],
      ["Infantry Shield", 1],
      ["Ironwill Forger", 1],
      ["Isolated Chapel", 1],
      ["Kaya, Geist Hunter", 1],
      ["Legion Loyalty", 1],
      ["Legion Warboss", 1],
      ["Lightning Greaves", 1],
      ["Lingering Souls", 1],
      ["Loyal Apprentice", 1],
      ["Mindblade Render", 1],
      ["Morbid Opportunist", 1],
      ["Mountain", 5],
      ["Myr Battlesphere", 1],
      ["Neriv, Crackling Vanguard", 1],
      ["Nomad Outpost", 1],
      ["Ogre Battledriver", 1],
      ["Ophiomancer", 1],
      ["Path of Ancestry", 1],
      ["Plains", 5],
      ["Redoubled Stormsinger", 1],
      ["Release the Dogs", 1],
      ["Selfless Spirit", 1],
      ["Shadow Summoning", 1],
      ["Shattered Landscape", 1],
      ["Shattered Sanctum", 1],
      ["Siege-Gang Commander", 1],
      ["Skullclamp", 1],
      ["Smoldering Marsh", 1],
      ["Sol Ring", 1],
      ["Solemn Simulacrum", 1],
      ["Stroke of Midnight", 1],
      ["Sun Titan", 1],
      ["Swamp", 5],
      ["Swords to Plowshares", 1],
      ["Talisman of Conviction", 1],
      ["Talisman of Hierarchy", 1],
      ["Temple of Silence", 1],
      ["Temple of Triumph", 1],
      ["Tempt with Vengeance", 1],
      ["Terramorphic Expanse", 1],
      ["Thalisse, Reverent Medium", 1],
      ["Tocasia's Welcome", 1],
      ["Twilight Drover", 1],
      ["Vault of the Archangel", 1],
      ["Viscera Seer", 1],
      ["Wayfarer's Bauble", 1],
      ["Will of the Mardu", 1],
      ["Windbrisk Heights", 1],
      ["Within Range", 1],
      ["Yahenni, Undying Partisan", 1],
    ],
    substitutions: [
      sub("Ainok Strike Leader", "Hanweir Garrison", "Attacks and brings attacking tokens with it."),
      sub("Divine Visitation", "Anointed Procession", "Five-mana enchantment: token payoff."),
      sub("Gix, Yawgmoth Praetor", "Midnight Reaper", "Three-mana creature: card draw for life, card draw."),
      sub("Kaya, Geist Hunter", "Ajani, Caller of the Pride", "Three-mana planeswalker."),
      sub("Legion Warboss", "Krenko, Tin Street Kingpin", "Three-mana creature: token maker, attack trigger."),
      sub("Myr Battlesphere", "Threefold Thunderhulk", "Seven-mana artifact creature that makes an army."),
      sub("Neriv, Crackling Vanguard", "Bonehoard Dracosaur", "Five-mana creature: impulse draw, card advantage."),
      sub("Redoubled Stormsinger", "Zurgo, Thunder's Decree", "Three-mana creature: token payoff, token maker."),
      sub("Will of the Mardu", "Bombard", "Three-mana instant: burn, removal."),
      sub("Within Range", "Dogged Pursuit", "Four-mana enchantment: drains opponents."),
    ],
  }),
  precon({
    name: "Jeskai Striker",
    bench: true,
    // The deck's two legendary leads swapped: Shiko and Narset commands it,
    // and Elsha plays in the 99 — the same 100 cards.
    commander: "Shiko and Narset, Unified",
    description: "Jeskai spells: cheap instants and sorceries, prowess and Monk tokens.",
    printed: [
      ["Abrade", 1],
      ["Adaptive Training Post", 1],
      ["Adarkar Wastes", 1],
      ["Aligned Heart", 1],
      ["Ancestral Vision", 1],
      ["Arcane Signet", 1],
      ["Archmage Emeritus", 1],
      ["Ash Barrens", 1],
      ["Azorius Signet", 1],
      ["Baral and Kari Zev", 1],
      ["Baral's Expertise", 1],
      ["Battlefield Forge", 1],
      ["Big Score", 1],
      ["Boros Signet", 1],
      ["Caldera Pyremaw", 1],
      ["Cascade Bluffs", 1],
      ["Clifftop Retreat", 1],
      ["Command Tower", 1],
      ["Compulsive Research", 1],
      ["Consider", 1],
      ["Curse of Opulence", 1],
      ["Curse of the Swine", 1],
      ["Deep Analysis", 1],
      ["Dismantling Wave", 1],
      ["Electrodominance", 1],
      ["Elsha, Threefold Master", 1],
      ["Evolving Wilds", 1],
      ["Exotic Orchard", 1],
      ["Expansion // Explosion", 1],
      ["Expressive Iteration", 1],
      ["Faithless Looting", 1],
      ["Fellwar Stone", 1],
      ["Ferrous Lake", 1],
      ["Frantic Search", 1],
      ["Ghostly Prison", 1],
      ["Glacial Fortress", 1],
      ["Goblin Electromancer", 1],
      ["Guttersnipe", 1],
      ["Haughty Djinn", 1],
      ["Irrigated Farmland", 1],
      ["Island", 5],
      ["Izzet Signet", 1],
      ["Lier, Disciple of the Drowned", 1],
      ["Magma Opus", 1],
      ["Mana Geyser", 1],
      ["Manaform Hellkite", 1],
      ["Mangara, the Diplomat", 1],
      ["Monastery Mentor", 1],
      ["Mountain", 5],
      ["Mystic Monastery", 1],
      ["Narset's Reversal", 1],
      ["Opt", 1],
      ["Path of Ancestry", 1],
      ["Perilous Landscape", 1],
      ["Plains", 4],
      ["Ponder", 1],
      ["Pongify", 1],
      ["Prairie Stream", 1],
      ["Preordain", 1],
      ["Prismari Command", 1],
      ["Reliquary Tower", 1],
      ["Rite of Replication", 1],
      ["Rugged Prairie", 1],
      ["Shiny Impetus", 1],
      ["Shivan Reef", 1],
      ["Skycloud Expanse", 1],
      ["Sol Ring", 1],
      ["Storm-Kiln Artist", 1],
      ["Sublime Epiphany", 1],
      ["Sulfur Falls", 1],
      ["Swords to Plowshares", 1],
      ["Talisman of Progress", 1],
      ["Tempest Technique", 1],
      ["Temple of Enlightenment", 1],
      ["Temple of Epiphany", 1],
      ["Temple of Triumph", 1],
      ["Think Twice", 1],
      ["Third Path Iconoclast", 1],
      ["Time Wipe", 1],
      ["Transcendent Dragon", 1],
      ["Transforming Flourish", 1],
      ["Vanquish the Horde", 1],
      ["Velomachus Lorehold", 1],
      ["Veyran, Voice of Duality", 1],
      ["Voracious Bibliophile", 1],
      ["Whirlwind of Thought", 1],
      ["Will of the Jeskai", 1],
      ["Young Pyromancer", 1],
    ],
    substitutions: [
      sub("Curse of Opulence", "Sticky Fingers", "One-mana enchantment: token maker, ramp."),
      sub("Dismantling Wave", "Solemn Offering", "Three-mana sorcery: artifact and enchantment removal, removal."),
      sub("Transforming Flourish", "Stroke of Midnight", "Three-mana instant: removal."),
    ],
  }),
  precon({
    name: "Draconic Destruction",
    commander: "Atarka, World Render",
    description: "Red-green Dragons: ramp into big fliers and burn.",
    // 2022 Starter Commander Deck (MTGJSON `SCD`).
    printed: [
      ["Akoum Hellkite", 1],
      ["Arcane Signet", 1],
      ["Atarka Monument", 1],
      ["Beast Within", 1],
      ["Blossoming Defense", 1],
      ["Chain Reaction", 1],
      ["Cinder Glade", 1],
      ["Clan Defiance", 1],
      ["Command Tower", 1],
      ["Commander's Sphere", 1],
      ["Crucible of Fire", 1],
      ["Cultivate", 1],
      ["Demanding Dragon", 1],
      ["Draconic Disciple", 1],
      ["Dragon Mage", 1],
      ["Dragon Tempest", 1],
      ["Dragon's Hoard", 1],
      ["Dragonkin Berserker", 1],
      ["Dragonlord's Servant", 1],
      ["Dragonmaster Outcast", 1],
      ["Dragonspeaker Shaman", 1],
      ["Drakuseth, Maw of Flames", 1],
      ["Dream Pillager", 1],
      ["Drumhunter", 1],
      ["Elemental Bond", 1],
      ["Fires of Yavimaya", 1],
      ["Flameblast Dragon", 1],
      ["Foe-Razer Regent", 1],
      ["Forest", 12],
      ["Frontier Siege", 1],
      ["Furnace Whelp", 1],
      ["Game Trail", 1],
      ["Garruk's Uprising", 1],
      ["Harbinger of the Hunt", 1],
      ["Harmonize", 1],
      ["Haven of the Spirit Dragon", 1],
      ["Hoard-Smelter Dragon", 1],
      ["Hunter's Insight", 1],
      ["Hunter's Prowess", 1],
      ["Kazandu Refuge", 1],
      ["Loaming Shaman", 1],
      ["Magmaquake", 1],
      ["Mordant Dragon", 1],
      ["Mountain", 18],
      ["Path of Ancestry", 1],
      ["Primal Might", 1],
      ["Provoke the Trolls", 1],
      ["Rapacious Dragon", 1],
      ["Return to Nature", 1],
      ["Rugged Highlands", 1],
      ["Runehorn Hellkite", 1],
      ["Sakura-Tribe Elder", 1],
      ["Sarkhan, the Dragonspeaker", 1],
      ["Savage Ventmaw", 1],
      ["Scourge of Valkas", 1],
      ["Shamanic Revelation", 1],
      ["Shivan Oasis", 1],
      ["Sol Ring", 1],
      ["Spit Flame", 1],
      ["Steel Hellkite", 1],
      ["Sweltering Suns", 1],
      ["Swiftfoot Boots", 1],
      ["Talisman of Impulse", 1],
      ["Temple of Abandon", 1],
      ["Thunderbreak Regent", 1],
      ["Thundermaw Hellkite", 1],
      ["Timber Gorge", 1],
      ["Tyrant's Familiar", 1],
      ["Unleash Fury", 1],
      ["Vandalblast", 1],
      ["Verix Bladewing", 1],
    ],
    substitutions: [
      sub("Foe-Razer Regent", "Old Gnawbone", "Seven-mana green flying Dragon."),
      sub("Loaming Shaman", "Scavenging Ooze", "Cheap green creature that interacts with graveyards."),
      sub("Sarkhan, the Dragonspeaker", "Garruk Wildspeaker", "Green planeswalker that makes creatures and has an overrun finisher."),
    ],
  }),
  precon({
    name: "Token Triumph",
    bench: true,
    commander: "Emmara, Soul of the Accord",
    description: "Green-white tokens: go wide, then pump the team.",
    // 2022 Starter Commander Deck (MTGJSON `SCD`).
    printed: [
      ["Ajani, Caller of the Pride", 1],
      ["Arcane Signet", 1],
      ["Aura Mutation", 1],
      ["Avacyn's Pilgrim", 1],
      ["Blossoming Sands", 1],
      ["Camaraderie", 1],
      ["Canopy Vista", 1],
      ["Champion of Lambholt", 1],
      ["Citanul Hierophants", 1],
      ["Citywide Bust", 1],
      ["Collective Blessing", 1],
      ["Collective Unconscious", 1],
      ["Command Tower", 1],
      ["Commander's Insignia", 1],
      ["Commander's Sphere", 1],
      ["Conclave Tribunal", 1],
      ["Curse of Bounty", 1],
      ["Dauntless Escort", 1],
      ["Dawn of Hope", 1],
      ["Devouring Light", 1],
      ["Dictate of Heliod", 1],
      ["Elfhame Palace", 1],
      ["Eternal Witness", 1],
      ["Farhaven Elf", 1],
      ["Felidar Retreat", 1],
      ["Forest", 15],
      ["Fortified Village", 1],
      ["Graypelt Refuge", 1],
      ["Great Oak Guardian", 1],
      ["Harmonize", 1],
      ["Harvest Season", 1],
      ["Holdout Settlement", 1],
      ["Hornet Nest", 1],
      ["Hornet Queen", 1],
      ["Hour of Reckoning", 1],
      ["Idol of Oblivion", 1],
      ["Jade Mage", 1],
      ["Jaspera Sentinel", 1],
      ["Karametra's Favor", 1],
      ["Leafkin Druid", 1],
      ["Loyal Guardian", 1],
      ["Maja, Bretagard Protector", 1],
      ["March of the Multitudes", 1],
      ["Mentor of the Meek", 1],
      ["Nissa's Expedition", 1],
      ["Nullmage Shepherd", 1],
      ["Overrun", 1],
      ["Overwhelming Instinct", 1],
      ["Path to Exile", 1],
      ["Plains", 14],
      ["Presence of Gond", 1],
      ["Reclamation Sage", 1],
      ["Rishkar, Peema Renegade", 1],
      ["Rootborn Defenses", 1],
      ["Scatter the Seeds", 1],
      ["Scavenging Ooze", 1],
      ["Selesnya Evangel", 1],
      ["Selesnya Guildmage", 1],
      ["Slate of Ancestry", 1],
      ["Sol Ring", 1],
      ["Sporemound", 1],
      ["Sylvan Reclamation", 1],
      ["Talisman of Unity", 1],
      ["Temple of Plenty", 1],
      ["Thunderfoot Baloth", 1],
      ["Tranquil Expanse", 1],
      ["Trostani Discordant", 1],
      ["Valor in Akros", 1],
      ["Verdant Force", 1],
      ["Vitu-Ghazi, the City-Tree", 1],
      ["Voice of Many", 1],
      ["White Sun's Zenith", 1],
    ],
    substitutions: [
      sub("Curse of Bounty", "Raise the Alarm", "Two-mana token maker."),
    ],
  }),
  precon({
    name: "First Flight",
    commander: "Isperia, Supreme Judge",
    description: "White-blue fliers: evasive creatures, card draw and countermagic.",
    // 2022 Starter Commander Deck (MTGJSON `SCD`).
    printed: [
      ["Absorb", 1],
      ["Aetherize", 1],
      ["Angler Turtle", 1],
      ["Arcane Signet", 1],
      ["Archon of Redemption", 1],
      ["Aven Gagglemaster", 1],
      ["Azorius Signet", 1],
      ["Banishing Light", 1],
      ["Bident of Thassa", 1],
      ["Cartographer's Hawk", 1],
      ["Cleansing Nova", 1],
      ["Cloudblazer", 1],
      ["Coastal Tower", 1],
      ["Command Tower", 1],
      ["Commander's Sphere", 1],
      ["Condemn", 1],
      ["Counterspell", 1],
      ["Crush Contraband", 1],
      ["Diluvian Primordial", 1],
      ["Disenchant", 1],
      ["Emeria Angel", 1],
      ["Empyrean Eagle", 1],
      ["Ever-Watching Threshold", 1],
      ["Faerie Formation", 1],
      ["Favorable Winds", 1],
      ["Generous Gift", 1],
      ["Gideon Jura", 1],
      ["Gravitational Shift", 1],
      ["Hanged Executioner", 1],
      ["Hedron Archive", 1],
      ["Inspired Sphinx", 1],
      ["Island", 15],
      ["Jubilant Skybonder", 1],
      ["Kangee, Sky Warden", 1],
      ["Kangee's Lieutenant", 1],
      ["Meandering River", 1],
      ["Migratory Route", 1],
      ["Moorland Haunt", 1],
      ["Negate", 1],
      ["Pilgrim's Eye", 1],
      ["Plains", 15],
      ["Port Town", 1],
      ["Prairie Stream", 1],
      ["Rally of Wings", 1],
      ["Remorseful Cleric", 1],
      ["Sejiri Refuge", 1],
      ["Sephara, Sky's Blade", 1],
      ["Sharding Sphinx", 1],
      ["Sky Diamond", 1],
      ["Skycat Sovereign", 1],
      ["Skyscanner", 1],
      ["Sol Ring", 1],
      ["Soul Snare", 1],
      ["Sphinx of Enlightenment", 1],
      ["Sphinx's Revelation", 1],
      ["Staggering Insight", 1],
      ["Steel-Plume Marshal", 1],
      ["Storm Herd", 1],
      ["Swords to Plowshares", 1],
      ["Talisman of Progress", 1],
      ["Temple of Enlightenment", 1],
      ["Thought Vessel", 1],
      ["Thunderclap Wyvern", 1],
      ["Tide Skimmer", 1],
      ["Time Wipe", 1],
      ["Tranquil Cove", 1],
      ["True Conviction", 1],
      ["Vow of Duty", 1],
      ["Warden of Evos Isle", 1],
      ["Windreader Sphinx", 1],
      ["Winged Words", 1],
    ],
    substitutions: [
      sub("Diluvian Primordial", "Steel Hellkite", "Large flying finisher."),
      sub("Gideon Jura", "Ajani, Caller of the Pride", "White planeswalker; its -3 grants flying."),
      sub("Jubilant Skybonder", "Thieving Magpie", "Blue flier that draws cards."),
    ],
  }),
  precon({
    name: "Grave Danger",
    commander: "Gisa and Geralf",
    description: "Blue-black Zombies: mill, recursion and sacrifice payoffs.",
    // 2022 Starter Commander Deck (MTGJSON `SCD`).
    printed: [
      ["Arcane Signet", 1],
      ["Army of the Damned", 1],
      ["Cemetery Reaper", 1],
      ["Champion of the Perished", 1],
      ["Choked Estuary", 1],
      ["Command Tower", 1],
      ["Commander's Sphere", 1],
      ["Crippling Fear", 1],
      ["Cruel Revival", 1],
      ["Curse of Disturbance", 1],
      ["Deep Analysis", 1],
      ["Dimir Signet", 1],
      ["Diregraf Captain", 1],
      ["Dismal Backwater", 1],
      ["Distant Melody", 1],
      ["Enter the God-Eternals", 1],
      ["Eternal Skylord", 1],
      ["Feed the Swarm", 1],
      ["Fleshbag Marauder", 1],
      ["Geralf's Mindcrusher", 1],
      ["Gleaming Overseer", 1],
      ["Gravespawn Sovereign", 1],
      ["Gray Merchant of Asphodel", 1],
      ["Grimoire of the Dead", 1],
      ["Havengul Lich", 1],
      ["Heraldic Banner", 1],
      ["Island", 13],
      ["Josu Vess, Lich Knight", 1],
      ["Jwar Isle Refuge", 1],
      ["Laboratory Drudge", 1],
      ["Lazotep Plating", 1],
      ["Lazotep Reaver", 1],
      ["Liliana, Untouched by Death", 1],
      ["Liliana's Devotee", 1],
      ["Liliana's Mastery", 1],
      ["Liliana's Standard Bearer", 1],
      ["Lord of the Accursed", 1],
      ["Lotleth Giant", 1],
      ["Loyal Subordinate", 1],
      ["Midnight Reaper", 1],
      ["Mire Triton", 1],
      ["Murder", 1],
      ["Necromantic Selection", 1],
      ["Necrotic Hex", 1],
      ["Open the Graves", 1],
      ["Overseer of the Damned", 1],
      ["Pilfered Plans", 1],
      ["Salt Marsh", 1],
      ["Scourge of Nel Toth", 1],
      ["Sinister Sabotage", 1],
      ["Sol Ring", 1],
      ["Spark Reaper", 1],
      ["Submerged Boneyard", 1],
      ["Sunken Hollow", 1],
      ["Swamp", 18],
      ["Syphon Flesh", 1],
      ["Talisman of Dominance", 1],
      ["Temple of Deceit", 1],
      ["Unbreathing Horde", 1],
      ["Undead Augur", 1],
      ["Undermine", 1],
      ["Unstable Obelisk", 1],
      ["Vampiric Rites", 1],
      ["Vela the Night-Clad", 1],
      ["Vengeful Dead", 1],
      ["Victimize", 1],
      ["Vizier of the Scorpion", 1],
      ["Wayfarer's Bauble", 1],
      ["Withered Wretch", 1],
      ["Zombie Apocalypse", 1],
    ],
    substitutions: [
      sub("Curse of Disturbance", "Phyrexian Arena", "Three-mana black enchantment."),
      sub("Grimoire of the Dead", "Slate of Ancestry", "Four-mana late-game artifact."),
      sub("Havengul Lich", "Bloodgift Demon", "Five-mana value creature."),
      sub("Liliana, Untouched by Death", "Mortivore", "Four-mana black card that grows with graveyards; no blue-black planeswalker is implemented."),
      sub("Scourge of Nel Toth", "Rakshasa Debaser", "Six-mana black finisher that returns creatures from graveyards to the battlefield."),
    ],
  }),
  precon({
    name: "Chaos Incarnate",
    commander: "Kardur, Doomscourge",
    description: "Black-red chaos: goad, punisher effects and symmetric damage.",
    // 2022 Starter Commander Deck (MTGJSON `SCD`).
    printed: [
      ["Abrade", 1],
      ["Akoum Refuge", 1],
      ["Ambition's Cost", 1],
      ["Arcane Signet", 1],
      ["Archfiend of Depravity", 1],
      ["Blasphemous Act", 1],
      ["Bloodfell Caves", 1],
      ["Bloodgift Demon", 1],
      ["Brash Taunter", 1],
      ["Breath of Malfegor", 1],
      ["Burnished Hart", 1],
      ["Chaos Warp", 1],
      ["Cinder Barrens", 1],
      ["Combustible Gearhulk", 1],
      ["Command Tower", 1],
      ["Commander's Sphere", 1],
      ["Coveted Jewel", 1],
      ["Deadly Tempest", 1],
      ["Dictate of the Twin Gods", 1],
      ["Dredge the Mire", 1],
      ["Explosion of Riches", 1],
      ["Feed the Swarm", 1],
      ["Fiery Confluence", 1],
      ["Foreboding Ruins", 1],
      ["Geode Rager", 1],
      ["Guttersnipe", 1],
      ["Hate Mirage", 1],
      ["Indulgent Tormentor", 1],
      ["Kaervek the Merciless", 1],
      ["Kazuul, Tyrant of the Cliffs", 1],
      ["Lightning Greaves", 1],
      ["Magmatic Force", 1],
      ["Mana Geyser", 1],
      ["Molten Slagheap", 1],
      ["Mountain", 14],
      ["Myriad Landscape", 1],
      ["Nihil Spellbomb", 1],
      ["Ob Nixilis Reignited", 1],
      ["Profane Command", 1],
      ["Rakdos Charm", 1],
      ["Rakdos Signet", 1],
      ["Rakshasa Debaser", 1],
      ["Read the Bones", 1],
      ["Reign of the Pit", 1],
      ["Sangromancer", 1],
      ["Scythe Specter", 1],
      ["Sepulchral Primordial", 1],
      ["Sign in Blood", 1],
      ["Smoldering Marsh", 1],
      ["Sol Ring", 1],
      ["Solemn Simulacrum", 1],
      ["Soul Shatter", 1],
      ["Spiteful Visions", 1],
      ["Stensia Bloodhall", 1],
      ["Stormfist Crusader", 1],
      ["Sunbird's Invocation", 1],
      ["Swamp", 15],
      ["Syphon Mind", 1],
      ["Talisman of Indulgence", 1],
      ["Tectonic Giant", 1],
      ["Temple of Malice", 1],
      ["Terminate", 1],
      ["Theater of Horrors", 1],
      ["Thermo-Alchemist", 1],
      ["Titan Hunter", 1],
      ["Unlicensed Disintegration", 1],
      ["Urborg Volcano", 1],
      ["Vampire Nighthawk", 1],
      ["Wayfarer's Bauble", 1],
      ["Wild Ricochet", 1],
      ["Wildfire Devils", 1],
      ["Worn Powerstone", 1],
    ],
    substitutions: [
      sub("Combustible Gearhulk", "Demanding Dragon", "Punisher creature: the opponent picks the lesser evil."),
      sub("Coveted Jewel", "Hedron Archive", "Mana rock that cashes in for cards."),
      sub("Dredge the Mire", "Victimize", "Reanimation sorcery."),
      sub("Explosion of Riches", "Fireball", "Top-end damage spell aimed at opponents."),
      sub("Fiery Confluence", "Chain Reaction", "Four-mana red sweeper."),
      sub("Molten Slagheap", "Sulfurous Springs", "Land that makes both colours."),
      sub("Ob Nixilis Reignited", "Ob Nixilis, the Fallen", "Same-cost black Ob Nixilis that drains life; no black-red planeswalker of the kind is implemented."),
      sub("Profane Command", "Kolaghan's Command", "Modal black-red Command with a recursion mode."),
      sub("Scythe Specter", "Hypnotic Specter", "Flying Specter that makes opponents discard."),
      sub("Sepulchral Primordial", "Overseer of the Damned", "Seven-mana black top-end with an enters-the-battlefield payoff."),
      sub("Soul Shatter", "Diabolic Edict", "Instant-speed edict."),
      sub("Sunbird's Invocation", "Phyrexian Arena", "Card-advantage enchantment."),
      sub("Wild Ricochet", "Act of Treason", "Uses an opponent's resources against them."),
      sub("Wildfire Devils", "Cinder Elemental", "Four-mana red creature that turns into damage."),
    ],
  }),
  precon({
    name: "Tramplesaurus Rex",
    commander: "Ghalta, Primal Hunger",
    description: "Mono-green stompy: ramp into big creatures, cheapened by Ghalta.",
    // Foundations Commander (MTGJSON `FDC`).
    printed: [
      ["Arachnogenesis", 1],
      ["Arasta of the Endless Web", 1],
      ["Beast Whisperer", 1],
      ["Beast Within", 1],
      ["Birds of Paradise", 1],
      ["Bite Down", 1],
      ["Bonders' Enclave", 1],
      ["Carnage Tyrant", 1],
      ["Challenger Troll", 1],
      ["Clifftop Lookout", 1],
      ["Collective Resistance", 1],
      ["Colossal Majesty", 1],
      ["Commander's Sphere", 1],
      ["Curious Altisaur", 1],
      ["Dungrove Elder", 1],
      ["Elder Gargaroth", 1],
      ["Elemental Bond", 1],
      ["Elvish Mystic", 1],
      ["Ezuri's Predation", 1],
      ["Forest", 32],
      ["Fyndhorn Elves", 1],
      ["Garruk's Packleader", 1],
      ["Garruk's Uprising", 1],
      ["Gigantosaurus", 1],
      ["Goreclaw, Terror of Qal Sisma", 1],
      ["Harmonize", 1],
      ["Hulking Raptor", 1],
      ["Ilysian Caryatid", 1],
      ["Kenrith's Transformation", 1],
      ["Llanowar Elves", 1],
      ["Llanowar Tribe", 1],
      ["Loot, Exuberant Explorer", 1],
      ["Managorger Hydra", 1],
      ["Monstrous Onslaught", 1],
      ["Mosswort Bridge", 1],
      ["Overwhelming Stampede", 1],
      ["Paradise Druid", 1],
      ["Pugnacious Hammerskull", 1],
      ["Ram Through", 1],
      ["Regal Imperiosaur", 1],
      ["Rhonas the Indomitable", 1],
      ["Rhonas's Monument", 1],
      ["Ripjaw Raptor", 1],
      ["Rishkar, Peema Renegade", 1],
      ["Rishkar's Expertise", 1],
      ["Rogue's Passage", 1],
      ["Scavenger Grounds", 1],
      ["Scavenging Ooze", 1],
      ["Scrapshooter", 1],
      ["Shamanic Revelation", 1],
      ["Sol Ring", 1],
      ["Steel Leaf Champion", 1],
      ["Surrak and Goreclaw", 1],
      ["Surrak, the Hunt Caller", 1],
      ["Swiftfoot Boots", 1],
      ["Tamiyo's Safekeeping", 1],
      ["Tangleweave Armor", 1],
      ["Terrian, World Tyrant", 1],
      ["Thickest in the Thicket", 1],
      ["Thrashing Brontodon", 1],
      ["Tranquil Thicket", 1],
      ["Unnatural Growth", 1],
      ["Verdant Sun's Avatar", 1],
      ["War Room", 1],
      ["Whiptongue Hydra", 1],
      ["Whisperer of the Wilds", 1],
      ["Witch's Clinic", 1],
      ["Yeva, Nature's Herald", 1],
    ],
    substitutions: [
      sub("Arachnogenesis", "Inspiring Call", "Three-mana green instant that saves the board."),
      sub("Challenger Troll", "Thragtusk", "Five-mana green creature with a big body."),
      sub("Ezuri's Predation", "Hornet Queen", "Seven-mana green answer to a wide board."),
      sub("Kenrith's Transformation", "Bridgeworks Battle", "Green removal: a creature fights."),
      sub("Monstrous Onslaught", "Primal Might", "Green removal that uses a creature's power."),
      sub("Pugnacious Hammerskull", "Topiary Stomper", "Three-mana green Dinosaur, big for its cost."),
      sub("Ram Through", "Rabid Bite", "Cheap one-sided fight."),
    ],
  }),
  precon({
    name: "Family Matters",
    commander: "Zinnia, Valley's Voice",
    description: "Jeskai go-wide: tokens and small creatures, made bigger by Zinnia.",
    // Bloomburrow Commander (MTGJSON `BLC`).
    printed: [
      ["Adarkar Wastes", 1],
      ["Aether Channeler", 1],
      ["Aetherize", 1],
      ["Agate Instigator", 1],
      ["Angel of the Ruins", 1],
      ["Arcane Signet", 1],
      ["Arthur, Marigold Knight", 1],
      ["Azorius Signet", 1],
      ["Battlefield Forge", 1],
      ["Bident of Thassa", 1],
      ["Blade Splicer", 1],
      ["Boros Signet", 1],
      ["Boss's Chauffeur", 1],
      ["Calamity of Cinders", 1],
      ["Cascade Bluffs", 1],
      ["Castle Ardenvale", 1],
      ["Chart a Course", 1],
      ["Circuit Mender", 1],
      ["Clifftop Retreat", 1],
      ["Cloudblazer", 1],
      ["Combat Celebrant", 1],
      ["Command Tower", 1],
      ["Curiosity Crafter", 1],
      ["Cut a Deal", 1],
      ["Devilish Valet", 1],
      ["Dusk // Dawn", 1],
      ["Echoing Assault", 1],
      ["Elspeth, Sun's Champion", 1],
      ["Evolving Wilds", 1],
      ["Exotic Orchard", 1],
      ["Fellwar Stone", 1],
      ["Ferrous Lake", 1],
      ["Fortune Teller's Talent", 1],
      ["Glacial Fortress", 1],
      ["Hanged Executioner", 1],
      ["Helm of the Host", 1],
      ["Illusory Ambusher", 1],
      ["Inferno Titan", 1],
      ["Inspiring Overseer", 1],
      ["Island", 4],
      ["Izzet Signet", 1],
      ["Jacked Rabbit", 1],
      ["Jazal Goldmane", 1],
      ["Junk Winder", 1],
      ["Loyal Warhound", 1],
      ["Luminous Broodmoth", 1],
      ["Martial Coup", 1],
      ["Mind Stone", 1],
      ["Mountain", 4],
      ["Murmuration", 1],
      ["Mystic Monastery", 1],
      ["Ornithopter of Paradise", 1],
      ["Path of Ancestry", 1],
      ["Path to Exile", 1],
      ["Plains", 5],
      ["Plumecreed Escort", 1],
      ["Pollywog Prodigy", 1],
      ["Pull from Tomorrow", 1],
      ["Rapid Augmenter", 1],
      ["Rapid Hybridization", 1],
      ["Restoration Angel", 1],
      ["Rose Room Treasurer", 1],
      ["Rowdy Research", 1],
      ["Rugged Prairie", 1],
      ["Seachrome Coast", 1],
      ["Selfless Spirit", 1],
      ["Shield Broker", 1],
      ["Shivan Reef", 1],
      ["Siege-Gang Commander", 1],
      ["Skyclave Apparition", 1],
      ["Skycloud Expanse", 1],
      ["Sol Ring", 1],
      ["Solemn Simulacrum", 1],
      ["Spirited Companion", 1],
      ["Stolen by the Fae", 1],
      ["Storm of Souls", 1],
      ["Sulfur Falls", 1],
      ["Sun Titan", 1],
      ["Sunscorched Divide", 1],
      ["Temple of Enlightenment", 1],
      ["Temple of Epiphany", 1],
      ["Temple of Triumph", 1],
      ["Terramorphic Expanse", 1],
      ["Tetsuko Umezawa, Fugitive", 1],
      ["Thopter Engineer", 1],
      ["Thriving Bluff", 1],
      ["Thriving Heath", 1],
      ["Thriving Isle", 1],
      ["Time Wipe", 1],
    ],
    substitutions: [
      sub("Arthur, Marigold Knight", "Adeline, Resplendent Cathar", "White creature that adds attackers when it attacks."),
      sub("Dusk // Dawn", "Wrath of God", "Four-mana white sweeper."),
      sub("Fortune Teller's Talent", "Ophidian Eye", "Blue enchantment that draws cards."),
      sub("Helm of the Host", "The Fire Crystal", "Red artifact that gives the team haste."),
      sub("Junk Winder", "Thought Monitor", "Seven-mana blue creature with affinity."),
      sub("Rowdy Research", "Concentrate", "Blue: draw three cards."),
      sub("Shield Broker", "Act of Treason", "Takes an opponent's creature."),
      sub("Skyclave Apparition", "Resculpt", "Two-mana removal for an artifact or creature."),
      sub("Tetsuko Umezawa, Fugitive", "Thieving Magpie", "Blue flier that draws cards."),
    ],
  }),
  precon({
    name: "Reign of Dragons",
    bench: true,
    commander: "Lathliss, Dragon Queen",
    description: "Mono-red Dragons: Lathliss makes more of them and pumps them.",
    // Foundations Commander (MTGJSON `FDC`).
    printed: [
      ["Abrade", 1],
      ["Anger", 1],
      ["Arcane Signet", 1],
      ["Atsushi, the Blazing Sky", 1],
      ["Basilisk Collar", 1],
      ["Bitter Reunion", 1],
      ["Blasphemous Act", 1],
      ["Bonders' Enclave", 1],
      ["Breaching Dragonstorm", 1],
      ["Breath Weapon", 1],
      ["Carnelian Orb of Dragonkind", 1],
      ["Chain Reaction", 1],
      ["Chandra's Ignition", 1],
      ["Chaos Warp", 1],
      ["Commander's Sphere", 1],
      ["Count on Luck", 1],
      ["Crucible of Fire", 1],
      ["Cursed Mirror", 1],
      ["Dragon Tempest", 1],
      ["Dragon's Hoard", 1],
      ["Dragonhawk, Fate's Tempest", 1],
      ["Dragonlord's Servant", 1],
      ["Dragonmaster Outcast", 1],
      ["Dragonspeaker Shaman", 1],
      ["Dragonstorm Globe", 1],
      ["Drakuseth, Maw of Flames", 1],
      ["Fire Diamond", 1],
      ["Firespitter Whelp", 1],
      ["Forgotten Cave", 1],
      ["Goddric, Cloaked Reveler", 1],
      ["Goldlust Triad", 1],
      ["Haven of the Spirit Dragon", 1],
      ["Hazoret's Monument", 1],
      ["Hellkite Charger", 1],
      ["Herald's Horn", 1],
      ["Hit the Mother Lode", 1],
      ["Leyline Tyrant", 1],
      ["Lightning Bolt", 1],
      ["Magmaquake", 1],
      ["Mana Geyser", 1],
      ["Minion of the Mighty", 1],
      ["Mountain", 32],
      ["Nogi, Draco-Zealot", 1],
      ["Orb of Dragonkind", 1],
      ["Outpost Siege", 1],
      ["Parapet Thrasher", 1],
      ["Rapacious Dragon", 1],
      ["Sarkhan, Dragon Ascendant", 1],
      ["Scourge of the Throne", 1],
      ["Scourge of Valkas", 1],
      ["Shivan Devastator", 1],
      ["Skyline Despot", 1],
      ["Sol Ring", 1],
      ["Spinerock Knoll", 1],
      ["Spit Flame", 1],
      ["Swiftfoot Boots", 1],
      ["Taurean Mauler", 1],
      ["Temple of the False God", 1],
      ["Terror of Mount Velus", 1],
      ["The Elder Dragon War", 1],
      ["Thrill of Possibility", 1],
      ["Thunderbreak Regent", 1],
      ["Thundermane Dragon", 1],
      ["Tyrant's Familiar", 1],
      ["Unexpected Windfall", 1],
      ["Utvara Hellkite", 1],
      ["War Room", 1],
      ["Warstorm Surge", 1],
    ],
    substitutions: [
      sub("Anger", "Fervor", "Gives the deck's creatures haste."),
      sub("Carnelian Orb of Dragonkind", "Ruby Medallion", "Red artifact that makes the deck's spells cheaper."),
      sub("Chandra's Ignition", "Slagstorm", "Red sweeper that can hit opponents instead."),
      sub("Dragonhawk, Fate's Tempest", "Demanding Dragon", "Five-mana red flying Dragon."),
      sub("Leyline Tyrant", "Archwing Dragon", "Four-mana red flying Dragon."),
      sub("Minion of the Mighty", "Dragonkin Berserker", "Cheap red creature that pays off Dragons."),
      sub("Sarkhan, Dragon Ascendant", "Reckless Fireweaver", "Two-mana red creature."),
      sub("Scourge of the Throne", "Rorix Bladewing", "Six-mana red flying Dragon with haste."),
      sub("The Elder Dragon War", "Enduring Courage", "Red enchantment that pumps and hastes the deck's creatures."),
    ],
  }),
  precon({
    name: "World Shaper",
    commander: "Hearthhull, the Worldseed",
    description: "Jund lands: ramp, sacrifice lands and replay them from the graveyard.",
    // Edge of Eternities Commander (MTGJSON `EOC`).
    printed: [
      ["Aftermath Analyst", 1],
      ["Arcane Signet", 1],
      ["Augur of Autumn", 1],
      ["Baloth Prime", 1],
      ["Beast Within", 1],
      ["Binding the Old Gods", 1],
      ["Blasphemous Act", 1],
      ["Bojuka Bog", 1],
      ["Braids, Arisen Nightmare", 1],
      ["Cabaretti Courtyard", 1],
      ["Canyon Slough", 1],
      ["Centaur Vinecrasher", 1],
      ["Cinder Glade", 1],
      ["Command Tower", 1],
      ["Cultivate", 1],
      ["Dakmor Salvage", 1],
      ["Escape to the Wilds", 1],
      ["Escape Tunnel", 1],
      ["Eumidian Hatchery", 1],
      ["Eumidian Wastewaker", 1],
      ["Evendo Brushrazer", 1],
      ["Evolving Wilds", 1],
      ["Exploration Broodship", 1],
      ["Fabled Passage", 1],
      ["Farseek", 1],
      ["Festering Thicket", 1],
      ["Forest", 8],
      ["Formless Genesis", 1],
      ["Gaze of Granite", 1],
      ["God-Eternal Bontu", 1],
      ["Groundskeeper", 1],
      ["Hammer of Purphoros", 1],
      ["Harrow", 1],
      ["Horizon Explorer", 1],
      ["Infernal Grasp", 1],
      ["Juri, Master of the Revue", 1],
      ["Karplusan Forest", 1],
      ["Korvold, Fae-Cursed King", 1],
      ["Llanowar Wastes", 1],
      ["Loamcrafter Faun", 1],
      ["Maestros Theater", 1],
      ["Mayhem Devil", 1],
      ["Mazirek, Kraul Death Priest", 1],
      ["Moraug, Fury of Akoum", 1],
      ["Mountain", 3],
      ["Mountain Valley", 1],
      ["Multani, Yavimaya's Avatar", 1],
      ["Myriad Landscape", 1],
      ["Nature's Lore", 1],
      ["Night's Whisper", 1],
      ["Omnath, Locus of Rage", 1],
      ["Oracle of Mul Daya", 1],
      ["Pest Infestation", 1],
      ["Planetary Annihilation", 1],
      ["Putrefy", 1],
      ["Rakdos Charm", 1],
      ["Rampaging Baloths", 1],
      ["Riveteers Overlook", 1],
      ["Rocky Tar Pit", 1],
      ["Roiling Regrowth", 1],
      ["Satyr Wayfinder", 1],
      ["Scouring Swarm", 1],
      ["Sheltered Thicket", 1],
      ["Skyshroud Claim", 1],
      ["Smoldering Marsh", 1],
      ["Sol Ring", 1],
      ["Soul of Windgrace", 1],
      ["Splendid Reclamation", 1],
      ["Springbloom Druid", 1],
      ["Sprouting Goblin", 1],
      ["Sulfurous Springs", 1],
      ["Swamp", 5],
      ["Szarel, Genesis Shepherd", 1],
      ["Tear Asunder", 1],
      ["Terramorphic Expanse", 1],
      ["The Gitrog Monster", 1],
      ["Tireless Tracker", 1],
      ["Titania, Protector of Argoth", 1],
      ["Twilight Mire", 1],
      ["Uurg, Spawn of Turg", 1],
      ["Vernal Fen", 1],
      ["Viridescent Bog", 1],
      ["Wastes", 1],
      ["Windgrace's Judgment", 1],
      ["World Breaker", 1],
      ["Worldsoul's Rage", 1],
    ],
    substitutions: [
      sub("Augur of Autumn", "Courser of Kruphix", "Three-mana green creature: play lands from the top of the library."),
      sub("Baloth Prime", "Mossborn Hydra", "Green creature that grows with land drops."),
      sub("Dakmor Salvage", "Twisted Landscape", "Land that fetches a basic in the deck's colours."),
      sub("Eumidian Wastewaker", "Icetill Explorer", "Four-mana green creature that plays lands from the graveyard."),
      sub("Formless Genesis", "Awaken the Woods", "Green spell that turns mana into land creatures."),
      sub("God-Eternal Bontu", "Ob Nixilis, the Fallen", "Five-mana black creature that pays off land drops."),
      sub("Loamcrafter Faun", "Ramunap Excavator", "Three-mana green creature: play lands from the graveyard."),
      sub("Moraug, Fury of Akoum", "Lumra, Bellow of the Woods", "Six-mana creature that pays off lands."),
      sub("Multani, Yavimaya's Avatar", "Ancient Greenwarden", "Green top-end creature that pays off lands."),
      sub("Soul of Windgrace", "Lord Windgrace", "Black-red-green Windgrace that returns lands from the graveyard."),
      sub("Windgrace's Judgment", "Decimate", "Black-red-green spell that destroys several permanents."),
      sub("Worldsoul's Rage", "Fireball", "Red X damage spell."),
    ],
  }),
];

/** The decks the bots are benchmarked on — see the header's `bench`. */
export const BENCH_DECKS: readonly SampleDeck[] = SAMPLE_DECKS.filter((d) => d.bench === true);
