/**
 * The starter decks: the five Tarkir: Dragonstorm Commander decks (2025,
 * MTGJSON set code `TDC`), each a real, format-legal 100-card Commander deck.
 * They replaced the five 2022 Starter Commander Decks (`SCD`) on 2026-09-30.
 *
 * Two consumers: `server/src/decks.ts`'s `SEATS` (a room's fallback deck for
 * a seat nobody brought their own deck to, and every bot's deck) and the
 * client's deck builder (offered as ready-made "starter decks" to play as-is
 * or duplicate and edit) — lives here, in the engine, so both share one
 * source of truth instead of each keeping its own copy.
 *
 * **Substitutions.** Each deck's `printed` list is the decklist exactly as
 * printed. A card the engine doesn't implement yet is swapped out through that
 * deck's `substitutions` table rather than edited out of the list, so the
 * printed list stays the record of what the real deck is. Each substitute was
 * picked to stay inside the commander's colour identity, not duplicate a card
 * already in the deck (singleton), and fill the same role at a similar mana
 * value — a Dragon for a Dragon in Temur Roar, a wall for a wall in Abzan
 * Armor — see `docs/plans/precon-decks.md`.
 *
 * **To revert one** once its card is implemented, delete its entry from the
 * table. `sample-decks.test.ts` fails for any substitution whose original is
 * now implemented, so none can outlive the reason for it.
 */

export interface PreconSubstitution {
  /** The printed card the engine doesn't implement yet. */
  readonly original: string;
  /** The implemented card playing in its slot. */
  readonly substitute: string;
  /** Why this card: the role it shares with the original. */
  readonly reason: string;
}

export interface SampleDeck {
  readonly name: string;
  readonly commander?: string;
  /** What the deck plays: `printed` with `substitutions` applied. */
  readonly cards: readonly string[];
  /** One line on what the deck does. */
  readonly description?: string;
  /** The 99 exactly as printed, for a real precon. */
  readonly printed?: readonly string[];
  readonly substitutions?: readonly PreconSubstitution[];
}

const list = (entries: readonly (readonly [string, number])[]): string[] =>
  entries.flatMap(([name, count]) => Array<string>(count).fill(name));

const sub = (original: string, substitute: string, reason: string): PreconSubstitution => ({
  original,
  substitute,
  reason,
});

function precon(deck: {
  readonly name: string;
  readonly commander: string;
  readonly description: string;
  readonly printed: readonly (readonly [string, number])[];
  readonly substitutions: readonly PreconSubstitution[];
}): SampleDeck {
  const printed = list(deck.printed);
  const swap = new Map(deck.substitutions.map((s) => [s.original, s.substitute]));
  for (const original of swap.keys()) {
    if (!printed.includes(original)) {
      throw new Error(`${deck.name}: substitution for ${original}, which isn't in the printed list`);
    }
  }
  return {
    name: deck.name,
    commander: deck.commander,
    description: deck.description,
    printed,
    substitutions: deck.substitutions,
    cards: printed.map((name) => swap.get(name) ?? name),
  };
}

export const SAMPLE_DECKS: readonly SampleDeck[] = [
  precon({
    name: "Temur Roar",
    commander: "Ureni of the Unwritten",
    description: "Temur Dragons: ramp, then Ureni digs Dragons out of the library onto the battlefield.",
    printed: [
      ["Arcane Signet", 1],
      ["Atarka, World Render", 1],
      ["Atsushi, the Blazing Sky", 1],
      ["Beast Within", 1],
      ["Become the Avalanche", 1],
      ["Blasphemous Act", 1],
      ["Bountiful Landscape", 1],
      ["Breaching Dragonstorm", 1],
      ["Broodcaller Scourge", 1],
      ["Chaos Warp", 1],
      ["Cinder Glade", 1],
      ["Command Tower", 1],
      ["Deceptive Frostkite", 1],
      ["Draconic Lore", 1],
      ["Dragon Tempest", 1],
      ["Dragon's Hoard", 1],
      ["Dragonlord Atarka", 1],
      ["Dragonlord's Servant", 1],
      ["Dragonmaster Outcast", 1],
      ["Elemental Bond", 1],
      ["Encroaching Dragonstorm", 1],
      ["Eshki, Temur's Roar", 1],
      ["Evolving Wilds", 1],
      ["Exotic Orchard", 1],
      ["Farseek", 1],
      ["Fellwar Stone", 1],
      ["Flooded Grove", 1],
      ["Forest", 5],
      ["Frontier Bivouac", 1],
      ["Frontier Siege", 1],
      ["Gadrak, the Crown-Scourge", 1],
      ["Glorybringer", 1],
      ["Hammerhead Tyrant", 1],
      ["Harbinger of the Hunt", 1],
      ["Haven of the Spirit Dragon", 1],
      ["Hellkite Courser", 1],
      ["Hinterland Harbor", 1],
      ["Island", 3],
      ["Karplusan Forest", 1],
      ["Keiga, the Tide Star", 1],
      ["Kessig Wolf Run", 1],
      ["Kodama's Reach", 1],
      ["Lathliss, Dragon Queen", 1],
      ["Leyline Tyrant", 1],
      ["Migration Path", 1],
      ["Mossfire Valley", 1],
      ["Mosswort Bridge", 1],
      ["Mountain", 6],
      ["Nesting Dragon", 1],
      ["Nogi, Draco-Zealot", 1],
      ["Opportunistic Dragon", 1],
      ["Parapet Thrasher", 1],
      ["Path of Ancestry", 1],
      ["Rapacious Dragon", 1],
      ["Rapid Hybridization", 1],
      ["Reality Shift", 1],
      ["Reflections of Littjara", 1],
      ["Rockfall Vale", 1],
      ["Rootbound Crag", 1],
      ["Sarkhan, Soul Aflame", 1],
      ["Scourge of the Throne", 1],
      ["Selvala's Stampede", 1],
      ["Sheltered Thicket", 1],
      ["Shivan Reef", 1],
      ["Skarrgan Hellkite", 1],
      ["Sol Ring", 1],
      ["Spit Flame", 1],
      ["Steel Hellkite", 1],
      ["Storm's Wrath", 1],
      ["Stormbreath Dragon", 1],
      ["Stormshriek Feral", 1],
      ["Sulfur Falls", 1],
      ["Talisman of Creativity", 1],
      ["Talisman of Impulse", 1],
      ["Taurean Mauler", 1],
      ["Temple of Abandon", 1],
      ["Temple of Mystery", 1],
      ["Temple of the Dragon Queen", 1],
      ["Temur Ascendancy", 1],
      ["Territorial Hellkite", 1],
      ["Thunderbreak Regent", 1],
      ["Thundermane Dragon", 1],
      ["Vengeful Ancestor", 1],
      ["Verix Bladewing", 1],
      ["Whirlwing Stormbrood", 1],
      ["Will of the Temur", 1],
      ["Yavimaya Coast", 1],
      ["Zenith Festival", 1],
    ],
    substitutions: [
      sub("Chaos Warp", "Regress", "Three-mana instant: removal."),
      sub("Deceptive Frostkite", "Sprite Dragon", "Two-mana blue flying Dragon."),
      sub("Dragonlord Atarka", "Drakuseth, Maw of Flames", "Seven-mana legendary Dragon that burns as it attacks."),
      sub("Glorybringer", "Terror of the Peaks", "Five-mana red flying Dragon that removes creatures."),
      sub("Hellkite Courser", "Rorix Bladewing", "Six-mana red flying Dragon with haste."),
      sub("Leyline Tyrant", "Archwing Dragon", "Four-mana red flying Dragon."),
      sub("Mosswort Bridge", "Khalni Garden", "Land: tapped land, utility land."),
      sub("Opportunistic Dragon", "Skyship Stalker", "Four-mana red flying Dragon."),
      sub("Reality Shift", "Resculpt", "Two-mana instant: removal, creature removal."),
      sub("Reflections of Littjara", "Crucible of Fire", "Enchantment that rewards a deck of Dragons."),
      sub("Sarkhan, Soul Aflame", "Goreclaw, Terror of Qal Sisma", "Makes the deck's big creatures cheaper."),
      sub("Scourge of the Throne", "Savage Ventmaw", "Six-mana red-green flying Dragon that rewards attacking."),
      sub("Selvala's Stampede", "Kodama of the East Tree", "Six-mana sorcery: puts creatures onto the battlefield, ramp."),
      sub("Skarrgan Hellkite", "Scourge of Valkas", "Five-mana red flying Dragon that deals damage as Dragons enter."),
      sub("Stormbreath Dragon", "Thundermaw Hellkite", "Five-mana red flying Dragon with haste."),
      sub("Stormshriek Feral", "Demanding Dragon", "Five-mana red flying Dragon."),
      sub("Temple of the Dragon Queen", "Game Trail", "Land that makes the deck's colours."),
      sub("Territorial Hellkite", "Young Red Dragon", "Four-mana red Dragon."),
      sub("Thundermane Dragon", "Draconic Muralists", "Four-mana green Dragon."),
      sub("Whirlwing Stormbrood", "Ganax, Astral Hunter", "Five-mana red Dragon that makes Treasure as Dragons enter."),
      sub("Zenith Festival", "Reckless Impulse", "Two-mana sorcery: impulse draw, card advantage."),
    ],
  }),
  precon({
    name: "Sultai Arisen",
    commander: "Teval, the Balanced Scale",
    description: "Sultai graveyard: mill yourself, bring lands and creatures back, and make Zombies as cards leave the graveyard.",
    printed: [
      ["Afterlife from the Loam", 1],
      ["Amphin Mutineer", 1],
      ["Arcane Signet", 1],
      ["Avenger of Zendikar", 1],
      ["Casualties of War", 1],
      ["Cephalid Coliseum", 1],
      ["Colossal Grave-Reaver", 1],
      ["Command Beacon", 1],
      ["Command Tower", 1],
      ["Conduit of Worlds", 1],
      ["Consuming Aberration", 1],
      ["Contaminated Aquifer", 1],
      ["Crawling Sensation", 1],
      ["Crypt of Agadeem", 1],
      ["Cultivate", 1],
      ["Darkwater Catacombs", 1],
      ["Dauthi Voidwalker", 1],
      ["Disciple of Bolas", 1],
      ["Diviner of Mist", 1],
      ["Dreamroot Cascade", 1],
      ["Drownyard Temple", 1],
      ["Essence Anchor", 1],
      ["Exotic Orchard", 1],
      ["Farseek", 1],
      ["Fetid Pools", 1],
      ["Floral Evoker", 1],
      ["Forbidden Alchemy", 1],
      ["Foreboding Landscape", 1],
      ["Forest", 6],
      ["Golgari Rot Farm", 1],
      ["Grapple with the Past", 1],
      ["Gravecrawler", 1],
      ["Grisly Salvage", 1],
      ["Harrow", 1],
      ["Haunted Mire", 1],
      ["Hedron Crab", 1],
      ["Hinterland Harbor", 1],
      ["Island", 4],
      ["Jarad, Golgari Lich Lord", 1],
      ["Junji, the Midnight Sky", 1],
      ["Kishla Skimmer", 1],
      ["Kotis, Sibsig Champion", 1],
      ["Lethal Scheme", 1],
      ["Life from the Loam", 1],
      ["Living Death", 1],
      ["Llanowar Wastes", 1],
      ["Lord of Extinction", 1],
      ["Lord of the Forsaken", 1],
      ["Memorial to Folly", 1],
      ["Meren of Clan Nel Toth", 1],
      ["Millikin", 1],
      ["Multani, Yavimaya's Avatar", 1],
      ["Myriad Landscape", 1],
      ["Necromantic Selection", 1],
      ["Necropolis Fiend", 1],
      ["Noxious Gearhulk", 1],
      ["Nyx Weaver", 1],
      ["Ob Nixilis, the Fallen", 1],
      ["Opulent Palace", 1],
      ["Phyrexian Reclamation", 1],
      ["Putrefy", 1],
      ["Rampant Growth", 1],
      ["Reassembling Skeleton", 1],
      ["River Kelpie", 1],
      ["Sakura-Tribe Elder", 1],
      ["Satyr Wayfinder", 1],
      ["Shigeki, Jukai Visionary", 1],
      ["Skull Prophet", 1],
      ["Sol Ring", 1],
      ["Springbloom Druid", 1],
      ["Steward of the Harvest", 1],
      ["Stitcher's Supplier", 1],
      ["Sunken Hollow", 1],
      ["Swamp", 5],
      ["Tasigur, the Golden Fang", 1],
      ["Tear Asunder", 1],
      ["Temple of Malady", 1],
      ["Terramorphic Expanse", 1],
      ["Teval's Judgment", 1],
      ["Timeless Witness", 1],
      ["Treasure Cruise", 1],
      ["Victimize", 1],
      ["Welcome the Dead", 1],
      ["Will of the Sultai", 1],
      ["Woe Strider", 1],
      ["Wonder", 1],
      ["Woodland Cemetery", 1],
    ],
    substitutions: [
      sub("Afterlife from the Loam", "Reanimate", "Reanimates a creature from any graveyard."),
      sub("Colossal Grave-Reaver", "Archon of Cruelty", "Eight-mana creature: attack trigger, evasive creature."),
      sub("Command Beacon", "Path of Ancestry", "Land: commander payoff, utility land."),
      sub("Consuming Aberration", "Umbris, Fear Manifest", "Five-mana creature: mill."),
      sub("Dauthi Voidwalker", "Scavenging Ooze", "Two-mana creature: graveyard hate."),
      sub("Disciple of Bolas", "Thallid Soothsayer", "Turns a sacrificed creature into cards."),
      sub("Essence Anchor", "Rune-Sealed Wall", "Three-mana artifact: self-mill, library manipulation."),
      sub("Gravecrawler", "Bloodghast", "Cheap black creature that keeps coming back from the graveyard."),
      sub("Jarad, Golgari Lich Lord", "Nantuko Husk", "Sacrifice outlet that turns creatures into damage."),
      sub("Kotis, Sibsig Champion", "Doomed Necromancer", "Three-mana creature: reanimation, recursion."),
      sub("Lethal Scheme", "Hero's Downfall", "Instant-speed creature or planeswalker removal."),
      sub("Life from the Loam", "Grim Discovery", "Two-mana sorcery: land recursion, regrowth."),
      sub("Living Death", "Rise Again", "Five-mana sorcery: reanimation, recursion."),
      sub("Lord of the Forsaken", "Mindscour Dragon", "Six-mana creature: mill, self-mill."),
      sub("Millikin", "Hedron Crawler", "Two-mana creature: mana creature, ramp."),
      sub("Multani, Yavimaya's Avatar", "Lumra, Bellow of the Woods", "Six-mana creature: recursion."),
      sub("Myriad Landscape", "Blighted Woodland", "Land: land fetcher."),
      sub("Necromantic Selection", "Blood Money", "Seven-mana sorcery: sweeper, removal."),
      sub("Necropolis Fiend", "Black Dragon", "Nine-mana creature: removal, evasive creature."),
      sub("River Kelpie", "Drelnoch", "Five-mana creature: card draw, card advantage."),
      sub("Shigeki, Jukai Visionary", "Coiling Oracle", "Two-mana creature: extra land, ramp."),
      sub("Steward of the Harvest", "Cemetery Reaper", "Four-mana creature."),
      sub("Tasigur, the Golden Fang", "Barrow Witches", "Six-mana creature: regrowth, recursion."),
      sub("Teval's Judgment", "Black Market Connections", "Three-mana enchantment: Treasure maker, modal."),
      sub("Treasure Cruise", "Last March of the Ents", "Eight-mana sorcery: card draw, card advantage."),
      sub("Welcome the Dead", "Deep Analysis", "Four-mana sorcery: card draw for life, card draw."),
      sub("Wonder", "Pixie Queen", "Four-mana creature: gives flying, evasion."),
    ],
  }),
  precon({
    name: "Abzan Armor",
    commander: "Felothar the Steadfast",
    description: "Abzan walls: defenders and high-toughness creatures that attack and deal damage by toughness.",
    printed: [
      ["Access Tunnel", 1],
      ["Anguished Unmaking", 1],
      ["Arasta of the Endless Web", 1],
      ["Arbor Adherent", 1],
      ["Arboreal Grazer", 1],
      ["Arcane Signet", 1],
      ["Assault Formation", 1],
      ["Axebane Guardian", 1],
      ["Baldin, Century Herdmaster", 1],
      ["Behind the Scenes", 1],
      ["Betor, Ancestor's Voice", 1],
      ["Blight Pile", 1],
      ["Bojuka Bog", 1],
      ["Canopy Gargantuan", 1],
      ["Canopy Vista", 1],
      ["Carven Caryatid", 1],
      ["Colfenor's Urn", 1],
      ["Command Tower", 1],
      ["Crashing Drawbridge", 1],
      ["Deceptive Landscape", 1],
      ["Despark", 1],
      ["Dragonlord Dromoka", 1],
      ["Evolving Wilds", 1],
      ["Exotic Orchard", 1],
      ["Expel the Interlopers", 1],
      ["Faeburrow Elder", 1],
      ["Feed the Swarm", 1],
      ["Forest", 7],
      ["Fortified Village", 1],
      ["Hornet Nest", 1],
      ["Ikra Shidiqi, the Usurper", 1],
      ["Indomitable Ancients", 1],
      ["Indulging Patrician", 1],
      ["Infernal Grasp", 1],
      ["Isolated Chapel", 1],
      ["Jaddi Offshoot", 1],
      ["Jaws of Defeat", 1],
      ["Nyx-Fleece Ram", 1],
      ["Orzhov Signet", 1],
      ["Overgrown Battlement", 1],
      ["Overgrown Farmland", 1],
      ["Path of Ancestry", 1],
      ["Plains", 6],
      ["Protector of the Wastes", 1],
      ["Radiant Grove", 1],
      ["Rampart Architect", 1],
      ["Reunion of the House", 1],
      ["Rhox Faithmender", 1],
      ["Sandsteppe Citadel", 1],
      ["Seedborn Muse", 1],
      ["Selesnya Signet", 1],
      ["Shadrix Silverquill", 1],
      ["Shalai, Voice of Plenty", 1],
      ["Sidar Kondo of Jamuraa", 1],
      ["Slaughter the Strong", 1],
      ["Sol Ring", 1],
      ["Staff of Compleation", 1],
      ["Sungrass Prairie", 1],
      ["Sunpetal Grove", 1],
      ["Swamp", 5],
      ["Swiftfoot Boots", 1],
      ["Swords to Plowshares", 1],
      ["Sylvan Caryatid", 1],
      ["Temple of Malady", 1],
      ["Temple of Plenty", 1],
      ["Temple of Silence", 1],
      ["Tip the Scales", 1],
      ["Tower Defense", 1],
      ["Towering Titan", 1],
      ["Tree of Redemption", 1],
      ["Twilight Mire", 1],
      ["Wakestone Gargoyle", 1],
      ["Walking Bulwark", 1],
      ["Wall of Blossoms", 1],
      ["Wall of Limbs", 1],
      ["Wall of Omens", 1],
      ["Wall of Reverence", 1],
      ["Wall of Roots", 1],
      ["Weathered Sentinels", 1],
      ["Welcoming Vampire", 1],
      ["Will of the Abzan", 1],
      ["Wingmantle Chaplain", 1],
      ["Woodland Cemetery", 1],
      ["Zetalpa, Primal Dawn", 1],
    ],
    substitutions: [
      sub("Assault Formation", "Doran, the Siege Tower", "Creatures deal combat damage equal to their toughness."),
      sub("Baldin, Century Herdmaster", "Syr Alin, the Lion's Claw", "Six-mana creature: team pump, attack trigger."),
      sub("Behind the Scenes", "History of Benalia", "Three-mana enchantment: team pump."),
      sub("Canopy Gargantuan", "Old Gnawbone", "Seven-mana green Dragon."),
      sub("Colfenor's Urn", "Resurrection Orb", "Three-mana artifact: protection."),
      sub("Faeburrow Elder", "Fyndhorn Elder", "Three-mana creature: mana creature, ramp."),
      sub("Protector of the Wastes", "Angel of the Ruins", "Six-mana creature: artifact and enchantment removal, removal."),
      sub("Reunion of the House", "Brilliant Restoration", "Seven-mana sorcery: mass reanimation, reanimation."),
      sub("Shadrix Silverquill", "Archangel of Thune", "Five-mana white flier that grows the team."),
      sub("Sidar Kondo of Jamuraa", "Delney, Streetwise Lookout", "Four-mana creature: evasion."),
      sub("Slaughter the Strong", "Citywide Bust", "Three-mana sorcery: sweeper, creature removal."),
      sub("Tip the Scales", "Toxic Deluge", "Three-mana sorcery: removal, sweeper."),
      sub("Tree of Redemption", "Ancient Lumberknot", "Four-mana creature that deals damage by toughness."),
      sub("Wakestone Gargoyle", "Wall of Swords", "Four-mana creature: evasive creature."),
      sub("Walking Bulwark", "Steel Wall", "One-mana artifact wall."),
      sub("Wall of Roots", "Vine Trellis", "Two-mana creature: mana creature, ramp."),
      sub("Weathered Sentinels", "Guardians of Meletis", "Three-mana artifact defender with high toughness."),
      sub("Will of the Abzan", "Breath of Life", "Four-mana sorcery: reanimation, recursion."),
    ],
  }),
  precon({
    name: "Mardu Surge",
    commander: "Zurgo Stormrender",
    description: "Mardu tokens: attack wide with tokens and cash them in as they leave.",
    printed: [
      ["Abrade", 1],
      ["Adeline, Resplendent Cathar", 1],
      ["Ainok Strike Leader", 1],
      ["Angel of Invention", 1],
      ["Arcane Signet", 1],
      ["Aron, Benalia's Ruin", 1],
      ["Bastion of Remembrance", 1],
      ["Battlefield Forge", 1],
      ["Beetleback Chief", 1],
      ["Bitter Triumph", 1],
      ["Blade of Selves", 1],
      ["Bojuka Bog", 1],
      ["Bone Devourer", 1],
      ["Canyon Slough", 1],
      ["Castle Ardenvale", 1],
      ["Castle Embereth", 1],
      ["Caves of Koilos", 1],
      ["Chittering Witch", 1],
      ["Clifftop Retreat", 1],
      ["Command Tower", 1],
      ["Commander's Insignia", 1],
      ["Deadly Dispute", 1],
      ["Divine Visitation", 1],
      ["Dragonskull Summit", 1],
      ["Eliminate the Competition", 1],
      ["Emeria Angel", 1],
      ["Exotic Orchard", 1],
      ["Fellwar Stone", 1],
      ["Fetid Heath", 1],
      ["Gix, Yawgmoth Praetor", 1],
      ["Goldlust Triad", 1],
      ["Goldnight Commander", 1],
      ["Grand Crescendo", 1],
      ["Grenzo, Havoc Raiser", 1],
      ["Hero of Bladehold", 1],
      ["Hour of Reckoning", 1],
      ["Idol of Oblivion", 1],
      ["Infantry Shield", 1],
      ["Ironwill Forger", 1],
      ["Isolated Chapel", 1],
      ["Kaya, Geist Hunter", 1],
      ["Legion Loyalty", 1],
      ["Legion Warboss", 1],
      ["Lightning Greaves", 1],
      ["Lingering Souls", 1],
      ["Loyal Apprentice", 1],
      ["Mindblade Render", 1],
      ["Morbid Opportunist", 1],
      ["Mountain", 5],
      ["Myr Battlesphere", 1],
      ["Neriv, Crackling Vanguard", 1],
      ["Nomad Outpost", 1],
      ["Ogre Battledriver", 1],
      ["Ophiomancer", 1],
      ["Path of Ancestry", 1],
      ["Plains", 5],
      ["Redoubled Stormsinger", 1],
      ["Release the Dogs", 1],
      ["Selfless Spirit", 1],
      ["Shadow Summoning", 1],
      ["Shattered Landscape", 1],
      ["Shattered Sanctum", 1],
      ["Siege-Gang Commander", 1],
      ["Skullclamp", 1],
      ["Smoldering Marsh", 1],
      ["Sol Ring", 1],
      ["Solemn Simulacrum", 1],
      ["Stroke of Midnight", 1],
      ["Sun Titan", 1],
      ["Swamp", 5],
      ["Swords to Plowshares", 1],
      ["Talisman of Conviction", 1],
      ["Talisman of Hierarchy", 1],
      ["Temple of Silence", 1],
      ["Temple of Triumph", 1],
      ["Tempt with Vengeance", 1],
      ["Terramorphic Expanse", 1],
      ["Thalisse, Reverent Medium", 1],
      ["Tocasia's Welcome", 1],
      ["Twilight Drover", 1],
      ["Vault of the Archangel", 1],
      ["Viscera Seer", 1],
      ["Wayfarer's Bauble", 1],
      ["Will of the Mardu", 1],
      ["Windbrisk Heights", 1],
      ["Within Range", 1],
      ["Yahenni, Undying Partisan", 1],
    ],
    substitutions: [
      sub("Ainok Strike Leader", "Hanweir Garrison", "Attacks and brings attacking tokens with it."),
      sub("Divine Visitation", "Anointed Procession", "Five-mana enchantment: token payoff."),
      sub("Eliminate the Competition", "Lich's Caress", "Five-mana sorcery: removal, creature removal."),
      sub("Gix, Yawgmoth Praetor", "Midnight Reaper", "Three-mana creature: card draw for life, card draw."),
      sub("Grenzo, Havoc Raiser", "Killian, Decisive Mentor", "Two-mana creature: card advantage."),
      sub("Hero of Bladehold", "Leonin Warleader", "Four-mana white creature that makes attacking tokens."),
      sub("Kaya, Geist Hunter", "Ajani, Caller of the Pride", "Three-mana planeswalker."),
      sub("Legion Warboss", "Krenko, Tin Street Kingpin", "Three-mana creature: token maker, attack trigger."),
      sub("Myr Battlesphere", "Threefold Thunderhulk", "Seven-mana artifact creature that makes an army."),
      sub("Neriv, Crackling Vanguard", "Bonehoard Dracosaur", "Five-mana creature: impulse draw, card advantage."),
      sub("Redoubled Stormsinger", "Zurgo, Thunder's Decree", "Three-mana creature: token payoff, token maker."),
      sub("Will of the Mardu", "Bombard", "Three-mana instant: burn, removal."),
      sub("Windbrisk Heights", "Memorial to Glory", "Land: tapped land, utility land."),
      sub("Within Range", "Dogged Pursuit", "Four-mana enchantment: drains opponents."),
    ],
  }),
  precon({
    name: "Jeskai Striker",
    // The deck's two legendary leads swapped: Shiko and Narset commands it,
    // and Elsha plays in the 99 — the same 100 cards.
    commander: "Shiko and Narset, Unified",
    description: "Jeskai spells: cheap instants and sorceries, prowess and Monk tokens.",
    printed: [
      ["Abrade", 1],
      ["Adaptive Training Post", 1],
      ["Adarkar Wastes", 1],
      ["Aligned Heart", 1],
      ["Ancestral Vision", 1],
      ["Arcane Signet", 1],
      ["Archmage Emeritus", 1],
      ["Ash Barrens", 1],
      ["Azorius Signet", 1],
      ["Baral and Kari Zev", 1],
      ["Baral's Expertise", 1],
      ["Battlefield Forge", 1],
      ["Big Score", 1],
      ["Boros Signet", 1],
      ["Caldera Pyremaw", 1],
      ["Cascade Bluffs", 1],
      ["Clifftop Retreat", 1],
      ["Command Tower", 1],
      ["Compulsive Research", 1],
      ["Consider", 1],
      ["Curse of Opulence", 1],
      ["Curse of the Swine", 1],
      ["Deep Analysis", 1],
      ["Dismantling Wave", 1],
      ["Electrodominance", 1],
      ["Elsha, Threefold Master", 1],
      ["Evolving Wilds", 1],
      ["Exotic Orchard", 1],
      ["Expansion // Explosion", 1],
      ["Expressive Iteration", 1],
      ["Faithless Looting", 1],
      ["Fellwar Stone", 1],
      ["Ferrous Lake", 1],
      ["Frantic Search", 1],
      ["Ghostly Prison", 1],
      ["Glacial Fortress", 1],
      ["Goblin Electromancer", 1],
      ["Guttersnipe", 1],
      ["Haughty Djinn", 1],
      ["Irrigated Farmland", 1],
      ["Island", 5],
      ["Izzet Signet", 1],
      ["Lier, Disciple of the Drowned", 1],
      ["Magma Opus", 1],
      ["Mana Geyser", 1],
      ["Manaform Hellkite", 1],
      ["Mangara, the Diplomat", 1],
      ["Monastery Mentor", 1],
      ["Mountain", 5],
      ["Mystic Monastery", 1],
      ["Narset's Reversal", 1],
      ["Opt", 1],
      ["Path of Ancestry", 1],
      ["Perilous Landscape", 1],
      ["Plains", 4],
      ["Ponder", 1],
      ["Pongify", 1],
      ["Prairie Stream", 1],
      ["Preordain", 1],
      ["Prismari Command", 1],
      ["Reliquary Tower", 1],
      ["Rite of Replication", 1],
      ["Rugged Prairie", 1],
      ["Shiny Impetus", 1],
      ["Shivan Reef", 1],
      ["Skycloud Expanse", 1],
      ["Sol Ring", 1],
      ["Storm-Kiln Artist", 1],
      ["Sublime Epiphany", 1],
      ["Sulfur Falls", 1],
      ["Swords to Plowshares", 1],
      ["Talisman of Progress", 1],
      ["Tempest Technique", 1],
      ["Temple of Enlightenment", 1],
      ["Temple of Epiphany", 1],
      ["Temple of Triumph", 1],
      ["Think Twice", 1],
      ["Third Path Iconoclast", 1],
      ["Time Wipe", 1],
      ["Transcendent Dragon", 1],
      ["Transforming Flourish", 1],
      ["Vanquish the Horde", 1],
      ["Velomachus Lorehold", 1],
      ["Veyran, Voice of Duality", 1],
      ["Voracious Bibliophile", 1],
      ["Whirlwind of Thought", 1],
      ["Will of the Jeskai", 1],
      ["Young Pyromancer", 1],
    ],
    substitutions: [
      sub("Curse of Opulence", "Sticky Fingers", "One-mana enchantment: token maker, ramp."),
      sub("Curse of the Swine", "Resculpt", "Two-mana sorcery: removal, creature removal."),
      sub("Dismantling Wave", "Solemn Offering", "Three-mana sorcery: artifact and enchantment removal, removal."),
      sub("Transforming Flourish", "Stroke of Midnight", "Three-mana instant: removal."),
    ],
  }),
];
